### ISSUE TITLE
[FEATURE] Make Header Sticky.

### ISSUE THREAD

**Issue by sohail-313** [EddieHubCommunity/BioDrop#10019]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Yes, the current issue is about the header not being fixed or sticky while scrolling, causing inconvenience in navigation. Making the header fixed would enhance user experience.

### Proposed Solution

Adding CSS  to make the header fixed at the top of the page while scrolling, ensuring a more user-friendly navigation experience.

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

<header class="sticky top-0 z-50">
  
</header>

**Comment by SaraJaoude** [comment]
Thank you for raising but I do not think you have checked whether this issue is a duplicate.  When I search I get multiple results of this issue being raised in the past and closed by maintainers.

I will therefore close this issue.
