### ISSUE TITLE
[DOCS] Update Testimonial Addition Process in Docs

### ISSUE THREAD

**Issue by ArvindParekh** [EddieHubCommunity/BioDrop#10055]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

https://www.biodrop.io/docs/how-to-guides/testimonials-json

### Version of BioDrop (for example "v1.2.3")

v2.93.7

### Description

The process outlined for adding a new testimonial to a user using JSON in the documentation is outdated. It directs users to click on the 'Add testimonial' button, which has been removed from BioDrop's latest version. The current method involves navigating to the issues tab, creating a new issue, and selecting the 'Testimonial' template. I believe we should update this information in the docs, along with the screenshots.

### Steps to Reproduce

1. Go to [Testimonials with JSON](https://www.biodrop.io/docs/how-to-guides/testimonials-json) page.
2. Go to the `Giving a Testimonial` section and read the description.

### Screenshots

Procedure highlighted in the docs:

![image](https://github.com/EddieHubCommunity/BioDrop/assets/71211731/b545f114-2de0-40d5-a801-47d9330b2794)

How the profile looks now:
![image](https://github.com/EddieHubCommunity/BioDrop/assets/71211731/a12c7d98-720c-4faf-b216-d5e199e9d034)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

Updating the docs to reflect the current procedure for adding a testimonial, along with screenshots for the same, would solve this issue.

**Comment by SaraJaoude** [comment]
Thank you for raising @ArvindParekh - I have assigned this to you.

**Comment by eugene4545** [comment]
please could i work on this issue?

**Comment by eugene4545** [comment]
oh okay sorry about that
