### ISSUE TITLE
[FEATURE] <Add Pagination to the Repos Page>

### ISSUE THREAD

**Issue by dhruvilmehta** [EddieHubCommunity/BioDrop#10054]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Currently, we are fetching every relevant `Repos` record and passing it to the front end. Instead, we can add pagination and make pages of 10 or 20

### Proposed Solution

Similar to how we are passing a query parameter of `sortBy` here, ```router.push(`/repos?sortBy=${e.currentTarget.value}`)```, we can also add the `?page` parameter so that we can fetch a particular number of records from the backend. 
For eg, if the Page Number is 1, we'll fetch first 10 records, if it is 2, we'll fetch next 10 records and display it on the screen and so on.

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

As I explained in the proposed solution, we can add the query parameter of `?page` and accordingly fetch relevant records.

**Comment by SaraJaoude** [comment]
Thank you raising.  However given that it is unlikely that any individual user would have so many repos that this would require pagination, I will be closing this issue for now.

**Comment by dhruvilmehta** [comment]
I am talking about the general repos page which is `https://www.biodrop.io/repos` and not the individual user's repos page.

**Comment by eddiejaoude** [comment]
Sorry that was my mistake when discussing with Sara - but tbh at the moment I quite like the longer page, but soon it will be needed - maybe we can revisit this after it grows a bit more.
