### ISSUE TITLE
[BUG] Added links not showing on profile

### ISSUE THREAD

**Issue by angkul07** [EddieHubCommunity/BioDrop#10062]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

https://www.biodrop.io/angkul07

### Version of BioDrop (for example "v1.2.3")

v2.97.6

### Description

I just created my biodrop profile and it seems that the links I added from "Links" section, are not showing up on my profile. I tried multiple times but it is not working.

### Steps to Reproduce

Go to biodrop.io and login into your account and go to Links section. Click on "Add Link", fill the form, turn on "Enable?" and "Pin?" and save. Thank you.

### Do you want to work on this issue?

No

**Comment by eddiejaoude** [comment]
It seems to be working fine, I just tested it, please can you elaborate what link you are trying to add. Your profile has the GitHub link pinned ...

<img width="1409" alt="Screenshot 2024-01-04 at 20 01 48" src="https://github.com/EddieHubCommunity/BioDrop/assets/624760/62b1387c-87f7-401f-b1ed-4dcdc05ee1a3">

**Comment by eddiejaoude** [comment]
This is a bug, thank you for raising and verifying 💪

**Comment by eddiejaoude** [comment]
I found the bug, just deploying a fix now

**Comment by eddiejaoude** [comment]
I just tested on live and it is now working, sorry for the confusion
