### ISSUE TITLE
[Improvement] Optimize Api calls on the search page

### ISSUE THREAD

**Issue by Abhishek-90** [EddieHubCommunity/BioDrop#10079]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

production

### Version of BioDrop (for example "v1.2.3")

v2.97.6

### Description

Currently on Search Page, when we select a tag, it directly makes an api call. Which is fine till only 1 tag is being selected. But incase when multiple tags are getting select, a new api call is made after adding the new tag with already selected tags. 

### Steps to Reproduce

NA

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

I would like to resolve this issue to reduce the number of api calls made. I would use `debouce` technique or `AbortController` method to address this issue, which will help us to reduce the number of API calls.

**Comment by SaraJaoude** [comment]
Thank you for raising.  However this would make the search appear slower, when only using one tag.  This is likely to be an over optimisation for now, as we have not had any issues  - so I shall close for now.
