### ISSUE TITLE
[FEATURE] Skills Endorsements

### ISSUE THREAD

**Issue by coderiksenthil** [EddieHubCommunity/BioDrop#10093]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Users on **BioDrop** struggle to showcase their skills effectively, impeding collaboration and networking within the community.

### Proposed Solution

Introduce a **Skills Endorsements feature**. Users can list skills on their profiles, and others can endorse them for specific skills. This creates a structured and visible way for users to showcase expertise, fostering better collaboration and networking.

### Do you want to work on this issue?

No

**Comment by SaraJaoude** [comment]
Thank you for raising. Users can already showcase their skills in the Tags section.  

We are not looking to add an endorsement functionality at this time so I will close this issue for now.
