### ISSUE TITLE
[FEATURE] Implement Individual Hover Effects for Social Icons

### ISSUE THREAD

**Issue by ritika728** [EddieHubCommunity/BioDrop#10112]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

No

### Proposed Solution

I would like to request the implementation of individual hover effects for each social icon in the footer. Currently, all social icons share the same hover effect. To enhance the user experience and make the design more engaging, I suggest implementing unique hover colors (official color) for each social icon.

### Screenshots

https://github.com/EddieHubCommunity/BioDrop/assets/91181981/0b031a4f-ff34-4915-9a28-7e77e3060304

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

By creating a function that maps each social media icon name to its corresponding hover effect color and modifying the footer component to utilize this function when rendering each social media icon.

**Comment by SaraJaoude** [comment]
Thank you for your suggestion.  This does look like a good idea in theory, however in practice there are some challenges with theming and accessibility, for example. To keep things simple we will avoid making these types of changes for now, so I shall close this Issue.
