### ISSUE TITLE
[BUG] Add Support for .tool-versions File in asdf

### ISSUE THREAD

**Issue by ThomasCode92** [EddieHubCommunity/BioDrop#10129]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

Local dev environment

### Version of BioDrop (for example "v1.2.3")

not relevant

### Description

**Issue Description:**
Currently, the project lacks support for a .tool-versions file, which is commonly used for [asdf](https://asdf-vm.com/) to specify the version of the tools required for a particular project. This file allows developers to explicitly declare the version of the tools they are using, ensuring consistent and reproducible environments.

**Expected Behavior:**
The addition of a .tool-versionq file would enable developers to specify the required version of the tools for their projects. This file would be recognized by asdf, and it would automatically use the specified version when working with the project, enhancing the predictability and reproducibility of development environments.

### Steps to Reproduce

I use WSL on my Windows system and utilize [asdf](https://asdf-vm.com/) for software management. Upon opening the project, I encountered an issue where asdf defaulted to the locally installed node version instead of adhering to the version specified in the `.nvmrc` file. To resolve this discrepancy, I installed _node v18.16.0_ and introduced a `.tool-version` file specifying this particular node version. Consequently, asdf correctly recognized and employed the specified node version for the project.

### Screenshots

Without .tool-versions
![image](https://github.com/EddieHubCommunity/BioDrop/assets/108367944/44a5d062-6980-415a-94e0-8fab923389e1)

With .tool-versions
![image](https://github.com/EddieHubCommunity/BioDrop/assets/108367944/d49d363f-4e3a-45b3-b083-d8dc6585d77d)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

1. Introduce a `.tools-version` file in the root directory of a project.
2. The file should contain a single line specifying the version of the tool required, adhering to the format used by asdf.
`nodejs 14.17.5`
3. When asdf encounters a `.tools-version` file, it should automatically use the specified version of the tool when working with the project.

**Comment by SaraJaoude** [comment]
Thank you for raising. 

As we have the node version `.nvmrc` and also in `package.json`, we feel that adding another place where we need to keep the node version number in sync and up to date will cause more problems than it will solve. Therefore I will close this issue for now.
