### ISSUE TITLE
[FEATURE] avatar integration for community repos contributor

### ISSUE THREAD

**Issue by badrivlog** [EddieHubCommunity/BioDrop#10138]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Introduce a visually engaging enhancement to the community repos by replacing `added by` usernames text into avatar photos. This feature will visually represent contributors, providing a more engaging and user-friendly experience. It adds a touch of personality to the project, fostering a sense of community and recognition for those who contribute.

Edit:
additional feature- make avatar photos clickable links within our platform. when a user clicks on an avatar, redirect them to the respective user profile.

### Proposed Solution
* ~Integrate a mechanism to fetch Github avatars based on repo.username array and display avatars associated with each user~

- [x] create  a reusable getUserAvatar function to fetch Github user avatar
- [x] create a reusable Avatar component
- [x] create a reusable AvatarGroup component
- [x] create  UserAvatarGroup component
- [x] integrate UserAvatarGroup component to repos page

### Screenshots

**Current users repo**
![biodrop-repos-1](https://github.com/EddieHubCommunity/BioDrop/assets/73095526/19bc3f90-bf2e-49ec-aec0-d1d53ae511e5)

**After making changes**
![biodrop-repos-2](https://github.com/EddieHubCommunity/BioDrop/assets/73095526/cbd887f6-f542-4561-8930-252f801c1331)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

to achieve this we can use the existing `FallbackImage` custom component

**Comment by ChinmayMhatre** [comment]
This is a great idea!

**Comment by SaraJaoude** [comment]
Great idea @badrivlog - I have assigned this to you.

**Comment by badrivlog** [comment]
After further consideration, i feel it would be beneficial to make avatar photos clickable within our platform. The idea is that when a user clicks on an avatar, they should be redirected to the respective user profile. This enhancement can significantly improve user navigation and interaction, adding a more intuitive element to our platform.

I'd love to hear your thoughts on this suggestion and discuss how it might fit into our project roadmap.

Thank you.

**Comment by SaraJaoude** [comment]
Thank you @badrivlog I agree with your suggestion. If you could please amend the Issue to reflect this latest addition, so everyone knows what the goal is, that would be great.

**Comment by ninadvyas** [comment]
Hello I would like to work on this issue.

**Comment by eddiejaoude** [comment]
Pull Request merged
