### ISSUE TITLE
[BUG] Update New Testimonial Image in docs to represent BioDrop

### ISSUE THREAD

**Issue by ArvindParekh** [EddieHubCommunity/BioDrop#10135]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

https://www.biodrop.io/docs/how-to-guides/testimonials-json

### Version of BioDrop (for example "v1.2.3")

v2.99.2

### Description

The image used for a new issue of type testimonial in the documentation still shows the old project name "Linkfree." We should update it with an image that represents the current project name, BioDrop.

This is a continuation of pr #10123 

### Steps to Reproduce

1. Go to [Testimonials with JSON](https://www.biodrop.io/docs/how-to-guides/testimonials-json) page.
2. Notice the image that shows a new issue being created. 

### Screenshots

![image](https://github.com/EddieHubCommunity/BioDrop/assets/71211731/b927cd65-fbe2-4ae8-95f8-7b6a7d26c91b)

### Do you want to work on this issue?

Yes

**Comment by SaraJaoude** [comment]
Thank you for raising, I have assigned this to you.
