### ISSUE TITLE
[BUG] Move Title and Select to One Line

### ISSUE THREAD

**Issue by ThomasCode92** [EddieHubCommunity/BioDrop#10148]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

Production

### Version of BioDrop (for example "v1.2.3")

v2.99.4

### Description

Move the title and select box on the `Community Repos` page to one line

### Steps to Reproduce

Not applicable

### Screenshots

![image](https://github.com/EddieHubCommunity/BioDrop/assets/108367944/017230a5-6185-4f1d-96cb-5c1d2e85352f)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

Wrap it with a div and use flexbox to align and center the title and select box.
Make sure it all works on mobile and desktop.

**Comment by SaraJaoude** [comment]
Thank you for raising - I have assigned this to you.
