### ISSUE TITLE
[FEATURE] <Add hover to the home page buttons>

### ISSUE THREAD

**Issue by Simer13** [EddieHubCommunity/BioDrop#10143]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

![Screenshot (262)](https://github.com/EddieHubCommunity/BioDrop/assets/113010708/17d4906f-265e-48d7-b8ab-3842a3810e0f)

### Proposed Solution

Create the hover CSS functionality over all the buttons to make them look more enhanced and better style appealing! 

### Do you want to work on this issue?

Yes

**Comment by ChinmayMhatre** [comment]
@Simer13  could you specify which buttons you are mentioning here? I believe all buttons on the landing page have some sort of a hover effect.

**Comment by Simer13** [comment]
@ChinmayMhatre When we hover over it, only the color changes we can have the border hover as well with scale and shadow effect too, giving it more 3d effect

**Comment by SaraJaoude** [comment]
Thank you for raising.  As we are currently looking at a redesign, we can approach this additional hover effect at that time - so I shall close this issue for now.
