### ISSUE TITLE
[FEATURE] Adding a "Home" button in menu list under navbar section 

### ISSUE THREAD

**Issue by antriksh-9** [EddieHubCommunity/BioDrop#10142]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

The problem: 
Suppose a user is navigating through the website such as reading the documentation scrolling through different sections of it and now the user wants to visit the [homepage](https://www.biodrop.io/) immediately but there is no feature like this that lands it directly to the homepage.

### Proposed Solution

The Solution: 
I propose an idea of adding a "Home" button in menu list under navbar section. 
This "Home" button will be present before the menu items such as "Search", "Events" etc.

### Do you want to work on this issue?

Yes

**Comment by ChinmayMhatre** [comment]
Hi @antriksh-9 , you can click on the BioDrop logo to navigate to the homepage.

This is a standard way if we see web apps like GitHub, Youtube and many more!

**Comment by ChinmayMhatre** [comment]
I'll close this issue. Feel free to have a chat in the discord or raise a discussion if you have Any more questions !
