### ISSUE TITLE
[BUG] No padding around 'Select a tab' label in mobile view

### ISSUE THREAD

**Issue by ThomasCode92** [EddieHubCommunity/BioDrop#10150]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

Production

### Version of BioDrop (for example "v1.2.3")

v2.99.4

### Description

The current mobile view of the application displays the '_Select a tab_' label with suboptimal padding, resulting in a less-than-ideal user experience. The inadequate padding around that label on smaller screens can lead to visual clutter and may impact the overall usability of the application.

### Steps to Reproduce

1. Open the application on a mobile device or use a mobile view of the developer tools
2. Navigate to [Community Events](https://www.biodrop.io/events).
3. Observe the spacing around the label (See screenshot below)

### Screenshots

![image](https://github.com/EddieHubCommunity/BioDrop/assets/108367944/659ab229-6254-490a-b1d5-6e53c072216c)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

Adjust the CSS or styling rules for labels in the mobile view to provide appropriate padding, ensuring a more comfortable and aesthetically pleasing display.

**Comment by SaraJaoude** [comment]
Thank you for raising.  Unfortunately @ThomasCode92 I cannot assign this issue to you at this time as we only assign one issue at any one time, per contributor (as reflected in our [Contributing Guide](https://github.com/EddieHubCommunity/BioDrop/blob/main/CONTRIBUTING.md)).

**Comment by eugene4545** [comment]
I'd be happy to work on this issue, could i be assigned to it?

**Comment by vrushabhgawas14** [comment]
> Thank you for raising. Unfortunately @ThomasCode92 I cannot assign this issue to you at this time as we only assign one issue at any one time, per contributor (as reflected in our [Contributing Guide](https://github.com/EddieHubCommunity/BioDrop/blob/main/CONTRIBUTING.md)).

Ma'am I want to work on this issue as I have figured out that only change is px-3 (as much padding needed) in ```EventTabs.js```

**Comment by ThomasCode92** [comment]
> Thank you for raising. Unfortunately @ThomasCode92 I cannot assign this issue to you at this time as we only assign one issue at any one time, per contributor (as reflected in our [Contributing Guide](https://github.com/EddieHubCommunity/BioDrop/blob/main/CONTRIBUTING.md)).

Yes, I understand. But I didn’t know which issue would be assigned first to me. You can assign it to someone else.

**Comment by arujjval** [comment]
@SaraJaoude  can I work on this issue?

**Comment by SaraJaoude** [comment]
> I'd be happy to work on this issue, could i be assigned to it?

@eugene4545 I have assigned this to you.

**Comment by charuchauhan** [comment]
Hello I guess no one is working on this, so can I work on this?

**Comment by ArvindParekh** [comment]
Hi @charuchauhan, thank you for your interest in contributing to BioDrop. The current issue has already been assigned to @eugene4545, and we usually allow a two-week window for individuals to address the task ([contributing guide](https://github.com/EddieHubCommunity/BioDrop/blob/main/CONTRIBUTING.md) - for more reference). But if you'd like, feel -free to explore other open issues.

**Comment by SaraJaoude** [comment]
> Hi, is it done or i can work on it?

@FazeenIjaz please check the conversation before raising this type of question.  As you can see there is a PR open by the assignee to fix this issue, which needs to be reviewed.

**Comment by HaydenII** [comment]
I've set up the project locally and explored it. I'm prepared to take it on if you'd like to assign it to me
