### ISSUE TITLE
[BUG] Account/Manage/Link button pointing to undefined.

### ISSUE THREAD

**Issue by girl-loves-coding** [EddieHubCommunity/BioDrop#10157]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

production

### Version of BioDrop (for example "v1.2.3")

2.99.5

### Description

The button preview is pointing to undefined.

<img width="566" alt="image" src="https://github.com/EddieHubCommunity/BioDrop/assets/100626279/918d092d-35af-4a65-84af-b052e998c119">

<img width="418" alt="image" src="https://github.com/EddieHubCommunity/BioDrop/assets/100626279/9a13f2c0-2709-4723-afd8-2a54f04abdfd">

### Steps to Reproduce

If you know the steps, follow the below format and provide steps to reproduce

For example:

1. Go to https://www.biodrop.io/account/manage/link/{your link} page.
2. Check the preview link button
3. All the buttons for me show undefined

### Do you want to work on this issue?

No

**Comment by eddiejaoude** [comment]
Great spot, thank you for raising the issue 👍  I will look into it

**Comment by sital002** [comment]
@eddiejaoude  I think passing _id [here](https://github.com/EddieHubCommunity/BioDrop/blob/02f4cd34ef4fbe2f67977047caa1335feb646842/pages/account/manage/link/%5B%5B...data%5D%5D.js#L293C4-L293C52) will fix the issue ``` link={{ name, url, icon, animation, _id: link._id }} ```

**Comment by eddiejaoude** [comment]
Great point @sital002 👍  for the edit the `id` will solve it 💯 , I also created a workaround for when adding a new link and the click will still work - I just raised the PR https://github.com/EddieHubCommunity/BioDrop/pull/10164
