### ISSUE TITLE
[BUG] groups field dropdown shift layout while suggestions are shown

### ISSUE THREAD

**Issue by sital002** [EddieHubCommunity/BioDrop#10163]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

production

### Version of BioDrop (for example "v1.2.3")

2.99.8

### Description

Just implementing the solution that we used for icon suggestion drop down here is the link for the https://github.com/EddieHubCommunity/BioDrop/pull/9898

### Steps to Reproduce

Steps to reproduce

1. Go to http://localhost:3000/account/manage/link page.
2.  Type on the group field if you already have some ths will shift the layout 

### Do you want to work on this issue?

No

**Comment by eddiejaoude** [comment]
I think the fix will be similar to the icons drop down https://github.com/EddieHubCommunity/BioDrop/pull/9898

**Comment by tix980** [comment]
Hello @eddiejaoude , This would be my first time contributing to this project, and I have already read the contributing guide. Would it be okay for me to work on this issue?

**Comment by eddiejaoude** [comment]
Sure, I will assign it to you @tix980

**Comment by TheShiveshNetwork** [comment]
Hello @eddiejaoude its almost been a week so can you assign this issue to me too?

**Comment by eddiejaoude** [comment]
> Hello eddiejaoude its almost been a week so can you assign this issue to me too?

@TheShiveshNetwork please read the contributing guide https://github.com/EddieHubCommunity/BioDrop/blob/main/CONTRIBUTING.md

**Comment by tix980** [comment]
Sorry, this is my first time contributing. I have finally figured out how to set up the environment, understand the code, and fix the problem. I will read the contribution guide again and proceed with the merge PR shortly.
