### ISSUE TITLE
[BUG] Missing Events Dropdown on Account

### ISSUE THREAD

**Issue by at-the-vr** [EddieHubCommunity/BioDrop#10185]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

production

### Version of BioDrop (for example "v1.2.3")

v2.99.9

### Description

No events are visible in my biodrop profile even though I have an old event added in past. Additionally, creating new events does not reflects on my profile 

### Steps to Reproduce

If you know the steps, follow the below format and provide steps to reproduce

For example:

1. Go to `https://www.biodrop.io/account/manage/events`
2. See missing events, add new events
3. No change occurs on profile but Success modal pops

### Screenshots

![image](https://github.com/EddieHubCommunity/BioDrop/assets/88548999/11e5191e-287c-46d6-9a57-65dc7c84c879)

### Do you want to work on this issue?

No

**Comment by eddiejaoude** [comment]
Thank you for raising, I have found the issue and will fix it now

**Comment by Nwakaego-Ego** [comment]
Hi @eddiejaoude Please assign this issue to me

**Comment by eddiejaoude** [comment]
We were discussing this issue in EddieHub Discord and I have already fixed it - please see my comment above (before) yours
