### ISSUE TITLE
New Testimonial

### ISSUE THREAD

**Issue by saksham-jain177** [EddieHubCommunity/BioDrop#10182]
### Name

dhruvabhat24

### Title

Open Source Projects

### Description

I had the pleasure of collaborating on a couple of open-source projects, including a Weather App and an E-Commerce App. Working with them has been an enriching experience.

@dhruvabhat24 possesses a remarkable skill set in creating applications and websites. The applications they have worked on showcase an ease of understanding in both the codebase and the overall code workflow. I look forward to future opportunities to work together.

**Comment by dhruvabhat24** [comment]
Thank you.
