### ISSUE TITLE
[BUG] While adding/ updating events tags are not been saved and making form unsubmissive

### ISSUE THREAD

**Issue by amanpreet-dev** [EddieHubCommunity/BioDrop#10197]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

production

### Version of BioDrop (for example "v1.2.3")

2.99.10

### Description

If you are creating / updating events and want to add tags, the `Save` button gets disabled and in case tags are removed, it remains disabled

### Steps to Reproduce

1. Go to [Events Page](https://www.biodrop.io/account/manage/event) page.
2. Enter all the required details without adding any tags.
3. **`Save`** button remains active 
4. Now try to add tags like `javascript` and enter it will be added in the below box
5. Now the **`Save`** button gets disabled. 
6. If you remove the added tags the button remains disabled.

- This is happening in both cases i.e. while adding an event and also while updating an event.
both

### Screenshots

![Without tags](https://github.com/EddieHubCommunity/BioDrop/assets/57353834/fbf24cfe-fba2-4af5-b77a-be409f1a8d5e)
![With tags](https://github.com/EddieHubCommunity/BioDrop/assets/57353834/58cd5e95-3f95-4b8d-91b1-456b161c6944)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

The issue is that the `Save` button is not getting its validated value reset in case tags are added or removed. This is most probably a form validation issue.

**Comment by khainl1110** [comment]
Hi there, can I try to work on this issue? I am new to this but I know fullstack and would love to give it a try

**Comment by amanpreet-dev** [comment]
> Hi there, can I try to work on this issue? I am new to this but I know fullstack and would love to give it a try

Hi @khainl1110,  I have already started the work and In case I am not able to do it in the next few days, I will update you and then you can try on this issue.

**Comment by eddiejaoude** [comment]
Pull Request merged
