### ISSUE TITLE
[BUG] X-axis Labels and Bars Misalignment on Profile Views Chart

### ISSUE THREAD

**Issue by loftwah** [EddieHubCommunity/BioDrop#10193]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

production

### Version of BioDrop (for example "v1.2.3")

v2.99.10

### Description

On the BioDrop analytics profile views chart, there is a misalignment between the x-axis labels and the corresponding bars. The first bar, representing the data for `01/01/2024`, does not start directly above its label but slightly to the right. This misalignment persists throughout the chart, potentially affecting data interpretation.

### Expected Behavior

Each bar should start directly above its corresponding x-axis label to ensure clear and accurate representation of the data.

### Possible Solution

Adjust the chart rendering logic to align the start of each bar directly above the center of its respective x-axis label.

### Additional Information

- Issue observed on the 'Profile Views' chart for the last 30 days.
- Screenshot attached for reference.

### Steps to Reproduce

1. Open the BioDrop account dashboard.
2. Navigate to the 'Statistics' section.
3. Observe the alignment of the bars with the x-axis labels.

### Screenshots

![image](https://github.com/EddieHubCommunity/BioDrop/assets/19922556/c627432e-f8e1-4a07-b0fb-0bfb84b66d9d)
![image](https://github.com/EddieHubCommunity/BioDrop/assets/19922556/218c366b-4b18-4620-b8b3-328e796513a7)

### Do you want to work on this issue?

No

**Comment by amandamartin-dev** [comment]
Hey @loftwah ! I'm not able to reproduce this but this issue has been open awhile.  Are you still experiencing it?
![stats-bar](https://github.com/EddieHubCommunity/BioDrop/assets/97615019/1b1ca352-d88b-4b32-b911-8f377b4c4fec)

**Comment by Vijaykv5** [comment]
@loftwah Even same, I'm not able to reproduce the issue on my side too

**Comment by loftwah** [comment]
Interesting I was only looking at this the other day and it was still there. Seems to be fixed now.

![image](https://github.com/EddieHubCommunity/BioDrop/assets/19922556/ca02b209-4d6e-4c6a-a6c7-6cc22ca406c3)

**Comment by amandamartin-dev** [comment]
Thanks @loftwah and @Vijaykv5 for checking again. I'll close for now since it appears to be resolved.

**Comment by loftwah** [comment]
<img width="1306" alt="image" src="https://github.com/EddieHubCommunity/BioDrop/assets/19922556/4b3ade89-ce97-4da0-8017-c818de2c7bb1">

**Comment by amandamartin-dev** [comment]
@loftwah ran a responsive test, I've been on a mac teting both times.  I'm seeing the chart respond to changes in viewport.  Will leave closed for now as I think the time it would take to track this down versus the impact to users may not be very high at this time. Wdyt?

https://github.com/EddieHubCommunity/BioDrop/assets/97615019/fe964377-d414-4408-bfe2-a311a30ae6b1

**Comment by loftwah** [comment]
Yeah if it is only my user it doesn't really matter. I could trace it down to being a strange bug to do with date formatting and locale. It doesn't always appear for me. You always have this if you notice it happens for anyone else.

**Comment by eddiejaoude** [comment]
thanks Dean for tracking it down! 👍

**Comment by loftwah** [comment]
> @loftwah ran a responsive test, I've been on a mac teting both times. I'm seeing the chart respond to changes in viewport. Will leave closed for now as I think the time it would take to track this down versus the impact to users may not be very high at this time. Wdyt?
> 
>  responsive-test.mov

I might be seeing things but is the empty bar on the chart in your video here the same issue as what I am describing? See how there is a blank day on the left of the chart? When I hover over mine it shows a date from the previous month.
