### ISSUE TITLE
[BUG] Error while cloning the repository

### ISSUE THREAD

**Issue by dhruvilmehta** [EddieHubCommunity/BioDrop#10204]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

While cloning or pulling the repository

### Version of BioDrop (for example "v1.2.3")

v2.99.11

### Description

`fatal: cannot create directory at 'data/https:': Invalid argument` 
`error: invalid path 'data/https:/github.com/dhruvabhat24/testimonials/pra00903.json'`
While cloning or pull the repository, git is throwing the above error. 

### Steps to Reproduce

1. Clone the repo

### Screenshots

![image](https://github.com/EddieHubCommunity/BioDrop/assets/68022411/c5e6fc98-669e-462f-abfc-c847d105ba77)

### Do you want to work on this issue?

No

**Comment by sital002** [comment]
Thanks for raising the issue

**Comment by eddiejaoude** [comment]
Thank you for raising 👍  I think this is now fixed
