### ISSUE TITLE
[BUG] Icon drop-down suggestions are not visible properly

### ISSUE THREAD

**Issue by chetannada** [EddieHubCommunity/BioDrop#10203]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

production on biodrop.io

### Version of BioDrop (for example "v1.2.3")

 v2.99.11

### Description

Icon drop-down suggestions are not visible properly in Edit section of Milestone. If we type 'FaLink' it suggests an icon related to Link, but due to the transparent background, suggestions are not visible properly. I added a screenshot for reference.

![Icon drop-down](https://github.com/EddieHubCommunity/BioDrop/assets/83969719/902763c6-0ed8-4dab-acfe-10bfa08ebaee) 

### Steps to Reproduce

If you know the steps, follow the below format and provide steps to reproduce

For example:

1. Go to [Milestone](https://www.biodrop.io/account/manage/milestones) page.
2. Click on the pencil Icon for Edit Milestone
3. Type 'FaLink' in Icon section, Icon Drop Down suggestions are not visible properly

### Screenshots

Another Screenshot for Reference:

![Icon Drop down Screenshot](https://github.com/EddieHubCommunity/BioDrop/assets/83969719/24e02093-287a-4c97-8c71-974bbb1f2cb8)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

I will make a background color white so Icon drop-down suggestions will visible properly.

**Comment by amandamartin-dev** [comment]
Able to recreate - note that this does not currently affect dark mode so be sure to test that dark mode still works as expected after your changes

**Comment by chetannada** [comment]
> Able to recreate - note that this does not currently affect dark mode so be sure to test that dark mode still works as expected after your changes

Sure. I will do testing after the changes.

**Comment by SaraJaoude** [comment]
> > Able to recreate - note that this does not currently affect dark mode so be sure to test that dark mode still works as expected after your changes
> 
> Hi, I have fixed this issue and created [PR](#10232) Thanks.

@chetannada  Thank you - the maintainers are going through open PRs systematically and will get to yours when they can.
