### ISSUE TITLE
[BUG] Add Hover Effect for Explaining Uneditable Links

### ISSUE THREAD

**Issue by ThomasCode92** [EddieHubCommunity/BioDrop#10215]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

Production

### Version of BioDrop (for example "v1.2.3")

v2.99.12

### Description

When users attempt to edit a link of their profile, there is no feedback or explanation provided for why the link cannot be edited. This lack of information can lead to confusion, especially for new users.

**Proposed Solution**
Implement a hover effect on uneditable links that triggers a tooltip or a small pop-up, providing a clear explanation for why the link cannot be edited. This enhancement will improve user experience and help users understand the constraints on link editing.

### Steps to Reproduce

1. Go to your [profile page](https://www.biodrop.io/account/onboarding).
2. In the center, click `Edit` in `Links` tab
3. Click the edit button of any link.
4. Try editting the url of the link

### Screenshots

![image](https://github.com/EddieHubCommunity/BioDrop/assets/108367944/0bd3bacc-bfed-4734-95ee-27d7a01646ac)

### Do you want to work on this issue?

No

**Comment by amandamartin-dev** [comment]
@ThomasCode92 great idea, what would be the mobile experience?

**Comment by ThomasCode92** [comment]
Maybe we can show some sort of helper text below (or above) the input?

**Comment by amandamartin-dev** [comment]
> Maybe we can show some sort of helper text below (or above) the input?
> 
That could be a good solution for both experiences perhaps?  Will add the discussion tag so others can weigh in on the best way to approach too. Thank you for your thoughts.

**Comment by manassingh17** [comment]
May be we can use  lock icons to visually indicate that it is not editable

**Comment by Rick-ftw** [comment]
I guess tooltip will work better for new users.

**Comment by SohamRoy-01** [comment]
Can I work on this issue @ThomasCode92 ,
My approach is pretty simple add a title attribute in the input field will do the work

**Comment by ThomasCode92** [comment]
@SohamRoy-01, you'll need to direct your inquiry to one of the maintainers. As for me, feel free to proceed with your work, but I lack the authority to make decisions as I'm not a maintainer.

**Comment by SohamRoy-01** [comment]
Ok @ThomasCode92.
Can I work on this issue @eddiejaoude ?

**Comment by BamaCharanChhandogi** [comment]
hello @ThomasCode92,
I am saying the link should be editable because users can enter a wrong link, so they may want to try to fix it.

**Comment by eddiejaoude** [comment]
> @BamaCharanChhandogi  I am saying the link should be editable because users can enter a wrong link, so they may want to try to fix it.

This will confusion with the stats, that is why we make it uneditable - they can create a new link in their profile

> @SohamRoy-01 My approach is pretty simple add a title attribute in the input field will do the work

Simple is good, we can make it fancier if required later on

@SohamRoy-01 I will assign it to you, thanks

**Comment by BamaCharanChhandogi** [comment]
hey, @eddiejaoude I am also available if @SohamRoy-01 doesn't want to work.
