### ISSUE TITLE
[BUG] Repeated links on Profiles

### ISSUE THREAD

**Issue by itsaakashpatel** [EddieHubCommunity/BioDrop#10223]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

Production

### Version of BioDrop (for example "v1.2.3")

2.99.13

### Description

While fixing issue #9906 I found that the current version allows repeated links for the same platform. Ideally, one link should suffice for each platform.

If this is not the case, I'm open to discussing it here.

### Steps to Reproduce

For example:

1. Go to https://www.biodrop.io/account/onboarding
2. Click on `Edit` in the `Links` section.
3. Add a new link for the platform that already exists.
4. You will see repeated links on your profile.

### Screenshots

![Screen-Shot-2024-02-06-20-08-06](https://github.com/EddieHubCommunity/BioDrop/assets/20282826/6d99ede9-2e07-412e-9a89-25df72751ec1)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

I will investigate and filter the repeated links.

**Comment by SaraJaoude** [comment]
Thank you for raising.  However we feel that it is up to the user whether they would like repeated links for the same platform or not (for example, they may have this under different categories) and not to restrict them.  Therefore I will close this issue for now.
