### ISSUE TITLE
[BUG] Biodrop showing error when viewing someone links

### ISSUE THREAD

**Issue by usmanfaki** [EddieHubCommunity/BioDrop#10237]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

production on biodrop.io

### Version of BioDrop (for example "v1.2.3")

v2.99.16

### Description

When I clicked on someone's link through X (Twitter) on android app, after a few seconds of viewing the user information and details, the site crashes and displays an application error: "A client-side exception has occurred" (see the browser console for more information).

### Steps to Reproduce

1.Go to <https://twitter.com/TimoCodes> on your x android app.
2. Click on the <biodrop.io/TimoCodez]>
3.After some few seconds the site craches.

### Screenshots

![Screenshot_20240216-222717](https://github.com/EddieHubCommunity/BioDrop/assets/64983488/d5bafde5-7f1e-4e19-bd54-d8518049a3f9)

### Do you want to work on this issue?

No

**Comment by SaraJaoude** [comment]
Thank you for raising. We have not been able to replicate this so I am marking this as `talk: discussion` to see if anyone else can.

**Comment by usmanfaki** [comment]
@Shahbaz898414  have you tried replicating the issue?, because it's still crashing from my end if click on someone's Biodrop link or my link through x(twitter) using Android.

**Comment by SaraJaoude** [comment]
> can i work on this issue??

@Shahbaz898414 please familiarise yourself with this project's [Contributing Guide](https://github.com/EddieHubCommunity/BioDrop/blob/main/CONTRIBUTING.md).  Issues are not ready to be worked on until they have the label `status: ready for dev`.

**Comment by ArvindParekh** [comment]
I tried replicating the issue but it works fine for me. @usmanfaki what happens when you try to open that page again in a new browser?

**Comment by usmanfaki** [comment]
It will go the Biodrop page and open for like 3 seconds, but then it will crash.@ArvindParekh

**Comment by eddiejaoude** [comment]
I cannot replicate either

**Comment by Naresh-chandanbatve** [comment]
not able to replicate either.

**Comment by ChinmayMhatre** [comment]
Cannot replicate it with the steps given in the description.

**Comment by eugene4545** [comment]
Couldn't recreate the issue

**Comment by eddiejaoude** [comment]
I tested it again and I could not replicate it. Maybe it is their browser plugin or similar. I will close for now as no one else can replicate either
