### ISSUE TITLE
[BUG] <Change Twitter Logo to X>

### ISSUE THREAD

**Issue by MaorBemdoo** [EddieHubCommunity/BioDrop#10240]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

On user's profile page

### Version of BioDrop (for example "v1.2.3")

v2.99.16

### Description

An issuse was raised before(#9971) but it was on the qrcode modal(by the way it is resolved and closed)

But on a user's profile page all twitter logo's are not yet updated to the X logo

### Steps to Reproduce

- Go to any user's profile page e.g biodrop.io/username
- You notice that all twitter logo's are still the former ones and not X

### Screenshots

![BioDrop Twitter Issue schreenshot](https://github.com/EddieHubCommunity/BioDrop/assets/100993978/de22d58a-c4c1-4aaf-9c15-33916ae143d1)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

On https://github.com/EddieHubCommunity/BioDrop/blob/main/components/Icon.js file all users that used FaTwitter or SiTwitter on their json file will be updated to FaTwitterX before it is fetched

**Comment by SaraJaoude** [comment]
Thank you for raising. 

Each individual user can - if they wish - update their Twitter logo from the flappy bird to the X (as this is an [available icon](https://www.biodrop.io/icons?keyword=twitter)) by editing the icon.

The logo was not updated automatically as there are some users who do not wish to make this change. 

Therefore I will close this issue.
