### ISSUE TITLE
[BUG] Typo in `pages/icons.js`

### ISSUE THREAD

**Issue by badrivlog** [EddieHubCommunity/BioDrop#10249]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

production

### Version of BioDrop (for example "v1.2.3")

v2.99.16

### Description

i found a typo in the project while walking through the codebase.
Here are the details:
**File name**: pages/icons.js
**Line number**: 66
**Current text**:  filterredIcons
**Suggested correction**: filteredIcons

### Steps to Reproduce

1. Navigate to `pages/icons.js`
2. Go to line 66
3. Observe typo in the variable name

### Screenshots

![Screenshot (69)](https://github.com/EddieHubCommunity/BioDrop/assets/73095526/bc0a21ec-f2f2-4223-acbb-0b77f169f63d)

### Do you want to work on this issue?

No

**Comment by sital002** [comment]
Good spot 👍

**Comment by PrajvalaRC** [comment]
Can I work on this?

**Comment by sital002** [comment]
> Can I work on this?

Assigning the issue to you

**Comment by bagenigilbert** [comment]
can i work on this

**Comment by sital002** [comment]
> can i work on this

We appreciate that you want to work on this issue but please check the assignee section before asking for the issue to be assigned. Please familiarize yourself with our contributing guidelines  https://github.com/EddieHubCommunity/BioDrop/blob/main/CONTRIBUTING.md
