### ISSUE TITLE
[FEATURE] scroll-to-top button 

### ISSUE THREAD

**Issue by Harsh12Codes** [EddieHubCommunity/BioDrop#10289]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

While browsing the BioDrop website, I noticed the need for a scroll-to-top button to easily return to the top of the page. Currently, users must manually scroll to the top, which can be inconvenient.

### Proposed Solution

www.eddiehub.org has a button at the bottom right corner , similar to that 
Like this : 
[Proposed solution for biodrop issue.webm](https://github.com/EddieHubCommunity/BioDrop/assets/83909388/c739f8a9-dc91-4323-bcde-e738914b63d7)

### Screenshots

![proposed solution example](https://github.com/EddieHubCommunity/BioDrop/assets/83909388/3a6369a2-3dd1-4781-a86d-713938f43dba)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

I would like to add a scroll-to-top button (like the help button which is a link) to each page with a fixed position above the help button. When a user clicks on the button, it should take them to the top of the page. I would like to add  this feature  on most pages( main, search, repos, pricing, events)

if you have a better idea I would like to hear it.

**Comment by ChinmayMhatre** [comment]
This issue and been discussed before and deemed not required. Thank you for raising the issue, please check the closed issues to avoid duplicates in the future
