### ISSUE TITLE
[BUG] Manage profile page button is disabled

### ISSUE THREAD

**Issue by MaorBemdoo** [EddieHubCommunity/BioDrop#10291]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

Production on biodrop.io

### Version of BioDrop (for example "v1.2.3")

v2.99.18

### Description

The Button Component on the manage profile page of a user is disabled ~~as a premium member~~

### Steps to Reproduce

1. As a pemium user go to [manage profile](https://www.biodrop.io/account/manage/profile)
2. After editing your profile the button becomes disabled

### Screenshots

https://github.com/EddieHubCommunity/BioDrop/assets/100993978/aed58d65-8ad3-414a-8a42-1158235b00ab

### Do you want to work on this issue?

No

**Comment by eddiejaoude** [comment]
I could not replicate this, can someone else please try and confirm?

**Comment by sital002** [comment]
the button is only  disabled when I try to add tag editing other fields doesn't seem to affect it

**Comment by sital002** [comment]
Thanks for raising the issue I will look into it.

**Comment by eddiejaoude** [comment]
Merged PR
