### ISSUE TITLE
[FEATURE] Add 404 page to all pages in a users account/* path

### ISSUE THREAD

**Issue by MaorBemdoo** [EddieHubCommunity/BioDrop#10292]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

If a user already has a json file, you are adviced on the forms to continue using your json file while if you use the forms and you try to make a pr for your json file, the gh workflow for accounts fails, telling you you are already on the biodrop database so continue using forms. I have tried both so this is from experience

### Proposed Solution

I suggest instead of telling a user to keep using their json file on their forms page(and yet they still edit on their forms page), all routes in account/ should redirect to a 404 page or say somthing like delete your json file first

### Do you want to work on this issue?

No

**Comment by amandamartin-dev** [comment]
I am not sure I am following and I think a 404 page would be very confusing to folks. 

When I go to edit my profile in forms, there is a notification letting me know that I have a json file still and I should delete it. Do you not see this?
![delete-json-message](https://github.com/EddieHubCommunity/BioDrop/assets/97615019/64483fce-635e-4bf6-8bd1-948d281e386c)

**Comment by MaorBemdoo** [comment]
I understand, my suggestion was that instead of advicing a user to delete their json data all routes to edit their profile on forms should redirect to a page telling them to keep using their json file(i.e they should not be able to edit on the forms)

**Comment by amandamartin-dev** [comment]
> I understand, my suggestion was that instead of advicing a user to delete their json data all routes to edit their profile on forms should redirect to a page telling them to keep using their json file(i.e they should not be able to edit on the forms)

Users are allowed and encouraged to use forms regardless of if they started with the json profile. We would not want to discourage this, but if you think there is a way to make it more clear that you should use one or the other?

**Comment by eddiejaoude** [comment]
Thank you for the collaboration and discussion. I think for now, I will close this issue as I think it will cause more confusion.
