### ISSUE TITLE
[FEATURE] Change the hover color of the light/dark mode and github icon

### ISSUE THREAD

**Issue by Abiheb** [EddieHubCommunity/BioDrop#10305]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Currently, there is inconsistency in the color scheme within the navbar of the application. When hovering over elements such as "Search," "Events," "Repos," "Pricing," "Login," and "Sign up," the color scheme follows a red/pink theme. However, when toggling between light/dark mode and hovering over the GitHub icon, the color abruptly changes to blue. This inconsistency detracts from the overall visual coherence and user experience of the application.

### Proposed Solution

The proposed enhancement aims to maintain consistency in the color scheme throughout the navbar. By unifying the color scheme to red/pink for all elements, including during hover states and across different modes (light/dark), the visual aesthetic of the navbar will be improved, providing users with a more cohesive and seamless experience.

### Screenshots

<img width="940" alt="github feature 2" src="https://github.com/EddieHubCommunity/BioDrop/assets/130907104/a459643f-7ddc-46f5-bcd9-8f011f295ba2">
<img height="100" alt="github feature" src="https://github.com/EddieHubCommunity/BioDrop/assets/130907104/3fbb02a6-d1c5-4226-9ffa-5e5e7552c43e">

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

To technically implement this enhancement, the CSS styles responsible for defining the colors of the navbar elements during hover states and across different modes would need to be adjusted, this could involve modifying existing CSS classes. Additionally, any JavaScript functions associated with toggling between light/dark mode or handling hover effects may need to be updated to reflect the unified color scheme.

**Comment by Vijaykv5** [comment]
I would love to work on it @amandamartin-dev

**Comment by amandamartin-dev** [comment]
> I would love to work on it @amandamartin-dev

you are assigned!

**Comment by Abiheb** [comment]
Doesn't the person who create the issue have priority for working on it, because when writing the issue it asks you wether you want to work on it or no and I specified "yes" @amandamartin-dev

**Comment by amandamartin-dev** [comment]
> Doesn't the person who create the issue have priority for working on it, because when writing the issue it asks you wether you want to work on it or no and I specified "yes" @amandamartin-dev, also I have already began working working on it and should be done within 2 days

Oh my. Apologies you are correct. Will fix the assignment. However, I would net recommend in the future working on an issue before it is unlocked in case it is modified or not approved for work. 

@Vijaykv5 I am removing your assignment. I placed you in error. Please take a look through other issues

**Comment by Abiheb** [comment]
Ok thank you

**Comment by anantha0811** [comment]
Hi @amandamartin-dev I would love to work on it
