### ISSUE TITLE
[BUG] User session should be checked on the server in Navbar

### ISSUE THREAD

**Issue by MaorBemdoo** [EddieHubCommunity/BioDrop#10313]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

Production

### Version of BioDrop (for example "v1.2.3")

v2.100.2

### Description

When you load biodrop.io especially on a slow network, the login and signup button on the Navbar show for a while before changing to the user's prfile(if the user is logged in). I feel this should be rendered on the server to prevent that flash

### Steps to Reproduce

1. Go to (biodrop.io) or refresh the page
1. The login and signup link flash for some second then change to the user;s profile picture if logged in

### Do you want to work on this issue?

No

**Comment by eddiejaoude** [comment]
Thank you for raisin the issue, but this component is on the client side, so I will close the issue for now
