### ISSUE TITLE
[BUG] remove login link from footer section

### ISSUE THREAD

**Issue by sital002** [EddieHubCommunity/BioDrop#10327]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

production

### Version of BioDrop (for example "v1.2.3")

v2.100.2

### Description

currently there is a login link on the footer even when the user is logged in 
I think we should remove it 

### Steps to Reproduce

If you know the steps, follow the below format and provide steps to reproduce

For example:

1. go to https://www.biodrop.io/
2. scroll to the footer section after while you are logged in.

### Screenshots

![image](https://github.com/EddieHubCommunity/BioDrop/assets/93700622/4d2d5f8c-f188-455e-9556-4cb8223a5e58)

### Do you want to work on this issue?

No

**Comment by MustaphaArfa00** [comment]
I want to work on it if it's not assigned to anyone

**Comment by amandamartin-dev** [comment]
> I want to work on it if it's not assigned to anyone

You are assigned. Thank you for contributing

**Comment by MustaphaArfa00** [comment]
> > I want to work on it if it's not assigned to anyone
> 
> You are assigned. Thank you for contributing

Ok , Thank you

**Comment by MustaphaArfa00** [comment]
Can you assign this issue to @MalekAchich ?

**Comment by MalekAchich** [comment]
I will gladly accept the assignment on this issue !

**Comment by MalekAchich** [comment]
@amandamartin-dev Can you assign me this issue ?

**Comment by sital002** [comment]
> @amandamartin-dev Can you assign me this issue ?

Please look at the assignee section before asking for the issue to be assigned we give contributors 2 weeks time to raise a PR and please don't tag specific maintainers.
https://github.com/EddieHubCommunity/BioDrop/blob/main/CONTRIBUTING.md

**Comment by sital002** [comment]
> @amandamartin-dev Can you assign me this issue ?

Assinging the issue to @MalekAchich

**Comment by eddiejaoude** [comment]
Pull Request merged
