### ISSUE TITLE
[BUG] Premium badge didn't appear despite being a premium user 

### ISSUE THREAD

**Issue by MustaphaArfa00** [EddieHubCommunity/BioDrop#10338]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

Production on biodrop.io

### Version of BioDrop (for example "v1.2.3")

2.100.2

### Description

Premium badge not displaying in my profile tags despite being a premium user.

### Steps to Reproduce

Here are the steps : 

1. Go to Pricing page.
2. Then Go to Upgrade
3. Subscribe to the premium service by inserting your email 
4. In your account's menu , It displays "You are now a premium user"
5. When you navigate to your profile , the premium badge doesn't appear in your profile tags

### Screenshots

![image](https://github.com/EddieHubCommunity/BioDrop/assets/156587287/1e5e7f8b-9608-4a08-affe-f33f198ddee1)

![image](https://github.com/EddieHubCommunity/BioDrop/assets/156587287/ad285f78-39e7-4397-8629-644b07ffb199)

### Do you want to work on this issue?

No

**Comment by ChinmayMhatre** [comment]
@eddiejaoude can you take a look at this.

**Comment by eddiejaoude** [comment]
Sure, thanks @MustaphaArfa00 and @ChinmayMhatre 👍

**Comment by eddiejaoude** [comment]
I have just checked your account @MustaphaArfa00 and it is not a premium account, that is why the badge doesn't show. So I will close this issue, but if you upgrade and the badge doesn't appear, please let us know

**Comment by MustaphaArfa00** [comment]
ok @eddiejaoude thank you for viewing this issue but why is it displaying "You are now a premium user !" ?
