### ISSUE TITLE
Design improvement footer <links in the footer could be displayed in a better way>

### ISSUE THREAD

**Issue by aminechamam2003** [EddieHubCommunity/BioDrop#10336]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

The links in the footer are not explicitly displayed as links, and the titles above the links (Solutions, Support, Community and Legal) are shown in a very similar way as the elements below them.

### Proposed Solution

Increasing the size of the titles (Solutions, Support, Community and Legal) and highlighting the link when the cursor is above would be a good way to make it clearer for the user.

### Screenshots

![footer biodrop](https://github.com/EddieHubCommunity/BioDrop/assets/62776155/e4e48860-a1fa-46e3-9742-6f5753d27783)
![Highlight improv](https://github.com/EddieHubCommunity/BioDrop/assets/62776155/13eb7f47-bf2c-41fd-8846-767b030499d0)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

i will increase the size of the header in a way that looks good and make so that when the cursor is above a link element, it highlights the link in the same red as the BioDrop logo.

**Comment by eddiejaoude** [comment]
Thank you for the suggestion. This came from a Tailwind template. We are not changing the design for now, so I will close the issue
