### ISSUE TITLE
[BUG] Navbar hidden when toggled on medium screen size

### ISSUE THREAD

**Issue by vneogi199** [EddieHubCommunity/BioDrop#10332]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

production

### Version of BioDrop (for example "v1.2.3")

v2.100.2

### Description

When the screen width is medium (768px to 1023px) on toggling the Navbar header, the contents are not visible.

### Steps to Reproduce

1. Go to https://www.biodrop.io/
2. Change window size to medium (between 768px to 1023px)
3. Click the drawer icon on the Navbar to expand the contents of Navbar
4. The contents do not show up

(the contents do show up for small or large screen sizes)

### Screenshots

<img width="729" alt="image" src="https://github.com/EddieHubCommunity/BioDrop/assets/20491952/b825cf72-7a3c-4e3a-8d53-a457e2f461a3">

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

`md:hidden` class is applied which causes it to be hidden. Removing the class fixes the issue.

<img width="605" alt="Screenshot 2024-04-12 at 12 54 04 AM" src="https://github.com/EddieHubCommunity/BioDrop/assets/20491952/b14b0118-3632-42fc-9c35-2cb567391e06">

**Comment by amandamartin-dev** [comment]
Good catch - it appears there is a display:none on the menu for that viewport.  You have asked to work on this so I will assing you.  If you are no longer able to please let us know so someoe else can work on it

**Comment by eddiejaoude** [comment]
PR merged
