### ISSUE TITLE
[BUG] Links under "Your links" in the Statistics page are not clickable/do not redirect

### ISSUE THREAD

**Issue by MalekAchich** [EddieHubCommunity/BioDrop#10334]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

Production

### Version of BioDrop (for example "v1.2.3")

v2.100.2

### Description

When on the profile statistics page, the links under "Your links" are not clickable and do not redirect to that URL.

### Steps to Reproduce

Steps to Reproduce:

1. Go to your profile page.
2. Click on Statistics to go there.
3. Scroll down to the very end of the statistics until you see your links under "Your links".
4. URLs under "Your links" are not clickable.

### Screenshots

https://github.com/EddieHubCommunity/BioDrop/assets/147720951/b8a4570a-b4cd-4345-864f-0d199e9d7c8a

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

under pages\account\statistics\index.js, inside: 

`<tbody className="divide-y divide-primary-low dark:divide-primary-medium bg-white dark:bg-primary-high">
            {data.links &&
              data.links.individual.map((link) => (
                <tr key={link._id}>
                  <td className="md:whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-primary-high dark:text-primary-low sm:pl-6 text-ellipsis overflow-hidden">
                    {session && session.accountType === "premium" && (
                      <Link href={`/account/statistics/link/${link._id}`}>
                        {link.url}
                      </Link>
                    )}
                    {session && session.accountType === "free" && (
                      <>{link.url}</>
                    )}
                  </td>
                  <td className="whitespace-nowrap px-3 py-4 text-sm text-primary-medium dark:text-primary-low">
                    {abbreviateNumber(link.clicks)}
                  </td>
                </tr>
              ))}
          </tbody>`

* Replace the Link component with an a tag using href attribute.

**Comment by eddiejaoude** [comment]
Thank you for the suggestion. 

But these links do not go anywhere on the free account, but on premium they redirect to get more detailed statistics of that url. So I will close this issue for now.
