### ISSUE TITLE
[BUG] Cannot save profile after adding tags

### ISSUE THREAD

**Issue by Abiheb** [EddieHubCommunity/BioDrop#10337]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

Production on biodrop.io

### Version of BioDrop (for example "v1.2.3")

v2.100.2

### Description

When attempting to add new tags to my profile, I am unable to save the changes. The interface does not indicate any specific error, but the new tags are not retained when saving the profile.

### Steps to Reproduce

Steps to Reproduce:

1) Log in to your account on biodrop.io.
2) Navigate to your account settings by selecting your profile icon.
3) In the account settings, go to "Profile."
4) Click the "Edit" button next to your profile information.
5) Scroll down to the "Tags" section.
6) Begin typing new tags in the provided input field, ensuring to use the correct syntax as requested.
7) Once you have entered your desired tags, click the "Save Changes" button.

### Screenshots

<img width="563" alt="github bug 1" src="https://github.com/EddieHubCommunity/BioDrop/assets/130907104/42221b88-7ce5-40e2-a668-1fbcb010a34e">
<img width="437" alt="github bug 2" src="https://github.com/EddieHubCommunity/BioDrop/assets/130907104/520ce34c-771f-4d7f-806f-c5c4c621054a">

### Do you want to work on this issue?

No

**Comment by ChinmayMhatre** [comment]
Issue can be replicated when pressing the enter key. The button doesn't get disabled when using comma .
<img width="808" alt="image" src="https://github.com/EddieHubCommunity/BioDrop/assets/51131670/cfd95305-6823-420a-8ece-d9faec9ca28b">
can be an issue with this handler

**Comment by Abiheb** [comment]
Do you confirm that im not the only one that has this issue?

**Comment by feres7** [comment]
I tested this issue it happens when adding tags by pressing enter its disabling the save button but works when using comma to add tags as @ChinmayMhatre said also there is another bug related to that handler tags can be duplicated I can work on this and fix both of this bugs could you assign this work to me I will open another issue for the bug related to tags duplication

**Comment by MustaphaArfa00** [comment]
I tested this issue and when you add an apostrophe ' to the tag the save button becomes disabled

**Comment by feres7** [comment]
nevermind someone already reported this bug and linked a pull request #10291 #10315

**Comment by ChinmayMhatre** [comment]
closing this as duplicate
