### ISSUE TITLE
[BUG] Premium Activation Bug: Trial Not Granted

### ISSUE THREAD

**Issue by MustaphaArfa00** [EddieHubCommunity/BioDrop#10352]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

Production on biodrop.io

### Version of BioDrop (for example "v1.2.3")

2.100.2

### Description

Upon upgrading to BioDro Premium, a message displays "You are now a premium user" to users without receiving the 30-day trial period as promised. Instead of displaying an error message, the system inaccurately confirms premium status without initiating the trial, leading to confusion and a lack of a trial for users.

### Steps to Reproduce

Click the "Upgrade" button to proceed.
Upon clicking, you'll be redirected to a new page.
On this page, you'll encounter an offer to try BioDro Premium with a 30-day trial period before subscription at $5/month.
You'll see the option to "Start Freely". Upon selecting this, you can input your email address. A message will confirm your trial's duration until 23/05/2023(which is 1 month from today ).
After entering your email, a green button will activate with the message "You are now a premium user". However, the trial isn't activated as expected.
Rather than showing an error message, the page displays "You are now a premium user" despite the trial not being activated.

### Screenshots

![image](https://github.com/EddieHubCommunity/BioDrop/assets/156587287/1121d427-86c8-423a-98a0-90de063d7b32)
![image](https://github.com/EddieHubCommunity/BioDrop/assets/156587287/658749a8-85d1-4f5c-8a2c-9308014e31b7)
![image](https://github.com/EddieHubCommunity/BioDrop/assets/156587287/fa37e15a-82f3-45ad-8044-b14a25dfb0af)
![image](https://github.com/EddieHubCommunity/BioDrop/assets/156587287/5da343a7-3493-4e27-84ca-490d6d7656db)

### Do you want to work on this issue?

No

**Comment by eddiejaoude** [comment]
Sorry for the inconvenience, I will look into this and see if I can upgrade your account for 30 days myself

**Comment by MustaphaArfa00** [comment]
> Sorry for the inconvenience, I will look into this and see if I can upgrade your account for 30 days myself
> 
> ℹ️ **eddiejaoude** has some opened assigned issues: 🔧[View assigned issues](https://github.com/EddieHubCommunity/BioDrop/issues?q=is%3Aopen+is%3Aissue+assignee%3Aeddiejaoude)

ok thank you

**Comment by eddiejaoude** [comment]
Because BioDrop is being closed down on the 10th of June, every user now has all Premium features (excluding custom domain) and payment has been removed.

So I will close this issue.
