### ISSUE TITLE
[FEATURE] Addding language translation option to the website

### ISSUE THREAD

**Issue by Abiheb** [EddieHubCommunity/BioDrop#10353]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Currently, the BioDrop community consists of users from various countries, some of whom may not be proficient in English. This language barrier can hinder their ability to fully engage with the platform's content and features.

### Proposed Solution

Introduce a language translation feature that enhances user accessibility and inclusivity. This feature will include:

Country Selector Dropdown: Implement a dropdown menu listing various countries.
Language Translation: Upon selecting a country, the entire page's content will be translated into the corresponding language.
Initial Implementation: Begin with translating the platform into French, considering its widespread usage and relevance in international contexts.
Future Expansion: Depending on the success and user feedback, consider adding support for additional languages.

Here is an image example of how i see it.

![image](https://github.com/EddieHubCommunity/BioDrop/assets/130907104/39520849-d1ca-42b4-9b89-9e230318db50)

### Screenshots

<img width="935" alt="image" src="https://github.com/EddieHubCommunity/BioDrop/assets/130907104/96305820-c0cd-48a7-8ea9-1577045059e4">

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

First, create a country selector dropdown dynamically populated with options. Upon country selection, trigger JavaScript to interact with a translation API such as Google Translate, translating the page content into the chosen language. Initially focusing on French, configure the API to default translations to French when selecting France, ensuring translation quality meets user expectations. Future expansion involves collecting feedback for potential language additions, updating the dropdown and translation API accordingly.

**Comment by eddiejaoude** [comment]
Thank you for the suggestion. Adding language functionality is a big architecture decision and not only a drop down selector.

As we do not have the capacity to re-architect the project to handle multiple languages and also get it translated, I will close this issue for now
