### ISSUE TITLE
[BUG] <Url not redirecting to particular profile>

### ISSUE THREAD

**Issue by parthamk** [EddieHubCommunity/BioDrop#10402]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

Github

### Version of BioDrop (for example "v1.2.3")

3.4.2

### Steps to Reproduce

NA

### Screenshots

NA

### Do you want to work on this issue?

No

**Comment by eddiejaoude** [comment]
Hi, the project was closed down a while ago, you can read more about it in the README - we extended the hosting even more than the announcement for this reason

In addition to social posts about the project, an email was sent 1 month before going offline to notify everyone that theu should stop using BioDrop (which was 2 months before now)

Thank you for using BioDrop, but the sun has now set on the project
