### ISSUE TITLE
[FEATURE] Standup timeline

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/BioDrop#2372]
### Description

I think to hold ourselves accountable, we could have a "standup" tab that has a timeline with...

- what I did yesterday
- what I want to do today
- any blockers

This could be done via the database or via issue templates and a GitHub Action similar to testimonials 🤔  (this data will grow fast)

- Information could be created by using an Issue template and GitHub Action
- Display in another tab in the user's profile
- Have a new page to display everyone's standup for the last 2 days (with link back to their profile)

IDEA
- limit of 2 per day?

**Comment by KlausMikhaelson** [comment]
sounds amazing @eddiejaoude !, can I work on this feature ?

**Comment by eddiejaoude** [comment]
@KlausMikhaelson this requires some more thought on how we do it, I would suggest to select another issue for now

**Comment by KlausMikhaelson** [comment]
got it !

**Comment by SaraJaoude** [comment]
Great idea but as this would require a lot of management of the content to ensure that it would be kept professional/not offensive and as we have other more highly requested features, I will close this for now.
