### ISSUE TITLE
[FEATURE] Users Events Mobile - filter UI improvement 

### ISSUE THREAD

**Issue by Aadarsh805** [EddieHubCommunity/BioDrop#3435]
### Description

same as #2902 but for user events under user profile

### the filter options take all the screen

![image](https://user-images.githubusercontent.com/95094057/212473212-694f890e-bd40-4f64-a193-8001d1cfcfa4.png)

### Additional information

We can have tabs for this too, as it is going to be changed in community events also
check the pr on #2902 for how it'll look for community events
We can have the same for User Events as well

**Comment by SaraJaoude** [comment]
Tabs under tabs will not look good.  

We need to explore other possible options.

**Comment by amandamartin-dev** [comment]
> We need to explore other possible options.

What about radio buttons, checkboxes, or toggles?  There are Tailwind UI components for all 3 of those options if we do like any of them.

**Comment by ArnabChatterjee20k** [comment]
I want to work on this issue.
Can you bit elaborate what will be final result?

**Comment by amandamartin-dev** [comment]
> I want to work on this issue.
> Can you bit elaborate what will be final result?

Hello! Please note the tags as this is in discussion and not yet at "ready for dev" so it will not be assigned.  If you have a proposed solution please share it.  Once one is accepted, then a maintainer will adjust the status to ready for dev.

**Comment by mrravipandee** [comment]
what will be final result?

**Comment by amandamartin-dev** [comment]
> what will be final result?

No solution has been agreed upon yet. the purpose of this discussion is to discuss options. Please read through the conversation so far and add a potential solution to the conversation if you ahve an idea

**Comment by hi-Kartik2004** [comment]
I think this issue is already solved, please correct me if I am wrong...

**Comment by SaraJaoude** [comment]
> I think this issue is already solved, please correct me if I am wrong...

@hi-Kartik2004 thank you - you are right, this has been fixed so I will close this issue.
