### ISSUE TITLE
[FEATURE] Able to follow someone

### ISSUE THREAD

**Issue by Ananya2001-an** [EddieHubCommunity/BioDrop#4795]
### Description

It would be great if we can allow LinkFree users to follow someone's profile so that if that person updates their profile like adds events or testimonials then we can see them and maybe also react to those updates. It's a big feature but probably will make LinkFree much more interactive.

**Comment by SaraJaoude** [comment]
Yes this is a great idea and it is on our roadmap. I block for now until some other features are completed.

**Comment by Ananya2001-an** [comment]
Hey @SaraJaoude what are these points labels. Just curious 🤔

**Comment by SaraJaoude** [comment]
> Hey @SaraJaoude what are these points labels. Just curious 🤔

@Ananya2001-an Have a look at this page in Docs: https://linkfree.eddiehub.io/docs/contributing/labels

**Comment by Ananya2001-an** [comment]
> > Hey @SaraJaoude what are these points labels. Just curious 🤔
> 
> @Ananya2001-an Have a look at this page in Docs: https://linkfree.eddiehub.io/docs/contributing/labels

I just studied about the points system for agile planning in college recently and I can't believe how I forgot about it so easily 😅

**Comment by psavan1655** [comment]
> > > Hey @SaraJaoude what are these points labels. Just curious 🤔
> > 
> > 
> > @Ananya2001-an Have a look at this page in Docs: https://linkfree.eddiehub.io/docs/contributing/labels
> 
> I just studied about the points system for agile planning in college recently and I can't believe how I forgot about it so easily 😅

Hey @Ananya2001-an @SaraJaoude If you start working on it. would love to be part of thought process and implementation of this feature. How we will handle it and thoughts regarding the scalability of it too with MongDb.

**Comment by SaraJaoude** [comment]
> Hey @Ananya2001-an @SaraJaoude If you start working on it. would love to be part of thought process and implementation of this feature. How we will handle it and thoughts regarding the scalability of it too with MongDb.

@psavan1655 thank you for your interest in working on this. This issue remains blocked for the moment so please keep an eye out for when the labels change.  You can then be asked to be assigned this in a comment - if you do so it is best not to  tag a particular maintainer: all maintainers can assign and will do so accordingly to their availability and timezone.

**Comment by MadhuSaini22** [comment]
> > Hey @Ananya2001-an @SaraJaoude If you start working on it. would love to be part of thought process and implementation of this feature. How we will handle it and thoughts regarding the scalability of it too with MongDb.
> 
> @psavan1655 thank you for your interest in working on this. This issue remains blocked for the moment so please keep an eye out for when the labels change. You can then be asked to be assigned this in a comment - if you do so it is best not to tag a particular maintainer: all maintainers can assign and will do so accordingly to their availability and timezone.

I would love to work on this issue :)

**Comment by SaraJaoude** [comment]
> I would love to work on this issue :)

@MadhuSaini22 as shown in the label this Issue remains `status: blocked`.  It will not be assigned to anyone until maintainers decide the label is changed to `status: ready for dev`.

I would recommend in future you only ask to be assigned to an Issue once it has the `status: ready for dev` label, as this reduces notifications for maintainers.

**Comment by MadhuSaini22** [comment]
> > I would love to work on this issue :)
> 
> @MadhuSaini22 as shown in the label this Issue remains `status: blocked`. It will not be assigned to anyone until maintainers decide the label is changed to `status: ready for dev`.
> 
> I would recommend in future you only ask to be assigned to an Issue once it has the `status: ready for dev` label, as this reduces notifications for maintainers.

got it, Thanks Sara :)
Will keep in mind this.

**Comment by SaraJaoude** [comment]
Really great idea but we will close this for now as we have some other highly requested features we are doing at the moment.
