### ISSUE TITLE
[FEATURE] Each user to have their profile on a subdomain

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/BioDrop#5310]
### Description

For example these do urls would link to my LinkFree profile

Current url
- linkfree.eddiehub.io/eddiejaoude

Wildcard to link to people's profile `<username>.linkfree.eddiehub.io`
- eddiejaoude.linkfree.eddiehub.io

This looks like it has 2 dots, but when we start using the new domain `linkfree.io` it will not be an issue

https://www.smashingmagazine.com/2021/11/nextjs-wildcard-subdomains/

### Additional information

https://platformize.co/

https://vercel.com/guides/nextjs-multi-tenant-application

**Comment by Hoargarth** [comment]
Will the subdomain just redirect to the current url, replace the current url, or maybe both urls serve the same content?
Just asking because having both urls with same content most probably would result in duplicate content.

**Comment by eddiejaoude** [comment]
It could erve the same content like an alias or redirect

**Comment by Harrish-Selvarajah** [comment]
Hi, I would like to work on this issue.

**Comment by eddiejaoude** [comment]
This issue is marked as `blocked`, so I will lock the issue for the moment

**Comment by SaraJaoude** [comment]
After more thought we have decided to close this issue for now.
