### ISSUE TITLE
[FEATURE] hints section of features to use on your profile

### ISSUE THREAD

**Issue by ChinmayMhatre** [EddieHubCommunity/BioDrop#5669]
### Description

Many people only add links to their profile because they are unaware of the other features like milestones, testimonials and events etc

When the [PR for forms](https://github.com/EddieHubCommunity/LinkFree/pull/6998) is completed, there will be a sub navigation, so this can have its own page of "profile suggestions" (arrow in screenshot below)

<img width="1667" alt="240759736-e532b3d6-5a35-430e-b95a-7d5956b3880e" src="https://github.com/EddieHubCommunity/LinkFree/assets/624760/7303abba-eaa0-4d7e-92af-fe488370b883">

**Comment by PratikDey** [comment]
Hi, I would like to work on this issue if someone can guide me a bit.

**Comment by FrozenHearth** [comment]
This is a very good idea. Would love to see this implemented.

**Comment by Landouda** [comment]
Hello, I would be glad to work on this. can you please assign this to me?

**Comment by eddiejaoude** [comment]
I added a list of missing sections to the progress bar, maybe links could be added to the docs for each section

**Comment by ChinmayMhatre** [comment]
> I added a list of missing sections to the progress bar, maybe links could be added to the docs for each section

Great Idea!

We could to update the `profileSections` array to have the title and the links for each

```
  let profileSections = [
    "bio",
    "links",
    "milestones",
    "tags",
    "socials",
    "location",
    "testimonials",
  ];
```

Something like this :
```
  let profileSections = [
    {title:"bio",
    link:"actual link",
    },
  ];
```

then update the filter to 

```
progress.missing = profileSections.filter(
    (property) => !Object.keys(profile).includes(property.title)
  );
```

**Comment by eddiejaoude** [comment]
Sounds great 👍

**Comment by ChinmayMhatre** [comment]
> Hi, I would like to work on this issue if someone can guide me a bit.

I have put the basic overview of what could be done. I cannot assign you but you can take the issue. Let me know if you need any help

**Comment by eddiejaoude** [comment]
@Landouda would you still like the issue? if not I will assign to @MAYANKpandey14

**Comment by Landouda** [comment]
@eddiejaoude  yes please, I would still like to work on this issue.

**Comment by eddiejaoude** [comment]
Sure, I have assigned it to you @Landouda

**Comment by Landouda** [comment]
I almost am done with the implementation of the hint feature. I created a hint component and extended the profileSection object to include the URL, the description and the targeted mdx code scippets. 
here is a glimpse of the UI, is there any feedback before I push the code?
![image](https://user-images.githubusercontent.com/119908341/231626481-3849023d-3da3-439c-af0c-7cace7ecf9c9.png)

**Comment by eddiejaoude** [comment]
@Landouda it is better to make a draft PR, so we can discuss the implementation before you get to far ahead

**Comment by Landouda** [comment]
@eddiejaoude, thank you for this information. I have just created a PR and linked it this issue as a draft proposal.

**Comment by SaraJaoude** [comment]
This issue has been unassigned due to lack of activity.

**Comment by KushagraVarshney05** [comment]
can i work on this issue

**Comment by SaraJaoude** [comment]
> can i work on this issue

@KushagraVarshney05 please familiarise yourself with our [Contributing Guide](https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md) which explains why this issue cannot be assigned to you.  Namely:

1. You have already been assigned an Issue and we only assign one Issue per person
2. The label on this Issue is `status: blocked` so it is not ready to be assigned to anyone. 

As mentioned in the Description of this Issue this is also dependent on #6998 being merged before it can be worked on.

**Comment by SaraJaoude** [comment]
Closing this as we now have a progress dashboard (and we will have a full on wizard coming soon)

<img width="1635" alt="Screenshot 2023-09-30 at 18 34 35" src="https://github.com/EddieHubCommunity/BioDrop/assets/82668196/17b6b48b-1cf4-425e-bdf1-4746984a8ad1">
