### ISSUE TITLE
[Feat] Events to have tags

### ISSUE THREAD

**Issue by Abhishek-90** [EddieHubCommunity/BioDrop#5832]
### Description

~~Can we add a filter to sort the upcoming events based on the topics/tech stack being spoken about in the event. We can use tags to filter it out.~~

Events to also manage tags (add/delete - similar to Profile tags), and these are displayed on the event component.

*Edit: steps added below*
1. Event form `pages/account/manage/events.js` to have tags similar to Profile tags

https://github.com/EddieHubCommunity/BioDrop/blob/caad13ad867a663a3b57d5f8fe6085d3715eae7d/pages/account/manage/profile.js#L238-L242

<img width="1333" alt="Screenshot 2023-10-01 at 10 00 34" src="https://github.com/EddieHubCommunity/BioDrop/assets/624760/6f12f6a7-024a-492f-8a31-fb69900d6b90">

2. Save tags from new form field in the manage event API `pages/api/account/manage/event/[[...data]].js`
3. Display tags on event component `components/event/EventCard.js`

<img width="1311" alt="Screenshot 2023-10-01 at 10 06 31" src="https://github.com/EddieHubCommunity/BioDrop/assets/624760/154d8de9-59ee-4f53-9958-f116d84aec4e">

**Comment by Eclipse175** [comment]
that would be a great addition

**Comment by amandamartin-dev** [comment]
This is an interesting idea,  can you provide a design suggestion on this issue for consideration that will keep the UI/UX clear and not overcrowded as there are a few filters already?

**Comment by Abhishek-90** [comment]
Yes @amandamartin-dev, I have come up with the below design of how we can add more filters. We will need to modify the current filters into drop-down lists. 

![SS](https://user-images.githubusercontent.com/43419831/230300975-9711a153-a732-42ff-beb1-d29601d0ff1b.jpg)

Let me know, what you think of the design.

**Comment by amandamartin-dev** [comment]
> Let me know, what you think of the design.

I see what you mean.  If it is decided to go this route, there are tailwind components that accomplish this (Eddie has an account for these for this project) https://tailwindui.com/components/application-ui/forms/select-menus

This update would also require a change the the events json as well if accepted so that folks can add tags.  We will also need to decide if folks should add one or many as sometimes events are multi-track. 

The only other thought I have here (but would be cluttered in the events page likely) is that we already have a tag search component that could be reused (search/map). Something to think about for reusability/consistency but potentially not appropriate on this page

I will let Eddie and others decide, thank you for adding some more detail and a design idea!

**Comment by Abhishek-90** [comment]
Yes lets wait to see what Eddie and others have to say about.

**Comment by Abhishek-90** [comment]
Alright @eddiejaoude as you say.

**Comment by eddiejaoude** [comment]
I have updated the title and description to add more information and to separate the issue into 2 parts:
- part 1: manage tags and display on the event (this issue)
- part 2: filter events by tags (another issue)

@Abhishek-90 I saw you mentioned yesterday you are looking to get started in open source and BioDrop, we ask new contributors to start with 1-2 points issues to get familiar with the project (this is a 5 pointer)

**Comment by Dun-sin** [comment]
hi @eddiejaoude can i take this?

**Comment by SaraJaoude** [comment]
> hi @eddiejaoude can i take this?

@Dun-sin I have assigned this to you.  

In future please avoid tagging a specific maintainer when asking for an issue to be assigned.  All maintainers can assign and this helps notifications become more manageable.

**Comment by Dun-sin** [comment]
> > hi @eddiejaoude can i take this?
> 
> @Dun-sin I have assigned this to you.  
> 
> In future please avoid tagging a specific maintainer when asking for an issue to be assigned.  All maintainers can assign and this helps notifications become more manageable. 

Yes I know I just didn't know if you got notifications or not when it's not an issue you created.

Thanks for clearing it up👍🏽

**Comment by Dun-sin** [comment]
Can you give me a summary of what was concluded in this issue? Looks like there was a conclusion, tried reading it but I'm a little confused, would love a summary of things I should keep in mind

**Comment by Abhishek-90** [comment]
> I have updated the title and description to add more information and to separate the issue into 2 parts:
> 
> * part 1: manage tags and display on the event (this issue)
> * part 2: filter events by tags [[FEATURE] Filter events based on tags #9233](https://github.com/EddieHubCommunity/BioDrop/issues/9233)
> 
> @Abhishek-90 I saw you mentioned yesterday you are looking to get started in open source and BioDrop, we ask new contributors to start with 1-2 points issues to get familiar with the project (this is a 5 pointer)

Sure @eddiejaoude, but if this issue is not urgent, I can take this up as well. Might help me to understand BioDrop better.

**Comment by SaraJaoude** [comment]
> > @Abhishek-90 I saw you mentioned yesterday you are looking to get started in open source and BioDrop, we ask new contributors to start with 1-2 points issues to get familiar with the project (this is a 5 pointer)
> 
> Sure eddiejaoude, but if this issue is not urgent, I can take this up as well. Might help me to understand BioDrop better.

@Abhishek-90 this issue has now been assigned to someone else and we only assign one issue per person at any one time.  We are pleased you want to get involved with the project so do look at unassigned issues with points between 1-3 (these are also unlikely to be marked as urgent).
