### ISSUE TITLE
Add a GitHub sponsors tab?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [EddieHubCommunity/BioDrop#5929]
### What would you like to share?

on a stream discussing how folks who have their GitHub sponsors set up need to advertise it a lot. Eddie had the idea of adding support for a tab. I think that's a great idea.

Specifically, this would be a tab that shows your top sponsors from your GitHub sponsors profile.

### Additional information

Note that this isn't the same as #2310. This issue is for asking a whole tab detailing sponsorships, not a single button.

**Comment by SaraJaoude** [comment]
Not on our roadmap for now so going to close.
