### ISSUE TITLE
[FEATURE] Performance improvements to the profile page

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/BioDrop#6376]
### Description

I think there are various performance improvements we can make to the LinkFree app, but this issue is focusing on the profile page

Currently this is the workflow of the file and I think some could be off-loaded to a serverless function as to be non-blocking for the page to return the data?

1. load json file
2. load profile
3. increment profile counter
4. increment app total profile view counter
5. increment profile counter for that date
6. check for location, and fetch if cache expired

I think we need steps 1, 2 and 6, can steps 3, 4 and 5 be done async and not effect the page load time?

API file `pages/api/profiles/[username]/index.js`
https://github.com/EddieHubCommunity/LinkFree/blob/main/pages/api/profiles/%5Busername%5D/index.js

**Comment by Bharadwajshivam28** [comment]
@eddiejaoude Hello sir can you elaborate this issue

**Comment by eddiejaoude** [comment]
@Bharadwajshivam28 I have added some more information to the issue description

**Comment by Bharadwajshivam28** [comment]
> @Bharadwajshivam28 I have added some more information to the issue description

Okay sir i will check it

**Comment by ChinmayMhatre** [comment]
`users` Api route has been renamed to `profiles` 

The new api route and files are 

`pages/api/profiles/[username]/index.js`
https://github.com/EddieHubCommunity/LinkFree/blob/main/pages/api/profiles/%5Busername%5D/index.js

**Comment by eddiejaoude** [comment]
@daxitpatel thank you for your suggestion, but this issue is not about `reads` it is about `writes`, wherever we read the data from we still need to write otherwise the stats will not be recorded

**Comment by SaraJaoude** [comment]
As there have already been small improvements to this I will close for now.
