### ISSUE TITLE
[FEATURE] Release notes to include contributors?

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/BioDrop#6925]
### Description

Trying to shoutout the amazing contributors, it would be great if we can tag them in every release

**Comment by dan-mba** [comment]
My guess is that #2243 will be a prerequisite to this

**Comment by eddiejaoude** [comment]
Good point, thanks Dan 👍

**Comment by SaraJaoude** [comment]
This is a great idea but let's close for now as we have other requested features.
