### ISSUE TITLE
[FEATURE] Default tags on Search and Map

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/BioDrop#6980]
### Description

Currently the tags are created from what people add to their profile.

I think it would be great to have some specific tags always displayed, for example

- EddieHub Maintainer
- EddieHub Moderator
...

These should only be added to the user's profile by an admin to avoid confusion.

**Comment by Akhilbisht798** [comment]
We can add those tags to `getTags()` function that map and Search use to get tags so that they will be available to search and map.
For adding it profile by admin, correct me if i am wrong there are no such things as isAdmin in Profile model so someone that can add those tags is admin in github

**Comment by eddiejaoude** [comment]
After more thought on the implementation, having the default tags appear on the search page is straightforward but then performing the search when the data is not in the database would require a lot of work - I feel this does not add enough value for the effort required, so I will close for now
