### ISSUE TITLE
[FEATURE] In development have alert with button to load data

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/BioDrop#7020]
### Description

Now the json files are loaded into the DB during deployment, for local development we need to load data into the DB otherwise the app is empty

To load data we can visit a url http://localhost:3000/api/system/reload?secret=development

TODO
- only appears in development mode and not on vercel (2 checks)
- message and button to hit API and reload data
- add to layout to appear on every page
- do not use secret variable because might leak data if every display on prod, hardcode to `development`

**Comment by theunhackable** [comment]
I would like to work on this.
I just need to confirm if the assignment is to:

- alert should only appear on dev mode
- a button on the alert something like this 👇:
![image](https://github.com/EddieHubCommunity/BioDrop/assets/53367382/ad35158e-9926-4360-a2f8-0f3026562b78)
- and if the dev navigates to other page without loading the data the alert must be appear on the other pages too
- the dev must not use any local env variables to solve this issue

**Comment by eddiejaoude** [comment]
Oh this issue has been done and merged, so I will close. thank you for bringing it to my attention @theunhackable 👍
