### ISSUE TITLE
[FEATURE] Add my best Open Source contributions to stand out

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/BioDrop#7164]
### Description

Looking at someone's profile is a lot of work, hiring managers etc do have time to go into the details of your GitHub profile. We need to make it as easy as possible for them. We can do this by allowing each LinkFree profile to select 1 issue and pull request they are proud of and promote this on their profile

**Comment by NiazMorshed2007** [comment]
It would be great to have this feature on LinkFree.

**Comment by itsaakashpatel** [comment]
Nice thought @eddiejaoude 🥳

According to me, having the top 3 issues makes more sense here, and a person would be able to show the best PRs in one go. Also, HR will get to know about the top 3 works from a single place.

Thanks!

**Comment by CBID2** [comment]
To add to that @eddiejaoude, there can be a component that provides the metrics of the contribution once the person picks their favorite pull request(e.g. Created a GitHub Action that has increased productivity rates by 50%). Displaying the contribution is one thing but showing how it has **impacted** the actual project is what recruiters ultimately look for.

**Comment by shoebilyas123** [comment]
> Nice thought @eddiejaoude partying_face
> 
> According to me, having the top 3 issues makes more sense here, and a person would be able to show the best PRs in one go. Also, HR will get to know about the top 3 works from a single place.
> 
> Thanks!

One thing that occured in my mind is what if the person has been very inconsistent or not been contributing for a long time. Then their top 3 contributions are not enough then. Additionally we can also display whether is consistent as a contributor or not. Maybe this can be opened up as a separate issue or included with this one.

**Comment by CBID2** [comment]
> > Nice thought @eddiejaoude partying_face
> 
> > 
> 
> > According to me, having the top 3 issues makes more sense here, and a person would be able to show the best PRs in one go. Also, HR will get to know about the top 3 works from a single place.
> 
> > 
> 
> > Thanks!
> 
> 
> 
> One thing that occured in my mind is what if the person has been very inconsistent or not been contributing for a long time. Then their top 3 contributions are not enough then. Additionally we can also display whether is consistent as a contributor or not. Maybe this can be opened up as a separate issue or included with this one.

This is where things get complicated. Someone might have been consistent due to having a job or other issues, and I feel like having the “not a consistent contributor” label can be very off-putting to them. To improve this, I'm thinking there can be a blurb of suggestions of issues to work with based on their skillset.

**Comment by itsaakashpatel** [comment]
> > Nice thought @eddiejaoude partying_face
> > According to me, having the top 3 issues makes more sense here, and a person would be able to show the best PRs in one go. Also, HR will get to know about the top 3 works from a single place.
> > Thanks!
> 
> One thing that occured in my mind is what if the person has been very inconsistent or not been contributing for a long time. Then their top 3 contributions are not enough then. Additionally we can also display whether is consistent as a contributor or not. Maybe this can be opened up as a separate issue or included with this one.

Agree with you. But we will show the top 3 for such persons who have contributed enough. My intention is to show the best contributions to HR/ Technical Recruiter and showing only one contribution may not satisfy their expectations. Because HR or a technical recruiter wants to judge a person based on skills on different levels and that's where showing different contributions would help a person to showcase his work in a more effective way.

**Comment by CBID2** [comment]
> > > Nice thought @eddiejaoude partying_face
> > > According to me, having the top 3 issues makes more sense here, and a person would be able to show the best PRs in one go. Also, HR will get to know about the top 3 works from a single place.
> > > Thanks!
> > 
> > 
> > One thing that occured in my mind is what if the person has been very inconsistent or not been contributing for a long time. Then their top 3 contributions are not enough then. Additionally we can also display whether is consistent as a contributor or not. Maybe this can be opened up as a separate issue or included with this one.
> 
> Agree with you. But we will show the top 3 for such persons who have contributed enough. My intention is to show the best contributions to HR/ Technical Recruiter and showing only one contribution may not satisfy their expectations. Because HR or a technical recruiter wants to judge a person based on skills on different levels and that's where showing different contributions would help a person to showcase his work in a more effective way.

I think you’ll like [this discussion](https://github.com/orgs/EddieHubCommunity/discussions/7530)

**Comment by CBID2** [comment]
Another idea just came to me. Maybe there can be a component that tracks the metrical value of the chosen pull request(e.g., percentage of positive views or visitors to Linkfree). What do you think @eddiejaoude and co?

**Comment by eddiejaoude** [comment]
Not sure if possible to get that sort of metrics @CBID2 related to a specific PR and what value it would add knowing it - I think it might discourage collaboration but fosters negative competition. Most PRs are by multiple people because of the reviewers feedback and collaboration.

**Comment by CBID2** [comment]
> Not sure if possible to get that sort of metrics @CBID2 related to a specific PR and what value it would add knowing it - I think it might discourage collaboration but fosters negative competition. Most PRs are by multiple people because of the reviewers feedback and collaboration.

Ooh good point @eddiejaoude. I wonder if there's another way to showcase metrics for HR and not make the contributors feel negative about it? 🤔

**Comment by Kgkunal** [comment]
Is it open still ?

**Comment by SaraJaoude** [comment]
> Is it open still ?

@Kgkunal please familiarise yourself with this project's [Contributing Guide](https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md) as this will help you understand the labels given to each Issue.  

This issue has a label `status: awaiting triage` so it is not ready to be worked on yet (this will change when the label becomes `status: ready for dev`).

**Comment by SaraJaoude** [comment]
Closing as this will be covered by https://github.com/EddieHubCommunity/BioDrop/issues/2274
