### ISSUE TITLE
[FEATURE] Rename GitHub user

### ISSUE THREAD

**Issue by SaraJaoude** [EddieHubCommunity/BioDrop#7349]
### Description

- After the issue https://github.com/EddieHubCommunity/LinkFree/issues/7065 is done
- perform check and display alert if logged in username does not matched associated profile
- have action button to renamed all their data to match their new username
- show warning that their url will change from X to Y, but they will keep their stats
- they need to type their username to confirm

**Comment by xkrishguptaa** [comment]
What is the update on this one? Really interested for this one!

**Comment by theunhackable** [comment]
@xkrishguptaa step 1 is done so I think you can ask for this issue to be assigned

**Comment by xkrishguptaa** [comment]
I don't believe I have right now enough time to do this due to exams, but who so ever picks it up, I'm happy to guide them and help them if they face any errors.

**Comment by sidrasa** [comment]
I want to work on this issue.

**Comment by SaraJaoude** [comment]
> I want to work on this issue.

@sidrasa I have assigned this to you.

**Comment by SaraJaoude** [comment]
@sidrasa as it has been two weeks since this was assigned to you and as mentioned in our [Contributing Guide ](https://github.com/EddieHubCommunity/BioDrop/blob/main/CONTRIBUTING.md) since no Pull Request has been created, I have unassigned this from you to give someone else a chance to work on this issue.

**Comment by akash19coder** [comment]
Isn't it the case that issue #8435 simiar to the one we are talking about here?

**Comment by eddiejaoude** [comment]
Thank you @akash19coder, yes it is 👍 I will close https://github.com/EddieHubCommunity/BioDrop/issues/8435 because it is a duplicate

**Comment by Vijaykv5** [comment]
Please close this issue @eddiejaoude @SaraJaoude as it's already fixed

**Comment by eddiejaoude** [comment]
thank you @Vijaykv5 but I don't think this has been fixed, but we are not going to do it, so I will close it for now
