### ISSUE TITLE
[FEATURE] Keyboard Shortcut for search page

### ISSUE THREAD

**Issue by Mohith234** [EddieHubCommunity/BioDrop#7354]
### Description

Adding a Keyboard Shortcut in order to directly go to the search box

When focused on something else (not input box) on the search page then pressing `Ctrl + K` on windows and `Cmd + K` on mac should move the focus to the search box.

### Additional information

- I would like to work on this issue

**Comment by Mohith234** [comment]
I would like to work on this

**Comment by SaraJaoude** [comment]
@Mohith234 how are you getting on?

**Comment by Ashish-simpleCoder** [comment]
@Mohith234, 
On which page/route should this feature be added?

**Comment by SaraJaoude** [comment]
@Mohith234 due to lack of activity for two weeks I have unassigned this from you

**Comment by hankadev** [comment]
@SaraJaoude I this is still for grabs, I would like to work on this. 
I guess the "Ctrl + K" should work whenever the "Search" in navigation is shown and it should trigger going to `/search` route? :thinking:

**Comment by SaraJaoude** [comment]
Yes absolutely @hankadev I will assign this to you. 

As to your question - thanks for raising - I think it is when you are on the search page already it changes focus to the search box.  @EmmaDawsonDev what do you think?

Once we have a better understanding we can also update the title and description as it is not clear at the moment.

**Comment by EmmaDawsonDev** [comment]
Yes, I'd say it's weird to be on a page without a search and control + K triggers a page redirect. That could be super confusing to users that might not be able to see the screen. I agree with Sara that this should just be on the /search page and if you are focused on something else then pressing Ctrl + K on windows and Cmd + K on mac should move the focus to the search box.

**Comment by hankadev** [comment]
@SaraJaoude @EmmaDawsonDev Thanks for the clarification :+1:

**Comment by eddiejaoude** [comment]
Thank you @EmmaDawsonDev  👍 

@hankadev I have updated the title and description
