### ISSUE TITLE
[OTHER] Support for debugging LinkFree

### ISSUE THREAD

**Issue by raviraj-github** [EddieHubCommunity/BioDrop#7438]
### What would you like to share?

During my analysis of the LinkFree issue [here](https://github.com/EddieHubCommunity/LinkFree/issues/7065), I noticed that we currently lack any configuration for debugging purposes.

Although debugging locally in VSCode can be a bit challenging, it is still achievable. Unfortunately, I couldn't provide a solution for this matter due to personal laptop issues, as my laptop is broken, and my office laptop has several restrictions in place.

### My Analysis:
During my analysis, I discovered that this issue can be resolved by adding a configuration to the project. Please refer to the screenshot below:
![image](https://github.com/EddieHubCommunity/LinkFree/assets/11041028/9fbcc673-140f-4af9-b95b-f669c6d9a205)

For more detailed information, you can visit the following link: [Debugging in Next.js](https://nextjs.org/docs/pages/building-your-application/configuring/debugging)

### Proposed Actions:
1. I kindly request someone to try implementing this solution and, if everything works properly, push it to the repository. Also, consider adding it as a candidate for the `.gitignore` file.
2. It would be beneficial to create documentation that provides a comprehensive guide on debugging for LinkFree.

**Comment by eddiejaoude** [comment]
This is a great idea @raviraj-github , thank you 👍

**Comment by yashpandey002** [comment]
Hey @raviraj-github, I implemented the solution in my local environment and got the following results. Can you guide me on how to ensure everything is working fine? 
![image](https://github.com/EddieHubCommunity/LinkFree/assets/75162407/13ca24f3-4a18-47da-815c-35fa9c26049a)

**Comment by raviraj-github** [comment]
**Steps to debug:** 

1. To begin the debugging process, kindly set a breakpoint at the desired location. In my case, I have added it in the event.js file for testing server-side JavaScript.
2. Please observe the highlighted breakpoint, marked with number 2.
3. Proceed by starting your application with the server-side profile. We have configured three profiles: Server Side, Client Side, and Full Stack. Please select the profile that best suits your use case.
4. As part of the process, please check the terminal to ensure that your VS Code IDE is successfully connected to the debug port. This is indicated with number 4.
5. Once the application is up and running, kindly log in and navigate to the desired flow that requires testing. In my case, it involves checking events in the graphical user interface and debugging them. Upon clicking on that specific flow, you will notice that the debug pointer stops at the first breakpoint. Now, you are ready to proceed with your debugging journey. If you are new to debugging, I recommend searching for YouTube videos on debugging Next.js apps in VS Code. You will find valuable resources to assist you.



![debug-linkfree](https://github.com/EddieHubCommunity/LinkFree/assets/11041028/132f1bff-a3ca-46ed-831e-0d3274a33dca)


If, by any chance, your debugger is not functioning properly, I suggest referring to this link([Debugging in Next.js](https://nextjs.org/docs/pages/building-your-application/configuring/debugging)) for additional details. You may need to make some adjustments to your configuration. Rest assured, with a little tweaking, it will certainly work.

After completing the task, please feel free to request to have this issue assigned to your name and proceed with pushing the code.

We greatly appreciate that you have begun working on it. We have full confidence in you and rely on your expertise. Thank you sincerely for your efforts!

Happy Coding!

**Comment by SaraJaoude** [comment]
@yashpandey002 I have assigned this to you but if you do not want this issue then please unassign yourself.

**Comment by yashpandey002** [comment]
Thanks @SaraJaoude for considering me for this issue, although I am not a pro and have some doubts related to the issue but I will do my best to resolve it by seeking help from other contributors🙌

**Comment by yashpandey002** [comment]
[client-side.webm](https://github.com/EddieHubCommunity/LinkFree/assets/75162407/d4974806-f377-4c2e-85a8-026c9fcd0245)

@raviraj-github, I think it is working fine. I have checked all three profiles and didn't find any issue while debugging, is there any thing missing?

**Comment by yashpandey002** [comment]
Hey @raviraj-github, I am having some doubts regarding committing the changes, actually the .vscode folder is added in gitignore file so when I am trying to commit my changes git is not tracking the .vscode folder. 

Should I remove .vscode from gitignore and then make a PR?

**Comment by SaraJaoude** [comment]
Unassigned as PR closed for lack of activity (see: https://github.com/EddieHubCommunity/LinkFree/pull/7694)

**Comment by raviraj-github** [comment]
Apologies for the delayed response regarding this matter. I was preoccupied with personal matters and office-related tasks.

I believe it would be beneficial to include detailed documentation for debugging instead of adding the .vscode folder directly to the project. This way, anyone in need of debugging our application can simply copy the provided configuration locally and initiate the debugging process.

Currently, I am working on issue #7065. Once I have completed that task, I will take care of this one unless someone else has already taken it up by then.

**Comment by ArthVhanesa** [comment]
> I believe it would be beneficial to include detailed documentation for debugging instead of adding the .vscode folder directly to the project. This way, anyone in need of debugging our application can simply copy the provided configuration locally and initiate the debugging process.

or else we can comment out `.vscode` from `.gitignore` locally and add only `.vscode` folder in a commit, then uncomment `.vscode` from `.gitignore`. It will add only `.vscode` folder in a commit without changing `.gitignore` file. 

I think this way anyone can debug without adding any additional files locally as well as `.vscode` won't get unnecessary changes when someone does commit as we have `.vscode` in `.gitignore`.

Open for discussion. 
I would like to work on this issue. Please assign this to me.

**Comment by SaraJaoude** [comment]
@ArthVhanesa I have assigned this to you

**Comment by ArthVhanesa** [comment]
As this change also requires updating the docs, should I add docs at this route `LinkFree/pages/docs/contributing` as debugging(dot)mdx? If No, then where else should I add the docs?

**Comment by SaraJaoude** [comment]
@ArthVhanesa yes, but probably best to use the file for the new docs `pages/docs/contributing/debugging.mdx`
