### ISSUE TITLE
[FEATURE] Log all database changes

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/BioDrop#7660]
### Description

Each time there is a db write/update, have a log collection with the following info

- username
- collection
- collection id
- changes before
- changes after
- date

This can be achieved with the `pre` middleware hook on the models https://mongoosejs.com/docs/middleware.html

**Comment by Atharv-Nalwade** [comment]
I know the logic behind and I can do it.
I just have never worked in an Open Source setting 
If allowed and explained the problem in detail would be a kickstart in my opensource journey.

**Comment by SaraJaoude** [comment]
> I know the logic behind and I can do it.
> I just have never worked in an Open Source setting
> If allowed and explained the problem in detail would be a kickstart in my opensource journey.

@Atharv-Nalwade thank you for your enthusiasm. However it would be best to start your open source journey with requesting to be assigned an issue with the label `good first issue` (you can find the list [here](https://github.com/EddieHubCommunity/LinkFree/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22)) and `points:1`

**Comment by babblebey** [comment]
Hi Sara, I can try patch this feature, if you assign me.

**Comment by SaraJaoude** [comment]
> Hi Sara, I can try patch this feature, if you assign me.

@babblebey I have assigned this to you

**Comment by eddiejaoude** [comment]
This is a really challenging ticket, great to see what you have achieved already 💪 

I will try to share my thoughts with my limited knowledge.

> First Blocker: In reference to the my implementation, the manner in which I picked the username property for the changes logged, I have since discovered that the username property will be undefined in the model that either doesn't have the username property in its document schema or doesn't use the username property in their query conditions. I have tried to implement getting the username to fill for this leveraging our auth mechanism in NextAuth, having tried the getServerSession() but I'm not able to figure it out.

I think we can pass extra parameters with each query, can we pass through the username?

> Second Blocker: This references to the changesAfter part of my implementation, I am able to straight-up select the document when !isUpdateOperation using this and within the context of my implementation to the LinkSchema, I was initially able to the update document after update using the findOne function and the query itself when isUpdateOperation. This in-turn stopped working and now picks thesame value as changesBefore (I thought that was only correct considering I was using the same logic to get both changesBefore and changesAfter); Hence I thought of introducing the post middleware hook, since this is executes after the pre middleware and db changes is completed for the related function.

On the `post` hook (I mention `pre` in the issue description but I think I meant `post`) you can use `doc` for the current document before the update and then `this.getUpdate()` to get the changes

> The Blocker: I am getting the error below for the on the query for changesAfter, its as though my schema variable that should receive the schema from the Models isn't really treated as a Model.

I will have to see this and have a play, I am not sure - maybe create a `draft` pull request?

> I still haven't figured out how to get the collection_id

Is this not `doc._id`? 

> Also, how to handle the username in the cases of usage within a Model that doesn't have the property in its document schema or in its query condition.

I think we can pass this on all queries as an extra parameter

**Comment by eddiejaoude** [comment]
> To pass the extra data...

I can't seem to find it but I definitely read it somewhere before 🤔 

---

> ...and even behave worse when its executes for the LinkStats schema, return just the incrementBy value 1 in the $setOnInsert, nothing readable.

Sorry I should have mentioned, for the incremented data, we can ignore this as I don't think it is important

~~Ignore changes on the models...~~
- ~~ProfileStats~~
- ~~LinkStats~~
- ~~Stats~~

Actually only track changes on the models that the user can change via the forms directly...
- Profile
- Link

---

> Haha, I'm not getting excited yet... I have only tested so far with 3 models (Link, LinkStats and Profile) so far at my time of comment.

That is great 💪

**Comment by babblebey** [comment]
> Actually only track changes on the models that the user can change via the forms directly... Profile and Link

If that's the Case, the PR is just ready... The Middleware functions works perfectly tracking changes within those collection.

On Edit/Action action (i.e. `save` or `findOneAndUpdate`) in the `Link` collection, a change also occurs in the `Profile` collection too, hence the `dbChangesLoggerMiddleware` function logs two changes object; one for the `Link` itself and the other for the `Profile` in acknowledge of the link's `id` that gets added/updated to/on the `links` property array on the `Profile` document.

______

Quick Question: Have we concluded to use the `doc._id` in place of the `collection_id`?

**Comment by eddiejaoude** [comment]
> If that's the Case, the PR is just ready... The Middleware functions works perfectly tracking changes within those collection.

awesome 🎉 

> If that's the Case, the PR is just ready... The Middleware functions works perfectly tracking changes within those collection.

Are they not the same value? or did I mis-understand?

**Comment by babblebey** [comment]
> Are they not the same value? or did I mis-understand?

Ummm, I don't think so;

Here's a screenshot separating document's `doc._id` from collections `collection_id` (I even now think that there's no such property at all)

![image](https://github.com/EddieHubCommunity/LinkFree/assets/25631971/d911042d-0f2d-4b57-8c12-6c874e5c4caa)

- There are `collections`, that holds a list of `documents`; the currently in view collection is the `links` collection
- Then there are lists of `documents` held within that `collection`
- Each/Individual document owns an `id` and that is the `doc._id`
- But, I don't see an `id` for `collection`, so I don't think a `collection_id` exists in mongo now

Now, In the case where you might agree that we stick to the `doc._id` in place of `collection_id`, I will suggest we just do away with it entirely because the `changeBefore` and `changesAfter` properties of the logged changes already holds the `doc._id` in there `changeBefore._id` and `changesAfter._id` respectively.

```shell
username: "babblebey"
collection: "links"
collection_id: "in progress...."
changesBefore: {
  "_id": "64d39c0a2c5a0394990e8dd0",
  ......
}
changesAfter: {
  "_id": "64d39c0a2c5a0394990e8dd0",
  .......
}
date: "2023-08-10T15:35:51.136Z"
```

What do you say, remove `collection_id` from the logged changes?

**Comment by eddiejaoude** [comment]
Sorry, yes I was thinking that `collection_id` is `doc._id`, so it would be... `collection_id: doc._id`

Therefore when/if we want to find the referencing document, we would use `collection` and `collection_id`.

**Comment by babblebey** [comment]
Oh I get that 100%, so we will be keeping that part, but

> Therefore when/if we want to find the referencing document....

Don't you think the naming `collection_id` is a little off in context of _"finding the referencing document"_.

IMHO the term `collection_id` has confused me enough right here so much now I don't see where it fits in that context, I would suggest instead that a `collection` and `doc` referenced ofcourse by its `id` seats better in that context. This way our logged changes object would look like...

```shell
username: "babblebey"
collection: "links" 
doc: "64d39c0a2c5a0394990e8dd0" // <- Reference a Document - Document Where the Change Occured
changesBefore: { }
changesAfter: { }
date: "2023-08-10T15:35:51.136Z"
```

It feels more in line of referencing a document without been told when I have a `collection` and `doc` property at hand. It also better explains the properties on the logged changes

`username` - name of user associated (with the document) where change occurred
`collection` -  the collection where the change occurred
`doc` - the specific document (in the collection) where the change occurred
`changesBefore` - the document before the change
`changesAfter` - the document after the change
`date` - when the change occurred

But what do we say about....

`collection_id` - the id of the collection where the change occurred???????????

My thoughts, what'd you think?

**Comment by eddiejaoude** [comment]
Great explanation 💪  (sorry for my slow reply)

Because it is `collection` and the `id` is referring to the `collection`, that is why I suggested `collectionId` - I am happy with `docId` if you feel it makes more sense, but I definitely believe it should be appended with `...Id` to be clear that it is an id for mongo
