### ISSUE TITLE
[FEATURE] Profile rank

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/BioDrop#7892]
### Description

On the profile statistics page, it might be fun to display a profile position, for example your profile is in position 9 out of 2142

The json in Mongo is in this format...

```js
[
   // ...
   {
      username: "username 1",
      views: 100
      // ...
   },
   {
      username: "username 2",
      views: 10000
      // ...
   }
   // ...
]
```

Mongo has a `$rank` feature that could help https://www.mongodb.com/docs/manual/reference/operator/aggregation/rank/

I think we could add another progress bar with the position on the `/account/statistics` page...

<img width="1667" alt="Screenshot 2023-07-20 at 10 43 26" src="https://github.com/EddieHubCommunity/LinkFree/assets/624760/adb31b80-4f9a-47a2-92bd-a08091b12dc7">

**Comment by akash19coder** [comment]
### Approach 

- [ ] Rank users on the `Profile Views` and Profile Completion data.
- [ ] Assign weightage to Profile Views and Profile Completion data. For example, we can consider 70% of Profile Views and 30% of Profile Completion in the overall rank score.
- [ ] Normalize the profile views and profile completion data to be on the same scale.
- [ ] Calculate the ranking score.
- [ ] Sort the ranking score in descending order.
- [ ] Display a specific users rank in their statistics page.

**Comment by bikrantjajware** [comment]
How about a number showing rank of user below the bio (like Rank: 10 ) or something like this.
<img width="891" alt="image" src="https://github.com/EddieHubCommunity/LinkFree/assets/34072248/19e4af3a-ed62-4266-98fe-0bd4feca1b66">


>  Assign weightage to Profile Views and Profile Completion data. For example, we can consider 70% of Profile Views and 30% of Profile Completion in the overall rank score.

is this the recommended approach to keep 70-30 weightage ?
i guess we can do aggregation query with a custom field ( based on views and profile completion)  to calculate $rank.

**Comment by Madankh** [comment]
Do we need to add that feature on backend ??

**Comment by zaid-ahmad** [comment]
I don't think we need to rank users on the basis of their profile completion because some people might be new to the platform and might not be as active in the community yet.

So naturally they'll have 0 things to add in the milestones, events or the repo tab.

I think it would be best to rank users purely on the basis of profile views. Also, it would be nice to have an option to display the position on an individual's profile itself.

**Comment by sital002** [comment]
I would like to work on this feature but just to clear should I add a progress bar or just add a rank section as shown on the image.

![](https://user-images.githubusercontent.com/34072248/259140337-19e4af3a-ed62-4266-98fe-0bd4feca1b66.png)

**Comment by akash19coder** [comment]
@sital002 I think simply displaying the rank would be much better like in the aforementioned image

**Comment by SaraJaoude** [comment]
@sital002 I agree with @akash19coder to just add a rank section.  I have also assigned this to you.
