### ISSUE TITLE
[FEATURE] set dark/light mode based on browser/system settings

### ISSUE THREAD

**Issue by schmelto** [EddieHubCommunity/BioDrop#8146]
### Description

Set dark/light mode based automatically based on browser settings.

**Comment by dan-mba** [comment]
We us the `next-themes` package to handle light/dark mode.

According to the documentation for [default settings](https://github.com/pacocoursey/next-themes#themeprovider), it uses the system setting to determine light or dark on first visit. The issue could be that it saves the current setting in local storage, so any change will persist over visits. Currently there is no way to disable this feature.

**Comment by schmelto** [comment]
Yeah, I switch light and dark mode during the day based on the current time. The "normal" behavior of websites imo is that they automatically change the theme based on the settings of the computer/browser.

**Comment by dan-mba** [comment]
> Yeah, I switch light and dark mode during the day based on the current time. The "normal" behavior of websites imo is that they automatically change the theme based on the settings of the computer/browser.

I found a workaround. If you set the `theme` key in LocalStorage to `system` it will use the system default. I tested it in Firefox & Chrome.

![localStorage](https://github.com/EddieHubCommunity/LinkFree/assets/35927536/cb84dc2e-520d-4675-9e6b-703d481e1f4c)
This is a screenshot in Firefox.
In Chrome, it is in the devtools under Application, Local Storage is in the sidebar

**Comment by schmelto** [comment]
Is this something we want to implement into the website? 
Most websites use system settings and in the account settings you can overwrite the "standard" with the preferred setting.
So maybe we want to delete the toggle for dark and light mode in the navbar and rather give the user the option the opt out of the system dynamic and setting the preferred theme in the account settings?

**Comment by dan-mba** [comment]
> Is this something we want to implement into the website? 
> 

That is a design decision, which is not my area of expertise.

@eddiejaoude any thoughts on this?

**Comment by eddiejaoude** [comment]
I am open to suggestions, we haven't had this come up before, maybe we leave it open see what others think? Thank you for suggesting it and both of you for experimenting with ideas and options

**Comment by eddiejaoude** [comment]
Going through the issue backlog, I think for now we should close this, but I would be keep to try and keep the example you did @dan-mba so (if you still have it), so if we decide to pick this up we have it - so I will close for now
