### ISSUE TITLE
[OTHER]: Improve the UI of the Dropdown list in the user profile

### ISSUE THREAD

**Issue by ashrafchowdury** [EddieHubCommunity/BioDrop#8313]
## Description

The current **Dropdown list in the profile event section is basic**. I suggest updating it with Headless ListBox UI for a more user-friendly and visually appealing design.

I believe that using the HeadlessUI library can improve user interaction and user experience. **The library is already present in the project**, so it would be a relatively easy way to make these improvements. 

-------

**Current Dropdown list**

![image](https://github.com/EddieHubCommunity/LinkFree/assets/87828904/653940c5-d624-416b-9b63-6f06abaeac64)

**Headless ListBox**

![image](https://github.com/EddieHubCommunity/LinkFree/assets/87828904/0f434bcf-6a5d-4c0b-9057-82471ec7c78c)

### Additional information

**I would like to work on this issue if all sounds good.**

**Comment by eddiejaoude** [comment]
Thank you for the idea 👍 

If no new libraries are required, then we can do it.

**Comment by ashrafchowdury** [comment]
Hey, Could you give me some feedback on the new Dropdown menu? It looks perfect or not?


https://github.com/EddieHubCommunity/LinkFree/assets/87828904/47c97d89-86ff-442d-9d0b-f807f66ea922

**Comment by SaraJaoude** [comment]
Given the lack of activity I have unassigned this issue from you @ashrafchowdury 

Additionally, as we are now going through the redesign process this will be looked at then, so I shall close this issue for now.
