### ISSUE TITLE
[BUG] Manage events toggle past events

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/BioDrop#8321]
### Description

When managing our events, the list gets long because of past events

- Add toggle or button to hide past events (hidden by default)

<img width="1661" alt="Screenshot 2023-07-23 at 11 19 22" src="https://github.com/EddieHubCommunity/LinkFree/assets/624760/60877214-5214-4786-a25e-0aa2e9e7d72d">

**Comment by ChiragM999** [comment]
Hey,

I would like to work on this issue.

**Comment by SaraJaoude** [comment]
> Hey,
> 
> I would like to work on this issue.

@ChiragM999 thank you for your enthusiasm to contribute.  I have recently assigned another issue to you and shown in our [Contributing Guide](https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md) we only assign one issue per contributor.

**Comment by MeenuyD** [comment]
Hello, I would like to work on this issue

**Comment by SaraJaoude** [comment]
> Hello, I would like to work on this issue

@MeenuyD I have assigned this to you

**Comment by SaraJaoude** [comment]
@MeenuyD how are you getting on?

**Comment by MeenuyD** [comment]
Working on that

**Comment by sital002** [comment]
@MeenuyD Can you provide update on this issue if won't be active this will be assigned to someone else.

**Comment by SaraJaoude** [comment]
Good spot @sital002 

@MeenuyD given the length of time since we assigned this ti you and as there has not been any activity, I have unassigned this issue from you.

**Comment by sital002** [comment]
I would like to work on this issue.

**Comment by eddiejaoude** [comment]
Thanks @sital002 I have assigned it to you 💪
