### ISSUE TITLE
[FEATURE] Middleware to project "admin" pages and api

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/BioDrop#8389]
### Description

Admin section is currently protected on each page route (inc. api) but they should be protected by NextJS middleware

- middleware protect `/admin/*`
- remove individual checks in admin files

**Comment by ashmeetsmonga** [comment]
I would like to work on this.

**Comment by eddiejaoude** [comment]
I have assigned it to you @ashmeetsmonga

**Comment by ashmeetsmonga** [comment]
Do I need to protect api routes for admin also in middleware.js or only pages?

**Comment by eddiejaoude** [comment]
Can the API routes `api/admin/*` be protected also? If they can, then yes please

**Comment by ashmeetsmonga** [comment]
Sorry, unable to find any way to protect api routes in middleware. Proceeding with middleware for admin pages

**Comment by eddiejaoude** [comment]
I have unassigned the issue, due to a lack of activity

**Comment by bikrantjajware** [comment]
Hello Eddie,
i would like to work on it, could you please assign me this

**Comment by SaraJaoude** [comment]
> Hello Eddie,
> i would like to work on it, could you please assign me this

@bikrantjajware I have assigned this to you.

**Comment by SaraJaoude** [comment]
@bikrantjajware following on from the conversation on Discord as there are challenges with getting the environment variable in the middleware file, we will close this for now.

**Comment by bikrantjajware** [comment]
Hello ,
create a PR for this please have a look at it 🙏
