### ISSUE TITLE
[FEATURE] Search sorting

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/BioDrop#8405]
### Description

Currently search is sorted randomly, I think we need more options

- most popular (by views)
- recently updated (should be default)
- random (current functionality)

These should be achieved within the mongo query.

**Comment by zahid47** [comment]
I would like to give it a try

**Comment by SaraJaoude** [comment]
> I would like to give it a try

@zahid47 I will assign this to you

**Comment by zahid47** [comment]
Should I wait for #8169 before starting? Otherwise, there could be a conflict

**Comment by SaraJaoude** [comment]
> Should I wait for #8169 before starting? Otherwise, there could be a conflict

@zahid47 good spot! I will block this Issue for now to avoid any confusion.

**Comment by SaraJaoude** [comment]
As we have had other more requested features, I will close this for now.
