### ISSUE TITLE
[BUG] Events list, overlap with photo and description

### ISSUE THREAD

**Issue by Anjali-Git-Hub** [EddieHubCommunity/BioDrop#8416]
### Description

On event page i found this issue .
Here the text and the image is overlapping and it is not looking good ,i think  adding some space between them will look good.

### Screenshots

![Screenshot 2023-07-31 122813](https://github.com/EddieHubCommunity/LinkFree/assets/122084921/a488a044-904f-49e3-96b4-b1e2333ec7a4)

**Comment by ChiragM999** [comment]
I would like to work on this issue. Please assign it to me

**Comment by SaraJaoude** [comment]
> pls assign this to me , i want to work on this issue .

@Anjali-Git-Hub I have assigned this to you

**Comment by Anjali-Git-Hub** [comment]
Thankyou.

**Comment by dhruvilmehta** [comment]
Does the issue still exist? I cannot see this thing happening now.

**Comment by SaraJaoude** [comment]
@dhruvilmehta good spot thank you - I will close.
