### ISSUE TITLE
[BUG] <Text blurs and user image moves when user card is hovered over>

### ISSUE THREAD

**Issue by saram7619** [EddieHubCommunity/BioDrop#8521]
### Description

On the LinkFree Search Users page, there are 9 cards that scale(1.05) when hovered over. 

- The users image moves slightly to the bottom left and the text becomes slightly blurred, then unblurred when the card has finished scaling. 
- The tags move slightly to the left when the animation starts and slightly to the right when the animation finishes and the card is not being hovered over.

### Additional information

I would like to work on this issue and fix the bug. Can this be assigned to me please.

**Comment by SaraJaoude** [comment]
We cannot replicate - can you please provide a screenshot

**Comment by saram7619** [comment]
[LinkFree-Search-Users-videoScreen Recording.webm](https://github.com/EddieHubCommunity/LinkFree/assets/82645022/2a0c1a08-750d-4869-b916-eaf61040c1f7)

I sent you a screenshot video. If you look closely at the text when the cursor pointer is on the card, 

- The text blurs and the image moves slightly when the card is focused on at the start of the animation. 
- When the card is fully scaled to 1.5x, the text is clear.
- As the card is unhovered over, the text blurs and the image and tags move slightly then goes back to normal.
- Slightly more noticeable on dark mode.

I thought it was maybe just happening with Firefox(desktop), but it happens with chrome(desktop) and safari(iphone12). 

I hope this helps

**Comment by theresaqueryforthat** [comment]
I can also replicate this issue. It appears to be an issue with the font swapping/losing its antialiasing when doing the css transforms.

I was able to resolve this (on Chrome 115.0.5790.110) with the following via styles: 
```diff
a {
  color: inherit;
  text-decoration: none;
+ will-change: transform;
}
```
and from there the antialiasing remains static before/during/after the scaling animation. I'm not sure if this is the optimal solution but wanted to post this in case it helps contribute to the final solution. [Here's a link](https://developer.mozilla.org/en-US/docs/Web/CSS/will-change) to the docs on the `will-change` property for reference.

**Comment by SaraJaoude** [comment]
Thank you everyone for your collaboration. The simplest solution would be to remove the scaling.

**Comment by saram7619** [comment]
I would like to work on this issue, can you assign this issue to me.

**Comment by SaraJaoude** [comment]
> I would like to work on this issue, can you assign this issue to me.

@saram7619 I have assigned this to you.

**Comment by eddiejaoude** [comment]
@saram7619 please can you raise the pull request on our repo, otherwise we don't get a notification to review and merge
