### ISSUE TITLE
[BUG] The order of pinned icons doesn't change.

### ISSUE THREAD

**Issue by mehmetkirkoca** [EddieHubCommunity/BioDrop#8533]
### Description

After ordering the links, the order of pinned links doesn't change; it remains the same.

Social shortcut icons should be ordered by the links order

<img width="1827" alt="Screenshot 2023-08-07 at 10 02 59" src="https://github.com/EddieHubCommunity/LinkFree/assets/624760/37af07de-2eb9-42e6-9ccd-46e68f575d61">

**Comment by anikdhabal** [comment]
Hey can you assign me to this issue?

**Comment by SaraJaoude** [comment]
> Hey, can you assign me to this issue?

@anikdhabal I have assigned this to you.

**Comment by ckelwin** [comment]
@anikdhabal  any updates on this? It looks like the socials are not sorted correctly in `getUserApi`. If you're no longer working on this, I'd like to give it a go. Thanks.

**Comment by SaraJaoude** [comment]
@ckelwin thank you for showing an interest in this issue.  I have unassigned it from the previous contributor but as I can see that you have an issue assigned to you, I cannot assign this one to you at the moment (as we only assign one issue per contributor).

**Comment by mianakbarjan** [comment]
Hi there, I'd like to work on this issue. Kindly assign it to me so I can start working on it as soon as possible.

**Comment by SaraJaoude** [comment]
> Hi there, I'd like to work on this issue. Kindly assign it to me so I can start working on it as soon as possible.

@mianakbarjan I have assigned this to you.
