### ISSUE TITLE
[FEATURE] Should show profile views of all the days.

### ISSUE THREAD

**Issue by abhijivani3001** [EddieHubCommunity/BioDrop#8569]
## Issue
- Inside the graph of **Profile views**, it only shows the bars of days in which the profile view of that day is more than 0.

## Solution
- It should show all the days in graph, whether the person's profile views is 0 or not.

### Screenshots

![Screenshot 2023-08-08 214336](https://github.com/EddieHubCommunity/LinkFree/assets/117305467/79184859-4c8c-459c-87f7-4661dc1b944c)

**Comment by nilerudra** [comment]
Could you please provide me with the code where its logic is written, or the path to its file?

**Comment by rizahmeds** [comment]
@nilerudra 
Component: [Display chart](https://github.com/EddieHubCommunity/LinkFree/blob/39ab4600c5c573da144158888e889bf59b0a1007/pages/account/statistics.js#L155)
API: [Profile Stats Data](https://github.com/EddieHubCommunity/LinkFree/blob/39ab4600c5c573da144158888e889bf59b0a1007/pages/api/account/statistics.js#L85)

**Comment by nilerudra** [comment]
database schema

**Comment by rizahmeds** [comment]
[https://github.com/EddieHubCommunity/LinkFree/blob/main/models/ProfileStats.js](https://github.com/EddieHubCommunity/LinkFree/blob/main/models/ProfileStats.js)

**Comment by nilerudra** [comment]
I attempted t solve this issue and created a PR please check it.

**Comment by SaraJaoude** [comment]
> I attempted to solve this issue and created a PR please check it.

@nilerudra I see you have opened a PR but this Issue had not been assigned to you.  Please read the [Contributing Guide](https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md) and familiarise yourself with how this project is run, so that this can be avoided in any future collaborations. 

I will now assign this to you.  The PR will be checked once maintainers go through the notifications on other PRs and Issue.

**Comment by nilerudra** [comment]
Thank you for assigning the pull request to me. I apologize for not having the issue assigned before opening the PR, and I appreciate your guidance. I've reviewed the Contributing Guide and will make sure to follow the project's workflow moving forward.
