### ISSUE TITLE
[FEATURE] Sort for repos page

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/BioDrop#8582]
### Description

Currently repos are sorted by most recently active, this is good for default, but additional options would be useful

- sort by stars
- sort by forks
- sort by push date
- sort by created date

**Comment by mishra-nikhil0110** [comment]
@eddiejaoude  I would like to work on this issue, adding more sorting functionalities. Could you please assign this to me?

**Comment by SaraJaoude** [comment]
> I can work on that

@yassineatik I have assigned this to you.

**Comment by yassineatik** [comment]
Hi @eddiejaoude , while trying to work on this feature , I face this problem on Github Api : 

<img width="960" alt="image" src="https://github.com/EddieHubCommunity/LinkFree/assets/77692478/7709ef6d-93b2-4a7a-b3ca-513ac56e44d1">


I have already setup the database and everything , and logged in with same github account that hosts the repo .
I don't know if I should change anything on the repos request to make this work .

**Comment by yassineatik** [comment]
Here it is : 

<img width="475" alt="image" src="https://github.com/EddieHubCommunity/LinkFree/assets/77692478/dfbed2f5-cee4-4821-a541-0c74e2593291">

**Comment by eddiejaoude** [comment]
Sorry for my slow reply @yassineatik , I missed the notification. With setting up the project locally, it is better to come and chat with us in the EddieHub Discord.

As you are having issues setting up the repo locally, let me assign this issue to someone else and we can assign you another issue when you have your local environment working.

**Comment by sital002** [comment]
I am happy to contribute.
