### ISSUE TITLE
[BUG] Milestones date sorting

### ISSUE THREAD

**Issue by loftwah** [EddieHubCommunity/BioDrop#8593]
### Description

Dates are sorted incorrectly on the Milestones. 
![image](https://github.com/EddieHubCommunity/LinkFree/assets/19922556/7d2649e9-8ea5-4a18-9b5b-ce3381908cab)

Milestones should be sorted from oldest to newest (or whatever it is) but it is sorted by month. If I have milestones in December they will appear as the most recent, instead of the most recent year being the most recently like it probably should.

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/19922556/98749533-b561-4594-ab92-a2e233ce6524)

**Comment by loftwah** [comment]
This is via the forms sorry. I think it might be a JavaScript thing because it is sorting correctly, just by the wrong place (it is currently sorted by month regardless of year, so Jan will be up top and Dec down the bottom). Grab me if you need any more info.

**Comment by loftwah** [comment]
![image](https://github.com/EddieHubCommunity/LinkFree/assets/19922556/fa9691e3-f8f6-4087-ac2a-1734f4c7cc6b)

I just changed some more and I can't figure out what it is doing. I was wrong before and it doesn't seem to have any order.

**Comment by SaraJaoude** [comment]
Thanks for clarifying!

**Comment by sainikhil-0521** [comment]
I would like to work on this!

**Comment by SaraJaoude** [comment]
> I would like to work on this!

@sainikhil-0521 I have assigned this to you

**Comment by sainikhil-0521** [comment]
@SaraJaoude SHould i make it ascending or descending order?

**Comment by RiteshK-611** [comment]
> @SaraJaoude SHould i make it ascending or descending order?

ascending imo

**Comment by SaraJaoude** [comment]
> @SaraJaoude SHould i make it ascending or descending order?

@sainikhil-0521 good questions.  After some thought, the most recent milestone should be at the top to mirror sites like LinkedIn.

**Comment by sainikhil-0521** [comment]
I have a problem during setup locally.

**Comment by SaraJaoude** [comment]
> I have a problem during setup locally.

@sainikhil-0521 please raise in Discord: https://discord.com/invite/jZQs6Wu

**Comment by SaraJaoude** [comment]
@sainikhil-0521 due to lack of activity I have unassigned this from you.

**Comment by Giuliano1993** [comment]
Can I have this assigned? :)

**Comment by SaraJaoude** [comment]
> Can I have this assigned? :)

@Giuliano1993 I have assigned this to you
