### ISSUE TITLE
[FEATURE] The Profile owner should be able to manual add testimonials

### ISSUE THREAD

**Issue by xkrishguptaa** [EddieHubCommunity/BioDrop#8614]
### Description

Profile owner should be able to add testimonials from different sources for example LinkedIn, so that their LinkFree profile has all their testimonials

**Comment by SaraJaoude** [comment]
We will keep this in triage for now as it is dependent on the following issue: https://github.com/EddieHubCommunity/LinkFree/issues/7406

**Comment by SaraJaoude** [comment]
Thanks for the good idea - but our concern is that this will get abused as people may want add fake testimonials (unfortunately this is already happening with Events), so I will close.
