### ISSUE TITLE
[BUG] - Incorrect conditional rendering logic to display profile stats

### ISSUE THREAD

**Issue by ShubhamSj07** [EddieHubCommunity/BioDrop#8684]
### Description

 The issue with the short-circuit operator (&&) in React when dealing with zero value, using an example. 

`true && "works?" -> works?`
`0 && "works?" -> 0` -> which gets rendered on UI.

![image](https://github.com/EddieHubCommunity/LinkFree/assets/56510414/7a55a9ad-8535-46bb-b961-aec331ba5c81)

Fix: use double bang operator to convert value to either true or false

![image](https://github.com/EddieHubCommunity/LinkFree/assets/56510414/d9df1f4e-02e1-40df-a586-b435c8a87dbb)

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/56510414/c316cf3a-bbf3-4605-9ff6-0d80e44e6dd7)

**Comment by SaraJaoude** [comment]
Thank you for the great issue!
