### ISSUE TITLE
[BUG]: overflow issue in Repos section

### ISSUE THREAD

**Issue by vedantnaik1008** [EddieHubCommunity/BioDrop#8686]
### Description

Repos section is overflowing in mobile screens at 320px 
![Screenshot (312)](https://github.com/EddieHubCommunity/LinkFree/assets/111636002/17df7c61-94af-4ef5-9d68-cbc8055985ee)

**Comment by SaraJaoude** [comment]
Thank you for raising!

**Comment by Giuliano1993** [comment]
I can work on this :)

**Comment by chiranjeevkapoor** [comment]
Hi, I want to work on this.

**Comment by SoundaryaKoutharapu** [comment]
I would like to fix this issue. can you please assign it to me.?

**Comment by SaraJaoude** [comment]
> I can work on this :)

@Giuliano1993 I have assigned this to you
