### ISSUE TITLE
[FEATURE] show/hide unused features

### ISSUE THREAD

**Issue by loftwah** [EddieHubCommunity/BioDrop#8695]
### Description

I don't use Events on my profile so if there was a settings menu, or an option to show/hide features somewhere that would be cool.

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/19922556/3a5aae19-054a-46e2-b8c9-d33bc027f827)

There could possibly be a settings page for account related stuff.
It could really live anywhere but the real idea is to be able to show or hide features that aren't used.

**Comment by SaraJaoude** [comment]
Thanks for the suggestion! These are hidden when the profile is viewed, but we are keen to have them displayed in the Manage Profile section to encourage people to use those features, so I will close this for now.
