### ISSUE TITLE
[BUG] All events does not show past events

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/BioDrop#8700]
### Description

- All events should show every event 
- But we should default to future events

<img width="1659" alt="Screenshot 2023-08-19 at 08 10 56" src="https://github.com/EddieHubCommunity/LinkFree/assets/624760/764a283e-697f-43e5-a46a-062b88915844">

<img width="1668" alt="Screenshot 2023-08-19 at 08 11 03" src="https://github.com/EddieHubCommunity/LinkFree/assets/624760/6c4efa03-57e1-4812-b014-5040a1f6e92b">

**Comment by SaraJaoude** [comment]
> Please assign this issue to me.

@rizahmeds I have assigned this to you
