### ISSUE TITLE
[FEATURE] Add label to the input in "Profile" section

### ISSUE THREAD

**Issue by zaid-ahmad** [EddieHubCommunity/BioDrop#8703]
### Description

The dropdown menu below the username input is confusing. I don't know what it's for or what it does. I think it would be helpful if there was a label for it.

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/39582467/838cf42a-cfa5-4131-9274-2466fc5c9a3a)

**Comment by SaraJaoude** [comment]
Thanks for raising - agreed this can be a bit confusing.

**Comment by ZeeMonk-pixel** [comment]
Good morning. What label should be there? I can work on this issue if i know what label you'll like to be there. pls assign it to me

**Comment by dhruvilmehta** [comment]
I think it's not just about the "Layout" label, we should put the Preview at the side so the user can see how the layout will look like. Because normal users cannot understand "Classic", "Inline" and "Column-2" layout by just seeing the name, they should be able to preview it as well.

**Comment by ZeeMonk-pixel** [comment]
Oh. Then I guess it should still be up for discussion then.

**Comment by dhruvilmehta** [comment]
https://github.com/EddieHubCommunity/BioDrop/assets/68022411/b9eb9815-0903-4d74-bfc9-41e9bf35e3fc

I have made this kind of preview. See if this can be implemented or not.

**Comment by SaraJaoude** [comment]
The label should be called `Profile Layout`. 

@ZeeMonk-pixel as you asked first I will assign this to you.  You may wish to consider collaborating with @dhruvilmehta given that they seem to have started work on this already?  If you are happy to do this I can add them as an assignee also.

**Comment by ZeeMonk-pixel** [comment]
the preview on the right seems like a new feature, one I think it'll be wise for the team to discuss before it is implemented. I'll stick to just the label now and an issue to add that new feature can be raised later on.
