### ISSUE TITLE
[OTHER] Automated test profile.spec.js

### ISSUE THREAD

**Issue by kbventures** [EddieHubCommunity/BioDrop#8707]
### What would you like to share?

What would you like to share?
I created a automoated test "After search click profile" in ./test/profile.spec.js

`test("Link navigates", async ({ page }) => {
  const username = "_test-profile-user-3";
  const endpoint = `/${username}`
  // Navigate to the profile
  await page.goto(endpoint);

  // Find all anchor tags on the page
  const anchorTags = await page.$$("a");

  // Loop through each anchor tag
  for (const anchor of anchorTags) {
    const href = await anchor.getAttribute("href");

    // Check if the href includes the username
    if (href.includes(endpoint)) {
      break; // No need to continue checking
    }
  }
});`

Additional information
Please assign issue to me so I can make a pull requests.

**Comment by eddiejaoude** [comment]
Assigned to you @kbventures 👍
