### ISSUE TITLE
[BUG] Overflow issue on account/statistics

### ISSUE THREAD

**Issue by hi-Kartik2004** [EddieHubCommunity/BioDrop#8712]
### Description

There is an overflow issue in the account/statistics page below the width of 300px (i.e on smaller mobile devices)

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/111000515/632a3e4e-34ea-4547-8270-8569bb8dc6c0)

### Additional information

Follow the screenshot dimensions to re-create the issue in chrome dev tools in the https://linkfree.io/account/statistics page.

**Comment by SaraJaoude** [comment]
Thank you raising but as this will be addressed during the redesign process I will close this issue for now.
