### ISSUE TITLE
Update Bio Textbox of profile edit page

### ISSUE THREAD

**Issue by devraj4522** [EddieHubCommunity/BioDrop#8714]
### Description

Bio textbox in profile edit form does not align with the UI it does not match color of dark background, and outline is different from other input components.

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/55313450/29604ef1-466f-41a0-b741-2737b664c6fe)
![image](https://github.com/EddieHubCommunity/LinkFree/assets/55313450/ff78f311-9c01-4e7a-ad2c-63555baa6ba8)
![image](https://github.com/EddieHubCommunity/LinkFree/assets/55313450/0e73f9cc-d3d9-4502-a655-889ab0174131)
![image](https://github.com/EddieHubCommunity/LinkFree/assets/55313450/0939f362-adf4-4946-94ab-60baebac1989)

**Comment by SaraJaoude** [comment]
Thank you for raising, but as this has now been fixed I will close this issue.
