### ISSUE TITLE
Infinitely long invalid dates gives error during edit in Event add page

### ISSUE THREAD

**Issue by devraj4522** [EddieHubCommunity/BioDrop#8715]
### Description

If I want to create an event with invalid dates (see the start date in the screenshot attached), I am able to do it, but when I want to edit this event it gives me error in the page.

We can handle these error during the time event is created.
I want to work on it.

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/55313450/925a7a73-cc74-4cb8-b0d0-e378ba5ec5d6)
![image](https://github.com/EddieHubCommunity/LinkFree/assets/55313450/be25d54a-7ed3-47a4-bd44-fb5f487a9b74)
![image](https://github.com/EddieHubCommunity/LinkFree/assets/55313450/c4e6f83e-3f48-41dc-9858-63287f955edf)

**Comment by eddiejaoude** [comment]
There has been work on the event dates, I think this is no longer an issue. Please can you recheck with the latest code. Thank you

**Comment by SaraJaoude** [comment]
Unable to replicate so closing this issue for now.  Please raise again if this reappears.
