### ISSUE TITLE
[FEATURE] Add a scroll to top button as a component 

### ISSUE THREAD

**Issue by karthiknadar1204** [EddieHubCommunity/BioDrop#8717]
### Description

Currently, when the user has scrolled to the bottom of the page, the user has to manually scroll back to the top of the page, to automate this process, I propose to add a small scroll to the top button to the bottom right corner on all the pages.
on clicking this button, the user would smoothly be led back to the top of the page.

### Screenshots

https://www.awesomescreenshot.com/video/19520861?key=537e2317b169eac559e3c472e83ad8ec

### Additional information

ABove is the preview of the button I propose to add, I implemented it in another project, and The design will be different.
Please share your views/opinions for the same.

**Comment by eddiejaoude** [comment]
Thank you for the suggestion (and video, that was great!), but I don't think the pages are so long that this would add value. 

You can see other issues have been raised and closed on this topic
- https://github.com/EddieHubCommunity/BioDrop/issues/6014
- https://github.com/EddieHubCommunity/BioDrop/issues/4920
- https://github.com/EddieHubCommunity/BioDrop/issues/2670
- https://github.com/EddieHubCommunity/BioDrop/issues/912
