### ISSUE TITLE
[BUG] <description>

### ISSUE THREAD

**Issue by Anjali-Git-Hub** [EddieHubCommunity/BioDrop#8724]
### Description

In the search section , this text and the number div is overlapping which is not looking good, as some words are visible and some are hidden because of that overlapping .

### Screenshots

![buggie](https://github.com/EddieHubCommunity/LinkFree/assets/122084921/0e096b62-6e4c-48b1-a5b2-b1a1ea587876)

**Comment by eddiejaoude** [comment]
Thank you for the suggestion, these will be fixed as part of the app redesign, so I will close this issue for now
