### ISSUE TITLE
[BUG] <Slow routing navbar links>

### ISSUE THREAD

**Issue by vijaydiyyala** [EddieHubCommunity/BioDrop#8737]
### Description

Go to Home section
Check on the Nav-bar components
Now clicks on the links .
 It takes time for routing when we click on the links.

### Screenshots

[screen-capture.webm](https://github.com/EddieHubCommunity/LinkFree/assets/107129196/e19d3164-1bc7-4c02-b89d-c6662bad594f)

**Comment by eddiejaoude** [comment]
Thank you for sharing 👍 Some pages are slower as they load all the users to display on the page, for example like search, map etc

There are other issues that focus on each improvement, so I will close this issue as it is too generic
