### ISSUE TITLE
[BUG] Visibility issues on Hover in light mode on repos page

### ISSUE THREAD

**Issue by adarshmalviya12** [EddieHubCommunity/BioDrop#8754]
### Description

The hover effect on the repository page is currently experiencing visibility issues when the user is using the light mode.

### Screenshots

https://github.com/EddieHubCommunity/LinkFree/assets/96465597/4e556b1d-fdd1-41e7-b1b0-a1927a979439

**Comment by eddiejaoude** [comment]
Thank you for raising the issue 👍 

This will completely change as part of the redesign, so I will close for now
