### ISSUE TITLE
[FEATURE] Add Confirmation Dialog for Repo Deletion

### ISSUE THREAD

**Issue by adarshmalviya12** [EddieHubCommunity/BioDrop#8763]
### Description

- When a user attempts to delete a repository, the action is executed immediately without any confirmation prompt. This can lead to the accidental deletion of the repo.
-By adding a confirmation prompt, we can reduce the risk of users accidentally deleting repositories. 

### Screenshots

https://github.com/EddieHubCommunity/LinkFree/assets/96465597/01b115e8-d45d-4e23-b0bb-ce26d2ca5ceb

### Additional information

I'm interested in working on this issue, If there are specific design or technical considerations, please provide guidance so that I can incorporate them effectively.

**Comment by eddiejaoude** [comment]
Thank you for the suggestion 👍 As requested I have assigned it to you.

Please look at the confirmation on the other manage pages, I think all the components you need is already in the app and you can reuse it

**Comment by ChinmayMhatre** [comment]
@adarshmalviya12  do you need any help with the issue ?

**Comment by adarshmalviya12** [comment]
Thank you so much for offering to help, @ChinmayMhatre. I really appreciate it. I've been working on this issue for the past couple of days, and I was having trouble with the project setup. However, I finally got it set up yesterday. I've found the required files and components, but I'm a bit unsure about how to use them effectively. Any guidance or tips on this would be greatly appreciated

**Comment by ChinmayMhatre** [comment]
> Thank you so much for offering to help, @ChinmayMhatre. I really appreciate it. I've been working on this issue for the past couple of days, and I was having trouble with the project setup. However, I finally got it set up yesterday. I've found the required files and components, but I'm a bit unsure about how to use them effectively. Any guidance or tips on this would be greatly appreciated

sorry for the late reply, thank you for raising the PR the maintainers will review it and give any feedback if necessary!
