### ISSUE TITLE
[BUG] Milestone page text area need some styles changes.

### ISSUE THREAD

**Issue by sital002** [EddieHubCommunity/BioDrop#8765]
### Description

The milestone page text area needs transparent background and on clicked the border color should be orange, but it is purple instead.

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/93700622/d822f42d-5f50-452e-9289-c12d2b7adb68)
![image](https://github.com/EddieHubCommunity/LinkFree/assets/93700622/28c798b3-c4a1-4904-ab50-a12b07fda39c)

### Additional information

I would like to work on this issue.

**Comment by eddiejaoude** [comment]
Thank you for raising 👍 

This has been fixed as part of another issue, so I will close
