### ISSUE TITLE
[FEATURE]Filter out the Community Repositories according to their star ratings.

### ISSUE THREAD

**Issue by anikdhabal** [EddieHubCommunity/BioDrop#8772]
### Description

Now all of them are listed in random order. It would be great if the user can filter out the repositories according to star ratings.

**Comment by eddiejaoude** [comment]
Thank you for raising but the order is not random, they are displayed by last pushed date.

More filter/sorting is a good idea. Another issue has been raised, so I will close this as it is a duplicate of https://github.com/EddieHubCommunity/BioDrop/issues/8660 I will close
