### ISSUE TITLE
[BUG] Add more space between link container and button container on Manage Links Page

### ISSUE THREAD

**Issue by khairnsaa** [EddieHubCommunity/BioDrop#8774]
### Description

i think we could add more margin between the `add link` button row and the `available link` row. the edit button looks like "touching" the add link button

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/53510222/ed4badfd-63b0-4aac-8441-b1a5e1bf6086)

### Additional information

if this issue got approved. i'd love to be the one working on this

**Comment by eddiejaoude** [comment]
Thank you for raising 👍  I have assigned it to you

Can the same gap be applied to all manage pages, for example milestone, events etc...

**Comment by khairnsaa** [comment]
Hi all,

I just cloned the repo to fix this problem. when i start local server, i got error from `pages/index.js` file. the error says `ReferenceError: StructuredClone not defined`. and when i look at the code, there is no import for the `structuredClone` function and no function declaration either. so, where does the function come from?
