### ISSUE TITLE
[BUG] API should reduce the data returned

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/BioDrop#8776]
### Description

On the user's statistics page, we are retrieving all their daily stats from the API but only displaying the last 30 days `pages/account/statistics.js`

We should add a query parameter to the API so that we only retrieve the requested data `api/account/statistics.js`, default to 30 days

**Comment by Dun-sin** [comment]
Hi Eddie, can I work on this?

**Comment by eddiejaoude** [comment]
Sure @Dun-sin , I have assigned it to you 👍

**Comment by Dun-sin** [comment]
> Sure @Dun-sin , I have assigned it to you 👍 

Thank you😆

**Comment by Dun-sin** [comment]
@eddiejaoude let me explain what I understand this issue to do, that way of there's any misunderstanding you can correct it before I make a pull request, from this issue the tasks are:
- Limit the data gotten from Mongodb for profile clicks and link clicks, to 30 days using the query on findOne?
- By default it should be 30 days but allow the option to pick any other number of days? The limit here should be what? 365 days?

**Comment by eddiejaoude** [comment]
hey @Dun-sin , yes you are correct 👍 

> Limit the data gotten from Mongodb for profile clicks and link clicks, to 30 days using the query on findOne?

Currently it is done in the UI here https://github.com/EddieHubCommunity/BioDrop/blob/42a9e1fd6d653a5b9df63971209f575bcd398b61/pages/account/statistics.js#L88 but we should be able to remove this limit as the backend API function should only return 30 by default, note is it not a `findOne` but a `find` https://github.com/EddieHubCommunity/BioDrop/blob/42a9e1fd6d653a5b9df63971209f575bcd398b61/pages/api/account/statistics.js#L39 

> By default it should be 30 days but allow the option to pick any other number of days? The limit here should be what? 365 days?

Yes 👍 I was thinking to have no limit, but if you are able to add a max limit of 365, that would be great 💯

**Comment by Dun-sin** [comment]
> hey @Dun-sin , yes you are correct 👍 
> 
> > Limit the data gotten from Mongodb for profile clicks and link clicks, to 30 days using the query on findOne?
> 
> Currently it is done in the UI here https://github.com/EddieHubCommunity/BioDrop/blob/42a9e1fd6d653a5b9df63971209f575bcd398b61/pages/account/statistics.js#L88 but we should be able to remove this limit as the backend API function should only return 30 by default, note is it not a `findOne` but a `find` https://github.com/EddieHubCommunity/BioDrop/blob/42a9e1fd6d653a5b9df63971209f575bcd398b61/pages/api/account/statistics.js#L39 
> 
> > By default it should be 30 days but allow the option to pick any other number of days? The limit here should be what? 365 days?
> 
> Yes 👍 I was thinking to have no limit, but if you are able to add a max limit of 365, that would be great 💯 
> 
> Also be aware of the changes in this PR in the UI https://github.com/EddieHubCommunity/BioDrop/pull/8580

Yes it's find, I will see what I can do about the issue thanks for clarifying, will ask more questions if I need to🔥

**Comment by eddiejaoude** [comment]
The limit could always be added in another issue/pull request - it has no limit now, so we are still moving forwards and making improvements by adding a default of 30

**Comment by Dun-sin** [comment]
> The limit could always be added in another issue/pull request - it has no limit now, so we are still moving forwards and making improvements by adding a default of 30

Are you saying i don't have to do it? but i can if i can?

**Comment by Dun-sin** [comment]
hi @eddiejaoude, i got an issue with testing it properly, i get network error even after populating the DB and server and client show they work properly
![image](https://github.com/EddieHubCommunity/BioDrop/assets/78784850/d6af06b2-fc8a-483e-9f02-ebbc7a968e51)

**Comment by eddiejaoude** [comment]
oh I have never seen this error before 😱  Could we discuss in EddieHub Discord to debug faster

**Comment by Dun-sin** [comment]
> oh I have never seen this error before 😱 Could we discuss in EddieHub Discord to debug faster

this is in dev btw and i'm using gitpod

**Comment by eddiejaoude** [comment]
Ah let me try Gitpod

**Comment by eddiejaoude** [comment]
I found the problem, in the `.env` file, the `NEXT_PUBLIC_BASE_URL` needs to be updated to your gitpod environment url (you can get this from the browser preview)

Thank you for raising the issue, I will add this step to the docs

**Comment by Dun-sin** [comment]
> I found the problem, in the `.env` file, the `NEXT_PUBLIC_BASE_URL` needs to be updated to your gitpod environment url (you can get this from the browser preview)
> 
> Thank you for raising the issue, I will add this step to the docs

oh awesome, didn't see your reply sorry.
