### ISSUE TITLE
[BUG] Testimonials not showing up 

### ISSUE THREAD

**Issue by Dun-sin** [EddieHubCommunity/BioDrop#8794]
### Description

I've gotten two testimonials so far and they aren't showing up on my profile

### Screenshots

![Screenshot_2023-08-26-14-10-02-749_com github android-edit](https://github.com/EddieHubCommunity/BioDrop/assets/78784850/3d50edfe-e12e-4e88-8c7e-d8f9cddf101c)

![Screenshot_2023-08-26-14-10-58-854_io github forkmaintainers iceraven-edit](https://github.com/EddieHubCommunity/BioDrop/assets/78784850/82cb199c-8914-45b3-8239-24afdd70037a)

**Comment by eddiejaoude** [comment]
Good spot @Dun-sin 👍 Thank you for raising the bug

The problem is when a profile starts to use forms and has no json file their testimonials are not loaded, I started on a fix

**Comment by Viveksati5143** [comment]
Hey @eddiejaoude 
How long can we expect a fix for this?

**Comment by eddiejaoude** [comment]
I am working on it at the moment, hopefully it should be done in a few days

**Comment by Viveksati5143** [comment]
> I am working on it at the moment, hopefully it should be done in a few days

Sure, Do let me know if it needs a contributor.
