### ISSUE TITLE
[BUG] Glow animation in Links section is not working in Dark mode

### ISSUE THREAD

**Issue by VaishnavJois** [EddieHubCommunity/BioDrop#8796]
### Description

Glow animation in Links section is not working in Dark mode

### Screenshots

![image](https://github.com/EddieHubCommunity/BioDrop/assets/44056482/52a88419-7295-45af-b2a8-454421730add)

### Additional information

Animation works fine in Light mode

**Comment by SaraJaoude** [comment]
Thank you for raising - good spot

**Comment by sital002** [comment]
I would like to work on this. I have checked everything else works fine except for glow animation on dark mode.

**Comment by theunhackable** [comment]
I would lie to work on this issue

**Comment by MeenuyD** [comment]
Hello @SaraJaoude I would like to work on this issue can you please assign it to me?

**Comment by sital002** [comment]
> I would lie to work on this issue

We are glad that you want to work on this issue, but you are already assigned to another issue, so we can't assign you another issue unless the PR gets merged.

**Comment by sital002** [comment]
> Hello @SaraJaoude I would like to work on this issue can you please assign it to me?

@MeenuyD  As mentioned earlier we only assign one issue to one person so don't ask for another issue to get assigned instead work on the issue that you are assigned. Also don't tag maintainer they are often busy.

**Comment by theunhackable** [comment]
> > I would lie to work on this issue
> 
> We are glad that you want to work on this issue, but you are already assigned to another issue, so we can't assign you another issue until the PR gets merged.

Sorry for that. I have completed the task and made a PR. I'm just waiting for the approval so I thought In the mean time I could contribute more here. I will come again after the PR is merged or if it is not a problem you can assign this for me. Thank you 🙏.

**Comment by zaid-ahmad** [comment]
Can I work on this issue?

**Comment by ShivaKodes** [comment]
I would like to work on this. Can you assign me?

**Comment by zaid-ahmad** [comment]
I've solved the issue, should I reference the pull request or wait before I get assigned for it?

![msedge_JzF6ExPdpE](https://github.com/EddieHubCommunity/BioDrop/assets/39582467/31896ae6-ff63-49c4-bee8-1a4539f3942c)

**Comment by SaraJaoude** [comment]
> I've solved the issue, should I reference the pull request or wait before I get assigned for it?
> 
@zaid-ahmad your enthusiasm is great but your messages have created a lot of extra admin for the maintainers. As shown in the [Contributing Guide](https://github.com/EddieHubCommunity/BioDrop/blob/main/CONTRIBUTING.md) please ask for an issue to be assigned and then **please wait** to find out if this has been assigned to you **before** doing any work. On this occasion as you are the first person to request this to be assigned that does not already have an issue, so I will assign this to you.  However, please follow our guidelines in future as we will not t keep making exceptions.

**Comment by zaid-ahmad** [comment]
Okay, sorry for that. I'll keep in mind next time.
