### ISSUE TITLE
[BUG] Unable to save a link without specifying an icon

### ISSUE THREAD

**Issue by datadeverik** [EddieHubCommunity/BioDrop#8799]
### Description

Today I was setting up my BioDrop profile. I wanted to add my website as a link. I didn't find an icon that looked right, but I did notice that the preview display of the link showed a generic "World Wide Web" globe when no icon was specified. (See screenshot). So I thought it would be fine. However, I discovered that when I clicked "save," nothing happened. After some trial and error, I found that I had to specify an icon in order to save a link. Since I didn't find a link that looked right, I just went with a Font Awesome Git Alt icon ("FaGitAlt") for now. However, I'd like to be able to submit a link without specifying an icon, and have it default to the "World Wide Web" globe shown in the preview in the screenshot below.

Update: While writing this issue, I discovered that the "World Wide Web" globe icon I wanted is actually available as an icon with the name "FaGlobe." So in some sense that fixes my issue. But I would like it better if I could skip selecting an icon and be assigned the globe. If that's not possible or desired, then I would at least want an error message that explains why I can't save the link (because of there being no icon specified).

Also, I would like to work on this issue as a developer.

### Screenshots

![Screen Shot 2023-08-26 at 11 26 37 AM](https://github.com/EddieHubCommunity/BioDrop/assets/52926724/df340bdb-a0ab-4fe1-8b05-ac9ba83cd807)

**Comment by eddiejaoude** [comment]
Good spot Erik 👍  I have assigned the issue to you

**Comment by datadeverik** [comment]
I find I have overcommitted myself, and I have been pushing this down in my priorities list. If someone else would like to work on this issue, I will release my claim to it.

**Comment by yashnerkar** [comment]
yes, I would like to work on this issue.

**Comment by SaraJaoude** [comment]
@datadeverik thank you for letting us know 

@yashnerkar I have assigned this to you

**Comment by yashnerkar** [comment]
Thanks @SaraJaoude . Regarding the behavior when an error occurs during icon selection on the form, should we reproduce the error or simply allow users to proceed with the default globe icon and submit the form? I believe that allowing users to submit the form with the default icon is a user-friendly approach. What are your thoughts on this from a user experience perspective?
