### ISSUE TITLE
[FEATURE] Conditional Visibility of "Add Testimonial"

### ISSUE THREAD

**Issue by Olaleye-Blessing** [EddieHubCommunity/BioDrop#8807]
### Description

Currently, the user profile page features an "Add Testimonial" button. The purpose of this button is to allow users to add testimonials related to other users. However, its visibility is constant regardless of whether the profile being viewed belongs to the logged-in user or another user.

Users should not be presented with an option to add a testimonial to their own profile:
- If the user is viewing their own profile, the "Add Testimonial" button should be hidden.
- If the user is viewing a profile that does not belong to them, the "Add Testimonial" button should be visible as usual.

### Screenshots

<img width="1512" alt="Screenshot 2023-08-27 at 06 15 31" src="https://github.com/EddieHubCommunity/BioDrop/assets/70102539/9706ebfb-1258-42bd-afe1-480c43e3e33a">

**Comment by SaraJaoude** [comment]
Thank you for raising. However we feel it is useful for the author to see how their Profile will look to others so we feel that there is no benefit in hiding this button, so I will close this issue for now.
