### ISSUE TITLE
[Improve] Making the visual hierarchy of the features section better.

### ISSUE THREAD

**Issue by shubhsharma19** [EddieHubCommunity/BioDrop#8810]
### Description

Here in the following image you can see that in the **features section** of the website, h3 has a `font-weight` of 500 

![2023-08-27 13_06_50-BioDrop - connect to your audience with a single link - Brave](https://github.com/EddieHubCommunity/BioDrop/assets/69891912/2e919635-c028-475e-9f60-01710ca866a5)

Which can be improved and made `700` to improve the overall visual hierarchy of the features section.

Here is the improved version with `font-weight: 700;`

![2023-08-27 13_07_26-BioDrop - connect to your audience with a single link - Brave](https://github.com/EddieHubCommunity/BioDrop/assets/69891912/67f351cb-7108-4096-8602-eb6fb4f1a7fb)

## Why?

Because this improves the overall visual hierarchy and thus puts more emphasis on the features.

**Comment by SaraJaoude** [comment]
Thanks for your suggestion

**Comment by theunhackable** [comment]
@SaraJaoude I would like to work on this.

**Comment by SaraJaoude** [comment]
> @SaraJaoude I would like to work on this.

@theunhackable I have assigned this to you

**Comment by theunhackable** [comment]
Hey @SaraJaoude  I have completed the work you can review it and give any further instructions to change the code if necessary.

**Comment by SaraJaoude** [comment]
> Hey @SaraJaoude I have completed the work you can review it and give any further instructions to change the code if necessary.

@theunhackable thank you for this.  One of the maintainers will review the PR when they get to it - I am sure you appreciate we have a long list to review. In future please do not tag specific maintainers as this creates extra notifications.
