### ISSUE TITLE
[BUG] Screenshots to change name from 'LinkFree' to 'BioDrop'

### ISSUE THREAD

**Issue by Viveksati5143** [EddieHubCommunity/BioDrop#8814]
### Description

Edit: all screenshots need updating. 

In the https://www.biodrop.io/docs/how-to-guides/testimonials-json -> Giving a testimonial section ->
the name in the screenshot should be updated from 'LinkFree' to 'BioDrop'

### Screenshots

<img width="959" alt="image" src="https://github.com/EddieHubCommunity/BioDrop/assets/100852245/325d1a95-bea6-49d6-9f52-8a52501aa862">

**Comment by SaraJaoude** [comment]
Thank you for raising.  I have edited the description to reflect that all screenshots which show the former repo name will need to be updated.

**Comment by SaraJaoude** [comment]
> I would like to work on this. Can you please assign it to me?

@rahulsiddarth I have assigned this to you

**Comment by Viveksati5143** [comment]
> > I would like to work on this. Can you please assign it to me?
> 
> @rahulsiddarth I have assigned this to you

But how is this fair I raised this issue I wanted to work on this @SaraJaoude ??!

**Comment by eddiejaoude** [comment]
> But how is this fair I raised this issue I wanted to work on this

Thank you for your Discord message @Viveksati5143 , but you didn't ask for it to be assigned to you and someone else did - please read our contributing guide to get tips on how to contribute effectively and efficiently

**Comment by eddiejaoude** [comment]
@Viveksati5143 why did you close the issue? Because it was assigned to someone else?

**Comment by Viveksati5143** [comment]
Sorry for the confusion @eddiejaoude I tried resolving the confusion in discord.

**Comment by SaraJaoude** [comment]
> Hi Eddie, requesting that this issue be reassigned to someone who has a better screen size. Currently, with my 16:9 screen ratio , I'm unable to capture all the details like how it is present now in the screenshots.

@rahulsiddarth thank you for letting us know, I have unassigned this from you

**Comment by chiragthakur09** [comment]
I would like to work on this issue, appreciate to be assigned.

**Comment by SaraJaoude** [comment]
> I would like to work on this issue, appreciate to be assigned.

@chiragthakur09 I have assigned this to you

**Comment by chiragthakur09** [comment]
<img width="1440" alt="new_issue_testimonial_screen_shot" src="https://github.com/EddieHubCommunity/BioDrop/assets/34659530/5943eaed-5244-4dcf-9797-e15bf2cdf6b6">

**Comment by chiragthakur09** [comment]
<img width="1680" alt="BioDrop_GitHub_report_forked_add_user_data_content" src="https://github.com/EddieHubCommunity/BioDrop/assets/34659530/815771e1-6548-485d-9032-697f98265d63">

<img width="486" alt="BioDrop_GitHub_report_forked_create_new_branch" src="https://github.com/EddieHubCommunity/BioDrop/assets/34659530/338a9991-8023-4b99-b7a7-aa9c29bae9a8">

<img width="1233" alt="BioDrop_GitHub_report_forked_compare_branch_changes" src="https://github.com/EddieHubCommunity/BioDrop/assets/34659530/12c06eb3-8fcb-420d-ac09-93a4dd50d1be">

**Comment by chiragthakur09** [comment]
<img width="1677" alt="BioDrop1" src="https://github.com/EddieHubCommunity/BioDrop/assets/34659530/4ca0783c-1fe6-4331-bbde-b48876bd9bf2">

<img width="1671" alt="BioDrop2" src="https://github.com/EddieHubCommunity/BioDrop/assets/34659530/25785be9-7b96-46a7-afc3-f5a38a8fbf90">

<img width="1671" alt="BioDrop3" src="https://github.com/EddieHubCommunity/BioDrop/assets/34659530/80038d45-ab70-42ea-b43f-14bd37e0a5ff">

**Comment by chiragthakur09** [comment]
<img width="1680" alt="Screenshot 2023-09-22 at 5 21 10 PM" src="https://github.com/EddieHubCommunity/BioDrop/assets/34659530/4a7b3522-e4de-491b-a39f-743ae10c196b">

<img width="1680" alt="Screenshot 2023-09-22 at 5 44 05 PM" src="https://github.com/EddieHubCommunity/BioDrop/assets/34659530/54907f20-3cd4-407d-8c45-9dbf60bc7c17">

**Comment by chiragthakur09** [comment]
<img width="1680" alt="Screenshot 2023-09-22 at 5 59 10 PM" src="https://github.com/EddieHubCommunity/BioDrop/assets/34659530/6f873928-024a-4f2a-812f-1550acf4b78d">

<img width="1680" alt="Screenshot 2023-09-22 at 6 01 14 PM" src="https://github.com/EddieHubCommunity/BioDrop/assets/34659530/bcf77bc5-73f7-427f-aea1-84cd8abeb03f">

<img width="1680" alt="Screenshot 2023-09-22 at 6 04 34 PM" src="https://github.com/EddieHubCommunity/BioDrop/assets/34659530/a9b3aa2e-554e-4e2d-b47c-b5fb21066686">

**Comment by SaraJaoude** [comment]
@chiragthakur09 due to lack of activity this issue has been unassigned from you.  The `staff only` label has now been added.

**Comment by Viveksati5143** [comment]
> @chiragthakur09 due to lack of activity this issue has been unassigned from you. The `staff only` label has now been added.

I opened this issue more than a month ago but due to some confusion couldn't get assigned at the very moment😅
Can I work it on now as I do have commented to assign me in the starting so atleast now it should be the right time.

**Comment by SaraJaoude** [comment]
> > @chiragthakur09 due to lack of activity this issue has been unassigned from you. The `staff only` label has now been added.
> 
> I opened this issue more than a month ago but due to some confusion couldn't get assigned at the very moment😅 Can I work it on now as I do have commented to assign me in the starting so atleast now it should be the right time.

@Viveksati5143 as shown on the message you commented on - this is marked as `staff`.  Please select another issue.

**Comment by Viveksati5143** [comment]
> > > @chiragthakur09 due to lack of activity this issue has been unassigned from you. The `staff only` label has now been added.
> > 
> > 
> > I opened this issue more than a month ago but due to some confusion couldn't get assigned at the very moment😅 Can I work it on now as I do have commented to assign me in the starting so atleast now it should be the right time.
> 
> @Viveksati5143 as shown on the message you commented on - this is marked as `staff`. Please select another issue.

Can I work on this one https://github.com/EddieHubCommunity/BioDrop/issues/9301 @SaraJaoude ?

**Comment by SaraJaoude** [comment]
> > > > @chiragthakur09 due to lack of activity this issue has been unassigned from you. The `staff only` label has now been added.
> > > 
> > > 
> > > I opened this issue more than a month ago but due to some confusion couldn't get assigned at the very moment😅 Can I work it on now as I do have commented to assign me in the starting so atleast now it should be the right time.
> > 
> > 
> > @Viveksati5143 as shown on the message you commented on - this is marked as `staff`. Please select another issue.
> 
> Can I work on this one 9301 SaraJaoude ?

Please do not ask about other unrelated issues here as this causes noise and confusion.

**Comment by utkarsh-1602** [comment]
Hey! I'm Interested working on the Issue !

**Comment by sital002** [comment]
> Hey! I'm Interested working on the Issue !

@utkarsh-1602  We are glad that you want to work on this but please read the above conversation as this issue is labeled ```staff only``` so please look for another issue.

**Comment by SaraJaoude** [comment]
Closing this issue as it is now being addressed here: https://github.com/EddieHubCommunity/BioDrop/issues/9697
