### ISSUE TITLE
[Testimonial] New Testimonial Cards with Carousel Functionality

### ISSUE THREAD

**Issue by Monilprajapati** [EddieHubCommunity/BioDrop#8815]
### Description

Current Testimonial card is not looking more attractive. it just look like static website. So I can create a new Testimonial card and add them with Carousel functionality which will slide each testimonial in a particular time.

**Comment by SaraJaoude** [comment]
Thank you for raising the idea.  As we are going to be doing the redesign soon, this will be covered by that process so I will close this issue for now.
