### ISSUE TITLE
[OTHER] badges looks out of place in the profile

### ISSUE THREAD

**Issue by PriyansuMaurya** [EddieHubCommunity/BioDrop#8817]
### What would you like to share?

This matter has been concerning me for a while. The badges under red don't appear quite right because their border radius is different from the items in yellow. It looks odd in my opinion.

![image](https://github.com/EddieHubCommunity/BioDrop/assets/101447544/82124e87-a32e-4046-aecd-19f9d20bbafa)

If you observe this image everywhere, the border radius is the same and it looks awesome.

![image](https://github.com/EddieHubCommunity/BioDrop/assets/101447544/d20451fa-cef6-4fb8-85e0-448fbd5564f5)

I intend to increase the border radius for the badges so that they look harmonious.

**Comment by SaraJaoude** [comment]
Thanks for raising.  As we will be going through a redesign process this will be covered at that stage, so I will close this issue for now.
