### ISSUE TITLE
[BUG] Update the Community repo pic

### ISSUE THREAD

**Issue by kumarankit999** [EddieHubCommunity/BioDrop#8827]
### Description

Remove this pic because this pic on https://www.biodrop.io/ contains Linkfree, and its icon contains linkfree icon, remove or update it asap.

### Screenshots

![image](https://github.com/EddieHubCommunity/BioDrop/assets/111564362/6365d23a-146d-4d68-aa4e-ba3298066d75)

**Comment by SaraJaoude** [comment]
Thank you for raising. 

As to the screenshot, this will be covered in another PR: https://github.com/EddieHubCommunity/BioDrop/issues/8814 so I will close this issue.
