### ISSUE TITLE
[FEATURE] Import from LinkTree

### ISSUE THREAD

**Issue by SaraJaoude** [EddieHubCommunity/BioDrop#8829]
### Description

It would make it easier for people migrating from LinkTree to BioDrop to have a way to import their links.

**Comment by theunhackable** [comment]
I have gone through linktree website. I don't think they provide any API to get user's data. So it should be implemented through web scraping from the given account. are there any alternative ways of doing it?

**Comment by SaraJaoude** [comment]
As there is no convenient way to do this, and as web scraping is very fragile - I will close this issue for now.
