### ISSUE TITLE
[FEATURE] Show the profile stats publicly

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/BioDrop#8835]
### Description

Give the user the option to display their views and rank publicly on their profile

- display `views` and `rank` on their profile
- manage profile page has toggle for `display views on profile` and `display rank on profile`

We have paid Tailwind component https://tailwindui.com/components

**Comment by sital002** [comment]
Wow nice idea. I would like to work on this feature.

**Comment by SaraJaoude** [comment]
> Wow nice idea. I would like to work on this feature.

@sital002 I have assigned this to you

**Comment by sital002** [comment]
Just to be clear should I all these field or just total profile views and rank in the profile page.
![image](https://github.com/EddieHubCommunity/BioDrop/assets/93700622/46ae7ae1-0557-4820-b91b-7054aeee42fa)

**Comment by eddiejaoude** [comment]
It depends, I am not sure if there is space on the profile or everything? I as initially thinking just the 2 stats but maybe this component from the homepage could be reused

- rank
- total views
- total views in the last 30 days

<img width="1669" alt="Screenshot 2023-08-30 at 08 35 55" src="https://github.com/EddieHubCommunity/BioDrop/assets/624760/253ffe87-9458-4cae-b99c-52f25412d0b4">
