### ISSUE TITLE
[BUG] <Irregular margins on the account profile tab form>

### ISSUE THREAD

**Issue by ZeeMonk-pixel** [EddieHubCommunity/BioDrop#8840]
### Description

The margin space between the labels and inputs are not regular on the profile tab

### Screenshots

![profile issue](https://github.com/EddieHubCommunity/BioDrop/assets/110388816/b92575b1-94c4-453d-a178-d46626890bc0)

**Comment by SaraJaoude** [comment]
Thank you for raising!

**Comment by hankadev** [comment]
Hey @SaraJaoude, I would like to work on this issue, can you please assign it to me?

**Comment by SaraJaoude** [comment]
> Hey @SaraJaoude, I would like to work on this issue, can you please assign it to me?

@hankadev I have assigned this to you.
