### ISSUE TITLE
[IMPROVE] <description>

### ISSUE THREAD

**Issue by JakeDamon** [EddieHubCommunity/BioDrop#8844]
### Description

Twitter is no longer twitter, it should be renamed to X. The URLs and logos should all be changed to x.com and 𝕏. 

I would like to work on this.

**Comment by SaraJaoude** [comment]
Thanks for raising but we cannot update users' individual profiles - they can update these if they wish.  As Twitter will redirect as well to X, I will close this issue.

**Comment by JakeDamon** [comment]
Okay, but the user can't change the name to X due to the limit being at least 2 characters.

![image](https://github.com/EddieHubCommunity/BioDrop/assets/46137179/e22896b0-57c2-45f5-b3bb-7c6c7eb36800)

**Comment by eddiejaoude** [comment]
We could reduce it to 1 character, but most people say something like `follow me on X`

**Comment by JakeDamon** [comment]
Okay, well and the other thing was I original meant the social logo on the main page at the footer. 
![image](https://github.com/EddieHubCommunity/BioDrop/assets/46137179/c7948bd5-5546-477d-9634-6661ab61ffa3)
