### ISSUE TITLE
[FEATURE] dark mode background color -> dark grey instead of black

### ISSUE THREAD

**Issue by schmelto** [EddieHubCommunity/BioDrop#8847]
### Description

Currently the dark mode has as background color pure black.

> A dark theme uses dark grey, rather than black, as the primary surface color for components. Dark grey surfaces can express a wider range of color, elevation, and depth, because it's easier to see shadows on grey (instead of black). 

~ https://m2.material.io/design/color/dark-theme.html#properties

Idea is to change the background to something like `#121212`

**Comment by SaraJaoude** [comment]
Thanks for raising!

**Comment by zaid-ahmad** [comment]
Hi Sara, I was assigned another issue and have linked the pull request for it. Can I be assigned for this issue or should I wait for the PR to be merged?

**Comment by theunhackable** [comment]
BG with `#121212`
![image](https://github.com/EddieHubCommunity/BioDrop/assets/53367382/dd9696ed-781b-4686-bee4-a192d2d822a6)

Current BG 👇:
![image](https://github.com/EddieHubCommunity/BioDrop/assets/53367382/d2bfd79b-e203-4074-b5ac-138fd57eef05)


Which one looks better?

**Comment by SaraJaoude** [comment]
> Hi Sara, I was assigned another issue and have linked the pull request for it. Can I be assigned for this issue or should I wait for the PR to be merged?

@zaid-ahmad please wait until the PR for your other assigned issue to be merged before requesting anything else.

**Comment by theunhackable** [comment]
Hey Sara! Does team aprove this design change? if yes assign this to me I would like to work on this.

**Comment by eddiejaoude** [comment]
What about using our official color `#122640`? https://github.com/EddieHubCommunity/BioDrop/blob/main/tailwind.config.js#L18

**Comment by theunhackable** [comment]
> What about using our official color `#122640`? https://github.com/EddieHubCommunity/BioDrop/blob/main/tailwind.config.js#L18

to be honest I like this!! and if we apply some shadow to the nav it would be cool

![image](https://github.com/EddieHubCommunity/BioDrop/assets/53367382/db55d0d7-5f05-49bd-9554-4c2ce0e95845)

**Comment by eddiejaoude** [comment]
thank you for the example, the color looks different as a background 🤔  let's see what other maintainers think

**Comment by theunhackable** [comment]
> > What about using our official color `#122640`? https://github.com/EddieHubCommunity/BioDrop/blob/main/tailwind.config.js#L18
> 
> 
> 
> I like it but we definitely have to take a look where this is also used. like the stats on the profile page will have the same color (also as the navbar as @theunhackable already mentioned)
> 
> 
> 
> ![image](https://github.com/EddieHubCommunity/BioDrop/assets/30869493/a7921d1e-c979-4b9c-b774-0c25db9974e4)
> 
> 

I will take care about the shadows just tell me ehich bg I should use...

**Comment by eddiejaoude** [comment]
Maybe going darker is better than using the blue color I shared

**Comment by theunhackable** [comment]
> Maybe going darker is better than using the blue color I shared

I thnk this blue makes the whole design beautiful than dark color.
The problem with dark or the black color is... it is not complementing the blue cards. I think it's better to ask a UI designer 🧐

**Comment by thevinitgupta** [comment]
> Maybe going darker is better than using the blue color I shared

I think the default blue is good, adding shadows or borders to the Navbar and the stats card will be better.

**Comment by thevinitgupta** [comment]
@SaraJaoude I would love to work on this when it is decided.

**Comment by AbhijeetBiswalCodes** [comment]
@SaraJaoude can you please assign me this issue

**Comment by SaraJaoude** [comment]
@theunhackable as you were the first to request this and give the help with the direction of the project you have shown above I have assigned this to you.  Please go ahead with your suggested colour so that we do not have to worry about the shadows - we are having the app redesigned in the near future so this would be a short term solution.

**Comment by theunhackable** [comment]
Sorry! Merge conflicts occured I will create other PR

**Comment by eddiejaoude** [comment]
Merged
