### ISSUE TITLE
[FEATURE] Highlight premium profile

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/BioDrop#8848]
### Description

If a profile belongs to a premium account, we should highlight it with a gold star.

This is UI only, so it will display for all profiles, I will do the dynamic switching as part of the work I am doing.

Please create the pull request to branch `premium-strip` (sorry for the typo 😂 ) - create your branch from this branch also not `main` https://github.com/EddieHubCommunity/BioDrop/tree/premium-strip

**Comment by JakeDamon** [comment]
I can work on this :)

**Comment by eddiejaoude** [comment]
Thanks Jake! Assigned to you 👍

**Comment by sital002** [comment]
The PR is merged so you can close this as completed.

**Comment by eddiejaoude** [comment]
Thank you @sital002 👍
