### ISSUE TITLE
[FEATURE] Only show global repos if they meet a criteria

### ISSUE THREAD

**Issue by PriyansuMaurya** [EddieHubCommunity/BioDrop#8867]
### What would you like to share?

![image](https://github.com/EddieHubCommunity/BioDrop/assets/101447544/e33c3960-9e8c-40b6-882d-bad34c1fd2de)

This space is meant for exploration of good projects and contribute to them. For that, We have to set some criteria for listing and accepting projects on the `repos` page.

Criteria for Listing Projects:
1. Projects should be developed to a certain level and be ready for launch.
2. Projects with at least 12 stars.
3. Projects with 100 or more commits.
4. Complete documentation is a must.
5. Projects should be in active development, and owners should be actively engaging with issues.

However, there are some repositories that might not meet these criteria and could potentially waste people's time.

<img src="https://github.com/EddieHubCommunity/BioDrop/assets/101447544/cbef0f6e-7414-46bb-8685-0979d6358768" alt="Image 1" style="border: 10px solid white;">

<img src="https://github.com/EddieHubCommunity/BioDrop/assets/101447544/90c9ee8f-c654-4863-9f5b-c70dc1058cab" alt="Image 2" style="border: 10px solid white;">

<img src="https://github.com/EddieHubCommunity/BioDrop/assets/101447544/44b53571-f184-4fd8-b699-e17d9874192f" alt="Image 3" style="border: 10px solid white;">

It's worth noting that some individuals are even using this space for their GitHub READMEs.

<img src="https://github.com/EddieHubCommunity/BioDrop/assets/101447544/ebf63e41-ae0c-425b-ba4f-e0f398925de0" alt="Image 4" style="border: 2px solid white;">

**Comment by eddiejaoude** [comment]
This is an interesting idea, I will comment on each of your points

> 1. Projects should be developed to a certain level and be ready for launch.

This is not possible to judge

> 2. Projects with at least 12 stars.

Maybe 100

> 3. Projects with 100 or more commits.

Good idea, although we don't get this information

> 5. Complete documentation is a must.

This is difficult to gauge

> 6. Projects should be in active development, and owners should be actively engaging with issues.

We have the last pushed date

My thoughts on the filters with info we already have:
- 100+ stars
- 10+ forks
- Recent commit in the last 30 days

**Comment by Dun-sin** [comment]
> This is an interesting idea, I will comment on each of your points
> 
> > 1. Projects should be developed to a certain level and be ready for launch.
> 
> This is not possible to judge
> 
> > 2. Projects with at least 12 stars.
> 
> Maybe 100
> 
> > 3. Projects with 100 or more commits.
> 
> Good idea, although we don't get this information
> 
> > 5. Complete documentation is a must.
> 
> This is difficult to gauge
> 
> > 6. Projects should be in active development, and owners should be actively engaging with issues.
> 
> We have the last pushed date
> 
> My thoughts on the filters with info we already have and the mongo query could be updated:
> - 100+ stars
> - 10+ forks
> - Recent commit in the last 30 days
> 
> We can then see how this goes and build on it later
> 

I think it's possible with the the github api, the stars limit I mean🤔

**Comment by eddiejaoude** [comment]
I think we have the functionality and info we need already...

https://github.com/EddieHubCommunity/BioDrop/blob/5d4eb0be1cb7527726e5c36e13e2c3f14bcbb258/models/Profile/Repo.js#L34-L40

**Comment by Dun-sin** [comment]
> I think we have the functionality and info we need already...
> 
> https://github.com/EddieHubCommunity/BioDrop/blob/5d4eb0be1cb7527726e5c36e13e2c3f14bcbb258/models/Profile/Repo.js#L34-L40

that's actually good then

**Comment by dhruvilmehta** [comment]
I can work on this issue.

**Comment by dhruvilmehta** [comment]
> This is an interesting idea, I will comment on each of your points
> 
> > 1. Projects should be developed to a certain level and be ready for launch.
> 
> This is not possible to judge
> 
> > 2. Projects with at least 12 stars.
> 
> Maybe 100
> 
> > 3. Projects with 100 or more commits.
> 
> Good idea, although we don't get this information
> 
> > 5. Complete documentation is a must.
> 
> This is difficult to gauge
> 
> > 6. Projects should be in active development, and owners should be actively engaging with issues.
> 
> We have the last pushed date
> 
> My thoughts on the filters with info we already have and the mongo query could be updated:
> 
> * 100+ stars
> * 10+ forks
> * Recent commit in the last 30 days
> 
> We can then see how this goes and build on it later

Should we update Mongo Query for this ?
we can simply apply a filter like this in the `pages/repos.js`
```js
export async function getServerSideProps() {
  let repos = await getRepos();
  return {
    props: { repos: repos.filter(repo=>repo.stats.stars>=100 && repo.stats.forks>=10) },
  };
}
```

And for `Recent Commit in 30 days` filter, should we consider the `pushedAt` variable for finding out the last commit ?
```js
dates: {
      createdAt: '2023-05-27T12:56:31.000Z',
      updatedAt: '2023-08-30T20:10:57.000Z',
      pushedAt: '2023-08-30T20:08:43.000Z'
    },
    updatedAt: '2023-08-30T20:30:06.820Z',
```

**Comment by eddiejaoude** [comment]
@dhruvilmehta this should be done in a mongo query not in javascript code, otherwise it will not be efficient. Do you still want it to be assigned?

**Comment by dhruvilmehta** [comment]
Yes you can assign this to me.
Can you tell me how to find out the last commit date. is it the same as `pushedAt` key in the dates object of the repository as shown in the above comment ?

**Comment by ChinmayMhatre** [comment]
Personally, I feel stars shouldn't be a metric for this. Newer projects can also be good if maintainers seriously want to contribute to the community. What do you think @eddiejaoude 

Other metrics such as commits and all are fine.

**Comment by eddiejaoude** [comment]
> Yes you can assign this to me.
> Can you tell me how to find out the last commit date. is it the same as `pushedAt` key in the dates object of the repository as shown in the above comment ?

I have assigned it to you. Yes use `pushedAt` 👍

**Comment by eddiejaoude** [comment]
> Personally, I feel stars shouldn't be a metric for this. Newer projects can also be good if maintainers seriously want to contribute to the community. What do you think @eddiejaoude
> 
> Other metrics such as commits and all are fine.

I agree, but also many projects are dropped early, I think the star metric also demonstrates a bit of commitment to their  project

**Comment by schmelto** [comment]
<img width="1225" alt="image" src="https://github.com/EddieHubCommunity/BioDrop/assets/30869493/d5955414-78f4-4877-ba90-fb4c0156100a">
