### ISSUE TITLE
[FEATURE] add everyone's rank publicly

### ISSUE THREAD

**Issue by Dun-sin** [EddieHubCommunity/BioDrop#8876]
### Description

Like a leaderboard where everyone can see the ranks of everyone else, But not everyone will be on the list unless they already have their rank turned on(enabled) in their profile public.

**Comment by eddiejaoude** [comment]
I really like this idea, but unfortunately, we had something very similar before and people just gamed the system by writing scripts, so it doesn't work 😢 - so I will close

**Comment by Dun-sin** [comment]
> I really like this idea, but unfortunately, we had something very similar before and people just gamed the system by writing scripts, so it doesn't work 😢 - so I will close

Oh damn😕

**Comment by Dun-sin** [comment]
> yes indeed 😢  we can't have nice things 😂 

Wait can't they still do it now? Because the rank actually never went away🤔

**Comment by eddiejaoude** [comment]
yes they can, but because there is no page with a list, they are less likely to do it from what we have noticed

**Comment by Dun-sin** [comment]
> yes they can, but because there is no page with a list, they are less likely to do it from what we have noticed

that's true, oh well, i would have really loved it. Maybe we can find a workaround in the feature
