### ISSUE TITLE
[FEATURE] Stats on Landing page | redundant information

### ISSUE THREAD

**Issue by schmelto** [EddieHubCommunity/BioDrop#8885]
### Description

The stats on the homepage shows duplicate information. Like "active users 2.8K from 2.8K"  I suggest only display the active users (28k) instead of showing the past ones.
Same for the other ones although it seems kind of wired links clicked xx from xx.

Hope this makes sense

### Screenshots

Old: 
![image](https://github.com/EddieHubCommunity/BioDrop/assets/30869493/c3fa79e9-7581-4f52-8ab7-220ae8601949)

New:
![image](https://github.com/EddieHubCommunity/BioDrop/assets/30869493/e86c8808-ab70-459f-a653-d7c31f617dcd)

**Comment by SaraJaoude** [comment]
Thanks for raising!
