### ISSUE TITLE
[BUG] need to add some control to the Milestone date field

### ISSUE THREAD

**Issue by Giuliano1993** [EddieHubCommunity/BioDrop#8926]
### Description

While adding milestones  I accidentally wrote in the year part of the date field "0008"; the form accepted the value showing a mileston in year 8. We should probably add some kind of control, like a minimum date

### Screenshots

![Screenshot 2023-09-02 202609](https://github.com/EddieHubCommunity/BioDrop/assets/12759050/17e11148-b8cb-4c53-ae17-060b42caea19)
![Screenshot 2023-09-02 202624](https://github.com/EddieHubCommunity/BioDrop/assets/12759050/b1a7602d-3fc6-44b6-83e3-424845bf10ae)

### Do you want to work on this issue?

Yes

**Comment by SaraJaoude** [comment]
Thank you for raising! I have assigned this to you.
