### ISSUE TITLE
[FEATURE] change style and position of events price

### ISSUE THREAD

**Issue by moAlireza** [EddieHubCommunity/BioDrop#8931]
### Description

in the **Events** section, Events that aren't free have a price and that price style is exactly the same as the event text so it is hard for a user to see the price. it will be good if the price has a different background or color. 
the other problem with price is its position. it is fine on mobile and small screens but on desktop and large screens, it doesn't have a fixed position, and its position changes based on the event text! the event's price on large screens like desktops must be fixed too otherwise the users will have some difficulties seeing prices. 

### Screenshots

**Event's price on desktop:**
![issue-desktop](https://github.com/EddieHubCommunity/BioDrop/assets/143579955/d3a3f2b7-6d1a-4dd6-9092-ebd50307754a)

**Event's price on mobile:**
![issue-mobile](https://github.com/EddieHubCommunity/BioDrop/assets/143579955/ef1894ee-9f01-43d8-bf57-cccc90c8fcc8)

### Do you want to work on this issue?

None

**Comment by SaraJaoude** [comment]
Thank you for raising, but as we will be going through a redesign process this is likely to be addressed then - so I will close this Issue for now.
