### ISSUE TITLE
[BUG] <description>

### ISSUE THREAD

**Issue by umar-webdev** [EddieHubCommunity/BioDrop#8933]
### Description

The Twitter Logo on Footer is old one on the website that is not the official Twitter logo.

### Screenshots

![image](https://github.com/EddieHubCommunity/BioDrop/assets/63943753/271d8fbe-6498-4012-8889-42a776006bef)

### Do you want to work on this issue?

Yes

**Comment by SaraJaoude** [comment]
Thank you for raising - this has actually been raised in multiple occasions and closed. It would be helpful if in future you could please check both the open and closed issues to avoid duplication.

We are using React Icons to collect a variety of icon sets together. As the icon libraries do not contain this new icon yet, this update to BioDrop cannot be done.

You may want to raise an issue on the relevant icon library, here is the React Icon Repo where you can see the multiple icon sets: https://github.com/react-icons/react-icons

I will therefore close this issue for now.
