### ISSUE TITLE
[FEATURE] <Request to Update Twitter icon to X>

### ISSUE THREAD

**Issue by Pravesh-Sudha** [EddieHubCommunity/BioDrop#8934]
### Description

Describe the bug
I would like to propose a change to the current Twitter icon. As icons play a significant role in representing the project and creating a visual identity, I believe updating the Twitter icon could enhance the overall aesthetics and recognition of the website.

### Screenshots

![Screenshot from 2023-09-03 22-47-34](https://github.com/EddieHubCommunity/BioDrop/assets/88569706/90dfee6e-37c4-4f80-b0c2-b0750f0c623f)

### Do you want to work on this issue?

Yes

### Expected Behavior
Change the old logo with the new one.

**Comment by SaraJaoude** [comment]
Thank you for raising.  This has been raised a number of times so I would ask that you would check the open but also the closed issues as well before raising. 

We are using React Icons to collect a variety of icon sets together. As the icon libraries do not contain this new icon yet, this update to BioDrop cannot be done.

You may want to raise an issue on the relevant icon library, here is the React Icon Repo where you can see the multiple icon sets: https://github.com/react-icons/react-icons 

I will therefore close this issue for now.

**Comment by Pravesh-Sudha** [comment]
OK, actually there was no accurate description on this Logo issue by others, so I thought there is a need to raise an issue with specific description. Sorry for the trouble
