### ISSUE TITLE
[BUG] : Hydration Error Issue When Running npm run dev

### ISSUE THREAD

**Issue by yashnerkar** [EddieHubCommunity/BioDrop#8935]
### Description

Today, while attempting to set up the project locally, I successfully installed all the necessary packages and configured the development environment. However, when I executed the npm run dev command on port 3000, I encountered a hydration error issue. I made an effort to debug this issue, but unfortunately, I was unable to identify the root cause.

### Screenshots

![image](https://github.com/EddieHubCommunity/BioDrop/assets/65919365/76392d91-8964-4ed5-8b41-be8e2e9ee242)

### Do you want to work on this issue?

None

**Comment by eddiejaoude** [comment]
Thank you for raising. Can you come and chat to us in EddieHub Discord so we can debug, then we can raise an issue as this is likely to be a local issue http://discord.eddiehub.org

**Comment by yashnerkar** [comment]
okay! thanks @eddiejaoude . Will chat on discord
