### ISSUE TITLE
[FEATURE] Color Picker for events

### ISSUE THREAD

**Issue by schmelto** [EddieHubCommunity/BioDrop#8946]
### Description

When creating an event there is the option to choose a color.
There is no explanation on how to add the color.

<img width="380" alt="image" src="https://github.com/EddieHubCommunity/BioDrop/assets/30869493/708ec4c3-4d3e-4997-be8f-da2dd7f298da">

-> best would be to implement a color picker so there will be no miss understandings.

### Screenshots

Maybe something like this:
<img width="256" alt="image" src="https://github.com/EddieHubCommunity/BioDrop/assets/30869493/68c2875d-00b8-4104-af57-c73a3811a45e">

### Do you want to work on this issue?

No

**Comment by ChinmayMhatre** [comment]
Love the idea!

**Comment by SaraJaoude** [comment]
I agree - great idea! I think we should start off simple and use the html colour picker: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/color

I appreciate it might not be as "fancy" as using a library but we are near the Vercel file limit and a library would include many files.

**Comment by AbhishekBhure** [comment]
Yeah we can start simple and use an HTML color picker, I am interested in working on this. Can I work on it?

**Comment by Nwakaego-Ego** [comment]
I am interested, please assign to me

**Comment by SaraJaoude** [comment]
> Yeah we can start simple and use an HTML color picker, I am interested in working on this. Can you please assign it to me?

@AbhishekBhure I have assigned this to you.

**Comment by AbhishekBhure** [comment]
Thank you, I will work on this

**Comment by AbhishekBhure** [comment]
> > Yeah we can start simple and use an HTML color picker, I am interested in working on this. Can you please assign it to me?
> 
> @AbhishekBhure I have assigned this to you.

Hello @SaraJaoude I have completed the task should I now create a pull request?

**Comment by schmelto** [comment]
@AbhishekBhure yeah please open a PR for this topic!

**Comment by AbhishekBhure** [comment]
> @AbhishekBhure yeah please open a PR for this topic! Remember to connect the PR and the issue with `fixes #8946` in the PR comment

Thank you!! I have created a pull request and connected it to the PR and the issue as well.

**Comment by AbhishekBhure** [comment]
And I also want to mention the other two commits do not change any code, please just consider the [346cb32]
