### ISSUE TITLE
[BUG] Inconsistent Profile Image Sizes on manage testimonials

### ISSUE THREAD

**Issue by JakeDamon** [EddieHubCommunity/BioDrop#8947]
### Description

As show in the screenshot, the profile images are not consistent on the manage testimonials page

The solution is to make them consistent. 

### Screenshots

![image](https://github.com/EddieHubCommunity/BioDrop/assets/46137179/d66a2d34-7937-4428-84c5-a708d8d00883)

### Do you want to work on this issue?

Yes

**Comment by allexgut** [comment]
Can I get this assigned? I already have a solution because I didn't realise I need the issue assigned to me first before starting work.

**Comment by SaraJaoude** [comment]
@JakeDamon as it has been two weeks without any activity, I am going to unassign this issue from you.

**Comment by SaraJaoude** [comment]
> Can I get this assigned to me? I already have a solution because I didn't realise I need the issue assigned to me first before starting work.

@allexgut on this occasion as the original assignee has not yet opened a PR and it has been two weeks, we will assign this to you.  Please do familiarise yourself with the Contributing Guide sent to you to avoid in future you doing any work which could then not be used.
