### ISSUE TITLE
[FEATURE] <Migrating > Migrating to TypeScript from JavaScript  

### ISSUE THREAD

**Issue by theunhackable** [EddieHubCommunity/BioDrop#8948]
### Description

I can see the application growing day by day which is wonderful. In the long run it would be harder to maintain the code if we do not implement TypeScript. I would suggest migrating to TypeScript which would enhance developer experience, self documenting code as types are provided, would improve error handling,  and attract more contributors to work on this project.

### Do you want to work on this issue?

Yes

**Comment by SaraJaoude** [comment]
This is a great idea and certainly something that we are considering, but not for the moment.  I will therefore close this issue for now.
