### ISSUE TITLE
[BUG] In the statistics, design breaks with long links

### ISSUE THREAD

**Issue by Giuliano1993** [EddieHubCommunity/BioDrop#8952]
### Description

If you have some long link in your link list, on the panel that shows click number on each link, the link line doesn't break so the card containing the links get larger and larger.

### Screenshots

![Screenshot 2023-09-04 164133](https://github.com/EddieHubCommunity/BioDrop/assets/12759050/d6fd5c86-a33a-476f-bbaa-286140f2c112)

### Do you want to work on this issue?

Yes

### Additional information

To fix this it would be enough to wrap the content or to add an overflow handling. Since those aren't clickable link but just informative, I feel like the wrap solution would work better, what do you think?

**Comment by SaraJaoude** [comment]
Thank you for raising.  Unfortunately @Giuliano1993 I cannot assign this to you at this time as you already have an issue assigned to you.  As reflected in our [Contributing Guide](https://github.com/EddieHubCommunity/BioDrop/blob/main/CONTRIBUTING.md) we only assign one issue per person at any one time.

**Comment by SaraJaoude** [comment]
> I would like to work on this!

@theunhackable I have assigned this to you.

**Comment by theunhackable** [comment]
help me please! I am doing this for the 2nd time I dont want to do this again.
How to avoid this? I contributed to one file about 20 lines only.
but it is showing more...

![image](https://github.com/EddieHubCommunity/BioDrop/assets/53367382/f5d16951-99f5-4e87-9e4b-31716b9e1cf8)

**Comment by theunhackable** [comment]
- I  removed the commits in the forked branch and synced the fork 
- Then I pulled to the clone of forked repo then I made the changes.

What is the correct way to do this?

**Comment by ckelwin** [comment]
> * I  removed the commits in the forked branch and synced the fork
> * Then I pulled to the clone of forked repo then I made the changes.
> 
> What is the correct way to do this?

Keep the `main` branch in your forked repo synced to with BioDrop. Create a new branch (from `main` of your or BioDrop repo) for each issue you fix. Do not fix them in the `main` of your forked repo. Create a PR from your feature branch into BioDrop main.
