### ISSUE TITLE
[BUG] QR code overlay crop on tiny screens

### ISSUE THREAD

**Issue by JayPatil9** [EddieHubCommunity/BioDrop#8959]
### Description

The QR code popup seems to be broken in **some** android devices.

### Screenshots

![Screenshot_20230904-191913](https://github.com/EddieHubCommunity/BioDrop/assets/75982633/e1905a1b-d7f7-4cf8-a69e-98694c5e4480)

### Do you want to work on this issue?

No

**Comment by eddiejaoude** [comment]
Thank you for raising the issue but I will rename the title "BROKEN UI" because the title is too aggressive

**Comment by Deveesh-Shetty** [comment]
I would like to work on this issue!

**Comment by SaraJaoude** [comment]
> I would like to work on this issue!

@Deveesh-Shetty I have assigned this to you
