### ISSUE TITLE
[FEATURE] Add ScrollToTop Button

### ISSUE THREAD

**Issue by AbhishekBhure** [EddieHubCommunity/BioDrop#8963]
### Description

For a better user experience, it would be great to add a scroll to the top button. When a user scrolls through the page they have to scroll to the top again. I would like to work on this issue if it is found that it can be added.

### Screenshots

![scroll](https://github.com/EddieHubCommunity/BioDrop/assets/87894780/6f76d19b-45f1-434b-8f11-f3dc95e3e288)

### Do you want to work on this issue?

Yes

### Additional information

We can add the button just above the help button and, it will disappear once it reaches the top, Although it is a basic thing it is better to allow the user to use the application easily.

**Comment by SaraJaoude** [comment]
Thank you for raising, but this has been raised multiple times - please see here: https://github.com/EddieHubCommunity/BioDrop/issues/8927#issuecomment-1704919129 - therefore I am closing this issue.
