### ISSUE TITLE
[BUG] manage event page isn't showing no events warning.

### ISSUE THREAD

**Issue by sital002** [EddieHubCommunity/BioDrop#8964]
### Description

Go to https://www.biodrop.io/account/manage/events
When there are zero events it should show no Events and the filter icon should be hidden if there are no events to display.

### Screenshots

![image](https://github.com/EddieHubCommunity/BioDrop/assets/93700622/a0e57f80-580c-4145-a3ee-99e7a121ca94)
It should have a warning message like
![image](https://github.com/EddieHubCommunity/BioDrop/assets/93700622/fe8e0181-10f4-42f9-88eb-514833c22936)

### Do you want to work on this issue?

None

**Comment by adarshmalviya12** [comment]
Is anyone working on this issue? If not, can I work on it?

**Comment by AbhishekBhure** [comment]
I am interested in working on this, as my first pull request was on adding color to events was successfully merged, can this be assigned to me?

**Comment by SaraJaoude** [comment]
@adarshmalviya12 as you were the first to request this I will assign to you.
