### ISSUE TITLE
[FEATURE] Profile show tab using query parameter

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/BioDrop#8969]
### Description

It would be great to be able to share our profile with a query parameter so that it can display the tab directly - for example I was chatting to someone about the events I am attending

- query parameter for tab
- click tab also sets the parameter 
- tab displays if query parameter set 

### Do you want to work on this issue?

None

**Comment by Dun-sin** [comment]
what i understand by this is when you click on milestones, the url should change to "https://www.biodrop.io/Dun-sin?tab=milestones", so if you copy that link and paste it somewhere else you directly go to milestones right?

**Comment by rizahmeds** [comment]
I can work on this.

**Comment by SaraJaoude** [comment]
> I can work on this. Please assign it to me.

@rizahmeds as mentioned we only assign one issue per contributor at any one time (see [Contributing Guide](https://github.com/EddieHubCommunity/BioDrop/blob/main/CONTRIBUTING.md)) and currently you have another issue assigned to you.

**Comment by Dun-sin** [comment]
can i be assigned?

**Comment by rizahmeds** [comment]
> > I can work on this. Please assign it to me.
> 
> @rizahmeds as mentioned we only assign one issue per contributor at any one time (see [Contributing Guide](https://github.com/EddieHubCommunity/BioDrop/blob/main/CONTRIBUTING.md)) and currently you have another issue assigned to you.

Currently assigned issue's PR is not yet merged, tasking longer time than usual.

**Comment by SaraJaoude** [comment]
> can i be assigned?

@Dun-sin I have assigned this to you

**Comment by SaraJaoude** [comment]
> > > I can work on this. Please assign it to me.
> > 
> > 
> > @rizahmeds as mentioned we only assign one issue per contributor at any one time (see [Contributing Guide](https://github.com/EddieHubCommunity/BioDrop/blob/main/CONTRIBUTING.md)) and currently you have another issue assigned to you.
> 
> Currently assigned issue's PR is not yet merged, tasking longer time than usual.

@rizahmeds thanks for your enthusiasm - but I am not sure what you mean by "longer time than usual". Please be mindful of other maintainers' time and the number of issues which need to be reviewed for this project. Extra notifications also do not help us move things along. To speed things up generally please feel free to assist with reviewing open PRs.

**Comment by rizahmeds** [comment]
> > > > I can work on this. Please assign it to me.
> > > 
> > > 
> > > @rizahmeds as mentioned we only assign one issue per contributor at any one time (see [Contributing Guide](https://github.com/EddieHubCommunity/BioDrop/blob/main/CONTRIBUTING.md)) and currently you have another issue assigned to you.
> > 
> > Currently assigned issue's PR is not yet merged, tasking longer time than usual.
> 
> @rizahmeds thanks for your enthusiasm - but I am not sure what you mean by "longer time than usual". Please be mindful of other maintainers' time and the number of issues which need to be reviewed for this project. Extra notifications also do not help us move things along. To speed things up generally please feel free to assist with reviewing open PRs. 

Thanks for the suggestions 🙂

**Comment by eddiejaoude** [comment]
> what i understand by this is when you click on milestones, the url should change to "https://www.biodrop.io/Dun-sin?tab=milestones", so if you copy that link and paste it somewhere else you directly go to milestones right?

that is correct @Dun-sin 👍

**Comment by Dun-sin** [comment]
> > what i understand by this is when you click on milestones, the url should change to "https://www.biodrop.io/Dun-sin?tab=milestones", so if you copy that link and paste it somewhere else you directly go to milestones right?
> 
> that is correct @Dun-sin 👍

awesome, getting right on it
