### ISSUE TITLE
[BUG] Can't delete a link i created

### ISSUE THREAD

**Issue by Giuliano1993** [EddieHubCommunity/BioDrop#8970]
### Description

When trying to delete a link it gives me an error, saying it is impossible to remove that link, with an error 400 to delete

### Screenshots

![Screenshot 2023-09-07 063632](https://github.com/EddieHubCommunity/BioDrop/assets/12759050/d033002b-f142-41eb-a40a-da6074532a29)

### Do you want to work on this issue?

Yes

**Comment by eddiejaoude** [comment]
Thank you raising the bug. This is quite urgent, so I went ahead and fixed it.
