### ISSUE TITLE
Change The Twitter logo 

### ISSUE THREAD

**Issue by Vijaykv5** [EddieHubCommunity/BioDrop#8976]
### Description

I believe that the Twitter logo with "flappy bird" has been replaced by "X" and I think we can also update that.

Just need to correct it in the footer.

### Screenshots

<img width="1389" alt="Screenshot 2023-09-07 at 8 14 39 PM" src="https://github.com/EddieHubCommunity/BioDrop/assets/94985341/9c88def5-a95c-492c-983f-ae66c3c96f11">

### Do you want to work on this issue?

Yes

**Comment by SaraJaoude** [comment]
Thank you for raising but this has been raised before (see https://github.com/EddieHubCommunity/BioDrop/issues/8934) so I will be closing this for now.
