### ISSUE TITLE
[BUG] Search query doesn't reset if search bar becomes empty

### ISSUE THREAD

**Issue by dhruvilmehta** [EddieHubCommunity/BioDrop#8980]
### Description

1. As you can see in the image below, the search bar is empty but the query parameter in the URL is still there
![image](https://github.com/EddieHubCommunity/BioDrop/assets/68022411/ebab95b5-134a-435f-81aa-c3da0faf329a)
---
2. Also, if there are less than 2 characters to search, then it is not searching, I think this should not be the case. Even if there is only 1 character to search, then it should search. In the image below, I first searched for 2 characters, but then I deleted the second character, but still there are 2 characters in the URL search query.
![image](https://github.com/EddieHubCommunity/BioDrop/assets/68022411/ff5baa8d-749a-4acf-b51b-26ffb175dea9)
---

I think this is how it should work. I have already solved the issue, just waiting to get it approved.
https://github.com/EddieHubCommunity/BioDrop/assets/68022411/fc8ed13f-db63-43a9-a370-5141ac2588d1

### Do you want to work on this issue?

Yes

**Comment by SaraJaoude** [comment]
Thank you for raising and the detailed explanation in the description - I have assigned this to you @dhruvilmehta .
