### ISSUE TITLE
[BUG] <Move Alert Box to the Top of the Page in Dev Mode>

### ISSUE THREAD

**Issue by Nwakaego-Ego** [EddieHubCommunity/BioDrop#8989]
### Description

In dev mode, when there's no data loaded, we currently have an alert box on the home page. However, it's not appearing at the  location, which is at the top of the page under the main navbar. This issue is about relocating the alert box to the top.

### Screenshots

![alert](https://github.com/EddieHubCommunity/BioDrop/assets/81041326/7b826490-751c-40c5-88b4-f806fd847774)

### Do you want to work on this issue?

Yes

**Comment by eddiejaoude** [comment]
Thank you for raising the issue, I have assigned it to you 👍
