### ISSUE TITLE
[BUG] Request to Update Twitter Icon to X

### ISSUE THREAD

**Issue by lalitkumawat1m** [EddieHubCommunity/BioDrop#9000]
### Description

The Twitter logo has been updated recently and hasn't been updated on the site. I didn't find any issue related to this.

What's the expected result?
The Twitter logo should be changed to X.

### Screenshots

<img width="960" alt="Screenshot 2023-09-09 061556" src="https://github.com/EddieHubCommunity/BioDrop/assets/91591901/b4df0eef-0272-4edf-bef2-89a1b5842aef">

### Do you want to work on this issue?

Yes

### Additional information

@eddiejaoude 
I am just starting with open source contribution. I would love to take this issue as my first ever contribution could you please assign this to me?

**Comment by SaraJaoude** [comment]
Thank you for raising. This has been raised a number of times so I would ask that you would check the open but also the closed issues as well before raising.

We are using React Icons to collect a variety of icon sets together. As the icon libraries do not contain this new icon yet, this update to BioDrop cannot be done.

You may want to raise an issue on the relevant icon library, here is the React Icon Repo where you can see the multiple icon sets: https://github.com/react-icons/react-icons

I will therefore close this issue for now.

**Comment by SaraJaoude** [comment]
@lalitkumawat1m I will assign this to you

**Comment by eddiejaoude** [comment]
We now have upgraded our icon library `react-icons` so the X icon is available

**Comment by ValkonX33** [comment]
anyone working on this? if not then i'd like to work please

**Comment by eddiejaoude** [comment]
please reason conversation above your message, yes it has been assigned already
