### ISSUE TITLE
[OTHER] Invitation to the github community organisation 

### ISSUE THREAD

**Issue by DigitalAbdool** [EddieHubCommunity/BioDrop#9003]
### What would you like to share?

I would like to be part of this awesome community organisation. 

### Do you want to work on this issue?

None

**Comment by eddiejaoude** [comment]
Great 👍  Please follow the steps to join our GitHub Org and to get started with the EddieHub community https://github.com/EddieHubCommunity?view_as=public#steps-to-get-started

**Comment by eddiejaoude** [comment]
Great 👍  Please follow the steps to join our GitHub Org and to get started with the EddieHub community https://github.com/EddieHubCommunity?view_as=public#steps-to-get-started
