### ISSUE TITLE
[BUG] Tag's border difference from other page

### ISSUE THREAD

**Issue by yashpreet2707** [EddieHubCommunity/BioDrop#9004]
### Description

In the Light mode, The tag's shadow is very Diluted, which makes it less distinguishing than other page colors. 

See the difference in the screenshot, if you think this issue is worth the shot, please assign it to me. 

I am just starting out contributing to the project. Please tell me how should I start contributing to this project, I want to contribute.

### Screenshots

Currently -

<img width="1440" alt="Screenshot 2023-09-09 at 2 28 12 PM" src="https://github.com/EddieHubCommunity/BioDrop/assets/111020648/d3a27d59-21d2-40ca-a500-ae311083ab50">

After the modification - 

<img width="1440" alt="Screenshot 2023-09-09 at 2 27 46 PM" src="https://github.com/EddieHubCommunity/BioDrop/assets/111020648/a40ec060-7ec4-4742-8366-910d66ab4f15">

### Do you want to work on this issue?

Yes

**Comment by SaraJaoude** [comment]
Thank you for raising but as we are going through the redesign process this will be looked at then, so I will close this issue for now. 

Please do have a look at other open issues marked with the label `status: ready for dev` - we look forward to your contributions!
