### ISSUE TITLE
[BUG]  React Hook useEffect has a missing dependency in ./pages/search.js

### ISSUE THREAD

**Issue by saram7619** [EddieHubCommunity/BioDrop#9006]
### Description

This issue came up as a warning in my vs code terminal after I ran git commit on an issue that I fixed. The warning can be recreated by going to ./pages/search.js 

This can be fixed by just adding the missing dependencies.

### Screenshots

<img width="1710" alt="Screenshot 2023-09-09 at 09 42 37" src="https://github.com/EddieHubCommunity/BioDrop/assets/82645022/769e5cd0-3f63-4a1d-a879-c9083b0bcfa8">

### Do you want to work on this issue?

Yes

**Comment by SaraJaoude** [comment]
Thanks for raising! I have assigned this to you @saram7619

**Comment by saram7619** [comment]
Thank you @SaraJaoude

**Comment by SaraJaoude** [comment]
Unassigned for the reason mentioned here: https://github.com/EddieHubCommunity/BioDrop/pull/9508

**Comment by Roshanchau** [comment]
hello can you assign me this issue?

**Comment by SaraJaoude** [comment]
> hello can you assign me this issue?

@Roshanchau I will assign this to you

**Comment by Roshanchau** [comment]
I cannot find the same timer function where the useEffect hook has missing dependency as in the screenshot.

**Comment by ArvindParekh** [comment]
Hello! I've noticed that the code causing the issue has been removed as part of PR #9248. The terminal no longer shows any missing dependencies. It looks like we might be able to close this issue now, but I'd love to get your thoughts on it.

![image](https://github.com/EddieHubCommunity/BioDrop/assets/71211731/9fdfa256-72fb-411b-979c-10ee3934b100)

**Comment by eddiejaoude** [comment]
> Hello! I've noticed that the code causing the issue has been removed as part of PR #9248. The terminal no longer shows any missing dependencies. It looks like we might be able to close this issue now, but I'd love to get your thoughts on it.

Good spot, thank you 👍
