### ISSUE TITLE
[OTHER] Enhancing primary buttons on homepage

### ISSUE THREAD

**Issue by GaganpreetKaurKalsi** [EddieHubCommunity/BioDrop#9008]
### What would you like to share?

The colours used for the primary button (the green one) are both dark which doesn't help develop a nice contrast.
Also, generally, a border and a background colour doesn't coexist in a button at the same time. Below is my suggestion

- text color - white(as the background is dark, we need something light to create contrast)
- no border - Primary buttons usually have a background colour and no border

Also, the Help button at the bottom looks good with a white colour.

<br>

**Below find screenshots to see how it would look :-**

See the "Get started" button below

**Image 1** - Normal
**Image 2** - Hover

<img width="1440" alt="image" src="https://github.com/EddieHubCommunity/BioDrop/assets/54144759/8bab43c5-b770-4933-b493-11ae92536844">
<img width="1440" alt="image" src="https://github.com/EddieHubCommunity/BioDrop/assets/54144759/61b566e0-dea2-4174-acde-09786a3a9ada">

### Do you want to work on this issue?

Yes

### Additional information

Let me know if this enhancement makes sense.
Also if you would like to refer a few buttons, below are links of some design systems
- [Antd](https://ant.design/components/button)
- [Carbon](https://carbondesignsystem.com/components/button/usage/#live-demo)
- [Material design](https://m3.material.io/components/buttons/overview)

**Comment by SaraJaoude** [comment]
Thank you for raising. On the text colour for the button it may look nicer with white text but this would fail AA accessibility for the contrast ration. As we are also going through a redesign this is likely to be addressed then, so I will close this issue for now.
