### ISSUE TITLE
Misalignment of the section in Mobile view

### ISSUE THREAD

**Issue by VivekBaldha0712** [EddieHubCommunity/BioDrop#9012]
### Description

At the end of the page, "Subscribe" button and the above line is left aligned. It should be in the center to enhance the site look.

### Screenshots

<img width="176" alt="Screenshot 2023-09-09 212817" src="https://github.com/EddieHubCommunity/BioDrop/assets/86009821/345e3b3a-b738-47c0-b816-2a08e2821bd4">

### Do you want to work on this issue?

None

**Comment by SaraJaoude** [comment]
Thank you for raising.  However as we are going through a redesign process we can look at this then so I will close this issue for now.
