### ISSUE TITLE
[FEATURE] Mobile View Profile Pic Issue

### ISSUE THREAD

**Issue by SreejithMVarma** [EddieHubCommunity/BioDrop#9014]
### Description

In the mobile view of the Community Events page, there is a discrepancy regarding the display of profile pictures. On desktop, profile pictures are visible, but they are missing in the mobile view.

**Steps to Reproduce:**
1. Access the Community Events page on a desktop browser.
2. Observe that profile pictures are displayed correctly.
3. Access the same page on a mobile device.
4. Notice that profile pictures are missing in the mobile view.

### Screenshots

- **Desktop view showing profile pictures** 

![Screenshot 2023-09-09 201454](https://github.com/EddieHubCommunity/BioDrop/assets/105853895/182cc9d6-8c46-40f9-8c35-86b4825b509c)

- **Mobile view without profile pictures** 

![Screenshot 2023-09-09 201519](https://github.com/EddieHubCommunity/BioDrop/assets/105853895/68eeeac9-034c-41c7-9659-3e1466f1e18e)

### Do you want to work on this issue?

Yes

### Additional information

**Expected Behavior:**
Profile pictures should be displayed consistently across both desktop and mobile views of the Community Events page.

**Labels: enhancement**

**Comment by SaraJaoude** [comment]
Thank you for raising.  This was a design choice as there is a lack of space in mobile view, so I will be closing this issue.
