### ISSUE TITLE
[BUG]  Display Name value disappearing

### ISSUE THREAD

**Issue by NanduNanduz** [EddieHubCommunity/BioDrop#9026]
### Description

Display Name value disappearing while adding animation

https://github.com/EddieHubCommunity/BioDrop/assets/115874551/ca8fa7b8-173b-41ce-ab61-e721aba78216

### Do you want to work on this issue?

Yes

### Additional information

Hai I'm new to this community

**Comment by SaraJaoude** [comment]
Thanks for raising. We are unable to replicate so I will close this issue for now.

**Comment by NanduNanduz** [comment]
Simply copying the Icon Name doesn't appear to work; we need to select the text copied from the corresponding dropdown, which I didn't do, and that seems to be the issue

**Comment by eddiejaoude** [comment]
I am still not sure I follow. The drop-down is to be clicked

**Comment by eddiejaoude** [comment]
thank you for raising the issue, it is always good to discuss these and be made aware of it 👍 

We are starting a complete redesign, I think this will be improved as part of that - as long as it is not broken at the moment I think we can leave it for now
