### ISSUE TITLE
[DOCS] Add LICENSE section to README

### ISSUE THREAD

**Issue by MaorBemdoo** [EddieHubCommunity/BioDrop#9036]
### Description

The README.md file does not have a LICENSE section to showcase LICENSE Biodrop is under.

### Do you want to work on this issue?

None

**Comment by SaraJaoude** [comment]
Thank you for your contribution but given that the License is shown on the Repo page I cannot see this would be necessary and will close this issue.

<img width="1590" alt="Screenshot 2023-09-13 at 13 24 55" src="https://github.com/EddieHubCommunity/BioDrop/assets/82668196/45a192c0-dac8-4092-9a70-762792f8ad42">
