### ISSUE TITLE
[OTHER] Add Kim's Community Resource

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/BioDrop#9037]
### What would you like to share?

- Update the json file https://github.com/EddieHubCommunity/BioDrop/blob/main/config/community-resources.json
- YouTube link 
   - https://twitter.com/kamcmahon/status/1701276223090073865
   - https://www.youtube.com/watch?v=LAsz48CixZY
- So it appears on the community docs page https://www.biodrop.io/docs/community-resources

### Do you want to work on this issue?

Going to be assigned to https://twitter.com/Nene_dev26

**Comment by Nenepo** [comment]
> ### What would you like to share?
> * Update the json file https://github.com/EddieHubCommunity/BioDrop/blob/main/config/community-resources.json
> * YouTube link
>   
>   * https://twitter.com/kamcmahon/status/1701276223090073865
>   * https://www.youtube.com/watch?v=LAsz48CixZY
> 
> ### Do you want to work on this issue?
> Going to be assigned to https://twitter.com/Nene_dev26
> 
> ### Additional information
> _No response_

Please assign it to me

**Comment by eddiejaoude** [comment]
Thank you for your enthusiasm @ianujvarshney but as you will see this has already been assigned to someone else. Please read our contributing guides to avoid extra work for the maintainers and also confusion within the community https://github.com/EddieHubCommunity/BioDrop/blob/main/CONTRIBUTING.md

**Comment by Nenepo** [comment]
Hello EddieHubCommunity/BioDrop,

Thank you for the opportunity, I have created a PR

**Comment by eddiejaoude** [comment]
thank you @Nenepo for the contribution 👍  I have left 2 small inline comments on your pull request

**Comment by shiivamtaneja** [comment]
Heyy @eddiejaoude can anyone contribute to issues or only people assigned can?

**Comment by eddiejaoude** [comment]
> Heyy @eddiejaoude can anyone contribute to issues or only people assigned can?
> Edit: i read the documentation, it's clear now. Although i have a question, how do people get assigned?

Comment on unassigned issues requesting it to be assigned to you. Please note, questions like this are great but not on other people's work that is unrelated, in future please as in Discord @shiivamtaneja

**Comment by Nenepo** [comment]
Good day Eddie,

I have made the necessary changes


thank you @Nenepo <https://github.com/Nenepo> for the contribution 👍 I

**Comment by shiivamtaneja** [comment]
@eddiejaoude sorry my bad, I'll keep this in mind going forward.

**Comment by Hamjaster** [comment]
Is this issue still open ?

**Comment by eddiejaoude** [comment]
@Hamjaster this issue is assigned to someone, please look at another issue
