### ISSUE TITLE
[BUG] Login and Signup navlink becomes active when we hover on darkmode icon or github link

### ISSUE THREAD

**Issue by nidhish-srivastava** [EddieHubCommunity/BioDrop#9046]
### Description

When we hover on dark/light mode icon or github icon in the navbar,we dont have any problem.But the moment we hover on Login or Signup, then after that,if we hover on dark/light mode icon or github icon,we get hover effect on Login button.

I want to work on this issue and be useful to this repository in some way.Please assign this issue

### Screenshots

![IMG20230913182904](https://github.com/EddieHubCommunity/BioDrop/assets/108972571/ef41cd3d-4201-4597-b154-68b4932e3b5d)
![IMG_20230913_182939](https://github.com/EddieHubCommunity/BioDrop/assets/108972571/118794c9-eeef-43f2-a20f-297a8c43154f)

### Do you want to work on this issue?

Yes

**Comment by SaraJaoude** [comment]
Thank you for raising but as we are going through a redesign process this will be dealt with then, so I will close this issue for now.
