### ISSUE TITLE
Remove nickytonline's data from the repo so BioDrop form can be used to edit profile

### ISSUE THREAD

**Issue by nickytonline** [EddieHubCommunity/BioDrop#9047]
### What would you like to share?

I'd like to be able to edit my profile from the BioDrop web site which is why I'm asking to have my data removed from the repository.

![image](https://github.com/EddieHubCommunity/BioDrop/assets/833231/c9bb6fac-647d-4c0b-b484-898d23b1392b)

### Do you want to work on this issue?

Yes

**Comment by SaraJaoude** [comment]
Thanks @nickytonline I have also merged [your PR](https://github.com/EddieHubCommunity/BioDrop/pull/9048) for this Issue so I will close this as completed.
