### ISSUE TITLE
 Font Awesome Issue <The 'Font Awesome' library has been updated to v6>

### ISSUE THREAD

**Issue by ianujvarshney** [EddieHubCommunity/BioDrop#9052]
### Description

![image](https://github.com/EddieHubCommunity/BioDrop/assets/57233251/505bc730-c575-4349-a563-039263b35307)

### Do you want to work on this issue?

None

**Comment by eddiejaoude** [comment]
I don't understand the bug?

**Comment by eddiejaoude** [comment]
I don't understand this issue, so I will close
