### ISSUE TITLE
[BUG] Tags Input Feature Not Functioning Properly on Mobile Keyboards

### ISSUE THREAD

**Issue by badrivlog** [EddieHubCommunity/BioDrop#9064]
### Description

In our project, we implemented a tags input feature, which allows users to add tags by pressing the comma key, works flawlessly on computer keyboards but encounters functionality issues on mobile keyboards. The comma key fails to trigger tag creation on mobile devices, impacting the user experience. This issue needs to be addressed to ensure consistent and user-friendly behavior across all platforms.

### Do you want to work on this issue?

Yes

**Comment by eddiejaoude** [comment]
Assigned to you @badrivlog
