### ISSUE TITLE
[BUG] Tooltips are not placed properly on Search tags.

### ISSUE THREAD

**Issue by mahfuzurrahman01** [EddieHubCommunity/BioDrop#9066]
### Description

In the search (https://www.biodrop.io/search) page the tooltips are not placed perfectly it covers the tags a bit. this needs to be updated. also on the small screen.
Please assign me this issue so that I can improve it.
Thanks.

### Screenshots

![14 09 2023_12 49 18_REC](https://github.com/EddieHubCommunity/BioDrop/assets/108393376/663e8ad1-5e18-4b3f-b8b0-e79a69c0244e)

### Do you want to work on this issue?

None

**Comment by SaraJaoude** [comment]
Thank you for raising.  These badges will be improved as part of the redesign process we are embarking on, so I will close this issue for now.
