### ISSUE TITLE
[FEATURE] Search clear/reset keyword button

### ISSUE THREAD

**Issue by nidhish-srivastava** [EddieHubCommunity/BioDrop#9072]
### Description

Currently after performing a search, to reset the search, the user must delete the text.

Having a reset or clear button would be a better user experience

### Do you want to work on this issue?

Yes

**Comment by eddiejaoude** [comment]
Thank you for the suggestion.

> THis feature is self explainatory,does need a description

I will rewrite the title and description as this does not give any context

**Comment by eddiejaoude** [comment]
@nidhish-srivastava you closed the issue as completed? but you also closed your pull request, so it is not completed I am confused
