### ISSUE TITLE
[Enhancement] <Navbar>

### ISSUE THREAD

**Issue by Nwakaego-Ego** [EddieHubCommunity/BioDrop#9080]
### Description

The navbar component lacks the "static" in its current implementation. I believe adding the "static" to the navbar can improve its behavior and provide a better user experience.

### Screenshots

![image](https://github.com/EddieHubCommunity/BioDrop/assets/81041326/0cbe9bcf-29cd-4cd2-a636-8eb160d95c7f)

### Do you want to work on this issue?

Yes

### Additional information

In the current implementation of the navbar, it doesn't have the "static" assigned.  Adding the "static" keyword will ensure that the navbar remains fixed at the top of the page, enhancing navigation and usability.

**Comment by SaraJaoude** [comment]
Thank you for raising, but as we will be going through a redesign process shortly this will likely be covered then, so I will close this issue for now

**Comment by Nwakaego-Ego** [comment]
Oh, that is great. Thank you for the feedback.
