### ISSUE TITLE
[FEATURE] Migrating the NextJs code to the recent one

### ISSUE THREAD

**Issue by nidhish-srivastava** [EddieHubCommunity/BioDrop#9088]
### Description

I know that this might seem a big migration but  From pages to app upgrade seems quite useful,which includes the getLayout upgrade and Head Component upgrade. If you think that its required,you can assign me this new feature to execute

### Do you want to work on this issue?

None

**Comment by SaraJaoude** [comment]
Thank you for raising.  If we do this now this will create many conflicts with the open PRs.  We will do this later as part of the redesign so I will close this issue.
