### ISSUE TITLE
[BUG] Restore scroll position after navigating via browser back/forward buttons 

### ISSUE THREAD

**Issue by nidhish-srivastava** [EddieHubCommunity/BioDrop#9089]
### Description

Whenever we are at the main home page of the website and we click on the link for ex,we clicked on Any link available in the footer,so when we navigate back,we are at the home page.If the user was interested in some more links in the footer,his ux is hampered since he has to scroll down at the very bottom.

So please assign this issue to me,i can confidently add the restore scroll position after navigating via browser back/forward buttons 
and be of some value to this repository

### Do you want to work on this issue?

Yes

**Comment by SaraJaoude** [comment]
Thank you for raising.  The footer is on every page so the user would not need to click on the back button, but can navigate to the footer and click on the other link they wish to visit. I will close this issue.
