### ISSUE TITLE
[Test] < Testing the search persistence feature>

### ISSUE THREAD

**Issue by jackli921** [EddieHubCommunity/BioDrop#9090]
### What would you like to share?

How about adding a test to test the search term persistance feature that was added recently?
Feature: https://github.com/EddieHubCommunity/BioDrop/issues/8109

### Do you want to work on this issue?

No

### Additional information

@dmitrykulakovfrontend would like to work on this issue if it opens.

**Comment by SaraJaoude** [comment]
Thank you for raising. 

@dmitrykulakovfrontend please comment to confirm if you would like this assigned to you.

**Comment by dmitrykulakovfrontend** [comment]
Yes, I would like to work on that issue

**Comment by SaraJaoude** [comment]
> Yes, I would like to work on that issue

Thank you @dmitrykulakovfrontend I have assigned this to you.
