### ISSUE TITLE
[BUG] Tags Input Field Becomes Undefined When Pressing BACKSPACE with No Tags

### ISSUE THREAD

**Issue by badrivlog** [EddieHubCommunity/BioDrop#9094]
### Description

When using the **TagsInput** component, there is a bug where the input field becomes undefined when there are no tags present, and the user presses the **BACKSPACE** key.

### Screenshots

![Screenshot (41)](https://github.com/EddieHubCommunity/BioDrop/assets/73095526/395c98e2-509e-4ccf-a973-86ab10536305)

### Do you want to work on this issue?

Yes

**Comment by eddiejaoude** [comment]
Thank you for noticing! Assigned to you

**Comment by mkayrajput** [comment]
Want to resolve this please assign this issue to me
