### ISSUE TITLE
[FEATURE] Using Chips in the "add Tags" section

### ISSUE THREAD

**Issue by schmelto** [EddieHubCommunity/BioDrop#9103]
### Description

Currently the add Tags section looks like this:

![image](https://github.com/EddieHubCommunity/BioDrop/assets/30869493/84e1326a-d1cb-4df0-91b5-37aa45094ad3)

It would be more convenient to add them via enter instead of having to enter a comma. At least for me I have pressed multiple times enter before using the comma.

An example on how this could work can be seen here: https://tailwind-elements.com/docs/standard/components/chips/
![image](https://github.com/EddieHubCommunity/BioDrop/assets/30869493/8fb7d0b4-eed2-4287-863e-82b445e8f3c7)

Note: it might be worth considering having both options (i.e. `enter` and `comma`).

**Comment by btme0011** [comment]
Can i work on this issue?

**Comment by TanyaLagodich** [comment]
I would like to work on this issue, if possible

**Comment by SaraJaoude** [comment]
> Can i work on this issue?

@btme0011 I have assigned this to you.

**Comment by MauryanKansara** [comment]
> > Can i work on this issue?
> 
> @btme0011 I have assigned this to you.

hey @SaraJaoude if possible can you assign this issue to me? The assigned contributor does not seem to be active.

**Comment by SaraJaoude** [comment]
> hey SaraJaoude if possible can you assign this issue to me? The assigned contributor does not seem to be active.

@MauryanKansara please familiarise yourself with the project's [Contributing Guide](https://github.com/EddieHubCommunity/BioDrop/blob/main/CONTRIBUTING.md):

- We only assign one issue per person and I can see you already have an issue assigned to you.
- We give our contributors two weeks to raise the PR for the issue they have been assigned.  As you can see from the history this issue was only assigned last week, so please do not chase as this puts added pressure on the contributor and creates unnecessary notifications. 

In future please also avoid tagging a specific maintainer - all maintainers receive notifications on the project and keep an eye on the issues which need to be assigned/unassigned.

**Comment by ThomasCode92** [comment]
I was updating my profile and was also trying to add a tag by pressing enter.
Glad to find that there is already an issue for this.

**Comment by MauryanKansara** [comment]
Hey @SaraJaoude I've solved the issue I was assigned for and my PR is also merged, can you assign this issue to me if possible?

**Comment by SaraJaoude** [comment]
> > Can i work on this issue?
> 
> btme0011 I have assigned this to you.

@btme0011 as two weeks have passed and we cannot see that you have opened a Pull request fr this Issue, following our Contributing Guide, I am unassigning this from you.

**Comment by SaraJaoude** [comment]
> Hey SaraJaoude I've solved the issue I was assigned for and my PR is also merged, can you assign this issue to me if possible?

@MauryanKansara I asked you previously not to tag a specific maintainer - can you please respect our project's guidelines.  As the first assignee has not made a Pull Request I have assigned this to you given the two weeks has elapsed.

**Comment by eddiejaoude** [comment]
Discussion from Discord

> as mentioned in the issue, we need to use a new library called "Tailwind Elements" for an input element called "Tags"

no external library required, i don't event think any tailwind is needed, the task is to "having both options include the tag, using enter and comma"

**Comment by MauryanKansara** [comment]
hey I have made the PR can any maintainer please review it and merge it?

**Comment by eddiejaoude** [comment]
@MauryanKansara I am reviewing

**Comment by mozi47** [comment]
If this issue is still open, I would be glad to assign me.....

**Comment by SaraJaoude** [comment]
> If this issue is still open, I would be glad to assign me.....

@mozi47 to avoid extra noise and notifications for maintainers please can you check the comment history and also the Assignees box at the top of the page - this issue is being worked by someone else still.
