### ISSUE TITLE
[FEATURE] Navbar should be sticky at least for mobile devices

### ISSUE THREAD

**Issue by raunak-mishraa** [EddieHubCommunity/BioDrop#9111]
### Description

The current navbar is not sticky on mobile devices, which makes it difficult to navigate the app. When a user scrolls down the page, the navbar disappears, and they have to scroll back to the top of the page to access it again. 

### Do you want to work on this issue?

No

**Comment by ChinmayMhatre** [comment]
Hi Raunak, I believe the core pages in BioDrop don't have much scroll such as the accounts pages and the actual user profile. I also don't thing switching between the pages quickly is essential for BioDrop.

Do let me know if you faced any difficulties why you think a sticky navbar would be an option to consider. If anyone else also faced these difficulties can mention them here.

**Comment by raunak-mishraa** [comment]
Actually there is a problem for mobile devices when you scroll the screen and come too far down and you want to go up, you have to scroll further, so it makes problem, at least if there would be something like top button by clicking which we can go to the top, instead navbar this can be done.

**Comment by adisuyash** [comment]
I think you should include some screenshots which will clear your issue thoroughly

**Comment by ChinmayMhatre** [comment]
This issue will be addressed as part of the design you can check the discussion on #9080.

Thank you for raising the issue. I'll be closing the issue.
