### ISSUE TITLE
[FEATURE] On Mobile hide:  Stats, Add Testimonial button and Tags

### ISSUE THREAD

**Issue by SaraJaoude** [EddieHubCommunity/BioDrop#9114]
### Description

On the Mobile there is less real estate and links are two pages down. 

By hiding `stats`, `add testimonials` button and `tags` this would be improved.

### Screenshots

<img width="554" alt="Screenshot 2023-09-21 at 09 40 21" src="https://github.com/EddieHubCommunity/BioDrop/assets/82668196/b6512011-81d3-44a3-b51f-3a86c5e59e6d">

### Do you want to work on this issue?

No

**Comment by AbhishekBhure** [comment]
hi Sara, I am interested in this issue would you please share a screenshot so it will be easier to understand what is the issue?

**Comment by Remi-dee** [comment]
Hello Sara, i would love to work on this issue, with the provision of a screenshot

**Comment by SaraJaoude** [comment]
> hi Sara, I am interested in this issue would you please share a screenshot so it will be easier to understand what is the issue?

@AbhishekBhure please see amended issue description - I have added a screenshot of what it will look like.  I have assigned this to you.

**Comment by SaraJaoude** [comment]
> Hello Sara, i would love to work on this issue, with the provision of a screenshot

@Remi-dee in future please avoid asking the same question someone else has just asked above - this adds extra noise and unnecessary notifications.

**Comment by AbhishekBhure** [comment]
Hello Sara!!, Thank you for assigning this issue to me. However, I am not able to find the amended description where you have added the screenshot of what it should look like. Would you please share a link or suggest me?

**Comment by SaraJaoude** [comment]
> Hello Sara!!, Thank you for assigning this issue to me. However, I am not able to find the amended description where you have added the screenshot of what it should look like. Would you please share a link or suggest me?

@AbhishekBhure  please check again

**Comment by AbhishekBhure** [comment]
Yes, Now I can see the screenshot. So I need to add the Testimonial and Tags Button within the dropdown?

**Comment by SaraJaoude** [comment]
> Okay, So we are talking about these tags, and the Add Testimonial button I highlighted in the screenshot should be hidden when in Mobile View?
> 
As well as the `stats` as mentioned in the Issue description.  Please look at the code as you will see the changes you need to make.



![IMG_8388](https://github.com/EddieHubCommunity/BioDrop/assets/82668196/b6171c92-08f1-4cfa-93aa-e48eab674c78)

**Comment by AbhishekBhure** [comment]
Okay, Thank you for the clarification. I need to hide these three things (stats, add Testimonial button and tags which are highlighted in the screenshot) on mobile view, earlier I was confused because the stats were not showing on my profile.

**Comment by SaraJaoude** [comment]
> Okay, Thank you for the clarification. I need to hide these three things (stats, add Testimonial button and tags which are highlighted in the screenshot) on mobile view, earlier I was confused because the stats were not showing on my profile.

Yes - this is correct.
