### ISSUE TITLE
[FEATURE] QR Code as Mobile Wallpaper

### ISSUE THREAD

**Issue by SaraJaoude** [EddieHubCommunity/BioDrop#9115]
### Description

The ability to export the QR code as wallpaper for your mobile so that this is easier to share when your mobile screen is locked and particularly if you do not have internet (similar to a digital business card). 

Rather than just have the QR code, it would be good if this could include the BioDrop logo below it.

### Do you want to work on this issue?

No

### Additional information

Please share your thoughts on how to implement this.

**Comment by Vijaykv5** [comment]
Hey @SaraJaoude I would like to work on this issue. May you can add some more details and a screenshot also would help

**Comment by Deveesh-Shetty** [comment]
> The ability to export the QR code as wallpaper for your mobile so that this is easier to share, particularly if you do not have internet.

Do you mean downloading the QR code as a PNG file?

> Rather than just have the QR code, it would be good if this could include the BioDrop logo below it.

We can have the BioDrop logo in the middle of the QR code, I found one [API](https://www.qr-code-generator.com/qr-code-api/) that does it (I am not sure whether it is paid or free), there may be alternatives as well.

Also, I generated a few for example from the same API website
<details>
<summary> QR Code Example 1</summary>
<img src="https://github.com/EddieHubCommunity/BioDrop/assets/89470104/df30b73e-136a-493a-a2db-2dc6870fd83a" alt="QR Code Example 1" width="300" height="300"/>
</details>
<details>
<summary> QR Code Example 2</summary>
<img src="https://github.com/EddieHubCommunity/BioDrop/assets/89470104/d5e22504-e465-40b0-85d2-0c52d92427e5" alt="QR Code Example 2"  width="300" height="300" />
</details>

**Comment by bikrantjajware** [comment]
This can be linked to the other issue[8640] for styled QR code. Downloading QR is already an available feature, so with 8640 fixed we can easily export a styled QR code

**Comment by SaraJaoude** [comment]
@Deveesh-Shetty thank you for your comments:

 - Downloading QR code as a PNG file already exists as @bikrantjajware mentioned
 - BioDrop logo - this is a separate issue #8640 (these are both independent issues)
 - We would rather use a library for this and not a third party API - this can be discussed in #8640 

For this issue we want to make it convenient for people to add it to the wallpaper on their mobile when their screen is locked.

**Comment by akash19coder** [comment]
> For this issue we want to make it convenient for people to add it to the wallpaper on their mobile when their screen is locked.
Are we talking about implementing in-app feature that will allow users to directly set their Biodrop QR code as a lock screen wallpaper on their smartphone? 

Also I would like to work on implementing this feature😀. Could you please assign it to me.

**Comment by eddiejaoude** [comment]
@akash19coder this feature has a lot of unknowns (8 points), please can you explain how you would approach it and your solution?

**Comment by eddiejaoude** [comment]
Yes we need to have a QR code that fits on the screen correctly and with other more useful information.

My question still remains about how you plan to achieve this issue...

> @akash19coder this feature has a lot of unknowns (8 points), please can you explain how you would approach it and your solution?

**Comment by akash19coder** [comment]
> My question still remains about how you plan to achieve this issue...

Here is how I have implemented it


https://github.com/EddieHubCommunity/BioDrop/assets/72060440/620b5c59-f81f-4493-8187-9f19de2066b2

**Comment by akash19coder** [comment]
The image on the lock screen appear the following:
<img src="https://github.com/EddieHubCommunity/BioDrop/assets/72060440/4d647d7e-e1aa-4056-8434-8e2e45558b48" width="360" height="640">

**Comment by eddiejaoude** [comment]
Thank you, it looks good 👍 , I would be interested to see the code - we are approaching the file limit for Vercel, so not sure how big the library is, we can take a closer look when the PR is created. I will assign the issue to you

**Comment by eddiejaoude** [comment]
Pull Request merged
