### ISSUE TITLE
[FEATURE] Improve manage testimonials page design

### ISSUE THREAD

**Issue by allexgut** [EddieHubCommunity/BioDrop#9116]
### Description

The manage testimonials page in the current user's account looks off compared to the public facing testimonials page. We can reuse the design of the public facing one with a bit of adjustment to fit in the manage testimonials page.

### Screenshots

Manage testimonials:
![](https://user-images.githubusercontent.com/7535401/269112481-587e1ee3-bd9f-4f99-b678-7cde078bfc0b.png)
Public facing testimonials:
<img width="1361" alt="image" src="https://github.com/EddieHubCommunity/BioDrop/assets/7535401/8e4848f3-a417-4a4a-85d5-1adfcf887bb9">

### Do you want to work on this issue?

Yes

**Comment by SaraJaoude** [comment]
Thank you for raising but as we will be going through the redesign process soon, this will be covered then - so I will close this issue for now.
