### ISSUE TITLE
Thank you for raising.  The tags at the top of search are generated from users' profiles.

### ISSUE THREAD

**Issue by nidhish-srivastava** [EddieHubCommunity/BioDrop#9117]
Thank you for raising.  The tags at the top of search are generated from users' profiles.  

If you search for both Web3 and Blockchain you will see that these are already existing tags. 

<img width="1314" alt="Screenshot 2023-09-20 at 13 09 26" src="https://github.com/EddieHubCommunity/BioDrop/assets/82668196/7421fa7c-f488-446d-8443-7e4d36a5f6f2">

So I will close this issue.

_Originally posted by @SaraJaoude in https://github.com/EddieHubCommunity/BioDrop/issues/9073#issuecomment-1727513934_

I am saying that we should include the Web3 or blockchain tag in this list rather than displaying 2 tags of same use(react and reactjs,replace either one of them with web3) 
            
![Screenshot (394)](https://user-images.githubusercontent.com/108972571/269335578-f9f617c6-3a80-4f35-ba34-48777fbf30d9.png)

**Comment by eddiejaoude** [comment]
> I am saying that we should include the Web3 or blockchain tag in this list rather than displaying 2 tags of same use(react and reactjs,replace either one of them with web3)

As @SaraJaoude explained in #9073 these tags are auto generated from user's profiles, we do not manually **add** them - as more people use those tags and they become popular they will automatically appear

Not sure why you created a new issue @nidhish-srivastava you can comment on #9073

**Comment by nidhish-srivastava** [comment]
Srry,i am a noob in open source

**Comment by eddiejaoude** [comment]
No problem! Welcome 👍
