### ISSUE TITLE
[BUG] Add more space between the buttons and the event card, when adding and editing the event(Mobile view). 

### ISSUE THREAD

**Issue by AbhishekBhure** [EddieHubCommunity/BioDrop#9119]
### Description

In mobile view when I am trying to add and edit an event there's no proper spacing between the buttons and the event card.

### Screenshots

when adding an event, there's no space between the save button and the event card:

![add-event](https://github.com/EddieHubCommunity/BioDrop/assets/87894780/810c58a2-d918-40f2-adb6-2d7daa50ee2a)

when editing the card, there's no space between the buttons(save / delete) and the event card :

![edit-event](https://github.com/EddieHubCommunity/BioDrop/assets/87894780/592ab61b-9704-480b-a3fc-d5dd7d07dc55)

 

### Do you want to work on this issue?

Yes

**Comment by SaraJaoude** [comment]
Thank you for raising @AbhishekBhure - however at this time I cannot assign this to you.  Currently you have already been assigned another issue and we only assign one issue per contributor.

**Comment by ezhil56x** [comment]
I'm interested to work on this. Can you assign this issue to me

**Comment by AbhishekBhure** [comment]
Thank you for the update. I understand the policy of assigning only one issue per contributor. Since I'm waiting for the pull request to be reviewed and merged, I'll prioritize that. Once it's merged, I'll be available to work on the issue I raised.

**Comment by Nwakaego-Ego** [comment]
Hi, If it is still available to be assigned,  please assign it to me

**Comment by SaraJaoude** [comment]
> Thank you for the update. I understand the policy of assigning only one issue per contributor. Since I'm waiting for the pull request to be reviewed and merged, I'll prioritize that. Once it's merged, I'll be available to work on the issue I raised.

Thank you @AbhishekBhure but other community members have expressed an interest to work on this issue so this will be assigned to someone else. Your other PR will be look at by the maintainers once they can, as we have several still to review.

**Comment by SaraJaoude** [comment]
> I'm interested to work on this. Can you assign this issue to me

@ezhil56x I have assigned this to you.

**Comment by AbhishekBhure** [comment]
Thank you for the update. I understand that others are interested in the issue as well. I'll continue to wait for my pull request to be reviewed by the maintainers.

**Comment by ezhil56x** [comment]
I have fixed this issue and have created a Pull Request
