### ISSUE TITLE
New Testimonial for Ali Mora

### ISSUE THREAD

**Issue by varchodi** [EddieHubCommunity/BioDrop#9126]
### Name

AliMora83

### Title

The Coding Genius and Team Player We all Need

### Description

Working with @AliMora83  on our Chingu Voyages project was fantastic. He's a coding genius, making tough problems look easy. Plus, he's great at explaining things and working together. If you need a talented developer who's also a great teammate, @AliMora83 is your guy!

**Comment by AliMora83** [comment]
Hey there 🥳
There is no button to toggle Testimonies:
<img width="1023" alt="Screenshot 2023-09-24 at 11 48 42" src="https://github.com/EddieHubCommunity/BioDrop/assets/56822813/79f5c5f3-8860-453a-ae8e-7a02d38603d8">

My page:
<img width="1673" alt="Screenshot 2023-09-24 at 11 48 29" src="https://github.com/EddieHubCommunity/BioDrop/assets/56822813/33a4a7db-c3d5-4a2e-8540-cf11ae979248">


Please help me add a testimony 🙏🏼

**Comment by AliMora83** [comment]
Sorry to ask this way @eddiejaoude, @eddiejaoude2  🤗
Thank you in advance.

**Comment by eddiejaoude** [comment]
Thanks for asking. Sorry for the confusion, we have a bug we are working on it at the moment to load new testimonials, they will appear soon
