### ISSUE TITLE
[IMPROVEMENTS] accessibility on tags input

### ISSUE THREAD

**Issue by badrivlog** [EddieHubCommunity/BioDrop#9132]
### What would you like to share?

In our current `components/tag/TagsInput` component code, we have an element where we visually hide content. However, instead of using the appropriate `sr-only` class provided by Tailwind CSS, we are currently using custom CSS classes.

https://github.com/EddieHubCommunity/BioDrop/blob/c6ea528a9c35ef6bde24ed8583feda49046cdd81/components/tag/TagsInput.js#L49 
The purpose of this issue is to enhance accessibility by replacing the existing custom CSS classes with the `sr-only` class, which is specifically designed for hiding content from sighted users while ensuring it remains accessible to screen readers.

### Do you want to work on this issue?

Yes

**Comment by ChinmayMhatre** [comment]
I had a question while going through the code for the component. 
I agree if we are to show the remove tag span we should use `sr-only` class from tailwind.

My question was can we add some sort of accessibility property to the icon itself or the button instead of adding a separate span?

<img width="858" alt="image" src="https://github.com/EddieHubCommunity/BioDrop/assets/51131670/eff689d8-f889-446a-844f-b2cc33ab6589">

**Comment by badrivlog** [comment]
> I had a question while going through the code for the component. 
> I agree if we are to show the remove tag span we should use `sr-only` class from tailwind.
> 
> My question was can we add some sort of accessibility property to the icon itself or the button instead of adding a separate span?
> 

Yes, we can make it accessible for screen reader by adding `area-label` property to the icon itself.

**Comment by EmmaDawsonDev** [comment]
An aria label on the SVG itself should be enough. But do check with a screen reader that the title and the aria label don't both get read out. The title attribute is a bit hit and miss with screen readers.

**Comment by badrivlog** [comment]
> An aria label on the SVG itself should be enough. But do check with a screen reader that the title and the aria label don't both get read out. The title attribute is a bit hit and miss with screen readers.

Thank you for your feedback and guidance! I really appreciate your help in addressing this issue. I'll follow your advice and work on the necessary changes. If I have any questions or need further clarification during the process, I'll make sure to reach out. 

Looking forward to contributing to the project.

**Comment by Rushi0508** [comment]
Can you assign me the issue

**Comment by SaraJaoude** [comment]
> Can you assign me the issue

@Rushi0508 this issue has been assigned to someone else.  In future please check the Assignees box at the top of the page first as you can find that information there.
