### ISSUE TITLE
[FEATURE] Increase execution time for loading json files

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/BioDrop#9135]
### Description

> The default timeout will be reduced to 15 seconds. Beginning Oct 1, a function will be stopped if it executes for more than 15 seconds. This change helps prevent uncontrolled function usage due to abuse and reduces the risk of unexpectedly high bills.

In config file `vercel.json` add
```js
{
  "functions": {
    "api/system/reload.js": {
      "memory": 3008,
      "maxDuration": 60
    }
  }
}
```

https://vercel.com/docs/functions/serverless-functions/runtimes?mkt_tok=MDAxLUxSRy0xOTQAAAGOV4bcIFqHBzkDjbbbS_WZ47UCs0j2Za5MqQ0XC0L23NJyXVoLB4Rcp5wHsYRD_Rkzt8DuMwK8FsLedhwp40AThPgwKpv_mLiCUZS7vZlJ#maxduration

### Do you want to work on this issue?

None

### Additional information

**note**: must be completed and merged by the 1st of October

**Comment by rizahmeds** [comment]
Please assign this issue to me.

**Comment by SaraJaoude** [comment]
> Please assign this issue to me.

@rizahmeds I have assigned this to you

**Comment by ahuja-sanchitt** [comment]
If this is still available, can you assign this issue to me?

**Comment by SaraJaoude** [comment]
> If this is still available, can you assign this issue to me?

@ahuja-sanchitt this issue has been assigned to someone else - in future please check the assignees box at the top of the page.
