### ISSUE TITLE
[BUG] Profile icon animations ignore prefers-reduced-motion

### ISSUE THREAD

**Issue by dan-mba** [EddieHubCommunity/BioDrop#9139]
### Description

`prefers-reduced-motion` is a CSS feature that allows developers to know when a user does not wish to see non essential movement. 

Not respecting these wishes is an accessibility issue. There are conditions that make these animations harmful to users (think the flashing lights warnings before certain TV shows).

Tailwind requires special notation to handle [prefers-reduced-motion](https://tailwindcss.com/docs/animation#prefers-reduced-motion)

### Do you want to work on this issue?

None

**Comment by amandamartin-dev** [comment]
Great idea! Here is one example of animation on the site for context https://www.biodrop.io/pricing

**Comment by Nwakaego-Ego** [comment]
Hi, Please assign this issue to me

**Comment by amandamartin-dev** [comment]
> Hi, Please assign this issue to me

Hello! You are now assigned to this issue. Thank you for contributing

**Comment by bibaswan7** [comment]
Hi, can I also work on this issue? In fact, I have already added the necessary tailwind classes

**Comment by amandamartin-dev** [comment]
> Hi, can I also work on this issue? In fact, I have already added the necessary tailwind classes on my code

This issue was already assigned. To be able to know if an issue is open you can check the assignees and the conversation in the issue to help you be able to know.
