### ISSUE TITLE
[FEATURE] Improvement - standard placement of price on events

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/BioDrop#9149]
### Description

On the events page, currently the location of the price is dependent upon the length of text due to the placement inside the div.  This creates a difficult to visually navigate situation at the price is not always in the same location on each event.

This issue is to create a standard location for the event price in the event cards so that it is no longer dependent on the description length and is easier to visually navigate.

See screenshot for an example of the issue.

### Screenshots

![events-price](https://github.com/EddieHubCommunity/BioDrop/assets/97615019/0dd86c0e-c708-4eff-9651-5658b7142671)

### Do you want to work on this issue?

No

**Comment by AbhijeetBiswal** [comment]
can you assign me this issue

**Comment by SaraJaoude** [comment]
> can you assign me this issue

@AbhijeetBiswal I have assigned this to you.
