### ISSUE TITLE
[DOCS]: Adding content to Step 8 in Open Source Roadmap

### ISSUE THREAD

**Issue by CBID2** [EddieHubCommunity/BioDrop#9152]
## Problem
Reviewing the open source roadmap, I noticed that Step 8 is empty.

## Possible Suggestion
I'm thinking we can talk about different ways to become a maintainer. Something like this:

## How to become a maintainer
- How do you become a maintainer on someone else's project - tips to achieve this
- Tips on how to become a maintainer on your own project

## Benefits
Adding these little sections and examples can help contributors gain ideas on how to interact with others and how to maintain a project. 

### Screenshots

<img width="755" alt="Screenshot of step 8" src="https://github.com/EddieHubCommunity/BioDrop/assets/105683440/504b47be-abd8-4ded-a810-a6f9f6d3d5aa">

### Do you want to work on this issue?

Yes

**Comment by SaraJaoude** [comment]
@CBID2 there appears to be some confusion as Step 8 is still referred to as "coming soon" and the actual page is empty. There is no mention of moving on to other projects.  Could you please clarify?

**Comment by CBID2** [comment]
> @CBID2 there appears to be some confusion as Step 8 is still referred to as "coming soon" and the actual page is empty. There is no mention of moving on to other projects.  Could you please clarify? 

Hi @SaraJaoude! I just now realized that you can click on the steps 🤦🏾‍♀️ I made a few changes to my suggestion

**Comment by CBID2** [comment]
If this issue gets accepted, can I count it as a pull request for Hacktoberfest?

**Comment by Dun-sin** [comment]
> If this issue gets accepted, can I count it as a pull request for Hacktoberfest? 

It will

**Comment by CBID2** [comment]
> > If this issue gets accepted, can I count it as a pull request for Hacktoberfest? 
> 
> It will 

Thanks @Dun-sin. Are you a maintainer on BioDrop?

**Comment by Dun-sin** [comment]
> > > If this issue gets accepted, can I count it as a pull request for Hacktoberfest? 
> > 
> > It will 
> 
> Thanks @Dun-sin. Are you a maintainer on BioDrop? 

I'm not

**Comment by CBID2** [comment]
> > > > If this issue gets accepted, can I count it as a pull request for Hacktoberfest? 
> > > 
> > > It will 
> > 
> > Thanks @Dun-sin. Are you a maintainer on BioDrop? 
> 
> I'm not

Lol I thought you were 😆

**Comment by Dun-sin** [comment]
> > > > > If this issue gets accepted, can I count it as a pull request for Hacktoberfest? 
> > > > 
> > > > It will 
> > > 
> > > Thanks @Dun-sin. Are you a maintainer on BioDrop? 
> > 
> > I'm not
> 
> Lol I thought you were 😆

I wish😆

**Comment by CBID2** [comment]
> @CBID2 thank you for amending the description since my initial comment.  I will be adding the `status: ready for dev` label and assigning this to you now, however the issue needs some more thought and other points taken into consideration when raising a PR:
> 
> 
> 
> **Code Reviews:**
> 
> 
> 
> It would be more appropriate to add this to [Step 5 of the Roadmap "How to Contribute"](https://www.biodrop.io/docs/open-source-roadmap/what-to-contribute). 
> 
> 
> 
> Please raise a new issue for this section. It should not be part of this PR.
> 
> 
> 
> Please note that the purpose of this roadmap is to provide a high level view (as you can see the existing examples are short and concise), therefore it would be best not to add the links you have suggested so as to keep this consistent with the remainder of the roadmap (i.e. there are no links to examples anywhere else). 
> 
> 
> 
> **How to become a maintainer:**
> 
> 
> 
> I do agree this should be added in this Step 8. When raising the PR can you add more context though please, for example:
> 
> 
> 
> - how do you become a maintainer on someone else's project - tips to achieve this
> 
> - tips on how to become a maintainer on your own project
> 
> 
> 
> Please also note my comment regarding links applies here.
> 
> 
> 
> **As part of the PR:**
> 
> 
> 
> Please can you also update the `Step 8 title` on the main roadmap page as follows:
> 
> 
> 
> <img width="828" alt="Screenshot 2023-10-04 at 10 09 51" src="https://github.com/EddieHubCommunity/BioDrop/assets/82668196/90da6fc4-c471-4c11-babd-466c26c64a72">
> 
> 
> 
> i. change `coming soon` to `draft` (the reason behind this is that we will need more than one item in there
> 
> ii. remove `review other people's changes` (see my point regarding Code Reviews above)
> 
> 
> 
> Let me know if you have any questions.  It would be helpful if you could please also amend the issue description to reflect this comment.

Hi @SaraJaoude. I made the necessary changes to this issue, and your suggestion is in issue #9334.

**Comment by SaraJaoude** [comment]
As mentioned in the [PR](https://github.com/EddieHubCommunity/BioDrop/pull/9353), changing `coming soon` to `draft` was not carried out.  This can be done as part of a new PR.
