### ISSUE TITLE
[DOCS] incorrect date format in "Milestones with JSON" code snippet

### ISSUE THREAD

**Issue by bL34cHig0** [EddieHubCommunity/BioDrop#9183]
### Description

I noticed the JSON snippet for the documentation on "Milestones with JSON" is somewhat ambiguous regarding the date format. It took me a while to realize that the correct date format is `Day/Month/Year` rather than `Month and Year`.

### Screenshots

![image](https://github.com/EddieHubCommunity/BioDrop/assets/133022207/66661d2d-3b12-4a31-9f1c-a18f3ee8d51b)

Found the correct format on Eddie's biodrop profile:
![image](https://github.com/EddieHubCommunity/BioDrop/assets/133022207/1b2b870a-c65b-49c8-80fa-252aa8c27054)

### Do you want to work on this issue?

Yes

### Additional information

I'm not well-versed in Node.js, but I'd like to attempt to resolve this issue. I'd also appreciate it if I could be paired with someone proficient in Nodejs to help solve it. Thanks

**Comment by SaraJaoude** [comment]
Thank you for raising.  What is the proposed changes that you are suggesting?

**Comment by bL34cHig0** [comment]
Thank you for responding. My proposed change is to use the correct date format `Month/Day/Year` in the json snippet.

**Comment by SaraJaoude** [comment]
@bL34cHig0 thanks - I have assigned this to you

**Comment by sital002** [comment]
Eddie is using form to make the profile here is the PR for date format https://github.com/EddieHubCommunity/BioDrop/pull/8973 now we can customize our milestone date format using forms.
The format options are:
 ```dd/mm/yyyy```
```month/year```
```year only```

**Comment by bL34cHig0** [comment]
Thanks for pointing that out @sital002. However, this fix is for the `Milestones with JSON` documentation.
