### ISSUE TITLE
[CI] Squash Merge PRs

### ISSUE THREAD

**Issue by xkrishguptaa** [EddieHubCommunity/BioDrop#9192]
### Description

We squash merge all of the prs in the repo apart from the release prs, I think we should squash then to as they are starting to through errors

### Screenshots

![](https://cdn.discordapp.com/attachments/883469466393010186/1156861654852710442/Screenshot_2023-09-28_at_08.54.45.png?ex=651682df&is=6515315f&hm=dd1e5d7d43a0b3cbe4348e53fa4095a974dba5fddf009ebdf7b1a7006db87582&)

### Do you want to work on this issue?

Yes

**Comment by eddiejaoude** [comment]
Thank you, assigned
