### ISSUE TITLE
[FEATURE] Add Multi-Language Support

### ISSUE THREAD

**Issue by Olaleye-Blessing** [EddieHubCommunity/BioDrop#9198]
### Description

Biodrop currently supports English. I think it would be nice to support multiple languages. This would allow users to interact with Biodrop in their preferred language, making it more accessible and user-friendly for non-English speakers.

### Do you want to work on this issue?

Yes

**Comment by SaraJaoude** [comment]
Thank you for the suggestion.  Yes it would be good to support other languages.  However this is not on our roadmap for now so I will close.
