### ISSUE TITLE
[FEATURE] Improve UX

### ISSUE THREAD

**Issue by Olaleye-Blessing** [EddieHubCommunity/BioDrop#9199]
### Description

User experience could be improved by making the circled part in the screenshot a clickable link. At the moment, users have to edit the search bar or copy and paste that link. Users won't go through this 'stress' if it's clickable.

### Screenshots

<img width="1491" alt="Screenshot 2023-09-28 at 19 39 16" src="https://github.com/EddieHubCommunity/BioDrop/assets/70102539/97f4c3bf-0303-4005-85f2-b2d5d11e7721">

### Do you want to work on this issue?

Yes

**Comment by SaraJaoude** [comment]
Thank you for raising.  As we are going through the redesign process this is likely to be addressed then, so I will close this issue for now.
