### ISSUE TITLE
[BUG] remove optional zod schema from name and bio

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/BioDrop#9200]
### Description

These 2 zod schema rules should not be optional (remove `.optional()`)

https://github.com/EddieHubCommunity/BioDrop/blob/e9cfd99b2737f3f29e98f3454d6d5d6e507830bd/config/schemas/jsonProfileSchemas.js#L27-L28

```diff
-   name: z.string().optional(),
-   bio: z.string().optional(),
+   name: z.string(),
+   bio: z.string(), 
```

### Do you want to work on this issue?

None

**Comment by HpatricioH** [comment]
Could you please kindly assign this to me?

**Comment by AbhijeetBiswal** [comment]
can you please assign me this issue

**Comment by shiivamtaneja** [comment]
Hey if no-one is assigned, can i work on this?

**Comment by SaraJaoude** [comment]
> Could you please kindly assign this to me?

@HpatricioH I have assigned this to you.
