### ISSUE TITLE
[BUG] Mobile Keyboard Fluctuation During Search

### ISSUE THREAD

**Issue by badrivlog** [EddieHubCommunity/BioDrop#9208]
### Description

In search page when performing a search on my mobile device, the on-screen keyboard initially appears, then unexpectedly disappears and reappears during the search process, causing an inconsistent user experience and making it challenging to input text efficiently.

**Environment**
OS: Android
Browser: Google Chrome

### Do you want to work on this issue?

Yes

**Comment by amandamartin-dev** [comment]
Hello! Unable to recreate in my environment. Will unlock for discussion so others can report:

Pixel6a
Android 13
Chrome

See screen recording below for search on mobile working as expected
https://github.com/EddieHubCommunity/BioDrop/assets/97615019/24540485-f648-4c21-a6d7-90ebf939c68d

**Comment by badrivlog** [comment]
> Hello! Unable to recreate in my environment. Will unlock for discussion so others can report:
> 
> Pixel6a
> Android 13
> Chrome
> 
> See screen recording below for search on mobile working as expected
> https://github.com/EddieHubCommunity/BioDrop/assets/97615019/24540485-f648-4c21-a6d7-90ebf939c68d
> 
> 

It's happening when you type slowly.

**Comment by amandamartin-dev** [comment]
haha! I am a fast typer, I will leave open for triage and discussion further

**Comment by badrivlog** [comment]
I've identified the code that's causing the issue with the mobile keyboard behavior during a search. It seems to be related to this code snippet that we're running in a useEffect hook
![New ss](https://github.com/EddieHubCommunity/BioDrop/assets/73095526/8266cb97-fe24-44d2-8687-07ec99e4c512)

In there we're replace the search url by `router.replace()` but problem is here when this code run page gets reloaded. I think to address this issue we should update search url without reloading the page. Thanks

**Comment by amandamartin-dev** [comment]
Great spot! That makes sense why it would cause the behavior.

**Comment by amandamartin-dev** [comment]
@badrivlog thank you for the details providing the problem and proposed solution. I have assigned you.

**Comment by eddiejaoude** [comment]
> In there we're replace the search url by router.replace() but problem is here when this code run page gets reloaded. I think to address this issue we should update search url without reloading the page.

This was added so people can use the back button and also share a  deep link to their search results. We want to keep this url history

**Comment by amandamartin-dev** [comment]
> This was added so people can use the back button and also share a deep link to their search results. We want to keep this url history

Perhaps there is a better approach that doesn't reload the page on each keystroke? Apologies for not realizing that was the implementation of the search persistence when I unlocked this.

**Comment by badrivlog** [comment]
Thanks for providing the details. After reviewing the code and considering the search persistent, I'm thinking of using `window.replaceState` instead of the `router.replace` method. This should help prevent page reloads when updating the search URL. What are your thoughts on this approach, and do you have any specific recommendations or considerations for implementing it?

**Comment by badrivlog** [comment]
Hello @eddiejaoude @amandamartin-dev

I hope you're doing well. I wanted to bring your attention to a PR I submitted #9248 . In my research, I came across a popular GitHub discussion https://github.com/vercel/next.js/discussions/18072 that seems closely related to the issue this PR aims to address. I believe the insights and solutions discussed in that thread could be beneficial in resolving our issue.

I understand that everyone has their own commitments, but I was wondering if you could take a moment to review my changes and consider the information shared in the linked discussion. Your feedback and guidance would be highly appreciated.

Thank you in advance for your time, and please let me know if there's anything specific you'd like me to address or clarify in the PR.

❤❤❤

**Comment by amandamartin-dev** [comment]
> Hello @eddiejaoude @amandamartin-dev
> 
> I hope you're doing well. I wanted to bring your attention to a PR I submitted #9248 . In my research, I came across a popular GitHub discussion [vercel/next.js#18072](https://github.com/vercel/next.js/discussions/18072) that seems closely related to the issue this PR aims to address. I believe the insights and solutions discussed in that thread could be beneficial in resolving our issue.
> 
> I understand that everyone has their own commitments, but I was wondering if you could take a moment to review my changes and consider the information shared in the linked discussion. Your feedback and guidance would be highly appreciated.
> 
> Thank you in advance for your time, and please let me know if there's anything specific you'd like me to address or clarify in the PR.

Thank you for doing this research.  I have not used this method myself so cannot speak from a place of experience but it does look promising.  I did notice in the conversation that many folks mentioned an issue with using the back button.  What did you see in your tests?  Also, I would like to hear Eddies (or someone elses) thoughts too since I have not implemented this before.

**Comment by badrivlog** [comment]
>  I did notice in the conversation that many folks mentioned an issue with using the back button. What did you see in your tests? 
>
I think it's working as same, when user click a profile and then press the back button we don't want to lost url search param(if I'm right) 
See my screen recording:

https://github.com/EddieHubCommunity/BioDrop/assets/73095526/df8c9595-d41f-4ca4-bff8-cf90390e457c

Here's my final result on mobile keyboard

https://github.com/EddieHubCommunity/BioDrop/assets/73095526/dc9b432d-478a-4be5-a937-1e3285acce2c
