### ISSUE TITLE
[BUG] error in repos section

### ISSUE THREAD

**Issue by Dun-sin** [EddieHubCommunity/BioDrop#9216]
### Description

To reproduce, go to a profile and click on repos

### Screenshots

![image](https://github.com/EddieHubCommunity/BioDrop/assets/78784850/f3b68bc4-f22e-4870-9ebb-791ea1fb8428)

### Do you want to work on this issue?

Yes

**Comment by eddiejaoude** [comment]
Thanks @Dun-sin - I just merged a fix for it, it should be deployed any minute now https://github.com/EddieHubCommunity/BioDrop/pull/9214

**Comment by Dun-sin** [comment]
> Thanks @Dun-sin - I just merged a fix for it, it should be deployed any minute now https://github.com/EddieHubCommunity/BioDrop/pull/9214

Yes I saw that, just created just incase cuz I wasn't sure

**Comment by eddiejaoude** [comment]
Thank you 👍  yes best to raise an issue just in case 💯 

I broke it and then immediately created a new PR to fix it 😂
