### ISSUE TITLE
[FEATURE] Remove app alert for new icons

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/BioDrop#9219]
### Description

We currently have a homepage alert, but this can now be removed

> [!NOTE]  
> this can be done in the GitHub UI if you prefer

Steps:
1. Delete these lines of json 
https://github.com/EddieHubCommunity/BioDrop/blob/040ab1e5145351a2937e9cde764b6c5a2ef77ac1/config/app.json#L4-L7

2. Create a pull request from your fork to our repo BioDrop

Screenshot before

<img width="1667" alt="Screenshot 2023-09-30 at 21 39 10" src="https://github.com/EddieHubCommunity/BioDrop/assets/624760/a71c7728-4993-4662-8824-e9ac501ff30a">

Screenshot after

<img width="1670" alt="Screenshot 2023-09-30 at 21 45 35" src="https://github.com/EddieHubCommunity/BioDrop/assets/624760/f26634f3-056b-4776-a621-87291548e885">

### Do you want to work on this issue?

None

**Comment by sarahvii** [comment]
Can I take this one please?

**Comment by eddiejaoude** [comment]
Sure Sara I have assigned it to you 👍

**Comment by iriteshmishra** [comment]
I can take this if no one is up for.

**Comment by Sumit21kumar** [comment]
Pls assign to me.
