### ISSUE TITLE
[BUG] Reorder button should be visible only if multiple links added

### ISSUE THREAD

**Issue by sanketmp** [EddieHubCommunity/BioDrop#9221]
### Description

Edit:
~~We can hide~~ `Disable` the reorder button unless there is more than one link added.

### Screenshots

![reorder](https://github.com/EddieHubCommunity/BioDrop/assets/68698332/d363a444-ba8c-4209-8f44-329fc29eb548)

### Do you want to work on this issue?

Yes

**Comment by SaraJaoude** [comment]
Thank you for raising.  It would be best to `disable` the button rather than hide the button for the following reasons:

- users can see that there is the ability to reorder when they have more than one link
- this prevents the Add Link button from getting too big

I will edit the description to reflect this. 

@sanketmp before we assign this to you, can you please explain how you intend to resolve this?

**Comment by sanketmp** [comment]
Using `disable={condition}` prop in `manage/links.js` because Button component has already `disabled={disable}` in it.
am I going in correct way?

**Comment by jatingodnani** [comment]
hlo,can you assign this issue to me. 
solution:i will check the linklist arry if the length is more than 2 thn i will the show the reorder button

**Comment by mittalsam98** [comment]
Hey @SaraJaoude can I work on this issue? 
My approach will be to pass the `disable={linklist.length<=1}` prop in the Button component

**Comment by SaraJaoude** [comment]
> Using `disable={condition}` prop in `manage/links.js` because Button component has already `disabled={disable}` in it.
> am I going in correct way?

@sanketmp thanks for clarifying - I will change the label to `status: ready for dev` and assign this to you.

**Comment by SaraJaoude** [comment]
@mittalsam98 and @jatingodnani in future please read through the timeline - as you can see this was already requested.  I appreciate your enthusiasm, but your additional comments are causing noise and additional notifications for all maintainers on the project. Please also avoid tagging specific maintainers.

**Comment by PradeepG-07** [comment]
Please assign me this issue

**Comment by SaraJaoude** [comment]
> Please assign me this issue

@PradeepG-07 before you ask for an issue to be assigned to you check the Assignees box at the top of the page.  As you will be able to see from this issue, this is assigned to someone else so you have created extra notifications for the maintainers on this project.

**Comment by SaraJaoude** [comment]
> Kindly assign me this issue. I will add disable functinality on reorder button

@mayank1784 please do not ask for an issue to be assigned to you, when it is currently assigned to someone else and they are working on a PR for it. This adds unnecessary notifications for maintainers and noise. I would suggest you read this project's [Contributing Guide](https://github.com/EddieHubCommunity/BioDrop/blob/main/CONTRIBUTING.md) so you can familiarise yourself with this project's requirements.
