### ISSUE TITLE
[BUG] tag names and number of respective tags in data is not aligned

### ISSUE THREAD

**Issue by milinddethe15** [EddieHubCommunity/BioDrop#9222]
### Description

In search section, tag names and number of respective tags in data is not aligned. They are overlapping. For hacktobefest assign it to me.  

### Screenshots

![issue1](https://github.com/EddieHubCommunity/BioDrop/assets/99114125/8bb5a309-a9f9-4fe8-a3ee-9d855f809e52)

### Do you want to work on this issue?

Yes

**Comment by SaraJaoude** [comment]
Thank you for raising.  As we will be going through the redesign process shortly this is likely to be looked at then, so I will close for now.
