### ISSUE TITLE
[BUG] Issue template for bug to default dropdown to "no"

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/BioDrop#9236]
### Description

Currently the issue template for `.github/ISSUE_TEMPLATE/bug.yml` has the question `Do you want to work on this issue?` 

The options are `none`, `yes` and `no`, this defaults to the option `none`. 

<img width="983" alt="Screenshot 2023-10-01 at 10 42 16" src="https://github.com/EddieHubCommunity/BioDrop/assets/624760/ab78193c-bcb6-4067-9dc5-7d5a0927fc74">

This should default to `no` (`none` to disappear, this is not in the code it is added when there is no default specified), this can be achieved with a few lines of yaml config and here is an example from the feature template ... 

https://github.com/EddieHubCommunity/BioDrop/blob/b4a3a53b425adc0c606704164769b88712ef6835/.github/ISSUE_TEMPLATE/feature_request.yml?plain=1#L25-L28

This will result in looking like...

<img width="293" alt="Screenshot 2023-10-01 at 10 45 35" src="https://github.com/EddieHubCommunity/BioDrop/assets/624760/851689fe-d320-4bb5-b57b-90397f69aec6">

### Do you want to work on this issue?

None

**Comment by Sathasivamthirumoorthi** [comment]
Can I work on this. Please assign it to me

**Comment by Kamlesh72** [comment]
May I work on this issue?

**Comment by SaraJaoude** [comment]
> Can I work on this. Please assign it to me

@Sathasivamthirumoorthi I have assigned this to you.

**Comment by Sathasivamthirumoorthi** [comment]
hey @SaraJaoude  . I have created a PR

**Comment by AyushK101** [comment]
i am working on this issue , please assign #9236

**Comment by Kamlesh72** [comment]
> Hey @eddiejaoude, where I'm making the mistake?
> defaulting it to 0 or 1 is not solving the issue, I even tried to set it to "No" but that's breaking it
> ![Screenshot 2023-10-02 191050](https://user-images.githubusercontent.com/120788538/271986182-e0b98ee5-84b1-4243-a54c-b8125cda41eb.png)
> And after all that, it's still to None
> ![Screenshot 2023-10-02 185431](https://user-images.githubusercontent.com/120788538/271986845-f09a4185-f634-48b0-8146-114f7afd31e5.png)

Hey @ayushsgithub, I hope you know that this issue is already assigned to @Sathasivamthirumoorthi #9245

**Comment by ayushsgithub** [comment]
> > Hey @eddiejaoude, where I'm making the mistake?
> > defaulting it to 0 or 1 is not solving the issue, I even tried to set it to "No" but that's breaking it
> > ![Screenshot 2023-10-02 191050](https://user-images.githubusercontent.com/120788538/271986182-e0b98ee5-84b1-4243-a54c-b8125cda41eb.png)
> > And after all that, it's still to None
> > ![Screenshot 2023-10-02 185431](https://user-images.githubusercontent.com/120788538/271986845-f09a4185-f634-48b0-8146-114f7afd31e5.png)
> 
> Hey @ayushsgithub, I hope you know that this issue is already assigned to @Sathasivamthirumoorthi #9245

Yes @Kamlesh72 bro, but only out of curiosity I was trying to solve it in my local development.

**Comment by eddiejaoude** [comment]
You can see in the issue description the exact code and link to a working example is provided - what you did is not wrong but we want to keep it consistent with the existing usage

https://github.com/EddieHubCommunity/BioDrop/blob/b4a3a53b425adc0c606704164769b88712ef6835/.github/ISSUE_TEMPLATE/feature_request.yml?plain=1#L25-L28
