### ISSUE TITLE
[BUG] The toast is difficult to read due to Z-index issue.

### ISSUE THREAD

**Issue by hi-Kartik2004** [EddieHubCommunity/BioDrop#9272]
### Description

The account & logout links have a higher z-index than the toast content. (The toast content is below the Account & logout link)

### Screenshots

PFB the screenshot showing the same!
![image](https://github.com/EddieHubCommunity/BioDrop/assets/111000515/d411a687-6c87-4866-ab87-ca13a4f21ee8)

### Do you want to work on this issue?

No

### Additional information

You might have to adjust the z-index of the Navbar so that it is below the toast, or give the toast a higher z-index.

**Comment by SaraJaoude** [comment]
Thank you for raising. We cannot replicate this and also as this will change as part of the redesign I will be closing this.
