### ISSUE TITLE
[Discussion] The button colors look very dull, I have suggested some changes.

### ISSUE THREAD

**Issue by hi-Kartik2004** [EddieHubCommunity/BioDrop#9274]
### Description

# Blue color change
```
    background-color: #68f3ff;
    border: 2px solid #5c5c5c;
```
### Light Mode
![image](https://github.com/EddieHubCommunity/BioDrop/assets/111000515/5e7446ba-6756-4f49-8480-bf769fced43c)

### Dark Mode
![image](https://github.com/EddieHubCommunity/BioDrop/assets/111000515/57d3fcba-7c9b-4e5a-9560-01f7c08cbd48)

# Border Color change for dark mode
```
  border: 2px solid #393939;
  box-shadow: 3px 10px 10px 1px #222;
```
## Suggested
![image](https://github.com/EddieHubCommunity/BioDrop/assets/111000515/90bb9ca3-6d69-4690-bbb6-fe78e85e27f8)

## Currently
![image](https://github.com/EddieHubCommunity/BioDrop/assets/111000515/4b5c285e-3abc-476f-bfa2-bfc9fced53b5)

# Border Color change for light mode
```
    border: 2px solid #d7d7d7;
    box-shadow: 3px 10px 10px 1px #eeeeee;
```

## Suggested (Note: Button borders)
![image](https://github.com/EddieHubCommunity/BioDrop/assets/111000515/1e0422d9-75d0-497c-9c13-78fa86b4b26a)

##Currently
![image](https://github.com/EddieHubCommunity/BioDrop/assets/111000515/080a21c1-5082-43a3-91af-1abc466b230d)

### Do you want to work on this issue?

None

### Additional information

I think changing these defaults (colors) will have a great impact in providing users with better UI/UX.
It would be nice to hear out your thoughts on this.

**Comment by SaraJaoude** [comment]
Thank you for the suggestion but we have used our brand colours so I will close this, as your suggestion is not part of the brand colour.
