### ISSUE TITLE
[FEAT] Remove "?" Badge On Events Page

### ISSUE THREAD

**Issue by khairnsaa** [EddieHubCommunity/BioDrop#9275]
### Description

There's a badge / chip (or whatever you called it) that contain "?" as the value, i don't know what's that for. maybe it means to show the total events that available on the website(?). 

i'm suggesting to remove it, because if it is intended to show the total number of available events, that information has been shown in the "show all" section. hence it's not necessary to have a badge that contains the total number of available events anymore

### Screenshots

![Group 3](https://github.com/EddieHubCommunity/BioDrop/assets/53510222/7b815e16-3350-4c80-8a05-71337ff46a13)

### Do you want to work on this issue?

Yes

**Comment by SaraJaoude** [comment]
Thank you for raising. If you hover the `?` you will see that this refers to help - and takes you to the docs for events.

<img width="1680" alt="Screenshot 2023-10-03 at 10 20 01" src="https://github.com/EddieHubCommunity/BioDrop/assets/82668196/a2a069d2-06dc-4963-aba2-6eb4870bfcfc">

However as we are now using forms mainly this can be removed.

I have assigned this to you.

**Comment by viditagrawal56** [comment]
I would like to work on this issue as the assignee has not made a pull request yet

**Comment by khairnsaa** [comment]
Done! sorry for taking a long time to open a PR, had a long day at work, but i submitted my PR

**Comment by SaraJaoude** [comment]
> I would like to work on this issue as the assignee has not made a pull request yet

@viditagrawal56 this an unreasonable request - when you commented the assignee had only been given this issue an hour before.  I would suggest you read the [Contributing Guide](https://github.com/EddieHubCommunity/BioDrop/blob/main/CONTRIBUTING.md) for this project - we give assignees two weeks to create a PR. We would be grateful if you could please avoid creating extra notifications for maintainers and noise.

**Comment by Sumit21kumar** [comment]
if you found any error in Assignees then you have a choice of another pull request. thank you 

sorry for void the "code of conduct" but this pull request is only done for practice purposes.

**Comment by eddiejaoude** [comment]
@Sumit21kumar that you for your enthusiasm but this creates more work, noise and confusion to everyone. It would be better for the project and your GitHub profile to provide help and support the the person it is assigned to. Please think collaboration not competition. I will be closing your pull request.
