### ISSUE TITLE
[FEATURE] : Event section

### ISSUE THREAD

**Issue by rahulpandey70** [EddieHubCommunity/BioDrop#9277]
### Description

If an event is paid we're showing `amount` Can we show `free` instead of blank text if it is free event, I know we are showing `cross dollar sign` but I think `BioDrop` users rarely notice.

### Screenshots

![Screenshot from 2023-10-03 12-43-00](https://github.com/EddieHubCommunity/BioDrop/assets/34403988/d715756f-87cf-40ee-b043-b8b8380ae095)

### Do you want to work on this issue?

Yes

**Comment by SaraJaoude** [comment]
Good idea.  Could you please explain how you would suggest solve/complete this issue?

**Comment by Dun-sin** [comment]
> Good idea.  Could you please explain how you would suggest solve/complete this issue?

There's a condition I'm sure to show the price if it exists, so Instead of `price && display` we go `price ? display : free`

**Comment by rahulpandey70** [comment]
![Screenshot from 2023-10-03 12-43-00](https://github.com/EddieHubCommunity/BioDrop/assets/34403988/273fecaf-b0d1-444c-9870-58b69bed3380)

As you can see on the `right side` for `paid` events we're showing `$349`, and for `free` events we're not showing anything so instead of nothing I wanted to put `Free` text. And one more on the `left side` for virtual events we're showing `Remote` and for `In-person` events we're not showing anything so instead of nothing I wanted to put `In Person` text.

if you agree I wanted to work on this feature.

**Comment by amandamartin-dev** [comment]
> > Good idea.  Could you please explain how you would suggest solve/complete this issue?
> 
> There's a condition I'm sure to show the price if it exists, so Instead of `price && display` we go `price ? display : free`

One thought about this - price is not a required field.  Therefore it would be misleading to replace all events with absence of price with free.  I would only look at once with a price that is 0 and for the blank ones do nothing

**Comment by rahulpandey70** [comment]
> > > Good idea.  Could you please explain how you would suggest solve/complete this issue?
> > 
> > 
> > There's a condition I'm sure to show the price if it exists, so Instead of `price && display` we go `price ? display : free`
> 
> One thought about this - price is not a required field. Therefore it would be misleading to replace all events with absence of price with free. I would only look at once with a price that is 0 and for the blank ones do nothing

I'll provide you a screenshot, then we'll decide this feature should be added or not.

**Comment by rahulpandey70** [comment]
![Screenshot from 2023-10-07 21-59-23](https://github.com/EddieHubCommunity/BioDrop/assets/34403988/64ac810a-bb57-4ff4-89b0-1010e443084b)
hey, this is what I wanted to add so users can see it as they click on the event section, users don't have to look at the right side small icon and figuring out that means. and I think this will improve users experience.

**Comment by SaraJaoude** [comment]
Thanks for your work so far @rahulpandey70, I have assigned this to you.  When raising the PR please do take into consideration Amanda's comment https://github.com/EddieHubCommunity/BioDrop/issues/9277#issuecomment-1744908710 as this is a requirement.
