### ISSUE TITLE
[BUG] There should be gaps between the tags on the profile card

### ISSUE THREAD

**Issue by AbhijeetBiswal** [EddieHubCommunity/BioDrop#9281]
### Description

There should be gaps between the tags on the profile card

### Screenshots

![biodrop issue2](https://github.com/EddieHubCommunity/BioDrop/assets/144774379/1a23d5cf-08b4-4a1b-ae1a-e899ec988408)

### Do you want to work on this issue?

Yes

**Comment by SaraJaoude** [comment]
Thank you for raising.  As we will be going through the redesign process shortly this is likely to be looked at then, so I will close for now.
