### ISSUE TITLE
[FEATURE] Improvement - add a link to github discussions in FAQ page

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/BioDrop#9292]
### Description

This issue is to add a section explaining BioDrop Github discussions page and adding a link. This can go at the end of the current FAQ's

[FAQ page url](https://www.biodrop.io/docs/faqs)

Wording to be used: 

(In bold) **My question is not answered by the FAQs/Where can I start a discussion about a feature or idea for BioDrop?**
(text below) BioDrop uses github discussions to have community conversations about anything related to the BioDrop project that does not fit into an issue.  An example of a github discussion could be proposing an idea for BioDrop that isn't ready for issue creation yet because it needs more details and input from the community.

Take a look at the discussions and [join the conversation](https://github.com/EddieHubCommunity/BioDrop/discussions)

### Do you want to work on this issue?

No

**Comment by Ahnaf-codes** [comment]
@amandamartin-dev i want to work on this

**Comment by PradeepG-07** [comment]
Please assign it to me

**Comment by SaraJaoude** [comment]
> I would like to work on this issue can you please assign it to me

@MeenuyD I have assigned this to you.  Please check the Issue description as I have updated this.

**Comment by Anuragwagh** [comment]
is this issue is still open?

**Comment by SaraJaoude** [comment]
> is this issue is still open?

@Anuragwagh this issue has been assigned to someone else and they are working on the PR - you van see this from the comment history and also the Assignees box at the top of the page.  Please check this in future before raising to avoid noise and extra notifications for maintainers.

**Comment by Anuragwagh** [comment]
@SaraJaoude Thanks for confirming, IK about github PR and assigness , this issue is begineer friendly and will not take much time and sometime folks just assign the task and don't work on it. So , I just confirmed is anyone is still working on it or not.

**Comment by SaraJaoude** [comment]
> SaraJaoude Thanks for confirming, IK about github PR and assigness , this issue is begineer friendly and will not take much time and sometime folks just assign the task and don't work on it. So , I just confirmed is anyone is still working on it or not.

@Anuragwagh - I am not sure from your message whether you are still asking if someone is still working on this issue.  If you take a look at the PR changes were requested a few days ago and in this project we like to give our contributors time to respond as we appreciate that people have other commitments. As reflected in our [Contributing Guide](https://github.com/EddieHubCommunity/BioDrop/blob/main/CONTRIBUTING.md)  and issue will be unassigned if there has been inactivity for two weeks.  I suggest you check back in then, to reduce extra notifications for maintainers and everyone else.
