### ISSUE TITLE
[BUG] Docs page missing nav

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/BioDrop#9298]
### Description

This issue is to add the docs nav menu the [Open Source Roadmap](https://www.biodrop.io/docs/open-source-roadmap) page to increase consistency in all of the docs pages.

Note: Check to make sure this update is reflected on desktop and mobile views

Screenshot of current docs page:
![open-source-roadmap](https://github.com/EddieHubCommunity/BioDrop/assets/97615019/2d72c189-b767-406b-b81c-3e116ca28ae1)

Screenshot of docs page with side nav:
![docs-side-nav](https://github.com/EddieHubCommunity/BioDrop/assets/97615019/4ae1c3e7-4dea-459d-a4fd-fd69adb0c45b)

### Do you want to work on this issue?

None

**Comment by Akib-Vijapura** [comment]
I would like to work on it

**Comment by Viveksati5143** [comment]
I want to work on this issue!

**Comment by waellerbe** [comment]
> > I want to work on it, amandamartin-dev can you assign me this issue ?
> 
> @Akib-Vijapura as you were the first to request this I have assigned this to you. In future please avoid tagging a specific maintainer - all maintainers are notified and can assign issues.

I will read up on the progress on this issue for learning purposes. I understand that the issue is __already__ assigned to another member of the community.
