### ISSUE TITLE
[BUG] Mobile - give us a star banner styling

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/BioDrop#9299]
### Description

On mobile, the "give us a star" banner is not properly aligned to be readable.  This issue is to adjust the banner to increase UI/UX consistency in the application

### Screenshots

![give-us-a-star](https://github.com/EddieHubCommunity/BioDrop/assets/97615019/63c7644a-0eed-45d1-b0c1-a62af5e2173d)

### Do you want to work on this issue?

None

**Comment by PradeepG-07** [comment]
please assign me this issue

**Comment by krushnarout** [comment]
> ### Description
> On mobile, the "give us a star" banner is not properly aligned to be readable. This issue is to adjust the banner to increase UI/UX consistency in the application
> 
> ### Screenshots
> ![give-us-a-star](https://user-images.githubusercontent.com/97615019/272294178-63c7644a-0eed-45d1-b0c1-a62af5e2173d.jpg)
> 
> ### Do you want to work on this issue?
> None
> 
> ### Additional information
> _No response_

Hi @amandamartin-dev,

I have experience with mobile responsiveness. Please assign me this issue :)

**Comment by krushnarout** [comment]
Hi @amandamartin-dev ,

I have experience with mobile responsiveness. Please assign me this issue :)

**Comment by SaraJaoude** [comment]
> please assign me this issue

@PradeepG-07 I have already assigned an issue to you. As mentioned in our [Contributing Guide](https://github.com/EddieHubCommunity/BioDrop/blob/main/CONTRIBUTING.md) we only assign one issue per person. Please also avoid commenting on multiple issues until you are assigned something - this creates a lot of unnecessary noise and notifications.

**Comment by SaraJaoude** [comment]
> Hi amandamartin-dev ,
> 
> I have experience with mobile responsiveness. Please assign me this issue :)

@krushnarout I have assigned this to you.  In future please avoid tagging a specific maintainer - all maintainers received these notifications and can assign issues.

**Comment by krushnarout** [comment]
> > Hi amandamartin-dev ,
> > I have experience with mobile responsiveness. Please assign me this issue :)
> 
> @krushnarout I have assigned this to you. In future please avoid tagging a specific maintainer - all maintainers received these notifications and can assign issues.

Okay, Thanks for assigning me @SaraJaoude.

**Comment by Sumit21kumar** [comment]
@amandamartin-dev , I am unable to find this type of message from my local repo (means after fork, clone and run on my server) so how we work for this issue 

![image](https://github.com/EddieHubCommunity/BioDrop/assets/115893008/3f5e1a60-a954-4d17-b3e7-c635aa0c2447)

I know this is assign to another but for knowledge i am working on it.

**Comment by xkrishguptaa** [comment]
@Sumit21kumar this issue was already assigned to @krushnarout, and they have made the PR, I suggest you look at some of our [other issues](https://github.com/EddieHubCommunity/BioDrop/issues)
