### ISSUE TITLE
[FEATURE] GitHub Action to update someones comment on a PR

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/BioDrop#9301]
### Description

When someone comments on a PR, it usually is requesting it to be assigned to them. It would be useful to know if they have any issues assigned to themselves at the moment already

- check if the author of the comment on the PR has any issue assigned to them
- if they do, update their comment with some meta information that they have an issue assigned to them with a url to the issue

### Do you want to work on this issue?

No

**Comment by SaraJaoude** [comment]
> Hey Eddie👋- I want to work on this issue!!

@Viveksati5143 as this is a 5 pointer, please can you explain how you would complete/solve this issue.

**Comment by Viveksati5143** [comment]
> > Hey Eddie👋- I want to work on this issue!!
> 
> @Viveksati5143 as this is a 5 pointer, please can you explain how you would complete/solve this issue.

I've worked on similar issue before in some other open source repo. So, I must be able to complete it😄

**Comment by Viveksati5143** [comment]
Also, It would a great step to moving ahead in contributing to BioDrop!!

**Comment by Pushkarm029** [comment]
I would like to work on this issue. Since this a 5 pointer. I can solve this issue in this way :
1. I will obtain the username of the commentator using `COMMENT_USER=$(jq -r .comment.user.login "$GITHUB_EVENT_PATH")`
2. I will search this query `https://github.com/$GITHUB_REPOSITORY/issues?q=is%3Aopen+is%3Aissue+assignee%3A$COMMENT_USER` on Github.
3. Then, update comment with the link of issue they already have.

**Comment by eddiejaoude** [comment]
> I've worked on similar issue before in some other open source repo. So, I must be able to complete it😄
> And also Eddie has made the 2 bullet points clear enough to solve the issue✅

@Viveksati5143 this is not a clear response to maintainers question

**Comment by eddiejaoude** [comment]
> I would like to work on this issue. Since this a 5 pointer. I can solve this issue in this way :
> 
> 1. I will obtain the username of the commentator using `COMMENT_USER=$(jq -r .comment.user.login "$GITHUB_EVENT_PATH")`
> 2. I will search this query `https://github.com/$GITHUB_REPOSITORY/issues?q=is%3Aopen+is%3Aissue+assignee%3A$COMMENT_USER` on Github.
> 3. Then, update comment with the link of issue they already have.

Thank you @Pushkarm029 for sharing your thought process. I don't think going via the UI as you suggest on step 2 is a good idea, this is what the API is for

**Comment by eddiejaoude** [comment]
@Pushkarm029 you don't need to come up with a full or complete solution, but before we assign the issue, we are keen people have a good idea of the tasks and challenges, and they are on the right track

**Comment by Pushkarm029** [comment]
@eddiejaoude so, i found this solution : 

1st : Check if the comment author has issues assigned
by using this -> 
`COMMENT_AUTHOR=$(jq -r .comment.user.login "$GITHUB_EVENT_PATH")`
`ISSUES=$(curl -s "https://api.github.com/search/issues?q=is:open+is:issue+assignee:$COMMENT_AUTHOR" | jq .total_count)`
`echo "has_issues=$(test $ISSUES -gt 0 && echo true || echo false)" >> $GITHUB_OUTPUT`

2nd : Update comment if author has issues
`if: steps.check-assignee.outputs.has_issues == 'true'
`

`curl -L \
              -X PATCH \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/$GITHUB_REPOSITORY/issues/comments/$COMMENT_ID \
              -d "{\"body\":\"$MESSAGE\"}"`

-> Tested on my Repo ->
->initial comment -> please assign me
![image](https://github.com/EddieHubCommunity/BioDrop/assets/81290616/65cb5b86-32af-4a43-a30b-05a86051bd0b)

**Comment by Viveksati5143** [comment]
I would implement something like this 
![image](https://github.com/EddieHubCommunity/BioDrop/assets/100852245/24948bcc-2047-4cda-9af6-53f978adfae5)

**Comment by eddiejaoude** [comment]
@Pushkarm029 thank you for sharing your approach, it looks concise - if your bash solution works, I will assign it to you

@Viveksati5143 I prefer your javascript style approach, as we use js into project and I think will be easier for us to make further changes - so please raise an issue with your comment and we can convert to this afterwards
