### ISSUE TITLE
[Updation] Change the a tags in the sidenav to Link tag

### ISSUE THREAD

**Issue by Shashmit** [EddieHubCommunity/BioDrop#9311]
### Description

I found out a tags in the sideNav.js. Shouldn't it be updated to Link tag to render the specific page faster. Or it just me who wants to change it

I would like your opinion on this.

### Screenshots

<img width="1305" alt="Screenshot 2023-10-04 at 06 44 30" src="https://github.com/EddieHubCommunity/BioDrop/assets/70282239/d1c57b99-6458-4afd-967f-4627978727f8">

### Do you want to work on this issue?

Yes

**Comment by SaraJaoude** [comment]
Thank you for raising, good spot.  I have assigned it to you.

**Comment by Shashmit** [comment]
Thank you, I will start fixing it now.
