### ISSUE TITLE
[FEATURE] Improvement: footer section on mobile view

### ISSUE THREAD

**Issue by rahulpandey70** [EddieHubCommunity/BioDrop#9313]
### Description

Footer section doesn't look good on mobile view.

### Screenshots

![IMG_20231004_121114](https://github.com/EddieHubCommunity/BioDrop/assets/34403988/c45af506-c73e-41d1-9327-4f4cc557248e)

### Do you want to work on this issue?

Yes

### Additional information

I'm thinking to provide `flex-direction=column` so the text `100% Open Source on GitHub` and icons align column wise.

**Comment by SaraJaoude** [comment]
Thank you for raising and adding a solution.  As you have already been assigned an issue I cannot assign this to you at this stage.

**Comment by PradeepG-07** [comment]
Please assign me this issue

**Comment by PradeepG-07** [comment]
Please assign me this issue

**Comment by Nwakaego-Ego** [comment]
If available , i will like to work on this

**Comment by rahulpandey70** [comment]
> Thank you for raising and adding a solution. As you have already been assigned an issue I cannot assign this to you at this stage.

As I already opened a PR for the previous issue, can you assign me now for this issue? if not you can assign it to someone else. thank you

**Comment by SaraJaoude** [comment]
> > Thank you for raising and adding a solution. As you have already been assigned an issue I cannot assign this to you at this stage.
> 
> As I already opened a PR for the previous issue, can you assign me now for this issue? if not you can assign it to someone else. thank you

@rahulpandey70 please only request to be assigned an issue once the existing PR you have raised has been completed (merged).

**Comment by SaraJaoude** [comment]
> Please assign me this issue

@PradeepG-07 I will assign this to you.

**Comment by rahulpandey70** [comment]
> > > Thank you for raising and adding a solution. As you have already been assigned an issue I cannot assign this to you at this stage.
> > 
> > 
> > As I already opened a PR for the previous issue, can you assign me now for this issue? if not you can assign it to someone else. thank you
> 
> @rahulpandey70 please only request to be assigned an issue once the existing PR you have raised has been completed (merged).

sure

**Comment by PradeepG-07** [comment]
Hey 👋 I have linked a PR please look at it.

**Comment by PradeepG-07** [comment]
It's been 4 days i have made a pull request. It is reviewed also. Please merge it.

**Comment by SaraJaoude** [comment]
> It's been 4 days i have made a pull request. It is reviewed also. Please merge it.

@PradeepG-07 this is not a very helpful comment.  Remember that maintainers are doing this work voluntarily and are going through Pull Requests that are open and are older than yours.  Chasing is not going to make anyone go faster.  I have see your comment on the PR that you want to have this merged so that you can work on other issues - this is not very collaborative and contributing to this project is not a race. You may wish to consider looking at other people's PRs and seeing how you can support.

**Comment by PradeepG-07** [comment]
Hi @eddiejaoude please merge this.
