### ISSUE TITLE
[DOCS] Alignment of Icons is not proper for mobile devices

### ISSUE THREAD

**Issue by Hero-codes** [EddieHubCommunity/BioDrop#9315]
### Description

Fixing the issue of icon's page
Alignment of the icons is not proper for mobile devices

### Screenshots

![image](https://github.com/EddieHubCommunity/BioDrop/assets/98174971/82b17578-46a1-42ea-99e6-816484288a6e)

### Do you want to work on this issue?

Yes

**Comment by SaraJaoude** [comment]
Thank you for raising.  As we will be going through the redesign process shortly this is likely to be looked at then, so I will close for now.
