### ISSUE TITLE
[BUG]: In mobile view, the keyboard is auto-closing and opening when giving or removing input.

### ISSUE THREAD

**Issue by SAGARSINGH-1** [EddieHubCommunity/BioDrop#9316]
### Description

Description
 In mobile view, the keyboard is auto-closing and opening when giving or removing input.

Do you want to work on this issue?
Reviewing the codebase

### Screenshots

https://github.com/EddieHubCommunity/BioDrop/assets/81561733/c6b7802d-d455-4c78-bd00-5dc80746f8d9

### Do you want to work on this issue?

Yes

**Comment by ChinmayMhatre** [comment]
Tested issue, occurs in my device as well.

**Comment by badrivlog** [comment]
This issue is duplicate of this #9208

**Comment by SAGARSINGH-1** [comment]
Thank you @badrivlog for pointing out the duplicate issue (#9208). I've reviewed it, and while there are similarities.

Closing this issue.
