### ISSUE TITLE
[FEATURE] Automatic issue assignement.

### ISSUE THREAD

**Issue by Abhishek-90** [EddieHubCommunity/BioDrop#9324]
### Description

Currently, in order for an issue to be assigned to requesting user, the maintainers has to do it manually. We can add a workflow using which the user can assign the issues to themselves. All the user needs to do is comment `/claim` on the issue page and bot will assign the issue to that user. 

This will facilitate in saving time where user does not need to wait for the issue to be assigned to start working on it. 

### Do you want to work on this issue?

Yes

### Additional information

We can also take it forward where the bot will also un-assign the issue incase there is not activity from the user after a fixed period of time, say 14 days.

**Comment by SaraJaoude** [comment]
Thank you for raising. Whilst technically this might be possible this is not the approach we want for this project. 

BioDrop has a bespoke approach and we do give careful consideration as to which contributor is assigned an issue especially as these have different complexities.  It is not simply a case of claiming it, but ensuring that the contributor understands the issue and how this is to be completed/resolved. A manual approach also prevents any sandbagging issues (as you know we assign one issue per contributor). For these reasons I will be closing this issue.
