### ISSUE TITLE
[DOCS] Typo issue on documentation.

### ISSUE THREAD

**Issue by Abhishek-90** [EddieHubCommunity/BioDrop#9327]
### Description

It should `Joining` instead of `Join`
Page URL: https://www.biodrop.io/docs/open-source-roadmap/where

### Screenshots

<img width="785" alt="Screenshot 2023-10-04 135849" src="https://github.com/EddieHubCommunity/BioDrop/assets/43419831/c335ca74-df3f-42c6-b122-936af6e1e343">

### Do you want to work on this issue?

Yes

### Additional information

We can also use this issue to keep adding such minor typos and issues in the docs.

**Comment by SaraJaoude** [comment]
Thank you for raising @Abhishek-90 I have assigned this to you.

**Comment by Abhishek-90** [comment]
Hello, I have made the changes required for this story, but I see that the link to EddieHub is just plain text, should create a link in the place? Refer the image where the link is present `https://eddiehub.org` I can create a link here.
