### ISSUE TITLE
[DOCS]: add more information in Step 5 of the Open Source Roadmap 

### ISSUE THREAD

**Issue by CBID2** [EddieHubCommunity/BioDrop#9334]
### Description

Edit:
~~##Problem~~
In my review of the roadmap, I noticed Step 5 is missing key information on contributing effectively to open source projects.

## Possible Suggestion 
Per [@SaraJaoude’s suggestion in issue #9152](https://github.com/EddieHubCommunity/BioDrop/issues/9152), it would be beneficial to mention giving code reviews as a contributing method. Something like this:

## Code Reviews 
- Ways to give effective feedback 
- Importance of etiquette when giving reviews

## Benefits 
By adding this information, beginners would: 
 - Understand that contributing to open source can be done in many ways, not just pushing commits.
 - Gain a better understanding of how to interact with others in a open source project.

### Do you want to work on this issue?

Yes

### Additional information

~~I would like to do count this towards my Hacktoberfest contribution list.~~ All contributions other than Profile creation/changes count towards Hacktoberfest.

**Comment by SaraJaoude** [comment]
@CBID2 thank you for raising. As you currently have another PR open I cannot assign this one to you.

**Comment by Vidip-Ghosh** [comment]
I would like to work on this.

**Comment by SaraJaoude** [comment]
> I would like to work on this.

@Vidip-Ghosh I have assigned this to you. Please ensure you familiarise yourself with the remainder of the [Open Source Roadmap page](https://www.biodrop.io/docs/open-source-roadmap) so that you can follow the same style guide.

**Comment by 0xSaksham** [comment]
If no one is working on this, I would like to take up this issue.

**Comment by CBID2** [comment]
> If no one is working on this, I would like to take up this issue.

I'm working on it @0xSaksham
