### ISSUE TITLE
UI enhancement for mobile screens [for overall components as well]

### ISSUE THREAD

**Issue by Harshhhh1701** [EddieHubCommunity/BioDrop#9338]
### What would you like to share?

Description:

I found out that the ui for the mobile screen is quite shifted towards left. I have added the screenshot for the issue.

Screenshot:
![image](https://github.com/EddieHubCommunity/BioDrop/assets/92477263/0fc3b7dc-c840-487f-aed5-59f79c8571ae)

### Do you want to work on this issue?

None

### Additional information

Please assign me the task.

**Comment by SaraJaoude** [comment]
Thank you for raising, but this has been recently fixed, retested and is working.
