### ISSUE TITLE
[FEATURE] Remove "Discover" page

### ISSUE THREAD

**Issue by schmelto** [EddieHubCommunity/BioDrop#9341]
### Description

Removing the Discover page and implement the logic in the Search page. So when you go initially in the Search page you get the latest updated Profiles.

This will reduce the page numbers and the confusing first screen of the search page (what are those profiles / why them) will be eliminated.

### Do you want to work on this issue?

No

### Additional information

Once the Discover page is removed, the [Pricing page](https://www.biodrop.io/pricing) needs to be updated as it refers to it:

<img width="1437" alt="Screenshot 2023-10-08 at 11 45 33" src="https://github.com/EddieHubCommunity/BioDrop/assets/82668196/3b0b0d59-2a64-46ab-80fe-d0bc09ca98ec">

It should be changed to "See a list of all those BioDrop Profiles which have been recently updated **on the Search page**"

**Comment by SaraJaoude** [comment]
Thanks @schmelto this is a great idea - I particularly like being able to reduce the number of pages.

**Comment by Harsh3363** [comment]
Hi, @SaraJaoude I would like to solve this issue please assign this to me.

**Comment by SaraJaoude** [comment]
> Hi, SaraJaoude I would like to solve this issue please assign this to me.

@Harsh3363 thank you for your enthusiasm. It appears you are a new contributor to this project.  With new contributors we ask that they request to be assigned issues with points between 1 and 2 (this issue is 5 points) at first.

**Comment by Blaize15** [comment]
I see, we no longer need random user logic for the `search` page. To reduce confusion we should mention `Recently updated profiles` as a heading just after the search bar.

**Comment by Harsh3363** [comment]
> > Hi, SaraJaoude I would like to solve this issue please assign this to me.
> 
> @Harsh3363 thank you for your enthusiasm. It appears you are a new contributor to this project. With new contributors we ask that they request to be assigned issues with points between 1 and 2 (this issue is 5 points) at first.

Alright I will look for the issues with  points between 1 and 2

**Comment by sansarmaske** [comment]
I would like to work on this issue

**Comment by SaraJaoude** [comment]
> I would like to work on this issue

@sansarmaske I will assign this to you

**Comment by sansarmaske** [comment]
Thanks Sara! I will get started on this.

**Comment by SaraJaoude** [comment]
The PR for this has been merged so I will close.
