### ISSUE TITLE
[FEATURE] Improvement - char limit on tags

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/BioDrop#9345]
### Description

Currently there is no limit to how long a tag can be on a profile.  To ensure a consistent experience with tags, this issue is to provide a character limit on tags inputs/save for profile tags.

This is a multi-part issue that should include the following:
1. Add a character limit of 32 on a tag
2. In account management - the field description for tags should be updated to inform the user of the character limit
3. An alert should be presented to the user if they exceed the character limit on a single tag and should prevent saving of longer tags
4. Documentation should be updated to include the character limit on tags

### Do you want to work on this issue?

No

**Comment by MeenuyD** [comment]
I would like to work on this issue can you please assign it to me

**Comment by notpritam** [comment]
can you please assign this to me 
!assign

**Comment by amandamartin-dev** [comment]
> I would like to work on this issue can you please assign it to me

We only assign one issue at a time and your PR for your issue is still open.  We consider an issue fully complete one an assigned issue is merged.

**Comment by notpritam** [comment]
> > I would like to work on this issue can you please assign it to me
> 
> We only assign one issue at a time and your PR for your issue is still open. We consider an issue fully complete one an assigned issue is merged.

can you assign this to me

**Comment by amandamartin-dev** [comment]
@notpritam assigning you now - in the future no need to comment twice on an issue asking to be assigned.  All maintainers get notifications and respond when we are able.

**Comment by mayank1784** [comment]
Kindly assign me the issue. I will add the functionality

**Comment by pratik9818** [comment]
@amandamartin-dev i think @notpritam  could not solve this issue ,it's been a more then 4 weeks , can you assign it to me , i would like to work on this issue .

**Comment by amandamartin-dev** [comment]
> @amandamartin-dev i think @notpritam could not solve this issue ,it's been a more then 4 weeks , can you assign it to me , i would like to work on this issue .

Thank you for bringing this to our attention, I will assign this to you

**Comment by pratik9818** [comment]
@amandamartin-dev  i want to ask some questions/doubt
1- Should I change the border color of tag after 32 characters to indicate the limit because  if user exceed the 32 char limit and then press backspace to remove the extra char then user will know where to stop for better UX although alert will shown but looking in it again and again to check  where to stop will be kind of annoying ?
2-is this documentation on this page should be updated - https://www.biodrop.io/docs/how-to-guides/editing-forms ?

**Comment by amandamartin-dev** [comment]
> @amandamartin-dev i want to ask some questions/doubt 1- Should I change the border color of tag after 32 characters to indicate the limit because if user exceed the 32 char limit and then press backspace to remove the extra char then user will know where to stop for better UX although alert will shown but looking in it again and again to check where to stop will be kind of annoying ? 2-is this documentation on this page should be updated - https://www.biodrop.io/docs/how-to-guides/editing-forms ? 3 - is this right description <img alt="Screenshot 2023-11-09 233120" width="411" src="https://user-images.githubusercontent.com/97376240/281825993-ddf3234d-8741-49db-aa1a-3dc1fdaeb0d0.png">

That's a great question...

I think the best approach is to have consistent error handling approaches throughout the form but for this particular feature that may be complicated.

Changing the border color will not be the best solution in this case bc the border color of the form element you are working on is already changed to the red/orange color while in focus.

Right now all error handling happens on save, so perhaps it should be then for now and a subsequent issue to consider another approach for better UX?  wdyt @eddiejaoude
