### ISSUE TITLE
[BUG] | Generates vertical scroll in profile

### ISSUE THREAD

**Issue by ivanosquis10** [EddieHubCommunity/BioDrop#9348]
### Description

if this issue has already been opened, tell me and I will delete it.

The problem I see is that being in mobile format breaks the profile of the person and generates a vertical scroll. Up to 650px is that it is fixed. 

### Screenshots

![image](https://github.com/EddieHubCommunity/BioDrop/assets/83567373/71203ad1-8929-49b2-9200-60f077409ae2)

### Do you want to work on this issue?

None

**Comment by SaraJaoude** [comment]
Thank you for raising.  As we will be going through the redesign process shortly this is likely to be looked at then, so I will close for now.
