### ISSUE TITLE
[FEATURE] Add name pronunciation audio clip to user profile

### ISSUE THREAD

**Issue by Abhijit-Dixit** [EddieHubCommunity/BioDrop#935]
### Description

For implementation, I was thinking to add a field (to `your-username.json` in the directory `public/data`) holding public gdrive link to user's audio file. This would work well with curent no database arrangement, as we can play it right from the link.

### Screenshots

![image](https://user-images.githubusercontent.com/41284892/148646052-024865d4-bb50-4d9b-90f0-1450b9af10f9.png)

### Additional information

If the idea sounds good, I can take on it.

**Comment by ChuksMbanaso** [comment]
This is a good idea tho

**Comment by eddiejaoude** [comment]
This is a great idea!

**Comment by VarathaRamanujam** [comment]
great

**Comment by kun-lex** [comment]
nice

**Comment by arun-kushwaha04** [comment]
@eddiejaoude can i try working on  this feature ?

**Comment by ShivaRapolu01** [comment]
It is absolutely great idea. This can make a nice impact. I would love to add this feature @eddiejaoude @Pradumnasaraf @krupalitrivedi

**Comment by eddiejaoude** [comment]
Can this be done without uploading an audio file, for example using a 3rd party API?

**Comment by Exar04** [comment]
i would say no, as i don't think people visiting the profile are interested in knowing the pronunciation. And and adding that to the profile just seems like unnecessary clutter, i prefer it simple and clean

**Comment by SaraJaoude** [comment]
This is a great idea, but as this would require a lot more architecture and infrastructure for the file upload and management - and there are no foreseeable features which would also make use of these efforts, we will close this for now.
