### ISSUE TITLE
[BUG] <The sub-navigation menu becomes non-responsive at a specific threshold>

### ISSUE THREAD

**Issue by seyyf** [EddieHubCommunity/BioDrop#9352]
### Description

Observing closely, it's evident that there is room for improvement in terms of the sub-navigation's responsiveness.

I want to work on this issue once it's ready to dev.

![image](https://github.com/EddieHubCommunity/BioDrop/assets/47918224/f2791de5-568c-4f8f-84ae-302d976c257e)

### Do you want to work on this issue?

Yes

**Comment by SaraJaoude** [comment]
Thank you for raising.  As we will be going through a redesign process soon, this will be looked at then - so I will close this issue for now.
