### ISSUE TITLE
[BUG] profile page is rendering twice 

### ISSUE THREAD

**Issue by sital002** [EddieHubCommunity/BioDrop#9368]
### Description

Steps to reproduce:
Go to https://www.biodrop.io/eddiejaoude
When going from the links tab to other tabs the page renders twice. You can see a flicker when you change the tab from links to other tabs. 

### Do you want to work on this issue?

Yes

**Comment by eddiejaoude** [comment]
Thanks for raising the issue @sital002 - when navigating between the tabs we add to the browser history using the built-in router but this causes a reload. I think we might be able to use React Memo here?

**Comment by Abhishek-90** [comment]
@eddiejaoude correct me, but are you talking about wrapping the page entirely inside useMemo hook which returns the page only when there is a change in the url?

**Comment by eddiejaoude** [comment]
I am not sure, it is a idea, I think some research needs to be done

**Comment by Abhishek-90** [comment]
@eddiejaoude if it is okay, I would like to take it up and being some research right away.

**Comment by eddiejaoude** [comment]
Please do some research and make suggestions on how to solve before we assign, this will avoid blocking the issue

**Comment by sital002** [comment]
I have already implemented similar feature on repos page https://www.biodrop.io/repos where the filter options is updated on the browser url we could do the same for this one as well.
Can you assign this to me

**Comment by eddiejaoude** [comment]
Sure @sital002 but could you also please share the solution you took here so others can learn from it

**Comment by sital002** [comment]
For the repos page, I added the query params to the URL which will rerender the page and rerun the getServerSideProps, and fetch the data from the database but in the profile page when we add the query param ```tab``` to the URL the ```getServerSideProps ``` method is rerunning which is causing the page to re-render multiple times. We can stop the re-running ```getServerSideProps``` by adding the property ``` shallow: true``` on the ``` router.push() ``` method which will prevent running ```getServerSideProps``` here is docs for shallow:true property https://nextjs.org/docs/pages/building-your-application/routing/linking-and-navigating#shallow-routing.

**Comment by eddiejaoude** [comment]
Sounds good 👍 We have a similar issue here I think? https://github.com/EddieHubCommunity/BioDrop/pull/9248#pullrequestreview-1662025375
