### ISSUE TITLE
[DOCS] Typo mistake in faqs section.

### ISSUE THREAD

**Issue by ikunal-04** [EddieHubCommunity/BioDrop#9374]
### Description

It should be **How much does it cost to use ```BioDrop ?```** instead of **How much does it cost to use**.
Page URL: https://www.biodrop.io/docs/faqs

### Screenshots

![image](https://github.com/EddieHubCommunity/BioDrop/assets/112847288/f9a586fc-62ff-469c-b72b-f16cf8232fb0)

### Do you want to work on this issue?

Yes

**Comment by SaraJaoude** [comment]
Thank you for raising @ikunal-04 I have assigned this to you.
