### ISSUE TITLE
[FEATURE] Copy Button

### ISSUE THREAD

**Issue by Abhishek-90** [EddieHubCommunity/BioDrop#9375]
### Description

When a contributor is setting up the BioDrop repo locally, they are required to setup .env file for it to run on local server. To register a new application on github, few details provided by Biodrop has to be copied and pasted. We can create a copy button which will copy the values, rather than selected the required text and adding it to github.

 

### Screenshots

<img width="696" alt="Screenshot 2023-10-06 150506" src="https://github.com/EddieHubCommunity/BioDrop/assets/43419831/4edc9279-d0dd-4ce9-a71c-da84fcdc65b8">

### Do you want to work on this issue?

Yes

**Comment by eddiejaoude** [comment]
Thank you for the suggestion. But when they run `npm ci` the `.env` file is created and populated with these values already. So I will close this issue
