### ISSUE TITLE
[OTHER] <Simple data loads test for home page> /tests/home.spec.js

### ISSUE THREAD

**Issue by kbventures** [EddieHubCommunity/BioDrop#9384]
### What would you like to share?

From the home page we want to test that the data loads.

![home_data_load](https://github.com/EddieHubCommunity/BioDrop/assets/30326135/fcf0a887-93c7-495c-9665-c727847a9459)

Specifically, we want to compare the abbreviated number generated by the abbreviateNumber function with database data as parameter to the number generated on the rendered home page. 

### Do you want to work on this issue?

Yes

**Comment by eddiejaoude** [comment]
I have assigned it to you @kbventures
