### ISSUE TITLE
[FEATURE] Page progress bar

### ISSUE THREAD

**Issue by ghoshRitesh12** [EddieHubCommunity/BioDrop#9398]
### Description

There should be a page progress bar indicating the status of a page. I am clicking a link to open a page, it should show me a feedback that the page is loading.

### Do you want to work on this issue?

Yes

**Comment by SaraJaoude** [comment]
Thank you for raising. 

This has been raised multiple times (and closed) as you can see here: https://github.com/EddieHubCommunity/BioDrop/issues/8963 so I will be closing.

In future, please check both closed and open issues before raising.

**Comment by ghoshRitesh12** [comment]
I would like to work on this issue.

**Comment by eddiejaoude** [comment]
Thank you for the suggestion. After moving to the app directory on NextJS this will work out of the box. So I will close for now
