### ISSUE TITLE
[BUG] Twitter icon change

### ISSUE THREAD

**Issue by pratham-yuxo** [EddieHubCommunity/BioDrop#9399]
### Description

Twitter icon on user's profile is still old 
for reference: 
https://www.biodrop.io/eddiejaoude

I think this icon should be changed to the new one.

### Screenshots

![Screenshot 2023-10-07 194413](https://github.com/EddieHubCommunity/BioDrop/assets/111678040/f752b4dc-2a0f-47ab-aa35-3537ea5ebfd0)

### Do you want to work on this issue?

Yes

**Comment by SaraJaoude** [comment]
Thank you for raising.  However whether a user updates their Twitter logo from the flappy bird to the X is entirely up to them. 

Users already have the ability to do so by editing their Links icon either via JSON or Forms, so I will close.
