### ISSUE TITLE
[BUG] Leaves space on right side

### ISSUE THREAD

**Issue by Blaize15** [EddieHubCommunity/BioDrop#9405]
### Description

Below the 640px breakpoint, a space on the right side of the page appears which takes up some of the space of the page. I have provided a screenshot for better understanding :) This could not be a bug if that space has been left on purpose, if so plz close this issue😁

### Screenshots

<img width="545" alt="image" src="https://github.com/EddieHubCommunity/BioDrop/assets/59837486/2d914533-5bbf-4700-8fd7-38d80297f6da">

### Do you want to work on this issue?

None

**Comment by eddiejaoude** [comment]
Thank you for the suggestion. I think this has now been fixed as part of another issue, so I will close for now. Also we will be redesigning the whole app soon also
