### ISSUE TITLE
[BUG] Rename bar graph component

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/BioDrop#9408]
### Description

Currently our bar graph component has a name that is too generic, we need to make this more specific as we add more graph types

Rename `StatsChart` to `BarGraph` and update usage.

https://github.com/EddieHubCommunity/BioDrop/blob/ba441accc667ea26060d268c214b29977301aa38/components/statistics/StatsChart.js#L21

### Do you want to work on this issue?

No

**Comment by MeenuyD** [comment]
I would like to work on this issue can you please assign it to me.

**Comment by PradeepG-07** [comment]
Please assign me this issue

**Comment by AbhijeetBiswal** [comment]
can you please assign me this issue

**Comment by tanbirali** [comment]
I would like to work on this, please assign me this.

**Comment by vins4407** [comment]
Hey Eddie, would like to work on this !

**Comment by kumarankit999** [comment]
Wait wait guys, don't spam here. I think the first who came will be assigned. So, you can look on further issues.

**Comment by SaraJaoude** [comment]
> I would like to work on this issue can you please assign it to me.

@MeenuyD as reflected in our [Contributing Guide](https://github.com/EddieHubCommunity/BioDrop/blob/main/CONTRIBUTING.md), which I would suggest you read, we only assign one issue per person at any one time - and you have an issue currently assigned to you.

**Comment by SaraJaoude** [comment]
Thank you @kumarankit999 for your comment and your support. 

To others, please do not spam issues - many of you have been asked not to do this many times already. 

@vins4407 I am assigning this to you.  Please read this project's [Contributing Guide]([vins4407](https://github.com/vins4407)) to familiarise yourself with the project.

As to the others who have requested this, you have all worked on `good first issues` for this project and these need to be shared amongst our contributors.

**Comment by ayushsgithub** [comment]
If this issue still persists, I would like to work on it.

**Comment by kainatazad1** [comment]
Hey, is it possible for me to be assigned this task?
