### ISSUE TITLE
[FEATURE] : Add cancel button to close alert message

### ISSUE THREAD

**Issue by rahulpandey70** [EddieHubCommunity/BioDrop#9417]
### Description

Can we add a cancel button to close the alert message?

### Screenshots

Before
![Screenshot from 2023-10-09 01-08-21](https://github.com/EddieHubCommunity/BioDrop/assets/34403988/b190420d-3b0e-4d05-a757-744f2e39fc22)
After adding a cancel button like this
![Screenshot from 2023-10-09 01-06-38](https://github.com/EddieHubCommunity/BioDrop/assets/34403988/32411487-afd1-44b7-bfae-dc884ce3166e)

### Do you want to work on this issue?

Yes

**Comment by eddiejaoude** [comment]
Thank you for the suggestion. To do this, we would also need to persist the state that the user has decided to hide the alert. I think this is not needed for now, so I will close.
