### ISSUE TITLE
[FEATURE] QuickStart Screenshots

### ISSUE THREAD

**Issue by rahulpandey70** [EddieHubCommunity/BioDrop#9418]
### Description

We are still using old `LinkFree UI` screenshot.

reference:- https://www.biodrop.io/docs/quickstart-forms

### Do you want to work on this issue?

No

**Comment by eddiejaoude** [comment]
Thank you for raising, this is a duplicate of https://github.com/EddieHubCommunity/BioDrop/issues/8814, so I will close.
