### ISSUE TITLE
[DOCS] Typo mistake in Links section.

### ISSUE THREAD

**Issue by RuchirDixit** [EddieHubCommunity/BioDrop#9432]
### Description

1) It should be '**_these will be shown here_**'  instead of '**_these will shown here_**'

2) It should be '**_please refer to Edit a Link section below_**'  instead of '**_please refer to Edit a Link below_**'

Page URL: https://www.biodrop.io/docs/how-to-guides/links-forms

### Screenshots

![EdditHub](https://github.com/EddieHubCommunity/BioDrop/assets/51926397/96091495-3d08-4215-9436-c7adcab977d3)

### Do you want to work on this issue?

Yes

### Additional information

Please assign this issue to me as part of **Hacktoberfest 2023** as I am new to this community and would like to contribute to it.

**Comment by ChinmayMhatre** [comment]
I believe the first sentence would be : 
If you already have links in your profile, they will be shown here.
The second suggestion looks good to me
