### ISSUE TITLE
[DOCS] <A typographical error>

### ISSUE THREAD

**Issue by devmamunur** [EddieHubCommunity/BioDrop#9433]
### Description

I found a typographical error on this page: https://www.biodrop.io/docs/open-source-roadmap/checks

1) estiablished will be established
2) issuses will be issues 

### Screenshots

![bio-drop-issues](https://github.com/EddieHubCommunity/BioDrop/assets/49125977/b1d81e7e-b04b-4547-ae10-7e4c37534a78)

### Do you want to work on this issue?

None

### Additional information

Assign me

**Comment by ChinmayMhatre** [comment]
@devmamunur assigned you the issue

Please also change the second para to 
" On the top tab, go to Insights, then scroll down the left side to go to Community. Check if they have a code of conduct and a contributing guide. "

**Comment by Nwakaego-Ego** [comment]
If this issue is still up,  please assign to me

**Comment by devmamunur** [comment]
> @devmamunur assigned you the issue
> 
> Please also change the second para to " On the top tab, go to Insights, then scroll down the left side to go to Community. Check if they have a code of conduct and a contributing guide. "

@ChinmayMhatre  what changes need to be made in the second para?
