### ISSUE TITLE
Lock the conversation after first person asks to assign the issue 

### ISSUE THREAD

**Issue by ezhil56x** [EddieHubCommunity/BioDrop#9434]
### Description

Currently the issue gets locked when someone raises an issue until it is changed to ready for dev. After it is labelled ready to dev, many contributors are interested to work on the same issue and asks to assign the issue to them which is good. Many new contributors are not reading the [BioDrop Docs](https://www.biodrop.io/docs/)  to get to know about contributing guide. And are asking to assign the issue to them. 

I would like to request a new feature based on GitHub actions to lock the issue or conversation as soon the first person comments asking to assign the issue. Through this maintainer can focus less on replying to the new contributors who are asking to assign the issue after someone have already asked for

💡 To implement (just a little idea I had)
Check if the comment have `assign` or some specific keywords to trigger the GitHub action 

### Do you want to work on this issue?

Yes

**Comment by eddiejaoude** [comment]
Thank you for the suggestion but I don't think this is good idea because many people who ask for the issue first cannot be assigned - for example they have another issue assigned or have already done multiple good first issues
