### ISSUE TITLE
[BUG] Navigation menu overflow on top alert message

### ISSUE THREAD

**Issue by badrivlog** [EddieHubCommunity/BioDrop#9445]
### Description

On our website, there is a top alert message displayed above the header. I have identified an issue when screen size is below 768px, the navigation menu overflows onto alert message, causing the top-left side of the page some navigation links partially clickable.

step to reproduce:
* go to https://www.biodrop.io/
* reduce the width of the browser window to less than 768px.
* hover over top-left side of the page
* observe that some navigation links are still partially clickable.

### Screenshots

https://github.com/EddieHubCommunity/BioDrop/assets/73095526/9db89f7a-c405-4cc8-9b6e-728a492ed509

### Do you want to work on this issue?

None

### Additional information

to fix this issue one potential solution could be replace `-translate-y-96` to `-translate-y-[26rem]`
https://github.com/EddieHubCommunity/BioDrop/blob/7da46bef90d25120b78b762238b127e25721c469/components/navbar/Navbar.js#L235

**Comment by SaraJaoude** [comment]
Thank you for raising and well done for finding such a special bug.  As we will be looking at doing the redesign shortly I expect this will be fixed as part of this process, so I will close this issue for now.
