### ISSUE TITLE
[BUG] Recommendation banner overflow out of container

### ISSUE THREAD

**Issue by Deveesh-Shetty** [EddieHubCommunity/BioDrop#9451]
### Description

I am not sure whether this is intended or not, but I am raising an issue as this seems out of the flow with other content.
The recommendation banner here in the screenshot is of "Pradumna Saraf's", should be within the container which is set for all the other elements in the home page. 

### Screenshots

![image](https://github.com/EddieHubCommunity/BioDrop/assets/89470104/2b5e6b06-5224-4617-a8b8-7e280bd95977)

### Do you want to work on this issue?

Yes

### Additional information

If this is unintended I would like to work on this, otherwise we can close this issue.

**Comment by SaraJaoude** [comment]
Thank you, but this was an intentional design choice so I will close.
