### ISSUE TITLE
[FEATURE] Change the text color of searched category button/label

### ISSUE THREAD

**Issue by aulth** [EddieHubCommunity/BioDrop#9460]
### Description

Searched category label has background color #ED616B with black text, it does not look appealing. Change the text to white.

### Screenshots

This is the button with white text
<img width="824" alt="Screenshot 2023-10-11 225158" src="https://github.com/EddieHubCommunity/BioDrop/assets/84888797/61929ea4-c797-4a28-8743-0d5e7be72a5f">

This is the button with black text
<img width="824" alt="black text" src="https://github.com/EddieHubCommunity/BioDrop/assets/84888797/f8d02ac9-0d63-4023-83aa-463833609ed0">

### Do you want to work on this issue?

Yes

**Comment by eddiejaoude** [comment]
Thank you for the suggestion. Unfortunately, using white text will fail accessibility tests - you can try this for yourself by changing the text color and running the automated tests. So I will close this issue.
