### ISSUE TITLE
[BUG] Docs URL refresh when using side nav

### ISSUE THREAD

**Issue by devmamunur** [EddieHubCommunity/BioDrop#9486]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

production on biodrop.io

### Version of BioDrop (for example "v1.2.3")

Current version v2.72.9

### Description

Most of the pages on biodrop.io load without refreshing the URL, but in the documentation module if I click any of the links from the left sidebar it refreshes the URL. ()

I can fix this, all documentation pages will load without refreshing the URL.

### Screenshots

Image of the links:
https://github.com/EddieHubCommunity/BioDrop/assets/49125977/5e787d09-b259-47c3-bb00-60130763c446

Video of the issue:
![Screenshot_1](https://github.com/EddieHubCommunity/BioDrop/assets/49125977/01fa58cd-3a29-418f-bcaf-170d64f8c6e5)

### Do you want to work on this issue?

Yes

### If you want to work on this issue...

Issue in code:
![before-issue](https://github.com/EddieHubCommunity/BioDrop/assets/49125977/4620a0e8-9620-42c5-bcf1-1a43cee8c2c8)

How to solve this : 
![issue_solve](https://github.com/EddieHubCommunity/BioDrop/assets/49125977/e69f662f-f8df-4aa1-a590-6bc11ef4951c)

I added the "next/link" to solve the URL refresh problem, And it works perfectly.

**Comment by eddiejaoude** [comment]
Good spot 👍 Thank you for the well written issue 🔥 I have assigned it to you

**Comment by hiteshmodi0624** [comment]
I want to work on this issue.

**Comment by hiteshmodi0624** [comment]
Okay
