### ISSUE TITLE
[BUG] Button in Open source roadmap page redirects to a invalid repo

### ISSUE THREAD

**Issue by Karan-Palan** [EddieHubCommunity/BioDrop#9502]
### Has this bug been raised before?

- [x] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

On Biodrop website, Open source page

### Version of BioDrop (for example "v1.2.3")

v2.75.0

### Description

When we click on the button,
![image](https://github.com/EddieHubCommunity/BioDrop/assets/143683619/bb6e304c-fd9b-4239-b535-98fefb7481f6)

 it redirects us to:
![image](https://github.com/EddieHubCommunity/BioDrop/assets/143683619/796d7a10-e81b-4e73-81bb-84e5001eb624)

### Screenshots

https://github.com/EddieHubCommunity/BioDrop/assets/143683619/8a90e782-da74-41dc-9ec9-39e16937780c

### Do you want to work on this issue?

No

**Comment by eddiejaoude** [comment]
Thank you for raising the issue 👍

**Comment by Ameya02** [comment]
can i work this?

**Comment by Pinaka-Pani-18** [comment]
Can I work on this issue?

**Comment by Karan-Palan** [comment]
> Thank you for raising the issue 👍

Welcome @eddiejaoude .
I had opened this request for others to contribute, but I realized i haven't contributed to this repository.
Really sorry for asking this but can you assign me this issue?

**Comment by Karan-Palan** [comment]
> Thank you for raising the issue 👍

Welcome, My pleasure

**Comment by mianakbarjan** [comment]
Hi there, can this issue be assigned to me?

**Comment by guranshdeol** [comment]
i would like to work on this issue, Kindly assign me. Thanks

**Comment by aryansri-19** [comment]
Please assign this issue to me.

**Comment by DivjotBatra** [comment]
Please assign this issue to me.

**Comment by RuchirDixit** [comment]
Please assign me this issue if possible, would like to contribute to this.

**Comment by khairnsaa** [comment]
Hi! if this issue still doesn't have assignee, i would love to work on this issue

**Comment by ATREAY** [comment]
Hey everyone, let's take it easy. Please avoid spamming here since only one person can be assigned to an issue. In the future, there will be more chances to work on different issues. 

**In open source, collaboration is key, not competition.**

**Comment by sohamtembhurne** [comment]
> Thank you for raising the issue 👍
Since this issue is still not assigned, I would love to get this assigned to me

**Comment by SaraJaoude** [comment]
To anyone who would like to be assigned this issue, please explain what technical solution you would implement.  

Please note the points (effort required) has been updated from `Points 3` to `Points 5` - therefore we are looking for the assignee to be familiar with this project and have worked on PRs before (and had these merged).

**Comment by khairnsaa** [comment]
i will fix it by changing the href value of "Open Source Roadmap" in the `components/layout/DocsLayout.js`

this is the current code
`{ name: "Open Source Roadmap", href: "/docs/open-source-roadmap" },`

and this is the code for my changes
`{ name: "Open Source Roadmap", href: "/docs/open-source-roadmap/index.js" },`

**Comment by Ameya02** [comment]
I will fix the issue by changing the line in the following in Edit Github Links file
Current Code
``` asPath === "/docs" ? `index.js` : `${asPath}.mdx```
My Code
``` asPath === "/docs" || asPath === "/docs/open-source-roadmap" ? `${asPath}/index.js` : `${asPath}.mdx```
It will open the links to there correct files in the repo

**Comment by Koushik1311** [comment]
Right now the current code is 
```javascript
const githubUrl = `https://github.com/EddieHubCommunity/BioDrop/edit/main/pages${
    asPath === "/docs" ? `/docs/index.js` : `${asPath}.mdx`
  }`;
``` 
by giving "/docs/open-source-roadmap" another condition to check and replace "/docs/index.js" with `${asPath}/index.js` we can solve this issue

My code
```javascript
const githubUrl = `https://github.com/EddieHubCommunity/BioDrop/edit/main/pages${
    asPath === "/docs" || asPath === "/docs/open-source-roadmap" ? `${asPath}/index.js` : `${asPath}.mdx`
  }`;
``` 

Here is the screenshot
On Production
![prod](https://github.com/EddieHubCommunity/BioDrop/assets/120767897/3991aa26-3f65-4e27-b90c-443851b3d3b2)

On development/my local machine
![dev](https://github.com/EddieHubCommunity/BioDrop/assets/120767897/9f54fba7-cdda-4b64-bde3-bd2cb1260c56)

**Comment by SaraJaoude** [comment]
> I will fix the issue by changing the line in the following Current Code `` asPath === "/docs" ? `index.js` : `${asPath}.mdx `` My Code `` asPath === "/docs" || asPath === "/docs/open-source-roadmap" ? `${asPath}/index.js` : `${asPath}.mdx `` It will open the links to there correct files in the repo

Thank you @Ameya02  - as you have written the correct solution first, I will assign this to you.
