### ISSUE TITLE
[BUG] View Profile Button not align properly.

### ISSUE THREAD

**Issue by Akib-Vijapura** [EddieHubCommunity/BioDrop#9504]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

login with your account and goto Statistics lab.

### Version of BioDrop (for example "v1.2.3")

v2.75.0

### Description

In the Statistics lab, there is a button labeled "View Profile," but the text within this button is not properly aligned, as depicted in the screenshot below.

### Screenshots

- Now 
<img width="1416" alt="Screenshot 2023-10-14 at 10 04 23 PM" src="https://github.com/EddieHubCommunity/BioDrop/assets/72021210/10da8051-2ee2-4116-9d03-c50bdf59acc1">

- What it should be.
 
<img width="1419" alt="Screenshot 2023-10-15 at 12 48 20 PM" src="https://github.com/EddieHubCommunity/BioDrop/assets/72021210/1bac8480-0dd7-42d8-b663-2c24228c182d">

### Do you want to work on this issue?

Yes

### If you want to work on this issue...

To address this issue, I will correct the text alignment properly.

**Comment by amandamartin-dev** [comment]
More context for this issue - it is not about the button text alignment itself, but the responsive nature of the containing div.  This will only be seen in profiles with very long descriptions

![statistics](https://github.com/EddieHubCommunity/BioDrop/assets/97615019/62ed98ab-cead-489e-aaf6-5419a899bb03)

**Comment by SaraJaoude** [comment]
Thanks for raising @Akib-Vijapura

Could you please explain how you would technically correct the issue? Please see Amanda's message.

**Comment by YuriDevAT** [comment]
I would be interested working on this issue.
I would suggest changing the width to the description container (since this seems to be the one making the difference when it becomes to large) to prevent the button from narrowing.

**Comment by Akib-Vijapura** [comment]
To address this issue, we can set the width size of that container so that it aligns properly.

- without width
<img width="1400" alt="Screenshot 2023-10-21 at 9 32 22 PM" src="https://github.com/EddieHubCommunity/BioDrop/assets/72021210/e9abc841-29f1-4272-95f3-8dea9073453f">

- With width
<img width="1401" alt="Screenshot 2023-10-21 at 9 31 46 PM" src="https://github.com/EddieHubCommunity/BioDrop/assets/72021210/89d4ee29-daba-4d30-9c47-48cffd667721">

**Comment by abfahimb** [comment]
@Akib-Vijapura  How can I login in localhost? to test is that fix is working or not 
![image](https://github.com/EddieHubCommunity/BioDrop/assets/76747782/ea446a83-fe68-4b10-a58e-8274ddf7f51d)

**Comment by vishalsingh2972** [comment]
Hi is this issue still open ?

**Comment by SaraJaoude** [comment]
> Akib-Vijapura How can I login in localhost? to test is that fix is working or not 

@abfahimb we ask that you do not raise support questions in an unrelated issue as this causes unnecessary noise. Please raise this in the Discord Help channel in future.

**Comment by eddiejaoude** [comment]
I think the best solution for this, is not to put a width on the description as this will change, depending on the the amount of text and also the responsiveness of the page, but to add a min width to the button, this can be done to the wrapping `div` of the button using the Tailwind class `min-w-fit` in this file...

https://github.com/EddieHubCommunity/BioDrop/blob/529209a32390cf4b6b1ca75c46e327d9453cef99/components/user/UserMini.js#L49

```diff
- <div className="mt-5 flex justify-center sm:mt-0">
+ <div className="mt-5 flex justify-center sm:mt-0 min-w-fit">
```

**Comment by akash19coder** [comment]
> I would love to work on it :) May you can assign me

You have already been assigned to #9406. BioDrop only assigns one issue per contributor at a time. Please go through the contributing guide to know more [[Contributing guide]](https://github.com/EddieHubCommunity/BioDrop/blob/main/CONTRIBUTING.md)

**Comment by Vijaykv5** [comment]
The PR for it had already being done..That's why I'm looking onto more issues

**Comment by eddiejaoude** [comment]
> The PR for it had already being done..That's why I'm looking onto more issues

@Vijaykv5 sorry for the confusion in the contributing guide, but @akash19coder is correct, so I have updated the contributing guide to be "1 **open** issue at a time"

**Comment by eddiejaoude** [comment]
@Akib-Vijapura I have assigned it to you
