### ISSUE TITLE
[FEATURE] Make cursor pointer on hovering to events

### ISSUE THREAD

**Issue by singodiyashubham87** [EddieHubCommunity/BioDrop#9506]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

This is not related to a problem but rather an enhancement

### Proposed Solution

Change cursor property on hover

### Screenshots

![image](https://github.com/EddieHubCommunity/BioDrop/assets/93720428/deaf7180-c55a-49f3-b80e-06e68ae4f5c3)

### Do you want to work on this issue?

Yes

### If you want to work on this issue...

I will add make the cursor property as pointer on hover state for the events divs

**Comment by SaraJaoude** [comment]
Thank you, but as the events are not clickable it would not make sense to add a pointer to the whole card - so I will close this issue.
