### ISSUE TITLE
[BUG] Docker rmi command requires lowercase Image name

### ISSUE THREAD

**Issue by Shiva-Sai-ssb** [EddieHubCommunity/BioDrop#9507]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

Local dev environment

### Version of BioDrop (for example "v1.2.3")

v2.75.0

### Description

The Docker image name in the "docker rmi" command should be in lowercase (i.e "docker rmi biodrop-app") to prevent errors, as using uppercase characters caused an error during execution. Please, refer to the attached screenshot. As, it says the name should be in lowercase, and when I changed it to lowercase, it worked. Though it's a minor issue, I want to address it. I got this error when I was trying to set up the project on my computer.

Link where I found the command in the project : https://www.biodrop.io/docs/environments/local-development#local-development

### Screenshots

Command :

![Screenshot (55)](https://github.com/EddieHubCommunity/BioDrop/assets/112751524/b46524d7-e4f6-4068-adb0-93a35bcc8d0d)

Error:

![Screenshot (42)](https://github.com/EddieHubCommunity/BioDrop/assets/112751524/cce51538-2fcc-44c6-a527-0ee729d0b6c4)

### Do you want to work on this issue?

Yes

### If you want to work on this issue...

I'll update the command to "docker rmi biodrop-app" because the image name should to be in lowercase.

**Comment by SaraJaoude** [comment]
@Pradumnasaraf could you please confirm whether this change is required? Thanks!

**Comment by Pradumnasaraf** [comment]
Hey,

Good spot. Yes, this is required, Sara. Shiva, I have assigned the issue to you, you can go ahead and work on it.
