### ISSUE TITLE
[BUG] UI breaking at 768 width devices

### ISSUE THREAD

**Issue by UlbertAO** [EddieHubCommunity/BioDrop#9509]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

production on biodrop

### Version of BioDrop (for example "v1.2.3")

2.75.0

### Description

UI breaking at 768 width devices
right side section in header is overflowing

refer below provided screenshots

### Screenshots

observe on the right side 
![image](https://github.com/EddieHubCommunity/BioDrop/assets/60578286/b711cfe4-d761-4cd7-bd9c-9044c0a02ba3)

### Do you want to work on this issue?

Yes

### If you want to work on this issue...

media query used :
``` 
@media (min-width: 768px)
```

but it starts breaking from around 812
thinking to increase min-width value to fix this.
![image](https://github.com/EddieHubCommunity/BioDrop/assets/60578286/ea4f8a93-0cf1-4391-9f93-597ad0b1dc2d)

fix 👇  with different breakpoint [may be we have to change in other places not sure ]
![image](https://github.com/EddieHubCommunity/BioDrop/assets/60578286/306f16b2-929f-4666-bfb1-2e593950dd8e)

or may be flex wrap can be used to align it, but since "sign up"is separated by space so they will come in 2 line.
![image](https://github.com/EddieHubCommunity/BioDrop/assets/60578286/b09d1570-6e53-43e7-a475-6aaa5fe8eea6)

fix with flex wrap 👇 
![image](https://github.com/EddieHubCommunity/BioDrop/assets/60578286/c3b5d29c-6053-411a-b37b-b5572e93a7d1)

**Comment by SaraJaoude** [comment]
Thank you for raising. As the Discover page has been removed from the main navigation now, this significantly reduces the problem raised in this issue.  As we will be going through the redesign process soon, we can look at this as part of that process so I will close this issue for now.
