### ISSUE TITLE
[FEATURE] <description>

### ISSUE THREAD

**Issue by Anjali-Git-Hub** [EddieHubCommunity/BioDrop#9518]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

I want to add tooltip to the links like this , it is good to use as it is providing extra info about the links .

### Proposed Solution

If we had the amazing feature of tooltips, we could use them to provide extra information about links before visiting them.
![tooltip](https://github.com/EddieHubCommunity/BioDrop/assets/122084921/3b4b6d65-dea2-4153-ab9d-ef608d350c5a)

### Do you want to work on this issue?

Yes

### If you want to work on this issue...

Yes i want to work on this new feature , i will add the tooltip to the links that required extra info before visiting to them .

**Comment by SaraJaoude** [comment]
Thank you for your suggestion, but this is not a feature we want at the moment so I will close.
