### ISSUE TITLE
[BUG] Typo mistake for subheading of Testimonial section

### ISSUE THREAD

**Issue by amanpreet-dev** [EddieHubCommunity/BioDrop#9519]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

production

### Version of BioDrop (for example "v1.2.3")

v2.75.0

### Description

There is a typo mistake in the subheading of the Testimonials section on the onboarding screen.
The correct spelling is "_Your favourite Testimonials_" but actually it is displayed as "_Your favourite Testinomials_"

URL : https://www.biodrop.io/account/onboarding

### Screenshots

<img width="1322" alt="Screenshot 2023-10-17 at 12 46 19 AM" src="https://github.com/EddieHubCommunity/BioDrop/assets/57353834/99ac9c3e-98b7-40ea-84bf-b373b5be5498">

### Do you want to work on this issue?

Yes

### If you want to work on this issue...

- I will fix the spelling mistake in the component rendering that section.
- I will make sure that there are no further typos regarding this.

**Comment by amandamartin-dev** [comment]
typo confirmed, assigned to you @amanpreet-dev

**Comment by Rajiv-paul** [comment]
assign me to this issue

**Comment by SaraJaoude** [comment]
> assign me to this issue

@Rajiv-paul in future - to avoid extra noise and notifications  - please check the conversation and also the Assignees box at the top of the page before asking. As you can see this has recently been assigned to someone else.
