### ISSUE TITLE
[BUG] unnecessary label on account page

### ISSUE THREAD

**Issue by sital002** [EddieHubCommunity/BioDrop#9521]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

Production

### Version of BioDrop (for example "v1.2.3")
Edit : 
~~Latest~~
v 2.77.2

### Description

Go to ```aacount/manage ``` there is a label named Select a tab which is not required 
This bug exists only on mobile view 

### Screenshots

![Screenshot_20231017-101036_Chrome](https://github.com/EddieHubCommunity/BioDrop/assets/93700622/f61e5ed5-9dde-4ee2-ba4a-3a551780dc41)

### Do you want to work on this issue?

Yes

**Comment by SaraJaoude** [comment]
Thank you for raising @sital002 - I will assign this to you. Could you please update the issue description with the version number (rather than "latest", as this will change and can be confusing).
