### ISSUE TITLE
[FEATURE] -Backcolor change for light-mode

### ISSUE THREAD

**Issue by pritipsingh** [EddieHubCommunity/BioDrop#9526]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

I know this is a very stupid request but I wanted to see if BioDrop team would be interested in introducing different background colors to the biodrop profile.

### Proposed Solution

Add options to select backgrounds colors in the form.

### Do you want to work on this issue?

Yes

### If you want to work on this issue...

I would make an array of colors that can be chosen and then add it to the form section. Whatever color is chosen, we update the state with it. We can also do the same with wallpapers perhaps?

**Comment by SaraJaoude** [comment]
Thank you for raising. This is a good request but requires a lot of thought in relating to colour palettes and accessibility. As we are planning a redesign soon, I will label this as a `future consideration` for us to look into after the redesign is done.

**Comment by pritipsingh** [comment]
Awesome! Thanks @SaraJaoude

**Comment by SaraJaoude** [comment]
As this presents accessibility challenges we will close this for now.
