### ISSUE TITLE
[DOCS] Standardize Method for Escaping Apostrophes in Contraction

### ISSUE THREAD

**Issue by CBID2** [EddieHubCommunity/BioDrop#9528]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

We currently have no standard for escaping apostrophes in contractions like “don’t.” 

### Proposed Solution

For code consistency and to leverage Unicode compatibility, I suggest we use Unicode \u2019 for the right single quotation marks.

### Do you want to work on this issue?

Yes

**Comment by SaraJaoude** [comment]
Thank you for raising. As this has not come up other than in your recent PR, at the moment we cannot see the need to have documentation written especially.  If this comes up multiple times then we can revisit this, so I will close this issue for now.
