### ISSUE TITLE
[BUG] <UI ELEMENT> Spacing for the select tab in profile section

### ISSUE THREAD

**Issue by Shashmit** [EddieHubCommunity/BioDrop#9536]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

production environment 

### Version of BioDrop (for example "v1.2.3")

v2.76.1

### Description

There seems to be no padding and margin given to the element of "select a tab". Because of this it is so close to the border of the parent div.
I would like to just shift the section inside with spacing between the option div and the select a tab div.

### Screenshots

Current UI with no spacing and padding between the Two DIv.

<img width="440" alt="Screenshot 2023-10-18 at 23 04 53" src="https://github.com/EddieHubCommunity/BioDrop/assets/70282239/cf29727e-e496-4b7c-85e3-1a480547685e">

After Some tweak:

<img width="440" alt="Screenshot 2023-10-18 at 23 03 53" src="https://github.com/EddieHubCommunity/BioDrop/assets/70282239/aac37b36-1582-444c-b0b9-594c0208307f">

### Do you want to work on this issue?

Yes

### If you want to work on this issue...

` className="block w-full rounded-md border-primary-medium-low dark:bg-primary-medium focus:border-secondary-medium focus:ring-secondary-medium px-2 mb-2"`
The only change is the px and mb added to give spacing between the two divs.

**Comment by SaraJaoude** [comment]
Thank you for raising, but as this will be addressed by the work in https://github.com/EddieHubCommunity/BioDrop/issues/9521 I will close this for now
