### ISSUE TITLE
[BUG] <A typographical error on docs/environments/gitpod page>

### ISSUE THREAD

**Issue by devmamunur** [EddieHubCommunity/BioDrop#9540]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

https://www.biodrop.io/docs/environments/gitpod

### Version of BioDrop (for example "v1.2.3")

v2.76.1

### Description

 found a typographical error on this page: https://www.biodrop.io/docs/environments/gitpod

1) horizonal will be horizontal

### Screenshots

![issue4](https://github.com/EddieHubCommunity/BioDrop/assets/49125977/ef79a747-ba57-4f8a-bbd1-03724b0f9164)

### Do you want to work on this issue?

No

**Comment by SaraJaoude** [comment]
Good spot, thank you for raising.

**Comment by Divjot02** [comment]
I would like to fix this. Please assign me.

**Comment by Lokendrakushwah12** [comment]
Please assign this issue to me I will fix it

**Comment by RuchirDixit** [comment]
I would like to work on this issue, could you please assign it to me.

I will be making the above mentioned change on line number 39 in following file:

https://github.com/EddieHubCommunity/BioDrop/blob/main/pages/docs/environments/gitpod.mdx

**Comment by Koushik1311** [comment]
I would like to work on this

**Comment by kumarsonsoff3** [comment]
> I would like to fix this. Please assign me.

@Divjot02, I'll assign this to you, as you're the first one to ask for this. Plus it seems to be your first contribution to BioDrop, so it's good to start with a `good first issue`.

@RuchirDixit & others thank you for your interest in this, but please look for other unassigned open issues [here](https://github.com/EddieHubCommunity/BioDrop/issues).
