### ISSUE TITLE
[BUG] <In add new milestone page, when user pick a date from calendar widget it displays previous days date>

### ISSUE THREAD

**Issue by balkris-pe** [EddieHubCommunity/BioDrop#9580]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

production 

### Version of BioDrop (for example "v1.2.3")

v2.80.1

### Description

In the Add new milestone page, when selecting a date from the date input field it shows a previous days date. For example when user selected 19th Oct 2023, it displays 18th Oct 2023.

### Screenshots

![milestones_bug](https://github.com/EddieHubCommunity/BioDrop/assets/72403689/ce55efca-3f1e-413d-aa54-ab0a9f43f415)

### Do you want to work on this issue?

No

**Comment by SaraJaoude** [comment]
Thank you for raising, but we have not been able to replicate this, so I will close this issue for now.

**Comment by balkris-pe** [comment]
Thanks for checking this @SaraJaoude. May i know from which time zone you are validating this. I can easily reproduce this Eastern Daylight time. I hope, this is what happening in shortenDate() method of utils/dateFormat.js

1. Date object is created using user input string date which stores the date internally in UTC and since no time is passed, it will default to 12AM. 
2. We are trying to get the date, month and year from the above created date object it uses browser local time zone. In my case its Eastern time which is 4 hours behind UTC and dates goes to previous days date.

<img width="433" alt="shortenDateLogic" src="https://github.com/EddieHubCommunity/BioDrop/assets/72403689/9986974f-2ce0-4096-ba11-ccfed4c48cc3">

![shortenDateConsoleOutput](https://github.com/EddieHubCommunity/BioDrop/assets/72403689/1a026e91-cfbe-4d49-b61d-982dad7642e1)

Sorry i couldn't add much information yday as i i'm new and haven't explored the code much.
Please verify and let me know. Thanks

**Comment by balkris-pe** [comment]
hi @SaraJaoude. Did you get a chance to check my last comment reg the bug? Thanks

**Comment by balkris-pe** [comment]
hi @SaraJaoude. Hope you are doing good. Did you get a chance to check my last comment reg the bug? Thanks

**Comment by eddiejaoude** [comment]
Thank you @balkris-pe for elaborating on the issue 👍  I couldn't replicate it either, I am in BST timezone

**Comment by balkris-pe** [comment]
Thanks @eddiejaoude for validating.  BST is ahead of GMT, it will set the current date at midnight and wont be reproduced considering we are not displaying the time. Basically this issue will be reproduced only in time zones that are behind GMT, like mine EST which is 4 hours behind. Want to understand one thing, why cant we directly get the values from string date using string operation like split(which will remove the timezone issues) rather than converting string to date and getting values from it?
Thanks.

**Comment by eddiejaoude** [comment]
sorry for my slow reply @balkris-pe 

I see, timezones are always painful. I think date manipulation should occur officially without string manipulation as there are more likely to create bugs. There are functions `toLocaleString` that do not include the timezone

**Comment by balkris-pe** [comment]
Hi @eddiejaoude Thanks for the reply. Happy New Year. Yes, working with dates will be hard in terms of considering different timezones. Just my thought, since this is UI change, we can leverage string operations to make it less complicated.
