### ISSUE TITLE
[FEATURE] <description>

### ISSUE THREAD

**Issue by ashrafchowdury** [EddieHubCommunity/BioDrop#9585]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

**The list of information on the main pages of the code includes things like the maintainers, pricing, features details,** and so on. This information is important, **but it is not necessary to have it on the main page of the code**. It would be better to move this information to a separate folder for better readability.

### Proposed Solution

**We can create a `queries` folder under `service/utils` and move all of the list information from the main pages to that folder**. Then, import the lists from the queries folder into the main JSX code as needed.

### Screenshots

![image](https://github.com/EddieHubCommunity/BioDrop/assets/87828904/a877f594-a883-452a-b5f1-763089bfa581)

![image](https://github.com/EddieHubCommunity/BioDrop/assets/87828904/53a8a4ef-2792-44b8-a039-777945441b96)

### Do you want to work on this issue?

Yes

### If you want to work on this issue...

I can refactor & can give a clean look to the main codebase by transferring the array of lists into a separate folder.

**Comment by SaraJaoude** [comment]
Thank you for the suggestion, however we don't see this as a needed change, so I will close for now.
