### ISSUE TITLE
[FEATURE] Vertical lines color black in light mode

### ISSUE THREAD

**Issue by singodiyashubham87** [EddieHubCommunity/BioDrop#9608]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

It's an enhancement

### Proposed Solution

In light mode the vertical lines are not visible, I want to fix this by making the colour of the vertical lines black.

Kindly assign me this issue.

### Screenshots

![image](https://github.com/EddieHubCommunity/BioDrop/assets/93720428/f74fc2f5-3a3e-4ae0-ad69-740d40381d83)
![image](https://github.com/EddieHubCommunity/BioDrop/assets/93720428/bd9ea5b3-dfbb-4bf0-9f14-1c8413b4ec3d)

### Do you want to work on this issue?

Yes

### If you want to work on this issue...

~~I'll change the color on light mode by changing the CSS~~

Edit:
In light mode use the colour of the font.  Changes can be made in the Tailwind classes `pages/index.js`

**Comment by Harshil-Desai** [comment]
I am ready to work on this issue, please assign it to me

**Comment by sital002** [comment]
> I am ready to work on this issue, please assign it to me

@Harshil-Desai  Please look at the assignee's section before asking for the issue to be assigned. I would recommend you to read our contributing guidelines https://github.com/EddieHubCommunity/BioDrop/blob/main/CONTRIBUTING.md
