### ISSUE TITLE
[FEATURE] Add a click animation on the navbar buttons

### ISSUE THREAD

**Issue by PoulavBhowmick03** [EddieHubCommunity/BioDrop#9614]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

In the Navbar, as seen in the video, there is no on click animation, which can sometimes lead the user in confusion as to whether or not the click actually worked

https://github.com/EddieHubCommunity/BioDrop/assets/133862694/8525488d-c3c0-4a4f-a537-b5387d2fffcb

### Proposed Solution

I will add a CSS click animation which might change the dimension or the color, according to what suits best

### Do you want to work on this issue?

Yes

### If you want to work on this issue...

I would like to work on this issue by changing the CSS, adding a pseudoclass or click effect.

**Comment by SaraJaoude** [comment]
Thank you for raising, but as we will be going through the redesign process soon this is likely to be looked at then - so I will close this issue for now.
