### ISSUE TITLE
[FEATURE] improving icon search 

### ISSUE THREAD

**Issue by sital002** [EddieHubCommunity/BioDrop#9625]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Currently, When I visit https://www.biodrop.io/icons it won't filter the searched icons it will be easier for sharing the link if we have filter icons pushed in the URL as query params

### Proposed Solution

We can add the searched icons in the URL so that they share the link 

### Screenshots

![image](https://github.com/EddieHubCommunity/BioDrop/assets/93700622/bc22e80e-10fd-465a-8d09-20c539ab77d1)

### Do you want to work on this issue?

Yes

**Comment by SaraJaoude** [comment]
Great idea.  We need to be consistent on how we achieve this in the Profile tab and the Search page. I will assign this to you.

**Comment by dlin2102** [comment]
Did you still need someone to work on this issue?

**Comment by SaraJaoude** [comment]
> Did you still need someone to work on this issue?

@dlin2102 

This issue is assigned to someone else - this can be seen in the Assignees box at the top right of the page and also in the comment history.  Please check this in future as your comment leads to unnecessary noise and notifications for maintainers.

**Comment by SaraJaoude** [comment]
I am closing this Issue as the PR for it has been merged.
