### ISSUE TITLE
[FEATURE] Check author's assigned issue when creating new issue

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/BioDrop#9627]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Currently we have a GitHub Action that checks when a comment to an issue is added if the author of the comment has any issues assigned and updates their comment with an appended message and link

<img width="622" alt="Screenshot 2023-10-26 at 10 56 16" src="https://github.com/EddieHubCommunity/BioDrop/assets/624760/30225e69-406b-4e26-8c89-638035ea74b9">

It would be good to add this also to when an issue is created and the author of the issue selected the dropdown "Do you want to work on this issue?" to "yes"

### Proposed Solution

Extend the current GitHub Action to be trigged on issue create event and perform the same check and append the issue description

### Do you want to work on this issue?

No

**Comment by AnithaDharaneedharan** [comment]
I would like to work on this. Could you please assign this to me ? Thanks

**Comment by bikrantjajware** [comment]
Hello, If this isnt assigned, i would like to work on this

**Comment by SaraJaoude** [comment]
> I would like to work on this. This will be my first open source ticket. Could you please assign this to me ? Thanks

@AnithaDharaneedharan thank you for your enthusiasm but as you are a new contributor to this project we ask that you should issues that are between `Points 1- - 3` (this issue is 5 points)

**Comment by SaraJaoude** [comment]
> Hello, If this isnt assigned, i would like to work on this

@bikrantjajware I will assign this to you

**Comment by AnithaDharaneedharan** [comment]
> > I would like to work on this. This will be my first open source ticket. Could you please assign this to me ? Thanks
> 
> @AnithaDharaneedharan thank you for your enthusiasm but as you are a new contributor to this project we ask that you should issues that are between `Points 1- - 3` (this issue is 5 points)

Thank you and I will look out for issues which are between 1-3 points
