### ISSUE TITLE
[BUG] double borders on input field in icons screen

### ISSUE THREAD

**Issue by JeevaRamanathan** [EddieHubCommunity/BioDrop#9636]
### Has this bug been raised before?

- [X] I have checked open AND closed issues and this is not a duplicate

### Where did you find this bug?

https://www.biodrop.io/icons

### Version of BioDrop (for example v1.2.3)

v2.83.6

### Description

When the search input of icons page is active, double border with multiple colors can be seen.

### Screenshots

![image](https://github.com/EddieHubCommunity/BioDrop/assets/64531160/a7158d18-4a96-4af6-9112-1ab5fdd56f6a)

### Do you want to work on this issue?

Yes

### If you want to work on this issue...

I want to fix this issue by replacing the default input with Input from components

ℹ️ **JeevaRamanathan** has some opened assigned issues: 🔧[View assigned issues](https://github.com/EddieHubCommunity/BioDrop/issues?q=is%3Aopen+is%3Aissue+assignee%3AJeevaRamanathan)

**Comment by SaraJaoude** [comment]
Thank you for raising.  However we cannot seem to replicate this and the search input field is using the input from the components.  Please see:

https://github.com/EddieHubCommunity/BioDrop/blob/3ec5973212d404107d8e6f69a830fedda15edd82/pages/search.js#L233-L239


Therefore I am closing this issue for now.

**Comment by SaraJaoude** [comment]
Thank you for raising, I will assign this to you.  

In future, if you do want to work on the Issue please select `Yes` for the `Do you want to work on this issue?` question, or else it makes this confusion for maintainers (in view of your comments to `If you want to work on this issue`).

**Comment by JeevaRamanathan** [comment]
Sure, @SaraJaoude. I have raised a pull request. Kindly review it when you have a chance.

**Comment by SaraJaoude** [comment]
@JeevaRamanathan please do not tag a specific maintainer to review a PR - we all receive the notification that the PR has been created, so this adds even more notifications.  This is in the queue and a maintainer will review once we are able to get to it.
