### ISSUE TITLE
[FEATURE] Add a scroll-to-top button

### ISSUE THREAD

**Issue by akash0708** [EddieHubCommunity/BioDrop#9637]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Scrolling down to the bottom of the website and then scrolling back to top can sometimes annoy users. 

### Proposed Solution

A scroll-to-top button will help in easier navigation and thus improve user experience.

### Screenshots

![backtotop2](https://github.com/EddieHubCommunity/BioDrop/assets/110753356/088520ea-57ec-406b-970a-738785ba379e)

### Do you want to work on this issue?

Yes

### If you want to work on this issue...

I would create a button that would come into view when the user starts scrolling down the website. On clicking the button the user will automatically be led to the top of that page.

**Comment by SaraJaoude** [comment]
@akash0708 I am not sure that you did check the closed issues as this has been raised on multiple occasions and closed, as this is not a feature we are looking for.  I am therefore closing this issue.
