### ISSUE TITLE
[BUG] - Typo in "Open Souce Roadmap" in footer in biodrop.io

### ISSUE THREAD

**Issue by mrinmay7875** [EddieHubCommunity/BioDrop#9653]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

production

### Version of BioDrop (for example "v1.2.3")

v2.83.8 ( latest version while creating this bug )

### Description

In the footer the "Open Source Roadmap" spelling there is a typo.
Here is a screenshot:

![image](https://github.com/EddieHubCommunity/BioDrop/assets/33797909/4a6ca0b0-afc3-47e1-ab55-085a88db7283)

### Do you want to work on this issue?

Yes

**Comment by SaraJaoude** [comment]
Thank you for raising. I can see you want to work on this issue but you already have an issue assigned to you - we only assign one issue per contributor (and will only assign again once the PR has been completed).  This is also a `good first issue` so it would be good to give this opportunity to a new contributor.

**Comment by mrinmay7875** [comment]
Sure, I can leave this issue and anyone ( someone newbie) can go ahead and work on this issue,

**Comment by Kamaruddheen** [comment]
Can I work on this issue?

**Comment by mrical** [comment]
Hey, I am sure I can do the job perfectly, can you assign this issue to me

**Comment by Koushik1311** [comment]
I also like to work on this issue

**Comment by SaraJaoude** [comment]
> Can I work on this issue?

@Kamaruddheen I have assigned this to you.
