### ISSUE TITLE
Improvement: Delete functionality on the different cards in profile section

### ISSUE THREAD

**Issue by sumitunique777** [EddieHubCommunity/BioDrop#9657]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

production

### Version of BioDrop (for example "v1.2.3")

v2.83.8

### Description

We can add a delete icon button on the cards itself on (milestones,links,events etc)as it will be easy to delete a particular item from there itself instead of edit it first and then delete it.Let me know if it is valid I can work on this

### Screenshots

<img width="960" alt="image" src="https://github.com/EddieHubCommunity/BioDrop/assets/105304243/631ddb34-24bc-4fdf-b779-47c554208058">

### Do you want to work on this issue?

Yes

**Comment by SaraJaoude** [comment]
I can see that you have raised this before: https://github.com/EddieHubCommunity/BioDrop/issues/7949

Therefore, I will close this for the same reasons as before.
