### ISSUE TITLE
Bug:Issue on Search page

### ISSUE THREAD

**Issue by sumitunique777** [EddieHubCommunity/BioDrop#9658]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

production

### Version of BioDrop (for example "v1.2.3")

v2.83.8

### Description

These two search values don't match.Please see the attached snapshot.

### Screenshots

<img width="960" alt="image" src="https://github.com/EddieHubCommunity/BioDrop/assets/105304243/56291d87-4741-448f-89d3-2793ab1ecc4b">

### Do you want to work on this issue?

Yes

**Comment by SaraJaoude** [comment]
Thank you for raising. I noticed that you want to work on this issue, but again you have not explained how you would go about this.  In future if you want to work on the issue please complete the `if you want to work on this issue` section.  If you are unsure of how to approach it, then we will open the question to other contributors and will assign based on that. 

On this occasion I will assign this to you and here is what you need to do...

The discrepancy relates to:

- badges result: has no filter (for example, includes tags from every Profile)
- search result: has filters applied (for example `isEnabled: true`)

The source files to look at are:

- tag api file `pages/api/discover/tags.js`
- search for get profiles `pages/api/profiles/index.js`

**Comment by aarjun8060** [comment]
hi @sumitunique777, If you do not resolve this issue?  I want to try to solve this issue.
would you assign to me? @SaraJaoude 

I am new in open source. if any guidance for me. Please tell me it's very helpful for me

**Comment by SaraJaoude** [comment]
> hi sumitunique777, If you do not resolve this issue? I want to try to solve this issue. would you assign to me? SaraJaoude
> 
> I am new in open source. if any guidance for me. Please tell me it's very helpful for me

@aarjun8060 this issue was assigned to @sumitunique777 3 days ago - it is not very collaborative to chase them to resolve the issue, especially as we give our contributors two weeks to start work. 

As you are new to open source and looking for guidance, I would suggest that you start out by reading this project's [Contributing Guide](https://github.com/EddieHubCommunity/BioDrop/blob/main/CONTRIBUTING.md).  This will explain how this project is run.

**Comment by sumitunique777** [comment]
<img width="959" alt="image" src="https://github.com/EddieHubCommunity/BioDrop/assets/105304243/8c56e4bd-dfdd-4ccb-af90-d7cab948665b">

The results are coming incorrect because the filters return the record even if there is not any tags list available by comparing the search string with username and another fields

**Comment by sumitappinfoinc** [comment]
Will you please suggest some ideas how can I approach this issue?

**Comment by SaraJaoude** [comment]
> Will you please suggest some ideas how can I approach this issue?

@sumitappinfoinc thank you for your interest but this issue is assigned to someone else. Please feel free to collaborate once a PR is raised.

**Comment by eddiejaoude** [comment]
Great discussion, but I am going to close this, because the search results does not just search the tags but also other profile fields - that is why the numbers do not match
