### ISSUE TITLE
[BUG] Edit button to manage link is not positioned properly

### ISSUE THREAD

**Issue by mrical** [EddieHubCommunity/BioDrop#9660]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

production on biodrop.io

### Version of BioDrop (for example "v1.2.3")

v2.83.8

### Description

The Edit button on the **/account/manage/links** page is not positioned correctly, which results in visual inconsistency and usability problem. This affects the user experience when attempting to manage links in their account.

### Screenshots

<img width="960" alt="70KfBUPo9W" src="https://github.com/EddieHubCommunity/BioDrop/assets/60258119/6c8c4182-aed1-4367-b913-c18280e12e77">

### Do you want to work on this issue?

Yes

### If you want to work on this issue...

To fix this issue I will be changing the position of edit link/button using **Tailwind CSS** styles

**Comment by SaraJaoude** [comment]
Thank you for raising - this has been raised before.  This will be improved as part of the redesign process which is coming up, so I will close this for now.
