### ISSUE TITLE
[FEATURE] <Add other OAUTH Providers like google, apple>

### ISSUE THREAD

**Issue by futoid** [EddieHubCommunity/BioDrop#9662]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

yes

### Proposed Solution

Add other famous OAUTH providers to let more users use BioDrop

### Screenshots

![image](https://github.com/EddieHubCommunity/BioDrop/assets/65010518/c8fee3c3-0407-43b5-84f1-a621a4dd5666)

### Do you want to work on this issue?

Yes

### If you want to work on this issue...

Next-Auth provides easy implementation to add other OAuth Providers

**Comment by SaraJaoude** [comment]
Thank you for raising, but this is not something we are looking to do at the moment (and we want to focus on GitHub users), so I shall close this for now.
