### ISSUE TITLE
[BUG] <adds multiple milestones>

### ISSUE THREAD

**Issue by malay44** [EddieHubCommunity/BioDrop#9687]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

while adding milestone sectio

### Version of BioDrop (for example "v1.2.3")

2.83.14

### Description

when clicked multiple times on save button in milestone section, it sends many requests which results in adding of the same milestone multiple times 

### Screenshots

<img width="1331" alt="Screenshot 2023-10-30 at 9 13 16 PM" src="https://github.com/EddieHubCommunity/BioDrop/assets/101856674/04c255d9-aa8c-40bd-8407-c1b2f81f0b35">

### Do you want to work on this issue?

Yes

### If you want to work on this issue...

By disabling the button when the request is sent.

**Comment by sital002** [comment]
@malay44 Good spot assigning the issue to you.

**Comment by eddiejaoude** [comment]
I was unable to replicate this bug. Milestones redirects after the save, similar to the links page. Are you trying to purposely break it by clicking multiple times before the request comes back successful and the page redirects?

If the above steps to reproduce are correct, it sounds like an edge case and would effect all manage pages and those would need to be updated accordingly too so they are consistent.

**Comment by sital002** [comment]
> I was unable to replicate this bug. Milestones redirects after the save, similar to the links page. Are you trying to purposely break it by clicking multiple times before the request comes back successful and the page redirects?
> 
> If the above steps to reproduce are correct, it sounds like an edge case and would effect all manage pages and those would need to be updated accordingly too so they are consistent.

If you spam the save button it would create the milestone 
multiple times what he is suggesting is to disable the button until the request comes so that there is only one request.

**Comment by eddiejaoude** [comment]
> I would also update other manage pages 😊.

Thank you 👍 I suggest you do 1 page first and create a draft PR and it can be reviewed, then you can apply it to all other pages afterwards
