### ISSUE TITLE
[BUG] <Margin & Padding on footer Section>

### ISSUE THREAD

**Issue by devmamunur** [EddieHubCommunity/BioDrop#9698]
### Has this bug been raised before?

- [X] I have checked open AND closed issues and this is not a duplicate

### Where did you find this bug?

https://www.biodrop.io/

### Version of BioDrop (for example v1.2.3)

v2.83.16

### Description

Balancing top and bottom padding can create visual harmony and improve the overall aesthetics of a design. It helps maintain a sense of consistency and balance in the layout. 

If we improve the footer section padding and margin, it will look more nice. 

### Screenshots

![ui-issue](https://github.com/EddieHubCommunity/BioDrop/assets/49125977/7c7f485d-c1de-4cff-beff-877fd8fe78b0)

### Do you want to work on this issue?

Yes

ℹ️ **devmamunur** has some opened assigned issues: 🔧[View assigned issues](https://github.com/EddieHubCommunity/BioDrop/issues?q=is%3Aopen+is%3Aissue+assignee%3Adevmamunur)

**Comment by SaraJaoude** [comment]
Thank you for raising.  This is a Tailwind component that we use and we do not feel that it needs to be changed.  However the footer will be looked at as part of the redesign process so may change regardless. I will close this issue for now.
