### ISSUE TITLE
[BUG] Accesibility Issue with Icon Dropdown

### ISSUE THREAD

**Issue by at-the-vr** [EddieHubCommunity/BioDrop#9707]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

production

### Version of BioDrop (for example "v1.2.3")

v2.83.18

### Description

The Icon Dropdown under [AddLink](https://www.biodrop.io/account/manage/link) & [Add Milestone](https://www.biodrop.io/account/manage/link) do not respond to Arrow Key Presses.

### Do you want to work on this issue?

No

**Comment by SaraJaoude** [comment]
Thank you for raising.  I have added the label `talk: discussion` so that the community can add their comments on how this can be resolved.

**Comment by aryanraj60** [comment]
I have fixed this issue, can you please assign this issue to me so that I can make a pull request to close this.. @SaraJaoude 

https://github.com/EddieHubCommunity/BioDrop/assets/72094124/c6be7d01-d21b-47e4-965a-f546b64b43fe

**Comment by SaraJaoude** [comment]
Thank you @aryanraj60 - we are going to review this.  In future, please can you avoid tagging a specific maintainer as this creates extra notifications.  

@EmmaDawsonDev and @YuriDevAT if either of you have a moment, we would love to get your thoughts on this.

**Comment by YuriDevAT** [comment]
Thanks for asking! As far as I can see, all it needs is to add **background-color to the active item**.

When you look at the DOM, you see that you CAN select the items by using the arrow keys up/down (`data-headlessui-state=""` changes its value from `""` to `active`), but it is not visible to the user.

As I see from the DOM, this combobox is a headless UI combobox - https://headlessui.com/react/combobox and there, it works perfectly fine. So my guess is that something went wrong by the implementation, and it was forgotten to set a background color for the active state, like they do here at headlessui.

```
className={({ active }) =>
  `relative cursor-default select-none py-2 pl-10 pr-4 ${
    **active ? 'bg-teal-600 text-white'** : 'text-gray-900'
  }`
}
```

Unfortunately they do not have line numbers in the very first example, but this code snippet can be found in the middle of the return statement.

I hope this helps.

**Note:** My insights are based solely on what I identified in the DOM and headlessui combobox example.

**Comment by eddiejaoude** [comment]
Amazing explanation @YuriDevAT ! Thank you for spending time and looking into it

**Comment by eddiejaoude** [comment]
@aryanraj60 please see response above, I think your solution can be simplified https://github.com/EddieHubCommunity/BioDrop/issues/9707#issuecomment-1850720416

**Comment by aryanraj60** [comment]
Thanks for your suggestion @YuriDevAT, Yes eddiejaoude, I checked and tested her suggestion and it's works fine just by adding this code to Combobox.Option -

`
className={({ active }) =>
                `px-3 py-2 flex items-center ${
                  active
                    ? "bg-red-400"
                    : "dark:hover:bg-tertiary-medium/60 hover:bg-secondary-low/40"
                }`
              }

`

**Comment by SaraJaoude** [comment]
@aryanraj60 please see my comments [here](https://github.com/EddieHubCommunity/BioDrop/pull/9913#issuecomment-1859946329).

On this occasion we will assign this issue to you and whilst we appreciate your enthusiasm, in future please follow this project's requirements and guidelines.

**Comment by eddiejaoude** [comment]
Pull Request merged
