### ISSUE TITLE
[BioDrop] Images refer to LinkFree instead of BioDrop

### ISSUE THREAD

**Issue by Abhishek-90** [EddieHubCommunity/BioDrop#9712]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

production

### Version of BioDrop (for example "v1.2.3")

v2.84.0

### Description

On Biodrop Homepage, Features section, Few images still refer to LinkFree instead of BioDrop. Those need to be u

pdate 

### Screenshots

<img width="746" alt="Screenshot 2023-11-01 192953" src="https://github.com/EddieHubCommunity/BioDrop/assets/43419831/ee900057-876d-4b7e-806d-b49371247563">

### Do you want to work on this issue?

Yes

**Comment by Abhishek-90** [comment]
> Thank you for raising. I can see you want to work on this issue, but you did not fill in the `If you want to work on this issue` section explaining your proposed solution - please do this in future.
>
Yes, I will add this section moving forward.

> On this occasion I will assign this to you. Please upload the image to this issue and use the generated URL to update the code.

<img width="947" alt="BioDropMap" src="https://github.com/EddieHubCommunity/BioDrop/assets/43419831/72354ed8-788f-4db2-9867-69fce000ef4c">

This is proper image for replacement?

**Comment by Abhishek-90** [comment]
<img width="880" alt="Screenshot 2023-11-02 144153" src="https://github.com/EddieHubCommunity/BioDrop/assets/43419831/1ed5c631-6e49-4de7-9029-ccd983d5ef1b">

Here is another image on Homepage referring to LinkFree, should replace this as well?

**Comment by ChinmayMhatre** [comment]
> <img alt="Screenshot 2023-11-02 144153" width="880" src="https://user-images.githubusercontent.com/43419831/279925894-1ed5c631-6e49-4de7-9029-ccd983d5ef1b.png">
> Here is another image on Homepage referring to LinkFree, should replace this as well?
> 
> <img alt="BioDropRepos" width="947" src="https://user-images.githubusercontent.com/43419831/279929395-6cd71cdc-4875-4b83-9ed4-c2006b9077d8.png">
> I can add this image for replacement.

you can raise a new issue and mention you want to work on this. maintainers will assign you if needed
