### ISSUE TITLE
[BUG] Showing background icons in popup message

### ISSUE THREAD

**Issue by Akib-Vijapura** [EddieHubCommunity/BioDrop#9716]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

production

### Version of BioDrop (for example "v1.2.3")

v2.84.0

### Description

Login with your account and go to. "https://www.biodrop.io/account/manage/links" and click on `reorder` button and then click on `save` button. in success pop up message it will showing background icons and button of navbar. and this issue in occurring only in dark mode

### Screenshots

https://github.com/EddieHubCommunity/BioDrop/assets/72021210/4980ed18-5e54-4761-a0e2-1d6e525c7453

### Do you want to work on this issue?

Yes

**Comment by sital002** [comment]
Thankyou for raising the issue but this is a duplicate issue https://github.com/EddieHubCommunity/BioDrop/issues/9618
I am closing this issue

**Comment by ChinmayMhatre** [comment]
@sital002  thank you for mentioning. I had missed it
