### ISSUE TITLE
[BUG] Icon dropdown shifts layout when suggestions are shown

### ISSUE THREAD

**Issue by ChinmayMhatre** [EddieHubCommunity/BioDrop#9717]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

production

### Version of BioDrop (for example "v1.2.3")

Current

### Description

Edit by Sara Jaoude:

In the Management pages there is a layout shift when we start typing in the icon input in:

- add & edit links
- add & edit milestones

Ideally the suggestion should be floating but in this case they shift the layout like a block element.

<img width="520" alt="image" src="https://github.com/EddieHubCommunity/BioDrop/assets/51131670/b9e41814-08da-4460-986b-1f9f92d04d52">

<img width="520" alt="image" src="https://github.com/EddieHubCommunity/BioDrop/assets/51131670/d51a9d63-0742-49bb-b0e5-d1b5e1c849a3">

I went through the code and saw the element is coming from headless ui ComboBox. I don't know if this can be don't but wanted other's opinion

### Do you want to work on this issue?

No

**Comment by SaraJaoude** [comment]
Thanks for raising.  I will add the `discussion` label so that we can see what solutions the community comes up with.

**Comment by Kamaruddheen** [comment]
We should position that suggestions dropdown/list absolutely so it floats overtop of everything and add higher z-index. That way it won't affect the layout when it appears and disappears. 

Extra: May be we should add some sliding up/down animation to make it look smooth.

**Comment by Abhishek-90** [comment]
I tried something using the developers tool to see how it would look, here is a screenshot. 

<img width="947" alt="Screenshot 2023-11-14 150500" src="https://github.com/EddieHubCommunity/BioDrop/assets/43419831/da0bb348-8977-4aeb-a610-3a79b373f094">

**Comment by Kamaruddheen** [comment]
> I tried something using the developers tool to see how it would look, here is a screenshot.
> 
> <img alt="Screenshot 2023-11-14 150500" width="947" src="https://user-images.githubusercontent.com/43419831/282729572-da0bb348-8977-4aeb-a610-3a79b373f094.png">

Could you please provide a short video or GIF that shows the behavior when we type text?

**Comment by Abhishek-90** [comment]
Here you go @Kamaruddheen. 


https://github.com/EddieHubCommunity/BioDrop/assets/43419831/48a59ebf-9b64-4135-b5ea-4d8fd982412d

**Comment by Kamaruddheen** [comment]
Looks good @Abhishek-90. Let the maintainer's decide whether to provide with solution.

**Comment by eddiejaoude** [comment]
I agree lets go ahead with this solution 👍 @Abhishek-90 I have assigned it to you

**Comment by Abhishek-90** [comment]
Hi, can we also add `status:ready for dev` label as well as the points for it.

**Comment by eddiejaoude** [comment]
> Hi, can we also add `status:ready for dev` label as well as the points for it.

Oh yes, sorry, I will do that now
