### ISSUE TITLE
UI Enhancement

### ISSUE THREAD

**Issue by gakshita** [EddieHubCommunity/BioDrop#9721]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Bold outlines can make the UI appear too visually intense.

### Proposed Solution

Enhancing the UI by replacing component outlines with coloured components and box shadows

### Screenshots

Current UI
![image](https://github.com/EddieHubCommunity/BioDrop/assets/36129505/b4627228-d8c4-4428-981b-83fcbc06c0e5)

Updated UI
![image](https://github.com/EddieHubCommunity/BioDrop/assets/36129505/39915ab9-d465-4810-9aa0-a523176b6a96)

### Do you want to work on this issue?

Yes

**Comment by SaraJaoude** [comment]
Thank you for raising. The image you shared as the `Updated UI` is actually how we used to have these cards, however a decision was made to change it to a simpler design.  

As we will be going through the redesign process shortly and this will be looked at then, I will close this issue for now.
