### ISSUE TITLE
[BUG] mobile navbar menu not displayed on dark mode

### ISSUE THREAD

**Issue by Kamaruddheen** [EddieHubCommunity/BioDrop#9731]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

production

### Version of BioDrop (for example "v1.2.3")

v2.84.3

### Description

When the hamburger button is clicked to open the navbar menu in dark mode on mobile, the menu animation begins but the menu renders behind the `<main>` element and contents are not visible.

### Steps to Reproduce 

- Enable dark mode on mobile viewport.
- Click the hamburger button  to open the navbar menu. 
- The menu slide animation will start but the menu contents do not appear.

**Note:** This issue started occurring after increasing the `z-index` on the `<main>` element to 40 on dark mode in PR #9726 (by me)

### Screenshots

https://github.com/EddieHubCommunity/BioDrop/assets/57263951/4a13ac6c-ceb2-4334-a8c2-6ff118f38fa5

### Do you want to work on this issue?

Yes

### If you want to work on this issue...

I suggest increasing the `z-index` of the mobile navbar menu to a value higher than the `<main>` element, when viewed on a mobile viewport. With this change, the menu should now slide over and display on top of the `<main>` element when opened via the hamburger icon on mobile.

**Comment by sital002** [comment]
The issue is caused by the PR raised by you   please fix this here is the PR link 
https://github.com/EddieHubCommunity/BioDrop/pull/9726#event-10864785417
