### ISSUE TITLE
[BUG] Sign up CTA in nav bar feel broken when you are already in pricing page

### ISSUE THREAD

**Issue by amitabh-sahu** [EddieHubCommunity/BioDrop#9750]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

biodrop.io

### Version of BioDrop (for example "v1.2.3")

v2.85.2

### Description

I was already on the [pricing page](https://www.biodrop.io/pricing) of BioDrop and when I clicked on "Sign up" CTA on the navbar it did nothing and when I clicked on "Sign up" CTA on the premium option it went to [signin page](https://www.biodrop.io//auth/signin), then realised that "Sign up" CTA of the navbar take to the [pricing page](https://www.biodrop.io/pricing) only.

It's a bit confusing when two CTA with the same label on the same page take to different route.

### Screenshots

<img width="1512" alt="Screenshot 2023-11-08 at 11 16 52 PM" src="https://github.com/EddieHubCommunity/BioDrop/assets/90052329/573ade17-6744-49c7-a941-7ea192e2a887">
Check the CTA's marked in red.

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

One solution can be the "Sign up" CTA on the navbar should also route to [signin page](https://www.biodrop.io//auth/signin), but this change put two separate CTAs "Login" and "Sign up" on the navbar which route to the same page. 

Another solution can be to keep a single CTA "Login/Signup" on the navbar route to [signin page](https://www.biodrop.io//auth/signin) as creating an account is handled by GitHub itself

Let me know if want to keep it as it is for now or which change should be implemented.

**Comment by amandamartin-dev** [comment]
I agree, this is a confusing UX. 

On the pricing page, there is a plan for a free account. But the flow for that CTA takes you directly to login. There is no actual signup flow for a free account so I have another option to offer to the conversation:

1. Change the nav button to a signup/login as OP suggested
2. On click you are taken to the pricing plans page but on the **free account, the CTA is Login**
on the **paid account, then CTA is "Upgrade"**

Potential downside to this flow - it creates 2 steps to login
Potential upside to this flow - ALL users see that there is an upgraded plan which will increase awareness of this option

**Comment by SaraJaoude** [comment]
Thank you both for your comments and suggestions.  As a simpler solution the text for the Premium button can be changed from `Sign Up` to `Join Premium plan`.  This has now been addressed [here](https://github.com/EddieHubCommunity/BioDrop/pull/9806)
