### ISSUE TITLE
[BUG] On mobile clicking on the edit fields => application error

### ISSUE THREAD

**Issue by TimoCodez** [EddieHubCommunity/BioDrop#9776]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

On production

### Version of BioDrop (for example "v1.2.3")

V2.87.1

### Description

On mobile:
Samsung A53 5G and A52 5G enterprise edition
Google Chrome browser mobile and When applying the "desktop view"

1. When trying to edit  Profile, Events, Milestones
Every other time you click on the area or edit button you get application error and other time you get the correct page.

2. When clicking links every other time links are not there and every other time they show up correctly.
3. When clicking repos and testimonials no errors when clicked multiple times back and forth

Added a screencapture video about all of these. Used the "desktop view" as its faster and no scrolöing needed. Same behaviors occurred on the mobile view.

This is the error message:
Application error: a client-side exception has occurred (see the browser console for more information).

This is my first issue so if I didn't do it correctly please forgive me and let me know if additional info is needed.

### Screenshots

https://github.com/EddieHubCommunity/BioDrop/assets/55003801/061094e2-4ac2-4c11-9f5c-8a92028dfb9a

### Do you want to work on this issue?

No

**Comment by eddiejaoude** [comment]
Thank you for raising 👍 I will unlock to get feedback from others because I can't replicate locally and I find it difficult to find a pattern of why it occurs

**Comment by amandamartin-dev** [comment]
Closing as fixed by #9784
