### ISSUE TITLE
[BUG] "Display Name" for a link has to be at least 2 chars

### ISSUE THREAD

**Issue by icepuma** [EddieHubCommunity/BioDrop#9803]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

production

### Version of BioDrop (for example "v1.2.3")

v2.89.2

### Description

I tried to create a link to my X profile, but unfortunately the "Display Name" for a link has to be at least 2 chars.

### Steps to Reproduce

1. Login to biodrop
2. Navigate to https://www.biodrop.io/account/manage/links
3. Create a new link, enter a "X" in the field "Display Name"
4. Fill out the rest of the mandatory fields
5. Press "SAVE" to raise the error

### Screenshots

<img width="1377" alt="Screenshot 2023-11-18 at 23 38 35" src="https://github.com/EddieHubCommunity/BioDrop/assets/362487/1c0858de-ed91-41d7-8639-c10c359727b8">

### Do you want to work on this issue?

No

**Comment by eddiejaoude** [comment]
Thank you for raising 👍

**Comment by Sahil0402** [comment]
Hey can I work on this issue.

**Comment by Abhishek-90** [comment]
Please assign it to me.

**Comment by eddiejaoude** [comment]
> Please assign it to me, if you just self assigned it as placeholder eddiejaoude

Please see the issue timeline just above my comment, you will see a Pull Request has already been raised

**Comment by icepuma** [comment]
It works. Thanks folks ❤️

**Comment by eddiejaoude** [comment]
Great 🎉
