### ISSUE TITLE
[FEATURE] Re-ordering repos

### ISSUE THREAD

**Issue by Giuliano1993** [EddieHubCommunity/BioDrop#9810]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

When I want to change the order in which my repos are displayed I have to delete and insert them in the order I want, it's a bit long of a process and one easily give up on that (or at least that's my case)

### Proposed Solution

That would be nice a re-ordering function, just like the one we use for re-ordering the links!
It's beautiful and usable and would allow to better showcase our most relevant repos on the top 

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

I would implement the <ReactSortable> wrapper just like in the links page, that could be enabled or disabled, so we could change the links order. That would also trigger a save method to save the new order.

**Comment by amandamartin-dev** [comment]
There is a similar request to #9768 which is about using drag and drop to reorder tags.  Another potential solution is to use the methodology agreed upon in that issue and apply

**Comment by eddiejaoude** [comment]
Thanks for raising @Giuliano1993 👍 

I think keeping it similar to the links page is a good idea 👍
