### ISSUE TITLE
[FEATURE] Character limit is not available in the Bio section

### ISSUE THREAD

**Issue by ai-naymul** [EddieHubCommunity/BioDrop#9829]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

I opened my account and when I went to write my bio, after writing something, I can't write, I think there is a character limit, but it does not show how many characters I can write.

### Proposed Solution

Add something like this:
![Screenshot_2](https://github.com/EddieHubCommunity/BioDrop/assets/68547750/50d0c88b-dcc7-42d7-97ec-7baecbb52ace)

### Screenshots

![Screenshot_1](https://github.com/EddieHubCommunity/BioDrop/assets/68547750/bb65e35d-7bc4-4193-b161-b69dd68ae82a)

### Do you want to work on this issue?

No

**Comment by eddiejaoude** [comment]
Thank you for raising the issue 👍

**Comment by bojangabric** [comment]
Hey, this seems like a good issue to get familiar with the project, could I work on it?

**Comment by SaraJaoude** [comment]
> Hey, this seems like a good issue to get familiar with the project, could I work on it?

@bojangabric thanks for your enthusiasm - I have assigned this to you.  As you are new to the project, I would suggest reading our [Contributing Guide](https://github.com/EddieHubCommunity/BioDrop/blob/main/CONTRIBUTING.md) to familiarise yourself with it's requirements and guidelines.
