### ISSUE TITLE
[FEATURE] Add a step to docker startup guide

### ISSUE THREAD

**Issue by ChinmayMhatre** [EddieHubCommunity/BioDrop#9830]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Documentation update

### Proposed Solution

I was trying to follow the steps for the docker setup. noticed that we need to have the docker daemon running. It maybe a small fix but we could add a step mentioning the need for it

above step 2 
<img width="1322" alt="image" src="https://github.com/EddieHubCommunity/BioDrop/assets/51131670/84d06cad-9804-46d3-916b-23895c7246ca">

### Do you want to work on this issue?

No

**Comment by abhinav26966** [comment]
Hey, can I get this issue assigned to me ?

**Comment by SaraJaoude** [comment]
> Can I get this issue assigned to me?

@bishal-jena I will assign this to you

**Comment by AnikethDeb2004** [comment]
**If this issue not done yet assign me.**

**Comment by sital002** [comment]
> **If this issue not done yet assign me.**

@AnikethDeb2004  We are glad that you want to contribute but the is assigned to someone else we usually give 2 weeks time to complete the issue.
Please familiarize yourself with our contributing guidelines https://github.com/EddieHubCommunity/BioDrop/blob/main/CONTRIBUTING.md

**Comment by AnikethDeb2004** [comment]
Ok no problem

**Comment by sital002** [comment]
@bishal-jena  Due to lack of inactivity, I am unassigning the issue

**Comment by Dhruval7878** [comment]
> > **If this issue not done yet assign me.**
> 
> @AnikethDeb2004 We are glad that you want to contribute but the is assigned to someone else we usually give 2 weeks time to complete the issue. Please familiarize yourself with our contributing guidelines https://github.com/EddieHubCommunity/BioDrop/blob/main/CONTRIBUTING.md

I would like to be assigned to this issue now because it seems that two weeks have passed.

**Comment by sital002** [comment]
Assigning the issue to you @Dhruval7878

**Comment by whysumedh** [comment]
Hi, please assign this issue to me if possible and in case of inactivity

**Comment by sital002** [comment]
> Hi, please assign this issue to me if possible and in case of inactivity

@whysumedh  We are glad that you want to contribute but the is assigned to someone else we usually give 2 weeks time to complete the issue.
Please familiarize yourself with our contributing guidelines https://github.com/EddieHubCommunity/BioDrop/blob/main/CONTRIBUTING.md

**Comment by SaraJaoude** [comment]
> Assigning the issue to you @Dhruval7878
> 

unassigned due to inactivity.

**Comment by whysumedh** [comment]
@SaraJaoude Please assign the issue to me.

**Comment by SaraJaoude** [comment]
> SaraJaoude Please assign the issue to me.

@whysumedh I have assigned this to you

**Comment by eugene4545** [comment]
I'm interested in contributing to this issue, can I be assigned to it?

**Comment by ArvindParekh** [comment]
Hi @eugene4545, thank you for your interest in contributing to BioDrop. Currently, this issue has already been assigned to @whysumedh, and we usually allow a two-week window for individuals to address the task ([contributing guide](https://github.com/EddieHubCommunity/BioDrop/blob/main/CONTRIBUTING.md) - for more reference). But if you'd like, feel free to explore other open issues.

**Comment by ChinmayMhatre** [comment]
unassigned due to inactivity.

**Comment by eugene4545** [comment]
if this issue is not fixed yet ,ill love to have a go at it

**Comment by Dhruval7878** [comment]
maybe we need to update docs only right ?

**Comment by Mursalin80** [comment]
Can I work on this issue?

**Comment by eddiejaoude** [comment]
Assigned it to @ArvindParekh from our discussion in Discord
