### ISSUE TITLE
[BUG] Incorrect UI screenshot on home page

### ISSUE THREAD

**Issue by badrivlog** [EddieHubCommunity/BioDrop#9831]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

production

### Version of BioDrop (for example "v1.2.3")

v2.90.1

### Description

After recent changes were made to the project, there is a noticeable discrepancy between the UI screenshot displayed on the home page (search by tags section) and the actual search page UI. The home page (search by tags section) appears to be showing an outdated or incorrect screenshot.

### Steps to Reproduce

1. go to https://www.biodrop.io/
2. compare the UI screenshot displayed on the home page (search by tags section) with the actual search page UI.

### Screenshots

**Home page (search by tags section) with incorrect UI screenshot**
![homepage-incorrect](https://github.com/EddieHubCommunity/BioDrop/assets/73095526/5e529fb4-ac6b-447b-b02f-5c555ae3c404)

**Actual search page screenshot**
![search-page-actual](https://github.com/EddieHubCommunity/BioDrop/assets/73095526/ffe8b30a-c4e8-4f49-aaca-f63e0097e65d)

### Do you want to work on this issue?

No

### If "yes" to above, please explain how you would technically implement this

_Edited by @kumarsonsoff3_

You need to edit the below screenshot src with the updated one: 
https://github.com/EddieHubCommunity/BioDrop/blob/f85ead6b9cbf97aa871d22dc3fdab71de92eb90a/pages/index.js#L88

**Comment by kumarsonsoff3** [comment]
Good spot, Thank you for raising @badrivlog! 👍

**Comment by omkar342** [comment]
@kumarsonsoff3, can you assign this to me?

**Comment by ArvindParekh** [comment]
Hi, do you think we should work on this after the issue #9828 is solved? That is related to the number badges overlapping with the tags, which leads to tags not being displayed properly. 
Working on this after fixing the overlapping issue would mean we have the latest and updated screenshot.

**Comment by kumarsonsoff3** [comment]
@ArvindParekh, the issue referenced by you here is being closed as a duplicate to the one which is already resolved. So I think it's good to go with this! 

@omkar342 will assign this to you, additionally, check the updated issue description for more info.

**Comment by omkar342** [comment]
Hi @eddiejaoude & @kumarsonsoff3, apart from the above screenshot, I have two more screenshots from our home page, I think that also needs to be changed. Please let me know your view on this.

### 1)
### Home page (your tags) screenshot
![old_search_tags_sc](https://github.com/EddieHubCommunity/BioDrop/assets/70514712/3f321ec2-fa42-4118-acf8-90824dc266a5)

### Actual UI screenshot
![new_search_tag_sc](https://github.com/EddieHubCommunity/BioDrop/assets/70514712/901fa975-1f72-4a6d-8f4c-838b59371336)

### 2)
### Home page (your tags) screenshot
![eddie_previous_sc](https://github.com/EddieHubCommunity/BioDrop/assets/70514712/5015f360-a3dc-441c-be94-fc08df59731c)

### Actual UI screenshot
![eddie_new_sc](https://github.com/EddieHubCommunity/BioDrop/assets/70514712/04936881-085c-43da-8914-41eebf4febd7)

If you want me to change this also, I am up for this.
Just let me know if I can fix these 3 screenshots under this same issue or not?

**Comment by omkar342** [comment]
Ok, I will do it.
Sure, I will make sure I do not tag anyone in the comment from next time.
Thank you.
