### ISSUE TITLE
[FEATURE] Users should be able to select from already existing groups

### ISSUE THREAD

**Issue by MichealCodez** [EddieHubCommunity/BioDrop#9836]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Unavailable functionality: If a user already typed in a group name for links, the user shouldn't need to type the same name again when assigning links to that group.

### Proposed Solution

I think after a group name is been typed in at first, next time the user is adding a link there should be options for user to either choose from existing group names or type a new one.

### Do you want to work on this issue?

No

### If "yes" to above, please explain how you would technically implement this

Would have love to implement this but not my tech stack, and I don't want to try and error
Here is what I propose though

Using the autocomplete library in JavaScript
1 - Make an empty array
2 - Save the names of group provided by the user if they don't already exist
3 - Put this names in the array and pass it to the autocomplete library to show them when ever users start typing

**Comment by eddiejaoude** [comment]
Thank you for raising the idea 👍
