### ISSUE TITLE
[FEATURE]:Add Clear All Filters Button for  User Experience

### ISSUE THREAD

**Issue by guptadeepak8** [EddieHubCommunity/BioDrop#9839]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Add a button to easily remove all search filters in the Bio tags. Right now, you have to click each tag again to clear them. This will make finding things simpler for users.

### Proposed Solution

create a 'Clear All Filters' button in the Bio tag search section. This button will allow users to easily remove all selected filters with a single click.
Also, please make sure the button matches the color scheme 

### Screenshots

![Screenshot (668)](https://github.com/EddieHubCommunity/BioDrop/assets/91896859/49b40f40-1eae-407e-82e3-4d88d9ee0066)

### Do you want to work on this issue?

No

**Comment by eddiejaoude** [comment]
Thank you for raising the issue, yes this is a good idea 👍 - the buttons could be next to each other

**Comment by pratik9818** [comment]
I would like to work on this issue .

**Comment by sital002** [comment]
Assigning the issue to you @pratik9818

**Comment by pratik9818** [comment]
> If @pratik9818 not working on this issue. Can you assign it to me I would like to work on this 
> 

@futoid i am working on it

**Comment by futoid** [comment]
Kindly assign this issue to me. I would like to work

**Comment by aryanraj60** [comment]
I Would like to work on this issue

**Comment by SaraJaoude** [comment]
> Kindly assign this issue to me. I would like to work

@futoid I have assigned this to you

**Comment by guptadeepak8** [comment]
Is this issue still pending may i get assigned?

**Comment by futoid** [comment]
@guptadeepak8 I'm working :D

**Comment by Harshalvk** [comment]
Does anybody working on this issue??
I would like to work on this issue.

**Comment by SaraJaoude** [comment]
@Harshalvk and @guptadeepak8 before commenting for an issue to be assigned to you, can you please check the history and also the Assignees box (top left of page) - there you would have seen that this has already been assigned, and you would have prevented noise and extra notifications for all.

**Comment by eddiejaoude** [comment]
Pull Request merged
