### ISSUE TITLE
[BUG] Update keyboard event handling to modern standards

### ISSUE THREAD

**Issue by badrivlog** [EddieHubCommunity/BioDrop#9840]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

Production

### Version of BioDrop (for example "v1.2.3")

v2.90.1

### Description

In the current `components/tag/TagsInput.js` component, keyboard event handling relies on the deprecated `event.keyCode`. To ensure compatibility with modern browsers and adhere to updated web standards, it's recommended to migrate to `event.key` or `event.code`.

The following resource could be helpful:
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode

### Steps to Reproduce

1. Navigate to `components/tag/TagsInput.js` component
2. Identify instances where `event.keyCode` is used.

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

Replace occurrences of `event.keyCode` with either `event.key` or `event.code` depending on the desired functionality.

**Comment by eddiejaoude** [comment]
Thank you for raising, I have assigned it to you @badrivlog
