### ISSUE TITLE
[BUG] Stars and forks count in GitHub projects for BioDrop profiles does not update

### ISSUE THREAD

**Issue by SaptarshiSarkar12** [EddieHubCommunity/BioDrop#9842]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

Production

### Version of BioDrop (for example "v1.2.3")

v2.90.1

### Description

The **repo** section in BioDrop profiles list projects hosted on GitHub. The count of **stars** and **forks** shown in them are not updated. The stars show **129** which was between 22 to 25th November. But, presently there is 140 stars.

### Steps to Reproduce

1. Go to <https://www.biodrop.io/SaptarshiSarkar12> page.
2. On right side, see the project given in the repo section.
3. The count of stars and forks are not updated in the profile. You can check [the original repo](https://github.com/SaptarshiSarkar12/Drifty).

### Screenshots

![image](https://github.com/EddieHubCommunity/BioDrop/assets/105960032/c154645c-c193-4bc7-a524-942d6ed5e562)
![image](https://github.com/EddieHubCommunity/BioDrop/assets/105960032/2f162033-e433-47e8-ae68-7c7c588c324e)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

I have found that there is something to do with the **`updateRepoApi`**. But, I couldn't figure out the exact cause of the problem. Help from the maintainers will be helpful for fixing this bug.

**Comment by eddiejaoude** [comment]
Thank you for raising but this is not a bug, it is by design cached for 3 days - so I will close.

https://github.com/EddieHubCommunity/BioDrop/blob/f85ead6b9cbf97aa871d22dc3fdab71de92eb90a/pages/api/system/github.js#L14

**Comment by SaptarshiSarkar12** [comment]
@eddiejaoude Sorry, I thought it was one day. Yeah, you can close this issue then.

**Comment by eddiejaoude** [comment]
No problem, 1 day would be a nicer UX but we do use GitHub API a lot and I worry to reach the rate limit

**Comment by SaptarshiSarkar12** [comment]
@eddiejaoude Yeah, I understood :smile:. Thanks for the explanation :sweat_smile:!
