### ISSUE TITLE
[FEATURE]: Change the default select option with headlessUI select component

### ISSUE THREAD

**Issue by ashrafchowdury** [EddieHubCommunity/BioDrop#9859]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

The current default options for selecting items are very basic and do not look visually appealing.

### Proposed Solution

The headlessUI library provides visually appealing UI for selecting items, it will enhance the application UI and improve user experience.

**The headlessUI library is already installed on the application so we don't have to install any other libraries.**

### Screenshots

**Default select option**

https://github.com/EddieHubCommunity/BioDrop/assets/87828904/c37ac3c1-55f4-4d53-bd8d-d3dd84c2f5ef

**After adding headlessUI select option**

https://github.com/EddieHubCommunity/BioDrop/assets/87828904/98589c2b-6c49-40b9-8130-d72d76c3ca76

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

I'm going to change the default select option with the headlessUI select component, and also I'll add new tests to ensure that the component is working everywhere in the application.

**Comment by eddiejaoude** [comment]
Sounds like a good idea, I have assigned it to you

**Comment by eddiejaoude** [comment]
@ashrafchowdury I see you have unassigned the issue from you, which is fine, but why close it and prevent someone else from doing it?
