### ISSUE TITLE
[BUG] Dragging Input field for Tags gives Error.

### ISSUE THREAD

**Issue by Abhishek-90** [EddieHubCommunity/BioDrop#9869]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

Production

### Version of BioDrop (for example "v1.2.3")

v2.94.1

### Description

Now that the tags are draggable on `events` and `profile` page, the input field is also draggable, but when we try to drag the input field, we get a client side exception. Checkout below video for reference.

https://github.com/EddieHubCommunity/BioDrop/assets/43419831/5bd8191f-9b2c-4d16-9ae2-cd978d229d2a

### Steps to Reproduce

If you know the steps, follow the below format and provide steps to reproduce

1. Go to https://www.biodrop.io/account/manage/profile or https://www.biodrop.io/account/manage/event page .
2. On bottom left side, you can see tags field. If you have a few tags skip to step 3, else add a few tags here.
3. Try to drag the tags it works fine. Now try to drag the input field and you will get the exception. 

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

The most optimal solution would be to take the input field out the `tags` box. I will take the input field out and place it above the box. This way, the input field will be of constant size and not draggable as well.

**Comment by Abhishek-90** [comment]
Hello @eddiejaoude are you okay with the proposed solution or do you have any other approach in mind?

**Comment by eddiejaoude** [comment]
Looks great! 👍 Merged 🎉
