### ISSUE TITLE
[BUG] Inefficient events filtering logic

### ISSUE THREAD

**Issue by badrivlog** [EddieHubCommunity/BioDrop#9877]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

production

### Version of BioDrop (for example "v1.2.3")

v2.94.1

### Description

The current implementation of events filtering in our project exhibits suboptimal performance. When users attempt to filter events using the provided button, repeatedly recalculate the entire filter logic.

### Steps to Reproduce

1. navigate to `pages/events.js` and `components/user/UserEvents.js`
2. notice the filtering logic

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

Consider managing a state variable `eventsToShow` that tracks the selected event type. When a user selects a specific event type, update the state variable accordingly. This way, the system can filter events more efficiently based on the selected type without repeatedly recalculating the entire filter logic. This approach should contribute to improved performance by reducing redundant computations during filtering processes.

**Comment by eddiejaoude** [comment]
Sounds like a good plan, I have assigned it to you
