### ISSUE TITLE
[BUG] mobile: statistic page not accessible 

### ISSUE THREAD

**Issue by schmelto** [EddieHubCommunity/BioDrop#9888]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

Production on mobile devices

### Version of BioDrop (for example "v1.2.3")

v2.95.0

### Description

When clicking on the profile picture and going into the account page statistics are marked in the drop down to switch between the account pages. But the initial page when clicking on the profile picture is an initial startup so Teen an d not the statistics page.

### Steps to Reproduce

Bio drop start page on mobile 

Go to account page 

now the overview page is displayed and in the navigation toggle statistics is displayed

you cannot switch to statistics

### Screenshots

![image](https://github.com/EddieHubCommunity/BioDrop/assets/30869493/d8e2b5cf-f782-48ea-bead-023436094924)

### Do you want to work on this issue?

No

**Comment by SaraJaoude** [comment]
Thanks for raising @schmelto 

Note to contributors: **This issue will only be assigned once the proposed solution is explained/agreed.**
