### ISSUE TITLE
[BUG] "Playground" text button is not visible clearly in darkmode

### ISSUE THREAD

**Issue by vrushabhgawas14** [EddieHubCommunity/BioDrop#9890]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

Documentation > Quickstart > Profile with JSON > NOTE (Darkmode)

### Version of BioDrop (for example "v1.2.3")

2.95.0

### Description

While going through the documentation I found that inside 
**Documentation > Quickstart > Profile with JSON > NOTE (Darkmode)** 
the **`Playground`** text button is not visible clearly in **Darkmode** as it has a white color text and its background is aslo light.

Same issue is found at "**Quickstart > Profile with Forms >NOTE**"  where **`Links`** text button is not visible clearly.

Edit by Sara Jaoude:

The colour of the links is the same throughout the app - whether this is in an Alert box or not. What has arisen here is that as the Alert box background colour does not change in Dark Mode.  

The Alert box needs to change. We would suggest that **only in Dark Mode**, the Alert box changes to the Alert box text colour and the text in the Alert box changes to the current background colour.  New colours should not be needed - we can invert the existing Cours. 

### Steps to Reproduce

- [Go to](https://www.biodrop.io/docs/quickstart-json) : **Documentation > Quickstart > Profile with JSON > NOTE (Darkmode) > "Playground text"** 

- [Go to](https://www.biodrop.io/docs/quickstart-forms) : **Documentation > Quickstart >  Profile with Forms > NOTE (Darkmode) > "Links text"** 

### Screenshots

![ss](https://github.com/EddieHubCommunity/BioDrop/assets/126388189/d6df420e-6ada-4258-913c-1ffb6f6c4b2c)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

As this will be the first time I will contribute to BioDrop and will give my best.
I don't know  what exactly to do but I have figured out that the link text color in darkmode should be change inside 
**quickstart-json.mdx > Alert > type info** with Link.js in darkmode

Edit by Sara Jaoude:

Changes need to be made to the Alert component `components/Alert.js`

**Comment by SaraJaoude** [comment]
@vrushabhgawas14 Thank you for raising and writing a good description.  I have assigned this to you - please take a look at the comments I have added in the Description box.

**Comment by vrushabhgawas14** [comment]
Hello, Ma'am I'm done with issue but just need a confirmation that this color invertion I was suppose to do right?
*(In light mode it is same and in Dark mode same colors are inverted.)*

![changes](https://github.com/EddieHubCommunity/BioDrop/assets/126388189/f1a8d55c-dc52-47a5-941e-55fa14a80d36)

**Comment by ChinmayMhatre** [comment]
> Hello, Ma'am I'm done with issue but just need a confirmation that this color invertion I was suppose to do right? _(In light mode it is same and in Dark mode same colors are inverted.)_
> 
> ![changes](https://private-user-images.githubusercontent.com/126388189/290193142-f1a8d55c-dc52-47a5-941e-55fa14a80d36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0ODEzNjUsIm5iZiI6MTcwMjQ4MTA2NSwicGF0aCI6Ii8xMjYzODgxODkvMjkwMTkzMTQyLWYxYThkNTVjLWRjNTItNDdhNS05NDFlLTU1ZmExNGE4MGQzNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QxNTI0MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YTIxZDY4ZGVkMDg1ODNmYWU2M2U1MTkyNmM3MWI0Y2U0Y2FhNTQyZTgzZDMwZjhlZjkxZjg4NDViMWZhOGUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.C-dJm6p3UENQb1VvRcI5FVMmibCJnqx_b_GpchKcMqg)

You can raise a PR and link this issue. You can get feedback from everyone on the PR.

**Comment by vrushabhgawas14** [comment]
@SaraJaoude Sorry for tagging you ma'am, but I have raised PR 2 weeks ago and I just wanted it to get reviewed.
