### ISSUE TITLE
[BUG] Enhance Onboarding Page Progress Bar

### ISSUE THREAD

**Issue by JeevaRamanathan** [EddieHubCommunity/BioDrop#9892]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

https://www.biodrop.io/account/onboarding

### Version of BioDrop (for example "v1.2.3")

2.95.0

### Description

The profile completion progress bar in onboarding page lacks a background and does not differentiate progress percentage. It would be better if a background is added to the progress bar for improving visual consistency and user understanding of their progress.

### Steps to Reproduce

Current:
![image](https://github.com/EddieHubCommunity/BioDrop/assets/64531160/684550ea-c502-4674-ad69-a5d06b1e0a62)

Suggested:
![image](https://github.com/EddieHubCommunity/BioDrop/assets/64531160/1567aa03-7b00-4899-8e9e-768764515d22)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

Adding `bg-primary-low` in the progress bar classname

**Comment by SaraJaoude** [comment]
@JeevaRamanathan thank you for the suggestion.  I have assigned this to you.
