### ISSUE TITLE
[BUG] default profile image text is not visible in dark mode

### ISSUE THREAD

**Issue by j-grosse** [EddieHubCommunity/BioDrop#9900]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

https://www.biodrop.io/EddieHubCommunity?tab=testimonials

### Version of BioDrop (for example "v1.2.3")

v2.95.1

### Description

When activating dark mode the grey text in the default profile picture (which is some text) changes to white.
This makes the text (on the white background) disappear.
It is still there as it can be selected, see screenshot.

### Steps to Reproduce

1. Go to the page's testimonial [tab](https://www.biodrop.io/EddieHubCommunity?tab=testimonials)
2. change from light mode to dark mode via sun/moon symbol in top right page menu
3. Now the profile picture text of user "LinuxGamer" disappears (but can still be selected)

### Screenshots

![by default 2023-12-12 at 15 22 08](https://github.com/EddieHubCommunity/BioDrop/assets/103175813/09c71019-33f9-460e-9b55-d6b9956b7d39)

### Do you want to work on this issue?

No

### If "yes" to above, please explain how you would technically implement this

No, as I don't know how to solve this exactly.
When inspecting the profile picture in Google Chrome I see that the style attribute of the img tag ist not set.
In the other profile pictures that are actual images and not text, it is set to style="color: transparent;".
If I add style="color: black;" inside of the inspected img tag, the profile picture becomes visible.
Maybe an automatically added default placeholder profile image instead of default text would be the solution. It would also look better than the cut-off default text.

**Comment by ChinmayMhatre** [comment]
Thanks for raising the issue, This is happening because the user doesn't exist on GitHub. 
<img width="1439" alt="image" src="https://github.com/EddieHubCommunity/BioDrop/assets/51131670/6aec9e3f-6f27-45d7-a192-654f69a3f9d9">
@eddiejaoude

**Comment by eddiejaoude** [comment]
I see the problem

LIGHT MODE

<img width="533" alt="Screenshot 2023-12-17 at 21 13 19" src="https://github.com/EddieHubCommunity/BioDrop/assets/624760/1040628d-87b6-4c86-af2e-1c643d88335c">


DARK MODE

<img width="553" alt="Screenshot 2023-12-17 at 21 13 23" src="https://github.com/EddieHubCommunity/BioDrop/assets/624760/a90b3fd6-49fb-4041-b646-d5748ddc0d5f">

**Comment by ankittankal** [comment]
Hey @eddiejaoude, I would like to work on this issue.

**Comment by anirudh-hegde** [comment]
Hey, @j-grosse 
I viewed your profile, no issues about your profile picture.
Your profile picture appears on https://www.biodrop.io/LinuxGamer however disappears on https://www.biodrop.io/EddieHubCommunity?tab=testimonials.

So, just try changing your profile picture and check whether the issue exists

**Comment by j-grosse** [comment]
> Hey, @j-grosse I viewed your profile, no issues about your profile picture. Your profile picture appears on https://www.biodrop.io/LinuxGamer however disappears on https://www.biodrop.io/EddieHubCommunity?tab=testimonials.
> 
> So, just try changing your profile picture and check whether the issue exists

Thanks, but it‘s not my profile. If the user has no profile picture on Github an automatically added default placeholder profile image would be the solution. But here the user does not even exist on Github anymore. So there was a picture from the user. Maybe just a very seldom case. Maybe close the issue @eddiejaoude ?

**Comment by SaraJaoude** [comment]
Thank you @j-grosse 

It might be that they changed their username.  However I do agree and this issue should be closed, which I will do now.
