### ISSUE TITLE
[BUG] two children with same key error in statistics page

### ISSUE THREAD

**Issue by sital002** [EddieHubCommunity/BioDrop#9906]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

Local Development

### Version of BioDrop (for example "v1.2.3")

2.96.0

### Description

While testing on local development I noticed that I get the warning of two children with the same key on the statistics page.

![image](https://github.com/EddieHubCommunity/BioDrop/assets/93700622/4c137e1c-95af-44c5-9ded-6d5b877841b6)
The error will only occur if you have the same link here in the above image you can see that I have the same and while we are mapping we are using url as key. 

### Steps to Reproduce

If you know the steps, follow the below format and provide steps to reproduce

For example:
1. First add some link with the same URL then 
2. Go to http://localhost:3000/account/statistics 
3. Open the dev tools.

### Screenshots

![image](https://github.com/EddieHubCommunity/BioDrop/assets/93700622/9b2d56b0-a0c0-40b1-a6bd-0d37b78c18b6)

### Do you want to work on this issue?

No

**Comment by SaraJaoude** [comment]
Thanks for raising Sital

**Comment by itsaakashpatel** [comment]
@SaraJaoude I would like to work on this bug, thanks!

**Comment by sital002** [comment]
> @SaraJaoude I would like to work on this bug, thanks!

Assigning the issue to you 
Please don't tag maintainers they all get notified

**Comment by itsaakashpatel** [comment]
I have attached the PR. How to proceed further?

Thanks!

**Comment by SaraJaoude** [comment]
> I have attached the PR. Could you please provide instructions on how to proceed?
> 
> Thank you!

Thank you @itsaakashpatel.  A maintainer will review your PR once they are able - there are several PRs to review and we are working through the list.
