### ISSUE TITLE
[FEATURE] EddieHub Survey ?

### ISSUE THREAD

**Issue by CodeTorso** [EddieHubCommunity/BioDrop#9908]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

No. It's just a survey when new users come. 

Helpful to see where the future of the community wants to go. 

### Proposed Solution

little option below create your own profile that asks to fill in the little survey.

the survey may ask what do you associate when you visit our website

how do you think our website should look like in a year or so (more bold or more colorful) ?

what features do you look forward to see in our website etc. 

just 5-6 questions.

### Do you want to work on this issue?

Yes

**Comment by SaraJaoude** [comment]
Thank you for raising. 

You mention an EddieHub survey on the website but you have raised this Issue on the BioDrop repo. There is an EddieHub website and also a BioDrop website as these are two different things. 

We have not had much success with surveys in the past and also the BioDrop website would not be the place to add this in relation to the EddieHub community.

As to the direction of the EddieHub community, members can raise a [GitHub Discussion](https://github.com/orgs/EddieHubCommunity/discussions) and also chat in Discord, so I will close this Issue.
