### ISSUE TITLE
[BUG] Low contrast in the category tag border

### ISSUE THREAD

**Issue by erandakarachchi** [EddieHubCommunity/BioDrop#9910]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

production (www.biodrop.io)

### Version of BioDrop (for example "v1.2.3")

v2.96.0

### Description

In the BioDrop search page, we can search for the user profiles. Some of these profiles might have some tags defined by the users.
However, the border of the category tags is barely visible in the light mode.

### Steps to Reproduce

1. Go to https://www.biodrop.io/search page.
2. Make sure that "Recently updated profiles" section is visible.
3. Make sure you are on dark mode.
4. Notice the white color border around the category tags
5.Now switch to light mode.
6. Notice that the border is not properly visible.

### Screenshots

Working in dark mode
![image](https://github.com/EddieHubCommunity/BioDrop/assets/60935597/09e01654-d56b-4818-97fa-19c8b7a3d28c)

Not properly working on light mode
![image](https://github.com/EddieHubCommunity/BioDrop/assets/60935597/71221d5e-d8c9-47b3-be85-dec1aa9c2950)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

I believe I need to add a border color to the div in `components\tag\TagSimple.js` 
Also, I'm aware that the border somehow works in the dark mode means that there might be some default color has been applied. Planning to investigate and fix this without affecting the global settings.

![image](https://github.com/EddieHubCommunity/BioDrop/assets/60935597/d282c178-6e69-422b-9894-1199ff1bfddc)

**Comment by SaraJaoude** [comment]
Thank you for raising.  The text is visible and this is the most important, so I will be closing this issue for now.
