### ISSUE TITLE
[BUG] Update BioDrop version location in bug.yml

### ISSUE THREAD

**Issue by ArvindParekh** [EddieHubCommunity/BioDrop#9946]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

GitHub Issue Template

### Version of BioDrop (for example "v1.2.3")

v2.96.2

### Description

While creating a new issue for bugs using the issue templates, the text to find the latest version of BioDrop indicates that the version is situated in the lower right corner, but it's actually positioned in the lower left corner. It's a minor detail, but thought it might be worth adjusting for accuracy.

### Steps to Reproduce

1. Go to `.github/ISSUE_TEMPLATE/bug.yml`
2. Check out the text inside the Version section.

### Screenshots

The text says `lower right` -

![image](https://github.com/EddieHubCommunity/BioDrop/assets/71211731/f9598b0b-1ec4-40d3-8784-6f2af188ba35)

But it has been moved to `lower left` -

![image](https://github.com/EddieHubCommunity/BioDrop/assets/71211731/7e73371a-0cc2-496b-9359-50d0918c1d6b)

### Do you want to work on this issue?

Yes

**Comment by eddiejaoude** [comment]
Good spot 👍  thank you for creating the great issue! I have assigned it to you
