### ISSUE TITLE
[BUG] Request to update Twitter icon to X on social share

### ISSUE THREAD

**Issue by krushnarout** [EddieHubCommunity/BioDrop#9971]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

https://www.biodrop.io/krushnarout

### Version of BioDrop (for example "v1.2.3")

v2.97.1

### Description

The twitter icon has been updated to X on footer but it's still same on social share link.

### Steps to Reproduce

Go to https://www.biodrop.io/eddiejaoude and click on social share.

### Screenshots

![New issue twitter](https://github.com/EddieHubCommunity/BioDrop/assets/129386740/b54c7d81-9491-4176-b494-1163a425c74c)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

I will update the `BsTwitter` to latest X logo from the `react-icons` library.

**Comment by SaraJaoude** [comment]
Good spot @krushnarout 

I will assign this to you.

**Comment by krushnarout** [comment]
@SaraJaoude Thank you

**Comment by adityaraute** [comment]
I wish this didn't have to happen :(

**Comment by cyberGHostJs** [comment]
hi guys! has this been fixed yet?
